### ISSUE TITLE
What engine do i use?

### ISSUE THREAD

**Issue by Maria0330** [Gcenx/WineskinServer#101]
Environment (please complete the following information):

OS: MAC OS Mojave 10.14.6
Winery version: 1.8.4.2
Master Wrapper version: Wineskin-2.9.0.7-rc4
Engine version: ?
Hardware: Mac Book Pro 2012

Hi, I have a 32bit sistem (MAC OS Mojave) and I want to install a 32bit program, what engine do I have to use? I'm new to using wineskin.
Thanks

**Comment by Gcenx** [comment]
As your running a supported version and macOS Mojave is practically the perfect version to be on, you'll be able to use any Engine that I provide.

I commonly stick to the latest WineCX builds are these I find to be the most stable, but you'll be able to use basically any provided Engine.

**Comment by Maria0330** [comment]
Hi

Thanks for you answer!
