### ISSUE TITLE
What engine do I use?

### ISSUE THREAD

**Issue by Maria0330** [Gcenx/WineskinServer#102]
Hi, I have a 32bit sistem and I want to install a 32bit program, what engine do I have to use? I'm new to using wineskin.
Thanks

**Comment by Gcenx** [comment]
You still didn’t provide any information, as this isn’t a feature request (not was the trample used) I’ll be closing this issue.

Edit the other issue using the following template https://github.com/Gcenx/WineskinServer/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
