### ISSUE TITLE
DX9 on DXVK?? (Not OpenGL/wined3d)

### ISSUE THREAD

**Issue by rafi16jan** [Gcenx/WineskinServer#106]
**Is your feature request related to a problem? Please describe.**
On readme it says:

> This will install DXVK for DirectX10 and DirectX11 support for 64Bit games.
32Bit DirectX10 and later is not supported on macOS

At first I was cool with that and kept looking at this wonderful repo, until I recall "Isn't DXVK runs on DX9 too??" And it turns out it is! At least on linux. Does it means this WineCX doesn't support DX9 on DXVK entirely? Or it's only supported on 64bit games? (Are there even 64bit DX9 games?) Or DX9 is actually working now via DXVK?

This could also mean games that performs badly like CSGO that runs on OpenGL could be configured to use DXVK > MoltenVK > Metal API and theoretically runs better (CMIIW).

**Describe the solution you'd like**
Maybe clarify on Readme if it is supported or not

**Comment by Gcenx** [comment]
> This will install DXVK for DirectX10 and DirectX11 support for 64Bit games.
32Bit DirectX10 and later is not supported on macOS

I believe this already covers what's supported, DXVK for macOS is different then DXVK on Linux.

MoltenVK does not support all the required extensions to support D9VK, wine can't support Vulkan on macOS due to Metal being a 64Bit only API. wine32on64 doesn't contain any trunking code currently also looks like CX21 also won't be providing this support.

**Comment by rafi16jan** [comment]
> > This will install DXVK for DirectX10 and DirectX11 support for 64Bit games.
> > 32Bit DirectX10 and later is not supported on macOS
> 
> I believe this already covers what's supported, DXVK for macOS is different then DXVK on Linux.
> 
> MoltenVK does not support all the required extensions to support D9VK, wine can't support Vulkan on macOS due to Metal being a 64Bit only API. wine32on64 doesn't contain any trunking code currently also looks like CX21 also won't be providing this support.

I seee, thanks to clarify. You may close this issue

**Comment by rafi16jan** [comment]
Oh, quick question. What's the difference between an engine with 64bit and non-64bit in the name?

**Comment by Gcenx** [comment]
> Oh, quick question. What's the difference between an engine with 64bit and non-64bit in the name?

64Bit tag in an Engine means it contains `wine64`

**Comment by rafi16jan** [comment]
> > Oh, quick question. What's the difference between an engine with 64bit and non-64bit in the name?
> 
> 64Bit tag in an Engine means it contains `wine64`

So non-64bit tag contain only wine32on64? But wine32on64 still exists on 64bit engine right?

**Comment by Gcenx** [comment]
> So non-64bit tag contain only wine32on64? But wine32on64 still exists on 64bit engine right?

WS11 Engines contain `wine` & `wine32on64`, the 64Bit tag means `wine64` is also included.

**Comment by rafi16jan** [comment]
> > So non-64bit tag contain only wine32on64? But wine32on64 still exists on 64bit engine right?
> 
> WS11 Engines contain `wine` & `wine32on64`, the 64Bit tag means `wine64` is also included.

Niceee. Thanks for answering!
