### ISSUE TITLE
(Apple Silicon) Battlefield 2 is very slow on WS11WineCX19 and room not starting on WS11WineCX20

### ISSUE THREAD

**Issue by rafi16jan** [Gcenx/WineskinServer#107]
**Environment (please complete the following information):**
 - OS: macOS version 11.2 Big Sur
 - Winery version: (Can't find it on Porting Kit)
 - Master Wrapper version: Wineskin 2.9.0.7-rc4
 - Engine version: WS11WineCX19.0.2-2
 - Hardware: Macbook Air 2020 (M1)

**Describe the bug**
Battlefield 2 is very slow on WS11WineCX19 and room not starting on WS11WineCX20 (but the game launches and pretty much all the menu works). Already tests adding +fullscreen 0 to exe parameters but room still not starting after texture load (is dxwnd still needed to fix windowed M1 bug?)

**To Reproduce**
1. Install Porting Kit
2. Install Battlefield 2 wsi (Advanced Installation)
3. Choose WS11WineCX19 and cancel installation when download finishes and choose WS11WineCX20 for the second installation (Skip if WS11WineCX20 and WS11WineCX19 are already downloaded from previous games installation, this step is only needed to be able to change the 2 engines afterward)
4. Add "+fullscreen 0" at the end of the WINDOWS exe
5. Run it

**Expected behavior**
Should run at a decent fps as newer titles like CSGO and Witcher 3 performs better (although Witcher 3 uses DXVK instead of wined3d/OpenGL)

**Comment by Gcenx** [comment]
I checked with PaulTheTall about this game and he currently hasn’t tested this on M1 but there are other titles that ether run slowly or have very bad graphical glitches.

There’s unfortunately nothing that I can do, CodeWeavers need to workaround the incompatibility with the M1 GPU.

Even after back-porting some M1 specific GPU fixes from upstream into CX19/CX20 hasn’t improved the situation.

**Comment by rafi16jan** [comment]
> Even after back-porting some M1 specific GPU fixes from upstream into CX19/CX20 hasn’t improved the situation.

So even if it's working on WS11WineCX20 the performance will still be as bad as it was on CX19?

**Comment by rafi16jan** [comment]
A little OOT regarding about DXVK on DX9 #106:

>wine can't support Vulkan on macOS due to Metal being a 64Bit only API. wine32on64 doesn't contain any trunking code currently also looks like CX21 also won't be providing this support.

Would it help if we somehow make MoltenGL or MetalAngle works with WineCX, although it's a long translation (d3d9 > OpenGL > Metal) maybe it's worth the try? And will it be painless-ish because MoltenGL states that it makes developer doesn't need to rewrite their application (to what extent is that?). And do we still need 32 to 64bit trunk code on wine32on64? (this is actually the hardest part I think). If we still need the trunking code then it's probably better to implement this on 64bit wined3d  only (wine64) because there's already a plenty of 64 bit DX9 games.

**Comment by rafi16jan** [comment]
Oh sh*t, MoltenGL is closed source...

**Comment by Gcenx** [comment]
Both of those only provide OpenGL ES not Core or better meaning until wine support using OpenGL ES it’s not a viable solution.

**Comment by rafi16jan** [comment]
My badd. Sorry for my ignorance. But that makes me wonder, how do they implement Android's wine? I remember back then crossover had a demo for Intel Chromebooks
