### ISSUE TITLE
Next master wrapper beta to be uploaded this weekend

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#109]
After adapting to the recent *changes* on Macports-ports, these breakages have been fixed upstream or worked around so it seems like a good time to push an updated master wrapper.

This will include;
 - Updated runtime
 - Updated DXVK dlls & verb
 - Some tweaks for Rosetta2
 The new runtime has swapped from jpeg9 to jpeg-turbo, jxrlib is a newly added dependency plus vkd3d.

 There’s was nothing much work done on WineskinLauncher/Wineskin.app other than some slight tweaks to help improve comparability when running under Rosetta2.

The min version will be locked to 10.13 in those version and Engines/updates going forward will officially drop support for macOS 10.12 and lower, this will help alleviate some of the maintenance burden.

## A pre warning;
After this version is finalized the projects Git history will be pruned to remove all traces of the older binaries that supported prior versions of macOS.

This will bring Wineskin inline to how I’m handling my Winehq like macOS wine packages.

**Comment by Gcenx** [comment]
Heres a direct link to hopefully the final version of the next master wrapper [Wineskin-2.9.0.7.tar.xz](https://mega.nz/file/KUg13CTI#AU71OeQ-OCP1nuAYCgsRqqKzaZZ8hShUWdQuUKjYAV4)

<br>

Before extraction run the following command in Terminal
```
xattr -drs com.apple.quarantine ~/Downloads/Wineskin-2.9.0.7.tar.xz
```
After extraction move __Wineskin-2.9.0.7.app__ to;
```
~/Library/Application Support/Wineskin/Wrapper
```
Make sure to remove __Wineskin-2.9.0.7-rc4.app__

<br>

All current Engines *should* still function including Winehq repacks (WS9), if there are issues with the current *WineCX19.0.2* and *WineCX20.0.2* Engines those can be rebuilt.

**Comment by vesper8** [comment]
If using Wineskin Winery, won't it auto-update to the latest? I just opened it but the Update button is still greyed out.

Also what is this quarantine command for above?

Many thanks!

**Comment by Gcenx** [comment]
@vesper8 the linked wrapper won’t be available for download via Winery yet, if I pushed it and there was some major issue I missed that would require hotfix.

**Comment by nsklaus** [comment]
it doesn't work,  first, if i double-click on Wineskin-2.9.0.7 i get this error message: ```Wineskin-2.9.0.7” is damaged and can’t be opened. You should move it to the Bin.```

if i enter the bundle and try to run things directly, when i try to open Wineskin-2.9.0.7.app/Contents/MacOS/wineskinlauncher, i get this output: ```2021-05-01 11:23:07.447 wineskinlauncher[71737:6037233] Error! Set executable not found.  Wineskin.app running instead.``` but nothing shows up.
 
if i try to run Wineskin-2.9.0.7.app/Wineskin.app/Contents/MacOS/Winskin
i get a popup windows indicating wineskin is busy, and a wheel spinning forever, when i quit it there's a new popup error message  ```Error while writting file: The folder “exec3886689149.bat” doesn’t exist.```
there's also a broken link to non-existent drive_c dir, i added that but that didn't help much, the app still refuse to open.

**Comment by nsklaus** [comment]
and fallout4 starts but all i get is blank screen. with previous version fallour4 used to work better.
here's the log: 
[LastRunWine_F4.txt](https://github.com/Gcenx/WineskinServer/files/6409430/LastRunWine_F4.txt)

**Comment by Gcenx** [comment]
> it doesn't work, first, if i double-click on Wineskin-2.9.0.7 i get this error message: `Wineskin-2.9.0.7” is damaged and can’t be opened. You should move it to the Bin.`
> 
> if i enter the bundle and try to run things directly, when i try to open Wineskin-2.9.0.7.app/Contents/MacOS/wineskinlauncher, i get this output: `2021-05-01 11:23:07.447 wineskinlauncher[71737:6037233] Error! Set executable not found. Wineskin.app running instead.` but nothing shows up.
> 
> if i try to run Wineskin-2.9.0.7.app/Wineskin.app/Contents/MacOS/Winskin
> i get a popup windows indicating wineskin is busy, and a wheel spinning forever, when i quit it there's a new popup error message `Error while writting file: The folder “exec3886689149.bat” doesn’t exist.`
> there's also a broken link to non-existent drive_c dir, i added that but that didn't help much, the app still refuse to open.
> 
> if i try to create a new blank wrapper anyway with winery (which list correctly Wineskin-2.9.0.7 as wrapper version), the new blank wrapper gets correctly created, but when i try to run it i get this output from the terminal:
> 
> ```
> [ Wineskin ] 
> $ pwd
> /Users/klaus/Applications/Wineskin
> [ Wineskin ] 
> $ open MyCoolWrapper.app 
> The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-128 "userCanceledErr" UserInfo={_LSLine=3691, _LSFunction=_LSOpenStuffCallLocal}
> [ Wineskin ] 
> $ 
> ```
> 
> and a popup error appear and tells:
> 
> ```
> “MyCoolWrapper” is damaged and can’t be opened. You should move it to the Bin.
> ```
> 
> update:
> if i run this:
> 
> ```
> [ klaus ] 
> $ xattr -drs com.apple.quarantine /Users/klaus/Applications/Wineskin/MyCoolWrapper.app
> ```
> 
> then MyCoolWrapper starts correctly. (!)
> i suspect your direction about removing quarantine on master wrapper are unsufficient.
> maybe it doesn't do it recursively on app bundled inside the master wrapper or something like that ?
> 
> by the way, trying to do the same thing on the uncompressed master wrapper didn't help:
> 
> ```
> [ klaus ] 
> $ xattr -drs com.apple.quarantine /Users/klaus/Library/Application\ Support/Wineskin/Wrapper/Wineskin-2.9.0.7.app
> 
> [ klaus ] 
> $ open /Users/klaus/Library/Application\ Support/Wineskin/Wrapper/Wineskin-2.9.0.7.app
> [ klaus ] 
> $ 
> ```
> 
> i still get the popup: `Error while writting file: The folder “exec1217742224.bat” doesn’t exist.`

You didn’t follow the provided instructions.

Firstly the quarantine flag needs to be removed from the downloaded archive before extraction. Removing the quarantine flag before extraction means the extracted files won’t all receive the quarantine flag.

Second you resolve the current master wrapper with the newly downloaded version, then use as normal to create a new wrapper.

The blank master wrapper is not designed to be used individually, the initial setup is handled by Winery where it places the Engine into the needed location and modify a the master wrappers info.plist as needed.

> and fallout4 starts but all i get is blank screen. with previous version fallour4 used to work better.
> here's the log:
> [LastRunWine_F4.txt](https://github.com/Gcenx/WineskinServer/files/6409430/LastRunWine_F4.txt)

According to the provided Log your attempting to run Fallout4 via OpenGL not DXVK.

**Comment by nsklaus** [comment]
i did it of course. the first thing i did was to follow your directions, so i did exactly what you suggested:
```
xattr -drs com.apple.quarantine ~/Downloads/Wineskin-2.9.0.7.tar.xz
```
and then i extracted the archive, and moved extracted content to 
```
~/Library/Application Support/Wineskin/Wrapper
```

and about fallout4, all i know is that when i installed it on previous wineskin, after install fallout 4 just worked.
now after install, when i start fallout 4 all i get is a blank screen, and this log i provided.
if there's some special setting to activate, this wasn't necessary before. and i don't know if something need to be done to have wineskin to use dxvk instead of opengl. i never had to touch anything before about that.

**Comment by Gcenx** [comment]
> i did it of course. the first thing i did was to follow your directions, so i did exactly what you suggested:
> 
> ```
> xattr -drs com.apple.quarantine ~/Downloads/Wineskin-2.9.0.7.tar.xz
> ```
> 
> and then i extracted the archive, and moved extracted content to
> 
> ```
> ~/Library/Application Support/Wineskin/Wrapper
> ```

The errors you provided give a very different impression, when the quarantine flag or removed macOS won’t complain about needing to trash the “invalid” app.

Unless you removed the quarantine flag then extracted with keka or similar third-party GUI utility as those will re-add the quarantine flag to all extracted files.

> if i try to run Wineskin-2.9.0.7.app/Wineskin.app/Contents/MacOS/Winskin

Never directly launch the master wrapper as it’s just a template and won’t function without an Engine being correctly placed within the template.\
Winery handles everything and provides the blank “wrapper” that’s ready to use.

> and about fallout4, all i know is that when i installed it on previous wineskin, after install fallout 4 just worked.
> now after install, when i start fallout 4 all i get is a blank screen, and this log i provided.
> if there's some special setting to activate, this wasn't necessary before. and i don't know if something need to be done to have wineskin to use dxvk instead of opengl. i never had to touch anything before about that.

To use DXVK your required to run the custom DXVK winetricks verb, this has been the case since this was added.\
Maybe your more use to doing this manually?

**Comment by nsklaus** [comment]
> Unless you removed the quarantine flag then extracted with keka or similar third-party GUI utility as those will re-add the quarantine flag to all extracted files.

i used keka to extract archive (after applying your command to disable quarantive first).
if using keka is bad, what should i use instead ?


> Never directly launch the master wrapper as it’s just a template and won’t function without an Engine being correctly placed within the template.

ok, well noted.


> To use DXVK your required to run the custom DXVK winetricks verb, this has been the case since this was added.
> Maybe your more use to doing this manually?

yes, normaly i use plain wine, and i don't have to use 'verbs'. i will try again with this information you provided.
thanks

**Comment by nsklaus** [comment]
i entered mycoolwrapper.app bundle, ran the winskin UI, clicked 'advanced' button, selected 'tools' tab and ran winetricks.
in the search field i typed 'dxvk' and selected top of the list 'dxvk (latest)'. this time, the game started, i could access the menu title, selected 'continue / load game' i got the loading screen, then when the game should begin (out of loading screen), the game crash, back to dekstop.

here's the wintricks dxvk log:
[wintricks_dxvk.txt](https://github.com/Gcenx/WineskinServer/files/6409801/wintricks_dxvk.txt)

and the wine log for fallout4_using dxvk:
[LastRunWine_F4_dxvk.txt](https://github.com/Gcenx/WineskinServer/files/6409802/LastRunWine_F4_dxvk.txt)

**Comment by Gcenx** [comment]
> i used keka to extract archive (after applying your command to disable quarantive first).
> if using keka is bad, what should i use instead ?

The system archive utility can unpack .tar.xz files.

> yes, normaly i use plain wine, and i don't have to use 'verbs'. i will try again with this information you provided.
> thanks
> i entered mycoolwrapper.app bundle, ran the winskin UI, clicked 'advanced' button, selected 'tools' tab and ran winetricks.
> in the search field i typed 'dxvk' and selected top of the list 'dxvk (latest)'. this time, the game started, i could access the menu title, selected 'continue / load game' i got the loading screen, then when the game should begin (out of loading screen), the game crash, back to dekstop.

Use the “Custom” box and enter `dxvk_macos.verb` that will install the macOS DXVK.\
Upstream DXVK won’t function on macOS and due to the requirements for built built with MoltenVK and requiring a custom patched version it’s not something that can be accepted into upstream winetricks.

I also don’t really want to run a custom from of Winetricks so providing a custom verb that can be installed is simpler for me.

As I’m the only person directly working on the Wineskin codebase I’ve not had the time nor energy to deal with a cleaner way of installing the custom DXVK, patching winetricks on the fly won’t be fun nor stable.

**Comment by nsklaus** [comment]
ok, i enter mycoolwrapper.app, run wineskin UI, choose advanced, select 'tools' tab, click 'winetricks' button, click on the 'custom' checkbox, i enter in the input field:  `dxvk_macos.verb` then i click run.
it crashed completely wineskin 2 times, the 3rd time it worked.

ok, now the game starts and play correctly. 
unfortunately, there is no improvement over the render glitches compared to previous version despite using higher dxvk (DXVK: v1.7-14-gef993b2f).

i attach log:
[LastRunWine_f4_dxvk_ok.txt](https://github.com/Gcenx/WineskinServer/files/6409829/LastRunWine_f4_dxvk_ok.txt)

**Comment by Gcenx** [comment]
> ok, i enter mycoolwrapper.app, run wineskin UI, choose advanced, select 'tools' tab, click 'winetricks' button, click on the 'custom' checkbox, i enter in the input field: `dxvk_macos.verb` then i click run.
> it crashed completely wineskin 2 times, the 3rd time it worked.

If you attempt to do anything too quickly when launching Wineskin.app via WineskinLanuncher there’s a known crash, still didn’t add a delay to avoid this.

> ok, now the game starts and play correctly.
> unfortunately, there is no improvement over the render glitches compared to previous version despite using higher dxvk (DXVK: v1.7-14-gef993b2f).
> 
> i attach log:
> [LastRunWine_f4_dxvk_ok.txt](https://github.com/Gcenx/WineskinServer/files/6409829/LastRunWine_f4_dxvk_ok.txt)

The graphical glitches are lightly still due to the lack of transformfeedback in MoltenVK.

> i wasn't expecting you to overhaul winetricks, custom verbs are fine, it's just that, since it's needed, if it could be stated in the directions being given that would be nice. as well as: "use The system archive utility" (keka will mess with quarantine bits).
> these are important details.

The custom verb is mention in the wiki and the related pre-release section.

Keka adding quarantine flags is something that been decided before but seems it wasn’t added to the wiki, maybe I can try getting around to this after I’ve officially pushed the release.

Most of my time these days gets spent on forking and updating Portfiles from Macports-ports as some are literally on versions from years ago and in not waiting on them fixing things or even merging pull-requests.

Still have additional patches to rebase onto WineCX20.0.x sources to get Origin functional (hopefully) and some other upstream fixes that have been back-ported.\
My local copy of WineCX20.0.2 is more stable than the corespondent CrossOver version due to all the additional patches.

**Comment by thmrtnz** [comment]
Instructions about archives and DXVK have been added to the Wiki Home page.

**Comment by Gcenx** [comment]
The latest version of PK4 can also make use of this master wrapper by enabling “Experimental” checkbox.

Hopefully the test data from PK4 will allow pushing this as the final version of the master wrapper quickly.

**Comment by AraHaan** [comment]
I have a Windows program that uses OpenGL from ``OpenTK.GLControl``

However it crashes currently whenever I go to a part of a file that tries to initialize an opengl context.

Any way to fix that since the program cannot be updated to a newer version of that library because for some reason the newer versions make the program unstable and failover.

**Comment by Gcenx** [comment]
> Instructions about archives and DXVK have been added to the Wiki Home page.

Thanks @thmrtnz, I quickly added that using the brew command will avoid this.

<br>

> I have a Windows program that uses OpenGL from `OpenTK.GLControl`
> 
> However it crashes currently whenever I go to a part of a file that tries to initialize an opengl context.
> 
> Any way to fix that since the program cannot be updated to a newer version of that library because for some reason the newer versions make the program unstable and failover.

@AraHaan this comment is off-topic, macOS  only provides OpenGL Core 4.1, even if the GPU can support a higher version.\
Meaning it’s lightly calling something that’s not supported in the macOS OpenGL implementation.

The only real way to get this working might be modifying the library to avoid the unsupported OpenGL API calls by using some alternative.

**Comment by AraHaan** [comment]
The issue is, how do I know what version of OpenGL it is requesting to use?

**Comment by Gcenx** [comment]
> The issue is, how do I know what version of OpenGL it is requesting to use or even the API's it is attempting to use?
> 
> Edit: It seems the program (CrashEdit) uses 2.0 features only and also binds textures to models. 🤔 What could be making it crash there?
> 
> It seems big sur running on x64 seems to not have OpenGL at all, perhaps the wrapper should create a version of opengl32.dll (that is normally on windows) that actually wraps vulkan or the apple Metal api's instead when it comes to it's provided `winetricks`.

As I’ve said above this is completely off topic.

macOS Big Sur does provided OpenGL in some manner or it wouldn’t be possible to play 32Bit games via wine32on64.

**Comment by Gcenx** [comment]
Seems the fullscreen FPS issue hen using DXVK was resolved, not exactly sure if the newer DXVK or the newer MoltenVK are what resolved this but still some good news.

**Comment by sn4f** [comment]
@Gcenx when can we expect an update? Can't play WoW 2.4.3 on M1 :( on Intel all it's ok

**Comment by Gcenx** [comment]
@sn4f that’s off topic, the master wrapper had nothing to do with WoW not working or being playable, CrossOver-20.0.4 is also unable to play WoW woltk along with other titles.

If CodeWeavers resolved the issues for CrossOver-21.0.0 then these fixes will be built into WineCX21 based engines.

**Comment by sn4f** [comment]
@Gcenx sorry for off topic, thanks for reply.

**Comment by Gcenx** [comment]
Thinking to finish updating whatever dependencies I can (Macports hasn’t updated of lot of things sigh) then just push the master wrapper live to everyone.
