### ISSUE TITLE
Error when creating blank wrapper

### ISSUE THREAD

**Issue by The-SamminAter** [Gcenx/WineskinServer#11]
Whenever I create a blank wrapper, this message pops up: 
![image](https://user-images.githubusercontent.com/48739810/58843846-23910b00-8629-11e9-84aa-f09f0e2507ac.png)
Everything seems to work though

**Comment by The-SamminAter** [comment]
I'm also getting this when I enable `Shutting Down Nicely`
![image](https://user-images.githubusercontent.com/48739810/58844107-8afb8a80-862a-11e9-9c21-279ac1b53a8f.png)

**Comment by Gcenx** [comment]
I’m not sure how that could happen, when wswine.bundle is added into the wrapper automatically by Winery on wrapper creation.

**Comment by Gcenx** [comment]
> I'm also getting this when I enable `Shutting Down Nicely`
> ![image](https://user-images.githubusercontent.com/48739810/58844107-8afb8a80-862a-11e9-9c21-279ac1b53a8f.png)

We’re you using the official Wineskin release before swapping to unofficial by chance?

As you need to update to using my master wrapper version via the provided version of Winery from the releases section

**Comment by The-SamminAter** [comment]
> > I'm also getting this when I enable `Shutting Down Nicely`
> > ![image](https://user-images.githubusercontent.com/48739810/58844107-8afb8a80-862a-11e9-9c21-279ac1b53a8f.png)
> 
> We’re you using the official Wineskin release before swapping to unofficial by chance?
> 
> As you need to update to using my master wrapper version via the provided version of Winery from the releases section

Yes I was, do I replace Wineskin-2.9.0.2.app?

**Comment by Gcenx** [comment]
> > > I'm also getting this when I enable `Shutting Down Nicely`
> > > ![image](https://user-images.githubusercontent.com/48739810/58844107-8afb8a80-862a-11e9-9c21-279ac1b53a8f.png)
> > 
> > 
> > We’re you using the official Wineskin release before swapping to unofficial by chance?
> > As you need to update to using my master wrapper version via the provided version of Winery from the releases section
> 
> Yes I was, do I replace Wineskin-2.9.0.2.app?

Don't manually replace the wrapper, you need to download it via "Unofficial Wineskin Winery"
Also don't unpack the `Unofficial.Wineskin.Winery.zip` using keka but built in Archive utility.

My Wineskin-2.9.0.2 wrapper is **not compatible** with the old official Wineskin release from doh123 due to a lot of internal changes.

Engines from doh123 will function to a point before XQuartz needs to be installed

**Comment by The-SamminAter** [comment]
> > > > I'm also getting this when I enable `Shutting Down Nicely`
> > > > ![image](https://user-images.githubusercontent.com/48739810/58844107-8afb8a80-862a-11e9-9c21-279ac1b53a8f.png)
> > > 
> > > 
> > > We’re you using the official Wineskin release before swapping to unofficial by chance?
> > > As you need to update to using my master wrapper version via the provided version of Winery from the releases section
> > 
> > 
> > Yes I was, do I replace Wineskin-2.9.0.2.app?
> 
> Don't manually replace the wrapper, you need to download it via "Unofficial Wineskin Winery"
> Also don't unpack the `Unofficial.Wineskin.Winery.zip` using keka but built in Archive utility.
> 
> My Wineskin-2.9.0.2 wrapper is **not compatible** with the old official Wineskin release from doh123 due to a lot of internal changes.
> 
> Engines from doh123 will function to a point before XQuartz needs to be installed

Oops... I deleted the original wrapper... Would you happen to have a copy of it?

**Comment by Gcenx** [comment]
The official version of Wineskin-2.6.2 can still be downloaded by using the official version of Wineskin Winery.
