### ISSUE TITLE
Mouse cursor doesn't stay within window

### ISSUE THREAD

**Issue by Moocow93** [Gcenx/WineskinServer#111]
**Environment (please complete the following information):**
 - OS: 11 
 - Winery version: Can't find
 - Master Wrapper version: 2.9.0.7-rc4
 - Engine version:WS11WineCX64Bit20.0.2
 - Hardware: Apple MacBook Air "Core i5" 1.8 13" (2017)

**Describe the bug**
Mouse cursor in the game Raft doesn't stay in the centre and can go outside the window onto another monitor. This causes the camera to move lots and makes the game unplayable.

**To Reproduce**
The game Raft with DXVK enabled

**Expected behavior**
The mouse should stay locked in the middle so it can be used to move the camera around

**Screenshots**

**Additional context**

**Comment by thmrtnz** [comment]
Have you tried checking these in winecfg ?  
(RMB on Wrapper.app, Show Package content, then Wineskin Launcher > Advanced > Tools)  
![Screen Shot 2021-05-04 at 10 22 48](https://user-images.githubusercontent.com/47714003/116977634-f50f8500-acc2-11eb-8853-0164a6ff671b.png)

**Comment by Gcenx** [comment]
Emulated Virtual Desktop option only works with X11 display driver not macDriver, wine32on64 also doesn’t support X11.

The mouse curser can’t be captured unless accessibility permissions are granted to the wrapper, else macOS won’t allow wine to take control of the mouse.

**Comment by Moocow93** [comment]
> Emulated Virtual Desktop option only works with X11 display driver not macDriver, wine32on64 also doesn’t support X11.
> 
> The mouse curser can’t be captured unless accessibility permissions are granted to the wrapper, else macOS won’t allow wine to take control of the mouse.

The wrapper doesn't ask for accessibility permissions anymore and manually giving the wrapper the permissions doesn't seem to do anything.

**Comment by Gcenx** [comment]
That would indicate that wine isn’t attempting to grab the mouse curser, I’ll need to check if this issue is DXVK or some wine registry entry.

**Comment by Moocow93** [comment]
I've found the issue. For some reason MacOS wouldn't let me give accessibility to my original wrapper, only the wineskin inside of it. That's why when I clicked test run the mouse worked fine. But when I created a new wrapper it would let me give it accessibility permissions. Renaming the original wrapper let me give it permissions somehow.

**Comment by Gcenx** [comment]
I’m guessing you created a wrapper with the default name and not a unique name?

As for the mouse still not getting grabbed I’ll need to look into this when I’ve finished up some other things.

**Comment by Gcenx** [comment]
> But now I have a different issue which is that the camera won't move if I only make small movements with my mouse, I have to move the mouse a fair bit to make the camera move.

@Moocow93 this sounds like something with mouse acceleration.
