### ISSUE TITLE
Wineskin-2.9.0.9-3 is now available.

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#112]
Some internal tweaks within `WineskinLaucher` and `Wineskin.app`

The new runtime was updated May 22nd 2021. Importing things to note
- DXVK was bumped
- libMoltenVK 1.1.3 (updated DXVK patches)
- VKD3D 1.2 (rebuilt with newer dependancies)
- jxrlib added

### Wineskin-2.9.0.8-1;
Bugs fixed #122 & #123
Also added some new `verbs`
- klite.verb
- vcrun2019_ws.verb (still installs `ucrtbase.dll`)
- wmp9_ws.verb

### Wineskin-2.9.0.8-2;
Bugs fixed #117 & #128

### Wineskin-2.9.0.8-3;
Correctly resolve #128

### Wineskin-2.9.0.8-4;
- Bump runtime Sep 3rd 2021
- Improved "Winehq Engine Launch"
- Fixed custom .verbs
- Removed klit.verb (still broken)
- libMoltenVK 1.1.5 (updated DXVK patches)
- VKD3D 1.2-20210827

**Comment by emendelson** [comment]
Thank you for your efforts with this! This seems to start up a lot faster than earlier versions. And if you could let us know whether we'll be able to run 32-bit Windows software in Wineskin someday, I'll be grateful...

**Comment by Gcenx** [comment]
@emendelson this wrapper update was a long time in the making so I’m glad there’s a noticeable improvement in launch speed.

Using a WS11 Engine it’s already been possible to run 32Bit Windows applications & games.

**Comment by diegov12** [comment]
I notice there is some stuttering with older games. Is there a setting I'm missing?

**Comment by emendelson** [comment]
By the way, yes, I did mean 16-bit Windows 3.x software. I suppose there's no way that will ever get supported...

**Comment by Gcenx** [comment]
> By the way, yes, I did mean 16-bit Windows 3.x software. I suppose there's no way that will ever get supported...

I don’t see this working anytime soon if ever unless Valve or similar large company ends up requiring it.

It’s weird by now MoltenVK would be giving a cutoff date for the next release…., guess that gives a little more time for PK for testing some experimental Engine builds.

**Comment by Gcenx** [comment]
# Wineskin-2.9.0.8-4;
All standard tools should also now function from **_Winehq Engine Launch_** like `winecfg` can be called directly instead of needing to call `wine winecfg`

A custom environment variable is available `$WINESKINWINEPREFIX` this can be used to easily run the wrapper _WINEPREFIX_ from **_Winehq Engine Launch_**, set `export WINEPREFIX="$WINESKINWINEPREFIX"`

#### Custom .verbs
- dxvk_macos.verb
- origin_ws.verb
- vcrun2019_ws.verb
- wmp9_ws.verb
- xactengine3_7_ws.verb

#### Custom verb wrappers
The following can be used to install the custom verbs from **_Winehq Engine Launch_**
- dxvk_macos
- origin_ws
- vcrun2019_ws
- wmp9_ws
- xactengine3_7_ws

**Comment by Gcenx** [comment]
# Wineskin-2.9.0.9;
- Wineskin.app shouldn't crash as often anymore
- Winetricks menu "Installed" list works (disabled by default)
- Winetricks menu "download" list works (disabled by default)
- Winetricks should retain log files between wrapper updates
- Runtime downgraded pango to 1.48.9 over using the development version
- Updated ObjectiveC_Extensions the M1 GPU should be now have RAM set

**Comment by Gcenx** [comment]
# Wineskin-2.9.0.9-1;
- Disabled GPU detection, this caused wrapper creation to break
- Winetricks menu, *`--force` option restricted

*_This option bypasses winetricks usual safety checks, this will only be used for custom Engines that fix the related bug_
