### ISSUE TITLE
InstallShield, GTA IV Activation and game patches issues.

### ISSUE THREAD

**Issue by Gravarty** [Gcenx/WineskinServer#113]
- macOS Big Sur 11.4 Official
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.0.8
 - Engine version: 20.0.0.2
 - Hardware: Mac mini 2020 (Macmini9,1) M1

Several InstallShield programs used for installing GTA III up to San Andreas doesn't work.
GTA IV's date verification doesn't work and starting the game process manually just ends with an black screen.
Using custom d3d8.dll's used for widescreen fixes and other patches for GTA also doesn't work
and fail with the c0000005 error. 

(0031:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bcafbc5)

**To Reproduce**
GTA III/SA: Mount the game image and select the setup.exe
GTA IV:       Mount the game image and select the setup.exe and let it install the game
after it's finished it can't continue because the date verification window doesn't show up.

GTA Patches: put the d3d8.dll inside the game folder, also add the name of the dll to winecfg and change it to native
and start the game.

**Expected behavior**
GTA III/SA: The installer should start and install the game normally.
GTA IV: The date verification window should pop up and checks the local date/time if the game is officially released.
GTA Patches: Everything should work without issues if the modified d3d8.dll was added into winecfg and set to native.

**Screenshots**
https://i.imgur.com/jC4arxw.png

**Comment by Gcenx** [comment]
Unfortunately I don’t own these games on CD only on Steam, but some installers just plain don’t work correctly under wine(64/32on64).

For the data window not appearing issue it would be useful to have a log of this, as I could submit this to CodeWeavers.

The other issue with the mod dll problem is due to setting it to `native`, these code injecting dlls need to be set to `native/builtin`

**Comment by Gravarty** [comment]
I'll reinstall GTA IV later and send you the logs.

Oh and InstallShield works just fine on CX19. I was able to install all my games on CX19 first and then upgrade the engine to CX20.

**Comment by Gcenx** [comment]
Need to check if the install shield is a known issue in wine-5.0 as you said it worked in CX19.0.2 thats wine-4.12.1 based.

**Comment by Gcenx** [comment]
The steam version uses Rockstar Launcher so I'm assuming the version you're using also requires this for activation?

**Comment by Gravarty** [comment]
Retail disc version with SecuROM. I never managed to get RGL to work.
GTA IV Retail activation works on Intel though, so i activated it on a Intel machine and then moved the Wrapper back to my Mac mini M1. GTA EFLC (GTA IV standalone DLC) works and is playable but GTA IV still stucks on a black screen.

**Comment by Gcenx** [comment]
It lightly needs one of the d3d compilers to be installed for the black screen.
