### ISSUE TITLE
winebrowser.exe doesn't run macOS apps

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#114]
This problem may be upstream, but I only use wine in Wineskin, so I thought I'd start here.

I use Wineskin to run a DOS emulator called vDos, with a traditional DOS-style command line. In a Wineskin app that I made in September 2020, this command works at the Wine command line:

winebrowser.exe file://C:\OSX\myapplescript.app

This runs an AppleScript app; I have a half-dozen of these that I use for various purposes.

With the latest Wineskin, winebrowser.exe seems to run the app, but nothing happens - it doesn't produce any results. Winebrowser.exe still opens websites in Safari, so it isn't completely broken, but the file:// protocol isn't working to run an app.

Has the winebrowser syntax changed or is there a problem in Wineskin?

**Comment by Gcenx** [comment]
Do you have a working copy around still?

Also please edit the bug using the provided issue template the more information the beater, if the issue isn’t a WineskinLauncher issue I can pass the information onto a wine maintainer.

**Comment by vesper8** [comment]
@emendelson You probably already know about this and it may not be helpful in any case but I recently discovered Dosbox-X which has two Mac builds for Intel and M1 Macs and just in case you didn't know about it I wanted to let you know about it https://dosbox-x.com/

**Comment by emendelson** [comment]
@Gcenx - Apologies for wasting your time. I started putting together a detailed bug report - and found that the problem had disappeared. It seems to have been solved by rebooting my machine. I can't explain why or how, but the problem doesn't exist. I'll close this now.

@vesper8 - About DOSBox-X: yes, I do know about it, and have contributed a few lines to its code. You can find my custom builds for macOS and Windows here: http://www.columbia.edu/~em36/dosboxapp.html
