### ISSUE TITLE
err:   D3D11CreateDevice: Failed to create a DXGI factory and Failed to create Vulkan 1.1 instance

### ISSUE THREAD

**Issue by vixxpy** [Gcenx/WineskinServer#115]
**Environment (please complete the following information):**
 - OS: 10.13.6
 - Winery version: Latest
 - Master Wrapper version: 2.9.0.8
 - Engine version: WS10Wine64Bit6.0
 - Hardware: iMac Mid 2011

**Describe the bug**
So i am trying to run a game with Winery. (including wine also) Ive pretty much download all DirectX items using that custom command thing i found (it was a .verb thing).  As im done, i try to run the game that supports directx 11(My graphics are supports directx 11 on this mac). When i ran it i got these 2 errors. Can someone please teach me how to get through this? Just help me pass these errors overall.
Ive seen some videos about getting vulkanlib32 or something like that. How do i get that>? and will that work?

I pretty much expected the game to work after installing all directx 9/10/11 things needed.

**Screenshots**
[NSUNS4_dxgi.log](https://github.com/Gcenx/WineskinServer/files/6557189/NSUNS4_dxgi.log)
[NSUNS4_d3d11.log](https://github.com/Gcenx/WineskinServer/files/6557190/NSUNS4_d3d11.log)

**Additional context**
I ALSO tried downloading these the first time on 32-bit wine WS10 and the directx things installed perfectly. Only problem was the app is 64-bit :/
Searching around youtube and google didnt help at all.....

**Comment by vixxpy** [comment]
Also this isnt really a bug, How do i remove the label?

**Comment by vixxpy** [comment]
No help?

**Comment by Gcenx** [comment]
You’ve opened this issue only 2 hours ago, I have a full-time job that’s 6 days a week.

As explained already the custom DXVK only provides support for 64Bit DirectX10/11 no 32Bit support due to Metal being a 64Bit only API.

Checking the provided logs shows you’ve installed regulate DXVK not the custom version, check the readme or the wiki on how to correctly install the custom DXVK.

The current lot created wrapper is now corrupted due to having installed the Linux version of DXVK.

**Comment by vixxpy** [comment]
Thank you. And My bad for rushing.

**Comment by vixxpy** [comment]
Thanks again. Everything works, But now i have another problem. I have the DX11 Device Creation Error. Ive tried youtube videos and google to fix this, and it hasnt been fixed
Log :
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/6557797/LastRunWine.log)

May you please try to help me out here with this problem?

**Comment by Gcenx** [comment]
That log shows OpenGL is being used and not DXVK.

**Comment by vixxpy** [comment]
alright. And how do I make it to where it uses DXVK?
I’m so sorry for being dumb, I just don’t know a lot lol.

**Comment by Gcenx** [comment]
How to correctly install DXVK is explain in the wiki.

**Comment by vixxpy** [comment]
![Screen Shot 2021-05-28 at 8 05 25 PM](https://user-images.githubusercontent.com/84942280/120051793-1dec1700-bff0-11eb-9f16-6b42e0cb54d6.png)

This is what you mean right? 
Ive did everything it says there. But i still have the problem?

Is there another way to this?

**Comment by vixxpy** [comment]
Also do i need to install moltenvk or something?, if so send me the wiki or readme so i can learn how to install it

**Comment by Gcenx** [comment]
No need to install MoltenVK the master wrapper includes a custom version of MoltenVK 1.1.3.

The last log you provided was not showing DXVK being used, try again on a new wrapper and provide the log, but it’s possible your hardware is too old.

The oldest hardware that DXVK was tested in is my personal Intel mac, that’s a 13inch mid 2014 MacBook Pro.

**Comment by vixxpy** [comment]
Alright, So new wrapper, ill Install DXVK using the command and then ill try to install/play a game and provide the logs.

**Comment by vixxpy** [comment]
Alright, Downloaded DXVK with the command.
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/6564005/LastRunWine.log)
this is the log i get. Any information?

**Comment by Gcenx** [comment]
What the title your attempting to play?

As I have a feeling this title is 32Bit and not 64Bit.

**Comment by vixxpy** [comment]
Im trying to play 2 games : My Hero One's Justice 2 and naruto ultimate ninja storm 4
Both support 64-bit games
(I think thats what u mean by the titles)

**Comment by vixxpy** [comment]
Is that what you meant btw?

**Comment by Gcenx** [comment]
I’m going to assume that your systems GPU doesn’t support the required Metal level to make use of the custom DXVK.

**Comment by vixxpy** [comment]
Yea, i think so. Dang it, Is there another way without installing using the custom or is this just final on whats going on.

it probably seems like im not gonna be able to play these games...

**Comment by Gcenx** [comment]
Only the custom versions of DXVK for macOS can work as they workaround the lack of geometry shaders.

I don’t see you being able to play these titles using wine on that system, I’m not even sure if they’d work via bootcamp.

**Comment by vixxpy** [comment]
My graphics card also supports DirectX 11 as said on google and my graphics card is this:

AMD Radeon HD 6750M

**Comment by vixxpy** [comment]
Well alright, that sucks, So what should i do now, Just wait for some more clarification or?

**Comment by Gcenx** [comment]
Did some digging and your iMac doesn’t support Metal https://discussions.apple.com/thread/8401350

Looks like your only option to possibly play those titles is by using Bootcamp.

**Comment by vixxpy** [comment]
Alrighty thanks.

**Comment by vixxpy** [comment]
Hey quick question, I decided to get the first game of My Hero's Justice and im getting this error, is it still directx problems?
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/6565358/LastRunWine.log)

**Comment by vixxpy** [comment]
so uhh im guessing its the same problem????

**Comment by vixxpy** [comment]
?????

**Comment by Gcenx** [comment]
Yeah this looks to be a similar issue.
