### ISSUE TITLE
how to run No Man's Sky ?

### ISSUE THREAD

**Issue by kagiana** [Gcenx/WineskinServer#116]
**Environment (please complete the following information):**
 - OS: 10.15.7
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.0.8
 - Engine version: WS11WineCX64Bit20.0.2
 - Hardware: Hackintosh 8-Core Intel Core i9 3.6 GHz Radeon RX 5700 XT

**Describe the bug**
From #95 it seems like No Man's Sky will work with this on Intel, but I cannot get it to run. I have GOG version.

**To Reproduce**
I have tried installing `dxvk_macos.verb`, setting vulkan-1 to built in, removing vulkan-1.dll, changing Windows version.

Either error `Unable to initialize Vulkan (vkEnumerateInstanceExtensionProperties failed)` or does not start at all.

[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/6558891/LastRunWine.log)

**Comment by Gcenx** [comment]
I don't see anything related to Vulkan/MoltenVK within the provided log.

There shouldn't be any reason to install DXVK if the game has a vulkan render, also don't mess with the wine provided vulkan dll files.

The issue might just be MoltenVK still doesn't support some required extension that No Man's Sky requires.

**Comment by kagiana** [comment]
Thank you for the quick reply. I do not understand much about Vulkan, but it seems on Linux the game works commonly in wine.

I am glad that Wineskin works with other software. Thank you.

**Comment by Gcenx** [comment]
@kagiana on Linux yes this will run however Linux had a native Vulkan driver where macOS uses [MoltenVK](https://github.com/KhronosGroup/MoltenVK) this currently support Vulkan 1.1 core APIs but some additional extensions are not yet supported.

**Comment by kagiana** [comment]
Now I tried adding this to the registry, and the game fails because of the driver version being old. Is there way to change the driver version in wine? 

`[HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers\]`
`"C:\Windows\winevulkan.json"=dword:00000000`

The wine log shows Vulkan starting. 
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/6563809/LastRunWine.log)

**Comment by Gcenx** [comment]
The problem isn’t the driver version but MoltenVK does t support the extensions that are being requested.

**Comment by kagiana** [comment]
Sorry to bother you. THank you.
