### ISSUE TITLE
WineskinStartupScript doesn't run in latest version

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#117]
**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.0.8
 - Engine version: WS11WineCX64Bit20.0.2
 - Hardware: MacBook Air 13" early 2015

**Describe the bug**
In the current version, the WineskinStartupScript apparently doesn't run when a bundle is launched.

**To Reproduce**
Create a new wrapper; add these commands to the foot of WineskinStartupScript:

```
pwd>~/Desktop/path.txt
export CNTS=$CONTENTSFOLD
osascript -e 'tell application "System Events" to display dialog "contentsfolder: " & (system attribute "CNTS") buttons {"OK"} '
```

Run the script from a terminal (./WineskinStartupScript). The file path.txt gets written to the Desktop, and a dialog box appears with the correct path displayed.

Launch the wrapper; the two actions called for in the edited startup script don't occur. No file gets written, and the dialog box doesn't appear.

**Expected behavior**

**Additional context**
The startup script runs correctly in my bundles based on Wineskin 2.9.0.7-rc1. Something seems to have regressed between that version and the current version.

I haven't tested whether the other scripts run in the current version, but presumably the same problem occurs with those also.

**Comment by Gcenx** [comment]
Seems I’d forgotten to remove the startup/shutdown shell scripts from the master wrapper template, should do that on the next bump.

I’d removed this functionality as it’s a security risk having shell scripts within the app bundle.

**Comment by emendelson** [comment]
Would you consider leaving them in, with some sort of requirement that a specific option be set by the user? Or at least make it possible to build with them included. I realize that may not be enough, but this feature is spectacularly useful for the bundles that I support.

**Comment by Gcenx** [comment]
I need to think of a good way to handle the scripts then as by default I will want those disabled for security reasons.

Maybe a plist entry with a checkbox in Wineskin.app to enable the shutdown/startup scripts might be sufficient.

**Comment by emendelson** [comment]
That would be terrific if it's possible. For what it's worth, Big Sur (and presumably recent versions) asks permission when the startup script accesses the desktop or documents folders, as mine do. The startup script makes it possible for me to perform complex setup steps that would be impossible without it.

**Comment by Gcenx** [comment]
@emendelson I just reverted the change in the newly pushed wrapper, I can deal with a checkbox or something else later as I don't plan on a major revision for sometime.

**Comment by emendelson** [comment]
@Gcenx - Thank you for that! Much appreciated.
