### ISSUE TITLE
2.9.0.8 damaged

### ISSUE THREAD

**Issue by EthabTab** [Gcenx/WineskinServer#118]
I downloaded the latest version of wineskin but whenever I try to open it, it says its damaged. Send help pls

**Comment by emendelson** [comment]
In a terminal, type this, followed by a space:

`xattr -rc `

Then drag the app into the terminal and press Enter.

**Comment by Gcenx** [comment]
This is explain directly in the readme see https://github.com/Gcenx/WineskinServer#gatekeeper

**Comment by EthabTab** [comment]
EthabTab@Ethan's-MacBook-Pro ~ % xattr -rc /Users/EthabTab/Downloads/Wineskin-2.9.0.8.app
xattr: No such file: /Users/EthabTab/Downloads/Wineskin-2.9.0.8.app/drive_c

**Comment by Gcenx** [comment]
Why did you directly download the master wrapper?, you should never be doing this outside of beta testing a new wrapper.

Winery downloads the master wrapper for you, if that’s not the case you need to trash the currently installed copy of winery and install the correct version.

**Comment by EthabTab** [comment]
sorry im not that great with this kinda stuff, and the reason i downloaded it directly was because it had worked for me in the past, sorry for my brain being dumb
