### ISSUE TITLE
Need help with running apps with compatibility

### ISSUE THREAD

**Issue by vixxpy** [Gcenx/WineskinServer#119]
Does anyone know how to run apps with compatibility??(like the properties one)
I changed my stuff on Wineskin to a staging engine but it still doesnt have that options, it only has added security....

[scrnli_5_30_2021_3-40-34 PM](https://user-images.githubusercontent.com/84942280/120117889-81e01e00-c15d-11eb-9e04-9c51899e9b02.png)
This thing ^^

**Comment by Gcenx** [comment]
Launch winecfg and change the windows version there.
