### ISSUE TITLE
Full screen apps?

### ISSUE THREAD

**Issue by The-SamminAter** [Gcenx/WineskinServer#12]
I noticed in the settings for the newer engines (CX18.5, Wine4.7x64) there is no built-in full screen option. Is there a way to make applications always launch in full screen?

**Comment by Gcenx** [comment]
> I noticed in the settings for the newer engines (CX18.5, Wine4.7x64) there is no built-in full screen option. Is there a way to make applications always launch in full screen?

Applications that support fullscreen will support fullscreen, if your taking about Virtual Desktop that would require XQuartz to be installed onto your system as the custom WineskinX11 from doh123 was removed as it was extremely old and only supported 32Bit.
