### ISSUE TITLE
Keyboard Input stops working after changing windows

### ISSUE THREAD

**Issue by StuartMesham** [Gcenx/WineskinServer#120]
- OS: 10.15.7
 - Winery version: 1.8.4.2
 - Master Wrapper version: Wineskin-2.9.0.8
 - Engine version: WS11WineCX64Bit20.0.2
 - Hardware: MacBook Pro 13" mid-2012

I downloaded and installed Among Us in a wineskin using legendary-gl. I can start the game and it runs fine. I can join online games and play normally. However, when I switch to a different window (e.g. Finder), use they keyboard and then switch back to the Among Us window. The keyboard inputs no longer work and only some of the in-game buttons that I click on with the mouse work.

**To Reproduce**

Click create new wrapper
Call it anything (e.g. Among Us)
Click view in finder

Double click the newly created Among Us.app
Click install software -> choose setup executable

Give it this one:
Download https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64.exe

On the installer window, check the box “Add Python 3.8 to PATH”
Click install now

Click “ok” on the “choose executable” dialogue that comes up.

Once that is done:
Go to advanced -> tools -> command line (cmd)
Type: pip install legendary-gl
Press enter

Type legendary auth
Press enter

Some windows should pop up, one of them being your browser with something like this:

{"redirectUrl":"https://epicgames.com/account/personal","sid":"bd62043u5yhw38uy4h87wf347”}

Copy the thing that looks similar to bd62043u5yhw38uy4h87wf347

On the terminal, right click -> edit -> paste
Press enter

Copy this line:
legendary install 963137e4c29d4c79a81323b8fab03a40

In the terminal, right click -> edit -> paste
Press enter
It should then say “Do you wish to install Among Us?”
Type Y and press enter

Wait for it to download Among Us

echo legendary launch 963137e4c29d4c79a81323b8fab03a40 > C:\launch.bat

Close the terminal

In the original window go to configuration -> Window EXE
Copy and paste this into it:
"C:\launch.bat" 

Close this setup

Open Among Us.app

Play the game, switch to another window, use the keyboard, switch back to the game window. The keyboard input no longer works.

**Comment by Gcenx** [comment]
This issue is unfortunately a wine problem.

To avoid this I play my games in windowed mode and for games that don't support a windowed mode I use [DxWnd](https://sourceforge.net/projects/dxwnd/)

**Comment by StuartMesham** [comment]
@Gcenx Thanks. Do you know how I can switch to using X11 (instead of the native Mac drivers)? I am hoping that if I switch to X11 then this fix https://www.reddit.com/r/linux_gaming/comments/ix6qh0/playing_among_us_using_wine_and_issue_with/g75a272?utm_source=share&utm_medium=web2x&context=3 might work for me.

However, when I go to set screen options -> X11 and then try start the application. It crashes and I get these logs:

000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x9e03
001d:err:plugplay:process_IOService_Device object 0x9c07
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x9c0b
001d:err:plugplay:process_IOService_Device object 0x650b
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x6707
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x670b
001d:err:plugplay:process_IOService_Device object 0x980b
001d:err:plugplay:process_IOService_Device object 0x6907
001d:err:plugplay:process_IOService_Device object 0x6c07
001d:err:plugplay:process_IOService_Device object 0x9303
0009:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:ntdll:FILE_GetNtStatus Converting errno 8 to STATUS_UNSUCCESSFUL
0025:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0027:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0029:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
002e:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
002e:fixme:sync:NtQueryInformationJobObject stub: 0x54 9 0x21f4c0 144 0x21f430
0030:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0030:fixme:msvcrt:_configure_wide_argv (1) stub
0030:fixme:msvcrt:_initialize_wide_environment stub
0030:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv6 not supported in this platform
0030:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv4 not supported in this platform
0033:err:user:load_desktop_driver failed to load L"C:\\windows\\system32\\winex11.drv"
0033:fixme:ntdll:create_logical_proc_info Relationship filtering not implemented: 0x4
0033:fixme:ntdll:create_logical_proc_info Relationship filtering not implemented: 0x4
0033:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0033:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0033:err:winediag:nodrv_CreateWindow The explorer process failed to start.
0033:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0030FA84
0036:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FD1C

**Comment by Gcenx** [comment]
This isn't possible as `wine32on64` doesn't support X11 display driver only macDriver.
