### ISSUE TITLE
Tried to install wine 6.0 but doesn't show up after being installed

### ISSUE THREAD

**Issue by futurelucas4502** [Gcenx/WineskinServer#121]
**Environment (please complete the following information):**
 - OS: 11.4
 - Winery version: 1.8.4.2
 - Master Wrapper version: ??
 - Engine version: N/A
 - Hardware: MacBook Pro 2019

**Describe the bug**

I installed WS10Wine6.0 but it doesn't appear in the list of engines or in the download a new engine list.

**To Reproduce**
Describe the steps to reproduce the behavior:
I installed WS10Wine64bit6.0 but it didn't work with my program so I went to install WS10Wine6.0 and yeah

**Expected behavior**

For it to appear in the installed engines page

**Screenshots**
My installed engines:
![image](https://user-images.githubusercontent.com/48055553/120199815-8bc85680-c21b-11eb-907b-7153d94602e9.png)
Add an engine as u can see WS10Wine6.0 is missing
![image](https://user-images.githubusercontent.com/48055553/120199879-984caf00-c21b-11eb-8a96-5568cd639840.png)

**Additional context**

**Comment by futurelucas4502** [comment]
If someone could tell me the folder the engines are stored in i could remove it manually and see if that fixes anything

**Comment by Gcenx** [comment]
macOS Catalina and later don’t natively support running 32Bit binaries so those are hidden in the main menu, the download menu just reads the available list here on GitHub.

Your only options for running 32Bit Windows binaries are WS11 Engines, this is explained in the [README.md][https://github.com/Gcenx/WineskinServer#macos-catalina-support]

Downloaded engines can be found in
```
~/Library/Application Support/Wineskin/Engines
```

**Comment by futurelucas4502** [comment]
Ah that makes sense and thank you for the directory!
