### ISSUE TITLE
Winehq Engine Launch fails to start apps with "terminals database is inaccessible"

### ISSUE THREAD

**Issue by airminer** [Gcenx/WineskinServer#122]
**Environment:**
 - OS: 11.2.3
 - Winery version: 1.8.4.2
 - Master Wrapper version: Wineskin-2.9.0.8
 - Engine version: WS11WineCX64Bit20.0.2
 - Hardware: MacBook Air (M1, 2020)

**Describe the bug**
"Winehq engine launch" fails to launch any windows apps

**To Reproduce**
- Create empty wrapper
- Open launcher
- Click Advanced
- Click Tools
- Click "Winehq Engine Launch"
- Type "wine explorer"

Prefix is created, but execution fails
Last error message: terminals database is inaccessible

**Expected behavior**
The explorer window appears

**Additional context**
Launching applications from the tools menu works as expected.
Pointing the WINEPREFIX variable to $WINESKINWINEPREFIX doesn't fix the issue.
The above bug appeared some time after upgrading to the 2.9.0.8 master wrapper.

**Comment by Gcenx** [comment]
Ah yes I haven't rebuilt WineCX engines yet to account for the ncurses change yet (still working on some patches)
Here is a copy of ncurses6 that should work for you [i386_x86_64.zip](https://github.com/Gcenx/WineskinServer/files/6571939/i386_x86_64.zip)

Unpack the dylibs and replace the versions within the wrappers /Frameworks directory with those.

**Comment by airminer** [comment]
Thanks, that worked!
