### ISSUE TITLE
Wineskin doesn't ask for microphone permissions

### ISSUE THREAD

**Issue by Gravarty** [Gcenx/WineskinServer#123]
macOS Big Sur 11.4 Official
Winery version: 1.8.4.2
Master Wrapper version: 2.9.0.8
Engine version: 20.0.0.2
Hardware: Mac mini 2020 (Macmini9,1) M1

So i've just found a big problem that causes many applications like Grand Theft Auto V and even Audacity to just not work because macOS doesn't show the "Allow microphone access" window. GTA V refuses to load map files and just stucks on the loading screen and Audacity also stucks on the splash screen. The only way to bypass is to unplug the microphone. Audio Plugins used for recording OBS desktop audio also make then unusable. The application is also not shown in System Settings, so there's no way of granting it. I also tried to force it by editing the TCC file but that also didn't work.

EDIT: CX19.0.2-2 doesn't have this issue and asks for permissions when required and doesn't crash when denied.

**Comment by Gcenx** [comment]
I’ll need to retest this but this really doesn’t make sense as CX19.0.2-2 only has working permission prompts as I’d extracted the changes from CX20.0.1 into a patches that was then applied onto CX19.0.2.

I do remember this was functional and while trying to get the Rockstar launcher mess working last night to play my copy of GTAV via Steam, I tried using a bypass and the wrapper did request mic permissions but this was CX20.0.2-1 (the PortingKit version of CX20.0.2)

**Comment by Gravarty** [comment]
Okay, that's really weird. I tried so many things to get the permission prompt to show up. This is why i also installed Audacity because it obviously needs permissions but that also didn't help. I completely reinstalled GTA V using CX19 and this time it also didn't ask for permissions (not enabled in System Settings) and for some weird reason the game loaded just fine but the pause menu was completely broken. I'll try the PortingKit version later.

**Comment by Gcenx** [comment]
I couldn’t get Audacity to request permissions period nor even find an audio output device, yet CrossOver-20.0.4 does work so I’m wondering if Apple has made any recent changes for microphone permissions.

PortingKit is fully code-signed and notarized so when it launches a wrapper that’s what requests the permissions and those get inherited by the launched wrapper.

That or the tcc database has become even more fragile and needs be wiped again...

**Comment by Gravarty** [comment]
Okay, i just downloaded Porting Kit, enabled all the experimental features and installed GTA V with DXVK. 
It immediately asked for microphone permission after the legal screen ended (this is where GTA V checks for sound/microphone and would stuck on the first loading screen image if it can't access it) and everything works fine.

https://i.imgur.com/Ipi2M9W.png
https://i.imgur.com/YIVcc0T.png

sorry for the foreign language shown in the screenshots.

**Comment by Gcenx** [comment]
Try to replace the master wrappers info.plist with the provided copy, just make sure you remove the quarantine flag before extracting [Info.plist.zip](https://github.com/Gcenx/WineskinServer/files/6591848/Info.plist.zip)

```
xattr -drs com.apple.quarantine <file>
```

![Screen Shot 2021-06-03 at 9 15 50 AM](https://user-images.githubusercontent.com/38226388/120651059-58204300-c44c-11eb-8281-cc74a4091ff6.png)

**Comment by Gcenx** [comment]
The above would only apply to newly created wrapper unless you wipe the relevant permission within TCC database, but each newly created wrapper did correctly request Microphone permission using WineCX20.0.2 when Audacity launched.

**Comment by Gravarty** [comment]
Oh nice! Yes, that actually fixed it! I just noticed today how many games just crash on launch or freeze by simply opening the game settings (Counter-Strike: Source and Black Mesa). Unbelievable how this silly permission breaks so many games in the strangest way possible.
