### ISSUE TITLE
Issues when trying to run the game

### ISSUE THREAD

**Issue by cattytian** [Gcenx/WineskinServer#124]
- **OS: Catalina** 10.15.4
 - **Winery version**: Wineskin-Winery-1.8.4.2
 - **Master Wrapper version**: Wineskin 2.9.0.8
 - **Engine version**: WS11WineCX64Bit20.0.2
 - **Hardware**: MacBook Air (2017)

**Describe the bug**: So the test run appears as success, but the game isn't opening and gave all these gambled codes. 

**To Reproduce**: 
Clicked into Wineskin advanced
Clicked Test Run in configuration
Test run success, but the app sim

**Expected behavior**: The window pops out, and the game starts.

**Screenshots**
![截屏2021-06-03 下午2 40 27](https://user-images.githubusercontent.com/64234892/120588989-7fdacf80-c47b-11eb-9b38-e1bbecf4111e.png)

**Additional context**: Log from the test run:
000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x9403
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x9407
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x940b
001d:err:plugplay:process_IOService_Device object 0x630f
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0027:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0025:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
0025:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0025:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0025:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0025:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0025:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0025:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0025:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0025:fixme:win:WINNLSEnableIME hwnd 0x0 enable 0: stub!
0025:fixme:win:WINNLSEnableIME hwnd 0x0 enable 1: stub!

**Comment by Gcenx** [comment]
Please modify the issues and fill out the provided issues template.

**Comment by Gcenx** [comment]
Didn’t mean to close this...

Whats the title you were attempting to launch?

**Comment by cattytian** [comment]
![截屏2021-06-05 下午1 18 50](https://user-images.githubusercontent.com/64234892/120878560-ad04ba80-c600-11eb-8388-3502d568893a.png)

**Comment by cattytian** [comment]
Thank you for reminding me the name of the file, I changed it into all English and it works, thank you
