### ISSUE TITLE
Shell scripts for getting the unix paths that correspond to Wineskin drive letters.

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#125]
This isn't a request, but I hope the information might be helpful to someone, and maybe (in an improved form) could go on the wiki.

For a project, I need to be able to identify the macOS path of the DOS drives in a Wineskin. Here are two barebones scripts that (1) create two files, one with a list of current drive letters, the other with a corresponding list of their unix paths and (2) let you query those lists to get the path of a specific driveletter.

For simplicity, I'll assume that the two scripts are in your dosdevices folder, though in practice you'll probably want to put them somewhere else. In my project, I've placed the commands from the first script into my WineskinStartupScript so that the letters and paths are available as needed afterwards (requires a Wineskin version that supports the startup/shutdown scripts, and assumes that a new drive letter hasn't been added after startup).

**devicelist.sh** - this creates the list of drive letters and the list of unix paths:

```
#!/bin/bash

cd "$(dirname "$0")"

ls -lF | grep @ | cut -d: -f2 | cut -d ' ' -f2 >letters.txt
ls -lF | grep @ | cut -d@ -f2 | cut -d '>' -f2 >tmp.txt
cat tmp.txt | tr -d "[:blank:]" >paths.txt
rm tmp.txt
```

**getpath.sh** - use the lower-case letter of the DOS drive as a parameter to get the unix path, as in `getpath.sh d` and outputs the path to the file drivepath.txt:

```
#!/bin/bash

cd "$(dirname "$0")"

linenum="$(grep -n "$1" letters.txt | head -n 1 | cut -d: -f1)"
head -n $linenum paths.txt | tail -1 >drivepath.txt
```

I know basically nothing about shell scripting, so I simply modify things that I find on the web. I've read the warnings about why you should never parse the output of `ls` as I do in the first script, but, for this specific purpose, there seems to be no problem with it. Of course, in the second script, you could put the drivepath into a variable by doing something like this (not tested by me, but should probably work):

`drivepath="$(head -n $linenum paths.txt | tail -1)"`

This is probably the least efficient way of accomplishing all this. If anyone knows a better method that's been available all along, I would be grateful to hear about it.

**Comment by Gcenx** [comment]
Unless I’m missing something it sounds like your trying to duplicate the functionally of [winepath](https://wiki.winehq.org/Winepath)

**Comment by emendelson** [comment]
You're not missing anything - I didn't know about winepath until you told me...

I'm trying to use these paths in shell scripts that will get launched by winebrowser.exe. Now I'll try to figure out how to use the output of winepath in a shell script launched by winebrowser.exe. Thank you for telling me this. I should have guessed that someone would have thought of this years ago.
