### ISSUE TITLE
problema con microsip.exe

### ISSUE THREAD

**Issue by gio92pes** [Gcenx/WineskinServer#126]
**Environment (please complete the following information):**
 - OS: [e.g. macOS version 11.3.1
 - Winery version:2.8
 - Master Wrapper version: 2.9.0.8
 - Engine version: ws11winecx64bit20.0.2
 - Hardware: [e.g. MacBook Pro 13 2020 intel i5

**Describe the bug**
I have the problem with the microsip software, the installation is successful and the program starts, but when I try to type any number on the numeric keypad the microsip program crashes
**To Reproduce**
Describe the steps to reproduce the behavior:
[e.g.
1. open microsip
2. Click on a number on the numeric keypad

**Expected behavior**
I managed to start the program and log in without any problem despite being a user that can only be connected in vpn, I did not expect a block in the final part, I assume there are missing dlls or libraries but I cannot understand which ones.

**Screenshots**
I
<img width="344" alt="Schermata 2021-06-06 alle 01 05 17" src="https://user-images.githubusercontent.com/85418739/120907640-72803980-c663-11eb-8682-ec130cb42972.png">

**Comment by Gcenx** [comment]
This might be related to #123, test again using “Winehq Engine Launch” to use the Engine like a Winehq package.

**Comment by gio92pes** [comment]
I replaced the info.plist file as per discussion # 127 but I haven't solved it, could you give me more detailed info on how to move, I'm groping in the dark

**Comment by gio92pes** [comment]
sorry #123

**Comment by Gcenx** [comment]
This is related to #123, trash your wrapper and make a new one using the 2.9.0.8-1 that was pushed last night.

Using 2.9.0.8-1 when clicking any number the wrapper requests access to the Microphone and then doesn't crash.
