### ISSUE TITLE
Unsuccesful process when installing any  windows software on Mac

### ISSUE THREAD

**Issue by rizalstrato** [Gcenx/WineskinServer#127]
**Environment**
 - OS: macOS 11.4
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.0.8
 - Engine version: WS11WineCX64Bit20.0.2
 - Hardware: Macbook Pro Mid 2012 13" Non Retina

**Describe the bug**
Everytime i want to install an .exe 64bit windows software, it wil show this error.

**To Reproduce**
Describe the steps to reproduce the behavior:
1. Go to Wineskin Winery
2. Click on Create New Blank Wrapper
3. Open the new wrapper
4. choose the .exe installer
5. See error]

**Expected behavior**
Installation will start and then finishes normally.

**Screenshots**
![Screen Shot 2021-06-06 at 5 14 15 PM](https://user-images.githubusercontent.com/81573561/120921053-0e558800-c6ec-11eb-85d0-56453044c511.png)

**Additional context**
Am i doing it wrong? or do i have to erase/uninstall and install a fresh wineskin winery?(in case maybe i made some wrong step when installing the wineskin winery)

Please help me.

**Comment by Gcenx** [comment]
What are you attempting to install here as you’ve not provided that information.

**Comment by Gcenx** [comment]
Closing, please provide the requested information and tag me so I can reopen this issue.
