### ISSUE TITLE
dxvk_macos.verb is broken

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#128]
**Environment (please complete the following information):**
 - OS: N/A
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.8.0.8-1
 - Engine version: Any 64Bit Engine
 - Hardware: M1 Mac mini

**Describe the bug**
`dxvk_macos.verb` fails to extract after downloading.

**To Reproduce**
`dxvk_macos.verb` fails to find downloaded archive.

**Expected behavior**
Install without issue.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Redecorating** [comment]
Same occurs on an Intel MacBookPro16,1

**Comment by Gcenx** [comment]
@Redecorating this would have happened to everyone, I’d opened the issue mostly as a reminding to fix the issue once I’d gotten home from work.
