### ISSUE TITLE
No new executable found

### ISSUE THREAD

**Issue by ddddddzezeezeze** [Gcenx/WineskinServer#129]
**Environment (please complete the following information):**
 - OS: [e.g. macOS version (10.13, 10.14, 10.15.4, 11...)]
 - Winery version:
 - Master Wrapper version:
 - Engine version:
 - Hardware: [e.g. MacBook Pro 13 2016, Mac mini 2020...]

**Describe the bug**
No new executable found appears when executing any .exe Xquartz is launched SIP deactivated on mac os big sur its just not working I think this app is broken 

**To Reproduce**
Describe the steps to reproduce the behavior:
[e.g.
4. See error]

**Expected behavior**
I except the app to work 
**Screenshots**

**Additional context**
No new executable found

**Comment by Gcenx** [comment]
Please fill out all fields fully and also provide the name and possibly a link to the software you’ve attempted to use.

Also as your running macOS Big Sur there’s no need to disable SIP nor is there a reason to have install XQuartz.

**Comment by emendelson** [comment]
Because you haven't given any real information ("different softwares" doesn't identify any) you can't expect any help here. The application works correctly when it is set up correctly. I hope someone will close this thread.

**Comment by ddddddzezeezeze** [comment]
I have tried to use InternetExplorer, Winrar and vlc.exe none worked also
tried a game

Le mar. 15 juin 2021 à 14:02, emendelson ***@***.***> a
écrit :

**Comment by ddddddzezeezeze** [comment]
I spent all night installing different versions of wineskin it just doesn’t
work I got other things to do if you can’t help me then okay

**Comment by Gcenx** [comment]
You have still not updated the first post with the required information.

You’ve disabled SIP when it’s not required nor recommended for your macOS version, not provided the Winery/Wrapper/Engine being used.

- WinRAR 64Bit is known not to work
- Internet Explorer. Why?
- VLC why?
- What game?

**Comment by emendelson** [comment]
As gcenx says, "VLC why?" It exists for macOS anyway.

However, the Windows version of VLC does in fact run correctly in Winery 2.9.0.8-3 with the WS11WineCX64bit200.2 engine under Big Sur.

Audio and video both play back correctly, though you will need to experiment with VLC's Tools menu to find the correct output settings for video and possibly for audio. Video works both in a window and full-screen.

**Comment by Gcenx** [comment]
@ddddddzezeezeze as you’ve not edited the first post fully filling out the template, nor really examples your issue I’ll be closing this.

If however you’ve managed to launch and install something and Wineskin didn’t find it that’s usually due to installing into your user directory over the wrappers wineprefix “Program Files” directly, an executable can also be manually selected.

**Comment by ddddddzezeezeze** [comment]
I tried to launch different Japanese little games that does not need any installer none worked when 4 months ago it worked perfectly. I also tried to launch the .exe of Winrar here : https://www.clubic.com/telechargement-en-cours/37764-0-winrar.html <https://www.clubic.com/telechargement-en-cours/37764-0-winrar.html> 

winrar_6-01_fr_9632_32.exe Again it does not work I don’t need to install the thing anywhere since its an executable I TRIED WITH EVERY EXE I COULD FIND BUT NOTHING IS WORKING ON THIS APP

**Comment by Gcenx** [comment]
You’ve not provided a LastRunWine.log showing any problems, the issue template was complete disregard.

You keep saying Japanese games but haven’t provided a name or link to any of these titles.

The provided link for winrar is not the official source and was shown function already, it’s also not needed when keka can simple be installed to unpack rar archives (and plenty of other free alternatives for unpacking archives)

At this point nobody can help you as you’ve not provided any of the requested information showing what possibly be wrong.
