### ISSUE TITLE
Run Windows App as Administrator

### ISSUE THREAD

**Issue by highjeans** [Gcenx/WineskinServer#132]
**Is your feature request related to a problem? Please describe.**
I am trying to run Among Us on my Mac using steps from a subreddit here: [https://www.reddit.com/r/AmongUs/comments/iz1gxn/guide_getting_among_us_running_on_macos/?utm_source=share&utm_medium=web2x&context=3](url)
However, I got Among Us from Epic Games, and I need it to run as Administrator in order for the game to be installed.

**Describe the solution you'd like**
I want there to be a way to run the app as administrator.

**Comment by Gcenx** [comment]
I’ve had no luck running the Epic games client on macOS, you’d need to use Legendary or of one the third-party GUI’s that provides a native macOS version then use that in combination with `wine-crossover` package you can install via my brew tap.

**Comment by highjeans** [comment]
Can you please provide a link to downloading Legendary?

**Comment by Gcenx** [comment]
Legendary is a CLI app and doesn’t officially support macOS however there’s a reboot binary https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/public/bin/darwin/legendary

That linked project also provides a macOS client that _can_ be used in combination with my `wine-crossover` package.

**Comment by highjeans** [comment]
Thanks!

**Comment by highjeans** [comment]
Do you know where I can get the wine-crossover package, I found it a few weeks ago but I can't find it now.

**Comment by Gcenx** [comment]
@highjeans you get my `wine-crossover` packages from https://github.com/Gcenx/homebrew-wine

**Comment by highjeans** [comment]
Thanks so much!
