### ISSUE TITLE
Appdata/Application support Mappings

### ISSUE THREAD

**Issue by hypersun-pro** [Gcenx/WineskinServer#133]
I was porting Mineways to MacOS when I found that automatic detection for Minecraft world is not working. I dig deeper into the problem. Mineways looks into C://users/(username)/AppData/.minecraft to scan for any Minecraft world, which doesn't work because the directory doesn't actually exist. I wish ~/Library/application support/ can be mapped to %AppData% so applications can use them. If possible, custom directory mapping would be something wonderful.

**Comment by Gcenx** [comment]
I really don’t see this as being a very good idea, even upstream wine doesn’t do along with overall I don’t see any real benefit to this overall as we don’t want Windows app data to potentially overwrite something that’s macOS specific.
