### ISSUE TITLE
Issue loading steam

### ISSUE THREAD

**Issue by MultiverseQueen** [Gcenx/WineskinServer#134]
Essentially, when I load up windows steam, it works alright except I cannot visit the store or download anything. It also lags a bit when I start it up.
As of now, it will not start up at all, staying on the "logging in" page, so I cannot grab a screenshot.

**Comment by Gcenx** [comment]
You need to fill out the provided issue template, tag me once it’s so plate filled out and I’ll reopen the issue.

**Comment by MultiverseQueen** [comment]
I'll just remake my post via the template I guess
