### ISSUE TITLE
Steam doesn't work properly

### ISSUE THREAD

**Issue by MultiverseQueen** [Gcenx/WineskinServer#135]
Information:
 - OS: Mac OS catalina, version 10.15.6
 - Winery version: Unofficial update/v1.8.4.2
 - Master Wrapper version: Wineskin-2.9.0.8-3
 - Engine version: WS11WineCX64Bit19.0.2-2
 - Hardware: Imac 2020 
 - Application/Game Name: Steam (windows version)
Bug:
There is some lag when the Wineskin (Renamed to Steam) opens and the application, when opened, boots up but does not show options to download, open store or any other typical steam options. Currently it's taking longer and longer to open the app.

Replication:
1. Open Wineskin application. 
2. Allow Steam to boot up
3. Click on the options in Steam to test if it works.

Expected behavior:
I expect Steam to work like it does on the Mac version but with the capability of running Windows games. Being able to click on the menus and get them to work properly and download applications from the application's store. 

Screenshots:
None, sadly, as the application lags my computer too much to do so. 

**LastRunWine.log**

Unsure what this is/how to access this. Can add this info in a comment if a way to access this info is provided.

**Comment by Gcenx** [comment]
If recommend using `WS11WineCX64Bit20.0.2-2` unless it’s some obscure old game that requires CX19.

As you didn’t explain _how_ you’ve installed Steam I’ll assume you installed it manually, that’s not a good idea install Steam via the winetricks menu as this configures some required overrides.

After install via the winetricks menu manually select Steam.exe and next add the following.
```
-allosarches -cef-force-32bit -udpforce
```

So the box should look something like
```
C:\Program File(86)\Steam\Steam.exe -allosarches -cef-force-32bit -udpforce
```

The first two options gets CEF working and the last launch option works around the new bug and forces Steam to use udp for secure connections.

**Comment by MultiverseQueen** [comment]
https://www.youtube.com/watch?v=vkQj0lZFz6I&t=509s this is the tutorial I used to install steam. 
I assume I have to install the new engine and then reinstall windows steam?
Also, how do I add the following? What do I pull up to add this? 
As you can see, this is kind of...Foreign to me. So yeah, excuse my barrage of questions.

**Comment by MultiverseQueen** [comment]
Okay, I've tried reinstalling it with the 20.0.2-2 version but it still doesn't work. How do I access the wine tricks menu?

**Comment by Gcenx** [comment]
The YouTube _guide_ you linked shows how to access and use the winetricks menu.

As for the log it’s also shown but I’ll add more detailed instructions when I’m free.

**Comment by MultiverseQueen** [comment]
Ok
