### ISSUE TITLE
Winery 1.8.4.2 Wrappers don't run on  ElCapitan 10.11.6

### ISSUE THREAD

**Issue by macuserguru** [Gcenx/WineskinServer#137]
done - no solution found
**Environment (please complete the following information):**
 - OS: 
     ElCapitan 10.11.6
 - Winery version: 1.8.4.2
 - Master Wrapper version: Wineskin-2.9.0.8-3
 - Engine version: WS11WineCX20.0.2.tar, WS11WineCX64Bit20.0.2.tar
 - Hardware: 
 - Application/Game Name 

**Describe the bug**

All created Wrappers not runable on ElCapitan 10.11.6
Error message:
Auf Ihrem Computer ist OS X 10.11.6 installiert. Das Programm erfordert OS X 10.13 oder neuer.
OS X 10.11.6 is installed on your computer. The programme requires OS X 10.13 or newer.

How do I get Winery to work on ElCapitan?
Which versions of the individual files do I have to install?

IgnoredEngines.txt contains
WS11WineCX64Bit20.0.2
WS11WineCX20.0.2

**To Reproduce**

First start and Install Engines, create Wrapper

**Expected behavior**

**Screenshots**

(https://user-images.githubusercontent.com/4521744/125305338-90aa1b00-e32e-11eb-9e24-d2dc4d6bd094.png)

**LastRunWine.log**

**Additional context**

**Comment by podycust** [comment]
Thats because its only support on 10.13 High Sierra or newer as the error message said!

**Comment by macuserguru** [comment]
Hardware: MacBook Pro (15 Zoll, Late 2008), 2,4 GHz Intel Core 2 Duo, RAM 8 GB 1067 MHz DDR3

**Comment by macuserguru** [comment]
Which version of programs I must install, that runs on ElCapitan 10.11.6?

**Comment by macuserguru** [comment]
Where I could download the latest master wrapper that runs on ElCapitan  10.11.6?
I have the base app Wineskin Winery 1.7 and the latest Wineskin Winery 1.8.4.2

**Comment by Gcenx** [comment]
I no longer support anything below macOS High Sierra, see #82 as you can see nobody objected to this.

Unless someone want to take on the maintenance burden for supporting these legacy versions of OS X/macOS I won’t be re-adding support.

#### LegacySupport requirements;
The interested party would need to add static libcurl into all components of Wineskin due to the GitHub TLS requirements changes.

All compatible dylibs would be required to be compiled on the targeted version of OS X/macOS, so if 10.8 is desired all required dylibs need to be built on this version then have `@rpath` fixed up correctly.

OS X 10.8 would be the minimum that would possibly be targeted without causing me an extreme headache but OS X 10.9 would be preferable as it’s easier to install Xcode etc.

**Comment by macuserguru** [comment]
Thank you!
I'm currently using Crossover, want to buy an M1 Mac in the foreseeable future and will only take a small part of the Windows programmes with me to the new computer. 
So I am looking for ways to run them with less effort. Mostly these are just exe files without an installer. But one programme needs .NET
One programme accesses the audio interface.
Once I have the M1 Mac, I will upgrade one of my old Macs to 10.13 High Sierra using macOS patchers (you can find them on the net).
Greetings
Fritz

**Comment by emendelson** [comment]
The original (pre-Gcenx) Wineskin Winery is here:

https://sourceforge.net/projects/wineskin/files/Wineskin%20Winery.app%20Version%201.7.zip/download

You may be able to get support for it from the sourceforge site, but, basically, you're on your own with the old version.

**Comment by Gcenx** [comment]
You must be using some old version of crossover as they list CrossOver-16 as minimum of macOS Sierra.

If you really need modern wine on your version of macOS you’d be better served using [macports-wine](https://github.com/Gcenx/macports-wine) this will allow you to use the most recent versions of wine.

**Comment by Gcenx** [comment]
@emendelson the deleted comment about using the legacy Winery unfortunately won’t be useful as doh123 site is offline meaning the need to then track down compatible Engines.

_Technically_ [Wineskin-2.9.0.7-rc4.app.tar.7z](https://raw.githubusercontent.com/Gcenx/WineskinServer/51a13480bc352512f136b1de68a37bf856862bc5/Wrapper/Wineskin-2.9.0.7-rc4.app.tar.7z) could be used on legacy versions of macOS but I don’t want to provide support _if_ theres any unforeseen issues with doing this. This wrapper can be used with  the current version of Winery and engines should also work using it.

**Comment by macuserguru** [comment]
> You must be using some old version of crossover as they list CrossOver-16 as minimum of macOS Sierra.
> 
> If you really need modern wine on your version of macOS you’d be better served using [macports-wine](https://github.com/Gcenx/macports-wine) this will allow you to use the most recent versions of wine.

My CrossOver version: 19.0.1 (19.0.1.32209) that run on ElCapitan.

**Comment by Gcenx** [comment]
@macuserguru guess CodeWeavers removed mentions of anything below 10.12 with the site revamp.

If you really require running on macOS 10.11 use the older master wrapper I linked above just ensure to remove the quarantine flag before extracting and don’t extract using keka or it will add the quarantine flag to everything once the archive is extracted.

Then place the extract master wrapper into ~/Library/Application Support/Wineskin then Winery will be able to use it just don’t upgrade to the current wrapper.

All current Engines _should_ function but anything below 10.13 was never extensively tested, even my own 10.9 tests have only been basic functionality testing.

**Comment by macuserguru** [comment]
Now I test it on my second old Mac - MB 13" early 2009, ElCapitan, 4GB RAM, 500GB SSD. This is my test Mac.

Double click on Wineskin-2.9.0.7-rc4.app 
„Wineskin is currently busy Please wait .......“
If I stop this app, it comes this message:
„Error while writting file: The folder “exec4145110484.bat” doesn’t exist.“

I copy the wrapper in ~/Library/Application Support/Wineskin as you wrote

Am I doing something wrong?

**Comment by Gcenx** [comment]
@macuserguru you don’t directly run the master wrapper it will corrupt it. I’d added a check to avoid this in the latest master wrapper.

You download the archive linked above, remove the quarantine flag extract and put into place. Then launch Winery and create a blank wrapper with a selected engine.
