### ISSUE TITLE
Make Cmd-Q send Alt-F4 to Windows app?

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#138]
In almost all macOS apps, Cmd-Q quits the app. In almost all Windows apps, Alt-F4 closes the app. Could Wineskin have an option to send Alt-F4 to the Windows app when the user presses Cmd-Q?

And again, thank you for all the work you've done on this project. It's amazing to see how reliable and smooth it is, even under Big Sur.

**Comment by Gcenx** [comment]
Wine _could_ be patched to accept CMD+Q over the current CMD+Alt+Q?, but if you map CMD to Ctr (I do this by default) this will cause a conflict in some applications.

**Comment by emendelson** [comment]
Aha! I didn’t realize that Cmd-Alt-Q did the job. Someday I should read the docs….

I see your point about Cmd mapped to Ctrl so it’s clearly best to leave things as they are.
