### ISSUE TITLE
macOS Monterey - Not supported (yet)

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#139]
There’s a known problem with how _thread 0_ is handled, CodeWeavers are currently in contact with Apple about this and hopefully will arrive at a solution in due time.

Hopefully Apples fixed this issue, if not and CodeWeavers workaround the issue I’ll provide a patched CX engine so something works.

**Comment by SergeySlice** [comment]
Latest Winery->Wineskin worked in Monterey beta 3 with CX20 and with Sherry engines.
https://www.insanelymac.com/forum/topic/333634-wineskin-unofficial-update/?do=findComment&comment=2762947
It's a pity crashed in Monterey beta 4.

**Comment by Gcenx** [comment]
@SergeySlice until macOS Monterey is released and CrossOver/Upstream are running I’ll be keeping the current stance of not supported to avoid confusion.

I don’t frequent insanelymac very often so might as well respond to the Sherry question here.

> I also should note that the game works with graphical artefact if using engine CX20. So I applied again my Sherry4.2 which is old but works perfect!
>
> Gcenx Can you include it into your distribution? Can be downloaded here

I _could_ provide Sherry for download via Winery, I do have some reservations about providing Sherry directly within Winery.

**Comment by Gcenx** [comment]
Removed comments to avoid potential confusion with the situation, upstream wine nor CrossOver-21.0.0 currently function this may be resolved by Apple before release or CodeWeavers will be forced to workaround the issue with a hack.

**Comment by Gcenx** [comment]
This _might_ have been resolved in Beta5 but I personally won’t be installing to confirm.

**Comment by Gcenx** [comment]
Not real point keeping this open anymore as CrossOver/Wineskin/PortingKit have all been confirmed as still running on the latest macOS Monterey beta version and hasn’t broken since Beta5.
