### ISSUE TITLE
New Engine available (6.0.1)

### ISSUE THREAD

**Issue by GalawynRM** [Gcenx/WineskinServer#140]
https://www.winehq.org/announce/6.0.1

**Is your feature request related to a problem? Please describe.**
Some bugs of the 6.0.0 engine got solved

**Describe the solution you'd like**
Add the engine 6.0.1

**Describe alternatives you've considered**
Is there a way where we can add engines not yet in the list? like "add custom engine"

**Comment by Gcenx** [comment]
Wine-6.0.1 will only be useful for macOS High Sierra and macOS Mojave. Even the cherry picked patches I’d requested for fixing `winemac.drv` on Apple Silicon a `wine64` it’s still mostly useless.

I plan on holding off on providing any newer Engines until after CX21 lands.

if you really need a newer Engine for what ever reason you could repackage one of the Winehq like packages I provide [macOS_Wine_builds](https://github.com/Gcenx/macOS_Wine_builds/releases), but I won’t recommend this as that ships stock libraries that will override the custom libraries provided within the Wineskin master wrapper meaning no macOS DXVK etc.

**Comment by GalawynRM** [comment]
Yes, I have HighSierra, and the 6.0.1 resolve a bug that I met.
I try your Mac_osWineBuilds

**Comment by vesper8** [comment]
@Gcenx CX21 just released!! Woohoo! https://www.codeweavers.com/blog/jschmid/2021/8/3/hello-crossover-21

**Comment by Gcenx** [comment]
@vesper8 it’s strange they made a blog post before sending the usual announcement email…..

We’ll guess I’ll be busy for the foreseeable future working on a decent WineCX21 based engine.

**Comment by Gcenx** [comment]
I’ll upload wine-6.0.1 based engine(s) sometime before or after the next wrapper update still waiting on the _fixed_ crossover-source archive to be uploaded….

**Comment by Gcenx** [comment]
@GalawynRM added Wine-6.0.1 based Engines

**Comment by GalawynRM** [comment]
You're the best!
