### ISSUE TITLE
I can't update my wrapper and I don't have a wrapper :(

### ISSUE THREAD

**Issue by TheDumpling143** [Gcenx/WineskinServer#143]
**Environment (please complete the following information):**
 - OS: 
 - Winery version:
 - Master Wrapper version:
 - Engine version:
 - Hardware: 
 - Application/Game Name 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="289" alt="Screenshot 2021-08-05 at 18 11 15" src="https://user-images.githubusercontent.com/88504187/128392464-2dea3b13-2b0b-43af-bf2c-0e67b6286828.png">

**LastRunWine.log**

**Additional context**

**Comment by Gcenx** [comment]
Your really not providing any information here. I have a feeling you’ve followed a guide video on YouTube and not even read the README

**Comment by TheDumpling143** [comment]
Sorry :I

**Comment by TheDumpling143** [comment]
But thank you so much! Without this great software I couldn't played the games I wanted. I just wanted to thank you :D
