### ISSUE TITLE
Hiding Wine version from games

### ISSUE THREAD

**Issue by Thobro** [Gcenx/WineskinServer#144]
**Is your feature request related to a problem? Please describe.**
Some games require separate Windows and Mac licenses. A game like FFXIV has a Mac client that is simply a Wine wrapper. Thus when attempting to run FFXIV using Wine, it detects it and gives an error that my account has no Mac license. The game detects that I'm attempting to run it in Wine.

**Describe the solution you'd like**
Add support for hiding the Wine version, which is a patch from WineStaging (https://github.com/wine-compholio/wine-staging/blob/master/patches/ntdll-Hide_Wine_Exports/0001-ntdll-Add-support-for-hiding-wine-version-informatio.patch)

**Describe alternatives you've considered**
Run the game in Parallels. Did not work for me on an M1 Mac on the ARM build of W10.

**Comment by Gcenx** [comment]
As there’s an official macOS client already that’s supported by CodeWeavers it’s best to stick to that.
