### ISSUE TITLE
How to actually Lower the Wrapper Version? 

### ISSUE THREAD

**Issue by umajawa26** [Gcenx/WineskinServer#145]
**Problem**
Hello, so i've recently used wineskin for a couple months now and its working properly, but yesterday i accidentally clicked Update on the Wrapper Version and it was updated to Wineskin-2.9.0.8-3. And the problem is now i can't create a new blank wrapper because every time i made one, it wont open the wrapper because i used macOS Sierra (10.12.6) and it now it is requires macOS 10.13 or later. 

![Screen Shot 2021-08-10 at 2 37 04 AM](https://user-images.githubusercontent.com/88684550/128766159-d5017fbc-62a4-45ef-908a-2424d0b069be.png)

![Screen Shot 2021-08-10 at 2 48 13 AM](https://user-images.githubusercontent.com/88684550/128765499-3ff6a792-84c7-443d-bc0b-5cdfffa5cc06.png)

![Screen Shot 2021-08-10 at 2 48 24 AM](https://user-images.githubusercontent.com/88684550/128765846-fae8c4ca-d0ae-4a7d-9789-b1a76a82e8aa.png)

**Solution**
Is there any solution for this problem? Like probably Lower the wrapper Version? or do you have older version of Winery Wineskin that compatible with my macOS (10.12.6)? I cannot update to a higher OS version but I really need to use wineskin like i used to. Please reply to this issue thank you!

**Comment by umajawa26** [comment]
@Gcenx

**Comment by Gcenx** [comment]
No need to tag me I get notified reguardless.

I’ve dropped support for anything below macOS High Sierra so you’ll need to grab an older master wrapper from git history.

**Comment by umajawa26** [comment]
Could you please drop the git history link or the older version of it? i'm kinda lost here...

**Comment by Gcenx** [comment]
This would be the last version that worked below macOS High Sierra [Wineskin-2.9.0.7-rc4](https://github.com/Gcenx/WineskinServer/blob/51a13480bc352512f136b1de68a37bf856862bc5/Wrapper/Wineskin-2.9.0.7-rc4.app.tar.7z?raw=true)

You’ll need to remove the quarantine flag (see the wiki) before extracting then move the wrapper to `~/Library/Application Support/Wineskin/wrapper` remove the newer wrapper leaving only Wineskin-2.9.0.7-rc4.app

**Comment by Gcenx** [comment]
@The-SamminAter while that might be the case all the provided dylibs were compiled targeting macOS High Sierra.

There will be instances where a newer function gets called and this _could_ cause a crash, this has happened during my own testing on mac OS X 10.9 prior.

Strangly according to Slice he’s unable to run the current master wrapper on macOS High Sierra but this could be something with his “Sherry” Engine that’s at fault.

**Comment by umajawa26** [comment]
Okay, ive tried to delete the wrapper and use Wineskin-2.9.0.7-rc4 on the wrapper folder. The wrapper can be opened, but it shows this 

![Screen Shot 2021-08-14 at 12 48 15 AM](https://user-images.githubusercontent.com/88684550/129399385-0f3513c4-c348-44f6-b4e9-f9937a0344ff.png)

It is damaged and can't be opened?

Is this error related to the quarantine flag? because i've search about it but i still have no idea about it.
Sorry i'm new to this so please give an explanation about it, thanks!

**Comment by Gcenx** [comment]
@umajawa26 that’s exactly what happens when the quarantine flag is not removed from the archive before extracting, the information of how to remove that is on the wiki see https://github.com/Gcenx/WineskinServer/wiki#important

**Comment by umajawa26** [comment]
So i already run the code on the terminal and it shows this? any explanation?

![Screen Shot 2021-08-14 at 1 12 11 AM](https://user-images.githubusercontent.com/88684550/129401749-b9ad4f7b-3c9e-4719-912b-958c06e368f2.png)

**Comment by Gcenx** [comment]
Because you need to substitute that path with where the path/file you want to remove the quarantine flag from.

**Comment by umajawa26** [comment]
And what file should i remove? and where is it located?
