### ISSUE TITLE
WineCX21.0.0 - Status “Still on hold”

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#146]
I’m awaiting the resolution of a support ticket from CodeWeavers before dedicating any major effort to the engine development.

As the current master wrapper already provides the latest version of MoltenVK and macOS DXVK I don’t see any need to rush out an Engine based on the currently crossover-sources-21.0.0 sources.

**Comment by Gcenx** [comment]
I’ve been rather quite on this but I have been testing a build of CX21 and this morning needed to install .Net…., .Net doesn’t work so that’s a rather major regression.

I had bumped wine-mono to 6.3 but that doesn’t really help, it at least _started_ the application I was testing but it soon crashed.

**Comment by diegov12** [comment]
I've noticed some of the visual c++ packages aren't installing in crossover 21, specifically the 2005 versions. They seem to install well enough in your rapper, however.

**Comment by Gcenx** [comment]
> I've noticed some of the visual c++ packages aren't installing in crossover 21, specifically the 2005 versions. They seem to install well enough in your rapper, however.

Strange if your a CrossOver customer you should open a support ticket for the issue, I currently have a support ticket open for the mentioned .Net problems in having.

As for Wineskin it makes use of the upstream winetricks project so usually things work unless a package is blocked due to an upstream wine bug. vcrun2005 installed via WineCX21.0.0 without issue so ether it’s one of the many patches I have applied on-top of CrossOver sources or Wineskins just works around what ever issue they are having.

**Comment by palxex** [comment]
Maybe [this](https://github.com/AMD-OSX/bugtracker/issues/6#issuecomment-962511870) will be a good need? Ryzentosh users will happy:)

**Comment by sofakng** [comment]
I'm new to Wineskin Winery but just installed it and noticed WineCX64 21.1 (and 21.0) were missing.  Is this issue tracking the status?

I'm a CrossOver customer but am hoping to try out Wineskin Winery to create separate bottles for each game, etc.

**Comment by Gcenx** [comment]
> I'm new to Wineskin Winery but just installed it and noticed WineCX64 21.1 (and 21.0) were missing. Is this issue tracking the status?

I’ve not updated the status of this issue but it’s a WIP (work in progress), I won’t be providing CX21.0 instead opting to go directly to CX21.1 as that reduced the needed patches considerably.\
Some required patches still need rebasing.

> I'm a CrossOver customer but am hoping to try out Wineskin Winery to create separate bottles for each game, etc.

I’m the BetterTester “Dean aka Gcenx” 🙃

CrossOver creates “Bottles”.

Wineskin creates “Ports” that contain the following;
- Master wrapper (the blank Port template”
- Engine (a wine compile)
- Runtime (the libraries needed to run wine part of the master wrapper)
- Wineskin.app (configuration utility)
- WineskinLauncher (the master wrappets main binary)

The target audience is different from CrossOver that’s more user friendly, for Wineskin some level of wine knowledge will be expected.

**Comment by sofakng** [comment]
Thanks for the information.  I do enjoy the simplicity of CrossOver but I'm also hoping to learn more about Wine itself which is another reason I am looking into this.

I'm still a bit confused on the difference pieces (wrapper, engine, and runtime) but I'll do some research and try to learn.

I'll look forward to seeing a CX 21.1 version!

**Comment by Gcenx** [comment]
CrossOver is commercial third-party GUI that bundles a custom version of wine.

Wineskin is a free third-party GUI that allows using multiple versions of wine.

Winehq is “upstream” aka where wine originally comes from and is also free but mostly ran via terminal.

The components as user would mostly cate about would be;
### Wineskin Winery
This utility is used the download the master wrapper and Engines.\
This is used to create the blank “Ports”

### Wineskin.app
The configuration utility mostly used to help setup the “Port”, the default launch option for blank “Ports”. This lives inside the each “Port”.

### WineskinLauncher
The thing that really runs the “Port”

### Runtime?
Standard app bundles on macOS contains all the necessary libraries within the app bundle, mostly invisible for an end-user but some more advanced user might go poking around here and changing files.

**Comment by sofakng** [comment]
Thanks so much again for the explanation!  You mention CrossOver uses a custom version of Wine but isn't that available as open-source (ie. WineCX?).

Also, I thought CrossOver upstreams most (all?) of their changes since they are the primary (?) contributors to Wine anyways.

**Comment by Gcenx** [comment]
> Thanks so much again for the explanation! You mention CrossOver uses a custom version of Wine but isn't that available as open-source (ie. WineCX?).

CodeWeavers do provide the open-source portion of CrossOver.

WineCX is built from the provided wine sources with additional patches/hacks/reverts etc.\
(WIP CX21.1 currently has 20 additional commits still some more to rebase)

> Also, I thought CrossOver upstreams most (all?) of their changes since they are the primary (?) contributors to Wine anyways.

CodeWeavers will upstream what they can’t but hacks simply are not allowed.

**Comment by tomnic79** [comment]
Cannot download anything from the main app... is there a way to use it in Monterey?

**Comment by Gcenx** [comment]
> Cannot download anything from the main app... is there a way to use it in Monterey?

Winery is showing engines just fine, sounds like you haven’t read the README

**Comment by tomnic79** [comment]
Wineskin is several programs working together, but Wineskin Winery is the main management program.  Wineskin Winery is the only program to download.  It is used to download everything else needed to use the software.  It has a built in update check and will prompt you when a new version is available, and let you auto download and update.

I downloaded the Wineskin Winery 1.7 app from source forge and I find this readme but cannot download anything from it :(

**Comment by Gcenx** [comment]
Wineskin on source forge is the original project from doh123 and has nothing to do with the project here.

This projects README here on GitHub provides the brew command to use for installation and also a manual direct url for Winery however I don’t recommend this as if the quarantine flag isn’t removed Wineskin won’t work correctly.

**Comment by tomnic79** [comment]
Trying now via brew ;) Thanks for pointing me to the right project ;)

**Comment by tomnic79** [comment]
Same hanging issues found in Crossover 20/21 are happening with 32 bit apps on AMD based Hackintosh... can we find out why since opemu32 doesn't exist anymore?

**Comment by asmaloney** [comment]
@tomnic79 Would you mind taking this to a [discussion](https://github.com/Gcenx/WineskinServer/discussions) or a new issue since it's not related to the status of the CX21.1 release? Thanks!

**Comment by tomnic79** [comment]
> @tomnic79 Would you mind taking this to a [discussion](https://github.com/Gcenx/WineskinServer/discussions) or a new issue since it's not related to the status of the CX21.1 release? Thanks!

Sorry, posted a discussion right now!

**Comment by Gcenx** [comment]
Resolved via https://github.com/Gcenx/WineskinServer/commit/f3c01047cd85903595fca9450ddf7cd9c55556eb
