### ISSUE TITLE
Allow environment variables to be set

### ISSUE THREAD

**Issue by Rastafabisch** [Gcenx/WineskinServer#15]
Currently the wineskin wrapper UI features settings for winedebug. However there are other interesting environment variables. Setting the wine-language system independent, enabling swizzle support for Vulkan enabled build and configuring the DXVK hub are just some which come to mind. Currently I manually edit the xyz123wine-preloader file, but as this gets overwritten with every update a native more intuitiv approach could be useful, especially as the current WINEDEBUG implementation already lies the ground work.

WINEDEDUG=[…]
MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE=[…]
DXVK_HUD=[…]
LANG=[…]

**Comment by Gcenx** [comment]
WINEDEDUG Is actually a hardcoded variable and the user setting is only read when using “Test Run” is used or keep logs checkbox is ticked.

I’ll see about getting these added into the next wrapper update in some fashion.
Might be hardcoded like WINEDEDUG, depending on my free time it could be more custom allowing any variable to be added.

**Comment by Gcenx** [comment]
@Rastafabisch did you ever try entering the required variables into the “Custom CLI” field? as that should already handle what your asking but not in as cleaner manner
