### ISSUE TITLE
How do you enable FPS counter with DXVK?

### ISSUE THREAD

**Issue by palmerj** [Gcenx/WineskinServer#152]
Normally in LINUX I would add DXVK_HUD=1 to the environment variables. I've tried adding `DXVK_HUD=1` to the Custom Commands in the configuration dialog of Wineskin Advanced options but that doesn't seem to be work. 

I'm running Ultra Street Fighter IV which is a DirectX 9 games (comes with June 2010 install). The only winetricks I've installed are WMP11 and dxvk_macos.verb.

**Comment by Gcenx** [comment]
> Normally in LINUX I would add DXVK_HUD=1 to the environment variables. I've tried adding `DXVK_HUD=1` to the Custom Commands in the configuration dialog of Wineskin Advanced options but that doesn't seem to be work.

Usually you need to use `export` making the command `export DXVK_HUD=“1”`

> I'm running Ultra Street Fighter IV which is a DirectX 9 games (comes with June 2010 install). The only winetricks I've installed are WMP11 and dxvk_macos.verb.

You’ve missed something important here, DXVK on macOS only supports 64Bit DirectX10/11, MoltenVK doesn’t provide the required Vulkan extensions for DirectX9 and there’s no Vulkan trunking for 32Bit.

**Comment by palmerj** [comment]
> You’ve missed something important here, DXVK on macOS only supports 64Bit DirectX10/11, MoltenVK doesn’t provide the required Vulkan extensions for DirectX9 and there’s no Vulkan trunking for 32Bit.

Ok sorry my fault. I did miss that in the readme. Cheers.

**Comment by palmerj** [comment]
Is there anyway with directx 9 games to report the FPS?

**Comment by Gcenx** [comment]
> Is there anyway with directx 9 games to report the FPS?

Maybe the Steam overlay?, WineD3D doesn't provide a realtime FPS counter unfortunately.

**Comment by palmerj** [comment]
Thanks. I don't use Steam. I guess will have to hope my games have the option
