### ISSUE TITLE
How do I change the default exe for my wrapper?

### ISSUE THREAD

**Issue by lpegoraro** [Gcenx/WineskinServer#153]
I somehow accepted the wrong exe and I want to change, is there a config file in the wrapper that I can change without redoing the wrapper?

**Comment by emendelson** [comment]
Right-click on the app; choose Show Package Contents. Launch Wineskin. Click Advanced. Click Browse and find the EXE file that you want to use (or just type in the path and filename). Click Test Run to make sure it's working. Close Wineskin.

**Comment by lpegoraro** [comment]
Thanks! Solved
