### ISSUE TITLE
Installing winbind package

### ISSUE THREAD

**Issue by Sinemora10** [Gcenx/WineskinServer#157]
Installing office 2010 suite on a wineprefix requires the winbind package. On linux, installing winbind is only a terminal command away, not quite so on Mac Os, unfortunately.

I was wondering if there is an easy way to solve the problem buit into wineskin, and if there isn't maybe it would be worth adding it?

Thanks

**Comment by Gcenx** [comment]
The message that wine provides as usual it’s Linux specific and not every distro provodes this package anyway it’s part of samba.

The needed binary is `ntlm_auth` the problem is I can’t really find information on how to compile only this component.

**Comment by Sinemora10** [comment]
Thank you very much for your answer. Indeed, the problem is pricely that. As a workaround Playonlinux downloads it into the 'tools' folder in library and set the variable path in the wineprefix to see that. Could that be feasible? 

Thanks again

**Comment by Gcenx** [comment]
I’d rather not go the same route and PlayOn as needing to download an entire samba install for a single required binary really goes against the idea of a self contained “Port”

I’ll eventually take another crack at this or reach out to CodeWeavers, I’ll lightly need to bundle `ntlm_auth` within the new official Winehq packages anyway.

**Comment by Sinemora10** [comment]
Thank you for your reply, and most of all for your work. I will keep my eyes peeled for the new release.

thank you again.

**Comment by stefandesu** [comment]
@Sinemora10 Did you figure out any way to install Microsoft Office 2010? I tried it and it seems to work at first, but it ends up showing that there was an error during installation without any details. Thanks!

**Comment by Sinemora10** [comment]
> @Sinemora10 Did you figure out any way to install Microsoft Office 2010? I tried it and it seems to work at first, but it ends up showing that there was an error during installation without any details. Thanks!

Hi, sorry for the slow reply. Office 2010 installation fails because it requires Samba to be installed. As of today the Samba the current wineskin does not support its installation. You could try installing Office 2007, which does not require Samba
