### ISSUE TITLE
Is DirectX 9 missing in dxvk_macos.verb?

### ISSUE THREAD

**Issue by markperez1904** [Gcenx/WineskinServer#159]
When installing `dxvk_macos.verb`, does it include the DirectX 9 libraries?

I am trying to run various games that can only use d3d9, and the performance seems quite poor.

<img width="488" alt="Screen Shot 2021-09-18 at 1 48 23 AM" src="https://user-images.githubusercontent.com/34041737/133879495-a8d3fbf9-1690-4bc5-a88a-2a72333e92eb.png">

 - OS: big sir 11.6
 - Winery version: 5.0
 - Master Wrapper version: 2.9.0.9-1
 - Engine version: ws11 20.0.4 (64-bit)
 - Hardware: macbook pro m1 2020
 - Application/Game Name: various games only using d3d9

**Comment by Gcenx** [comment]
https://github.com/Gcenx/WineskinServer/blob/808a2c9ce340519db179dda7bea29b5000a27d05/README.md#L22-L31
As explained there’s is no DirectX9 support nor is there any 32Bit Vulkan support (missing Vulkan features in MoltenVK)

You haven’t provided _any_ game title(s) so I can’t reference if it’s one of the known problem titles. Some games will simply run worse on the M1 (Rosetta2 bugs) and some simply run badly via wine32on64 (32on64 trunking issues)

**Comment by markperez1904** [comment]
I m just trying out gta4 and mw3, one of my most favorite games.
some people are able to boost performance my dragging the 32-bit d3d9 dll inside the games directory, but i don't think it's compatible with the m1 arch

**Comment by Gcenx** [comment]
I’m really not sure what your trying to ask.

There is no 32Bit Vulkan support currently in wine (Metal is a 64Bit API), there’s also missing Vulkan API features so no DirectX9.

You can install any required native d3d compiler dlls from winetricks but those usually aren’t required.
