### ISSUE TITLE
Updating a wrapper causes Wineskin to error with "No engine installed"

### ISSUE THREAD

**Issue by kelvSYC** [Gcenx/WineskinServer#161]
I recently wanted to update the version of a wrapper of a Wineskin app, only to find that after doing so, I get an error saying:

```
Warning
No Engine installed.

Don't directly launch <application> you need to use "Wineskin Winery" to create a working wrapper
```

Thereafter, the wrapper would be stuck in the `Wineskin is currently busy` prompt.

Additionally, the existing engine is installed in my local copy of Wineskin Winery, and no engine updates were ever ordered. It is as if updating the wrapper removed the existing engine, if the error is anything to go by, but it does not explain why no engine was ever reinstalled in its place.

At this point, the wrapper and application is entirely unusable, likely causing me to re-create the application from scratch. Please assist in trying to recover the corrupted wrapper and/or engine.

**Comment by Gcenx** [comment]
Once created a wineskin _port_ is self contained so when you run "Update Wrapper" it will run the currently embedded update function so won't take into account any structure changes.

The old Engine location was;
```
/Contents/Framework/wswine.bundle
```

The new Engine location is;
```
/Contents/SharedSupport/wine
```

I'd recommend remaking the _port_ as this still won't account for changes in `info.plist`, the Engine location was changed a while ago to improve M1 support. A later wrapper version will move the wineprefix to make this more seamless.
