### ISSUE TITLE
Change titlebar icon in Windows app?

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#162]
This is not a problem, only a request for information.

In some of my wrappers, the system menu in the title bar has a small wine-glass icon:

<img width="99" alt="Screen Shot 2021-09-25 at 10 17 29 AM" src="https://user-images.githubusercontent.com/5208505/134774727-7c81e3db-0371-4410-b2ed-eeca43949634.png">

I've been trying to figure out where that icon is located so that I can replace it with a. custom icon. Does anyone know where that icon is? Many thanks for any information

**Comment by Gcenx** [comment]
That’s a generic fallback icon compiled into wine so to resolve it would require a recompile. Alternatively use [Resource Hacker](http://www.angusj.com/resourcehacker/) and embed an ico into vDos

**Comment by emendelson** [comment]
Will do - I'm an old hand at Resource Hacker. Thanks for clarifying this.
