### ISSUE TITLE
Steam Blank screen with latest Engine/Wrapper and macOS 11.6

### ISSUE THREAD

**Issue by andiweli** [Gcenx/WineskinServer#163]
**Environment (please complete the following information):**
 - OS: macOS 11.6
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.0.9-1
 - Engine version: WS11WineCX64Bit 20.0.4
 - Hardware: iMac Late 2013
 - Application/Game Name: Steam

**Describe the bug**
Steam starts with a blank screen, cannot use it

**To Reproduce**
1. create a wrapper with the above given Winery settings
2. install Steam via Winetricks
3. change path to .../steam.exe
4. startup the wrapper
5. login
6. voila ... blank screen with Steam framework

**Expected behavior**
Steam as expected on a Windows computer

**Screenshots**
![Bildschirmfoto 2021-09-27 um 08 31 12](https://user-images.githubusercontent.com/11447150/134855872-2ae2d3df-7f8d-400a-859a-47f9633a0ab0.png)

**LastRunWine.log**
I only found these logs inside "Resources/Logs" ...
[LastRunX11.log](https://github.com/Gcenx/WineskinServer/files/7233874/LastRunX11.log)
[Winetricks.log](https://github.com/Gcenx/WineskinServer/files/7233875/Winetricks.log)

**Comment by Gcenx** [comment]
How to have a working Steam Client is explained in the wiki https://github.com/Gcenx/WineskinServer/wiki#steam
