### ISSUE TITLE
Create wrapper prompt “No Engine installed"

### ISSUE THREAD

**Issue by succbua** [Gcenx/WineskinServer#164]
OS: macOS 11.6
Winery version: 1.8.4.1
Master Wrapper version: 2.9.0.9-1
Engine version: WS11WineCX64Bit 20.0.4
Hardware: MacBook Pro 15 2018
Application/Game Name: Steam

I used  Wrapper 2.9.0.5 before and Can be created。
today I upgrade wrapper 2.9.0.5 to 2.9.0.9-1,prompt “No Engine installed" when creating
I've looked at other issues，
The engine is not in the \SharedSupport directory，But I don't know how to modify it

**Comment by Gcenx** [comment]
Your using an older version of Wineskin Winery and not the latest, trash the app and install using the provided brew command provided on the readme.

Also as you’ve obviously manually i packages/installed the latest wrapper you also need to trash that and download it via the latest version of Wineskin Winery.

**Comment by succbua** [comment]
it's great！
According to the method you provide, the creation was successful。
Thanks a lot.
