### ISSUE TITLE
[Request] Windows 11 ARM wrapper

### ISSUE THREAD

**Issue by mbparsley** [Gcenx/WineskinServer#172]
It would be great to add Windows 11 ARM64 wrapper to increase compatibility with Apple silicon Macs, keeping the emulation layer to run 32/64 bit apps

**Comment by Gcenx** [comment]
This project focuses on wrapping wine to make it easier to use. Currently only using x86 based wine until CodeWeavers/upstream provide a way to run native wine arm64 to run x86 Windows binaries.
