### ISSUE TITLE
I can't install an engine

### ISSUE THREAD

**Issue by Rock-Parade** [Gcenx/WineskinServer#173]
**Environment (please complete the following information):**
 - OS: Big Sur 11.5.2
 - Winery version: 2.9.0.9-3
 - Master Wrapper version: Couldn't get that far
 - Engine version: Could not download an engine 
 - Hardware: Macbook Air (M1, 2020)
 - Application/Game Name: N/A

**Describe the bug**
The + button used to bring up the window to install new engines did not work. 

**To Reproduce**
No idea if it will work on other systems, but it has had a 100% reproduction rate so far. 

**Expected behavior**
I expected the window which lists engines to pop up.

**LastRunWine.log**
I cannot find this, sorry

**Comment by Gcenx** [comment]
The provided Winery version is not a version of Winery, you need to install Winery using the provided brew command.

**Comment by Rock-Parade** [comment]
> The provided Winery version is not a version of Winery, you need to install Winery using the provided brew command.

Oh, my bad. I watched a video on how to install it and that was not explained. Sorry to bother you, but is there any resource that you know of that explains how I would go about doing this?

**Comment by Gcenx** [comment]
The projects readme provides instructions on installing using `brew` https://github.com/Gcenx/WineskinServer/blob/master/README.md

Please provide a url for the “guide” you followed on YouTube and that like many I’ve found provide completely wrong installation instructions.

**Comment by Rock-Parade** [comment]
> The projects readme provides instructions on installing using `brew` https://github.com/Gcenx/WineskinServer/blob/master/README.md
> 
> Please provide a url for the “guide” you followed on YouTube and that like many I’ve found provide completely wrong installation instructions.

https://www.youtube.com/watch?v=vkQj0lZFz6I&ab_channel=JacobTownsend here is the guide

**Comment by Rock-Parade** [comment]
> The projects readme provides instructions on installing using `brew` https://github.com/Gcenx/WineskinServer/blob/master/README.md
> 
> Please provide a url for the “guide” you followed on YouTube and that like many I’ve found provide completely wrong installation instructions.

Just downloaded it correctly, thanks! That being said, I have no idea how to use it. Is it at all possible to run 32 bit games? If theres somewhere else I should bring this, like an FAQ or a video or something please tell me I'd hate to waste your time.
