### ISSUE TITLE
Tapping gcenx/wine breaks searches in brew

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [Gcenx/WineskinServer#174]
**Environment (please complete the following information):**
 - OS: macOS 12.0.1
 - Winery version: n/a
 - Master Wrapper version: n/a
 - Engine version: n/a
 - Hardware: n/a
 - Application/Game Name: none

**Describe the bug**

As per installation instructions, `brew install --no-quarantine gcenx/wine/unofficial-wineskin` has tapped `gcenx/wine`. Since that, any `brew search` that hits `wine-crossover@19.0.2` from your repo breaks brew. E.g.:

```
$ brew search wi
Error: Cask 'wine-crossover@19.0.2' is unavailable: No Cask with this name exists.
```

**To Reproduce**

```
brew install --no-quarantine gcenx/wine/unofficial-wineskin
brew search wi
```

**Expected behavior**

`brew search` works as usual

**Screenshots**

**LastRunWine.log**

**Additional context**

Cheers :)

**Comment by Gcenx** [comment]
Assuming you have the same name on Reddit.

Can’t say I’ve ever used `brew search` but I’ll assume it simply doesn’t like the `@` symbol being used within the casks name. So the simplest solution is simply renaming/removing the problem cask.

**Comment by Gcenx** [comment]
This should be resolved via https://github.com/Gcenx/homebrew-wine/commit/47f6b76d8d0237068b870981337671d8d11bc471

**Comment by DanielSmedegaardBuus** [comment]
Indeed, that fixed it :) Thank you, and have a nice weekend.
