### ISSUE TITLE
16-bit support in Wine 6.20?

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#175]
This is only a question, and probably uninformed. The page on Wine 6.20 at WineHQ lists fixes for 16-bit applications:

https://www.winehq.org/announce/6.20

Does this mean that 16-bit-support may be possible in Wineskin? If I've missed a clear statement about this elsewhere on this page, just ignore me.

**Comment by Gcenx** [comment]
The answer is yes for `wine`, however `wine64` and `wine32on64` don’t support 16Bit.

The same is also true on Linux if your kernel provides 16Bit support.

**Comment by emendelson** [comment]
Understood. Thank you. I guess we can only hope that wine64 and wine32on64 might someday support 16Bit, but it will obviously be a long wait.
