### ISSUE TITLE
Diablo 2 Key

### ISSUE THREAD

**Issue by I0kii** [Gcenx/WineskinServer#178]
When downloading Diablo 2 from winetricks, it asks for my official blizzard key. I have one, but I don't know how I get get winetricks to recognize it- I've tried to type it in, copy and paste it, etc. If anyone knows anything about this, I'd appreciate your help. Thanks in advance!

**Comment by Gcenx** [comment]
I wouldn’t install games using winetricks, all the Winetricks menu does is wrap [winetricks](https://github.com/Winetricks/winetricks)

You’d be better server download the Windows installer and running it from Wineskin and installing thing entering your digital key as usual.

**Comment by I0kii** [comment]
Thank you!
