### ISSUE TITLE
Wineskiin Wrapper File Damaged

### ISSUE THREAD

**Issue by WZRD9AYSE** [Gcenx/WineskinServer#179]
Hello All,

I have successfully downloaded the WineSkin Master folder, yet when i attempt to extract the Wrapper portion of the file, i recieve an error message stating the file is corrupted or damaged? Any help would bee appreciated.

All The Best.

**Comment by Gcenx** [comment]
You’ve skipped the issue template and obviously not read the README.md.

**Comment by Gcenx** [comment]
> Are you sure of it??? Don't be so brash, there's no such thing as a dumb question as you've clearly portrayed in your abrupt response. I have read the "README.md" and am having trouble understanding it. If you're not willing to help, it would be better to say that clearly that to be so brash and hostile.

Let’s review _why_ I say you didn’t read the README.md. (And yes you bypassed the issue template completely)

> I have successfully downloaded the WineSkin Master folder.

Why would you download any directory when I provide a direct url to “Winery Winery” in the README.md?

I _don’t_ recommend manually downloading “Wineskin Winery” as by default modern macOS automatically adds a quarantine flag to all downloaded binaries meaning Gatekeeper will reject any none code-signed applications as “damaged”.

> yet when i attempt to extract the Wrapper portion of the file, i recieve an error message stating the file is corrupted or damaged?

_Why_ would you be downloading the Wrapper?, “Wineskin Winery” is used to download the master wrapper and the “Engines”, the master wrapper on its own is modestly useless (only PortingKit uses this directly)

<br>

As explained in the README.md it’s recommended to install using the provided homebrew command (the homebrew title is a url explaining how to install brew)
