### ISSUE TITLE
macOS Monterey , Apps aren't working ever since I updated from Big Sur to Monterey 

### ISSUE THREAD

**Issue by Shafas1** [Gcenx/WineskinServer#182]
**Environment (please complete the following information):**
 - OS: 12.0.1 
 - Winery version: ?
 - Master Wrapper version: 2.9.0.9-3
 - Engine version: 20.0.4
 - Hardware: ?
 - Application/Game Name: ? 

**Describe the bug**
Apps not opening ever since updating MacOs version.

**To Reproduce**

**Expected behavior**

**Screenshots**

**LastRunWine.log**

**Additional context**

**Comment by Gcenx** [comment]
> **Describe the bug** Apps not opening ever since updating MacOs version.

What are you referring to here exactly?

As per README.md I currently only officially support macOS 11 (Big Sur) at this time, while I’ve had reports of Wineskin working without issue on macOS 12 (Monterey) I’ve not personally verified this.

**Comment by Shafas1** [comment]
> > **Describe the bug** Apps not opening ever since updating MacOs version.
> 
> What are you referring to here exactly?
> 
> As per README.md I currently only officially support macOS 11 (Big Sur) at this time, while I’ve had reports of Wineskin working without issue on macOS 12 (Monterey) I’ve not personally verified this.

I used to run Gta 5 using wineskin but after updating the os , app isn't launching or responding.

**Comment by emendelson** [comment]
For what it's worth, all my Wineskin apps are working perfectly under Monterey, but I created a new volume with Monterey instead of upgrading from Big Sur. Maybe it's worth trying to refresh the wrapper or engine in the app on an upgraded system?

**Comment by Gcenx** [comment]
PaulTheTall hasn’t reported an issues using Wineskin nor PortingKit on the latest version of macOS so this doesn’t seem to be a Wineskin issue.

**Comment by goodhyun** [comment]
No problem with Monterey here. Upgraded from Big Sur.
