### ISSUE TITLE
Loading bar for Exe Install - can't tell if process is done or not - Executeble Setup taking 2+ hrs

### ISSUE THREAD

**Issue by mitsukiyouko555** [Gcenx/WineskinServer#183]
**Is your feature request related to a problem? Please describe.**

Following this youtube vid: https://www.youtube.com/watch?v=vkQj0lZFz6I
I am at the "Choose Executable setup" and orig ran into an alias'd ver of the c drive and ran into an issue but fixed that by right clicking -> show source file -> moving the source file to the resources folder, deleting the alias. 

Game being installed is Star Conflict. EXE downloaded from here: https://star-conflict.com/ 

It did run without issue..... BUT it has been running for 2 HOURS! how do i know if it is stuck or if it is just not done yet??

**Describe the solution you'd like**

It would be really nice if there is a way to tell whether the process is stuck or not or if it is x% done so that we can see an ETA of the process.... (if there is a way to do that through mac terminal please let me know cuz i couldnt find any when i googled it)

**Describe alternatives you've considered**

Tried using ps -aux | grep wine but it did not show me an ETA :( and also i couldnt get the header to show up so i could only tell if it was running or sleeping which helps a little but not rly what I'm looking for.

**Additional context**

Loading still.......
<img width="224" alt="Screen Shot 2021-11-24 at 11 31 55 PM" src="https://user-images.githubusercontent.com/25854884/143399096-e8a04d8c-bd14-489f-840e-e913432f03c5.png">

Dis don't help me much...

<img width="1440" alt="Screen Shot 2021-11-24 at 11 32 47 PM" src="https://user-images.githubusercontent.com/25854884/143399415-3a2e8871-6fd4-4735-9c22-d1ab123c2f91.png">

Any help would be appreciated thanks! will probs kill this and try again tmr since its getting late.

**Comment by Gcenx** [comment]
This feature request is more of an invalid bug report. The video _guide_ you’ve followed will have you install “Wineskin Winery” incorrectly resulting in broken behavior.

You should instead follow the steps in the readme to install “Wineskin Winery” correctly.

Wineskin isn’t responsible for proving an ETA for an installer as those would provide it directly to the user unless ran in some unattended mode. More lightly issue is WineskinLauncher being installed while still quarantines is unable to correctly execute the desired installer.

**Comment by mitsukiyouko555** [comment]
Hi @Gcenx,  

Thanks for the reply! 

I had forgotten to mention that while i did follow the video, it didnt work so THEN i read the read me and installed it using this line: 

brew install --no-quarantine gcenx/wine/unofficial-wineskin

I'll double check to see if it is in quarantine and try again...

Do you by chance know how long games typically take to install? just so i can gague if its stuck or not?

Thank you!

**Comment by Gcenx** [comment]
You’d also need to have removed any files that the incorrect installed “Wineskin Winery” downloaded as those all would also have the quarantine flag added to them.

Installer can be quick or take literally 3+ hours depending on the titles size and if compress was used.

Here’s something that might work better so additional information can be obtained. Launch Wineskin.app, click Advanced, goto the advanced tab and find the button labeled “Winehq Engine Launch”, click this and a terminal window will open. 

Next type in “wine explorer” this will open a Windows like explorer window where you’ll be able to navigate to the games installer. It will lightly now request permissions to access this location. 

After that if it opens great if not it will at least show additional information in that terminal window as to why it didn’t launch.

**Comment by Gcenx** [comment]
Still this would still be considered an invalid feature request, this really should have been a bug report without the mention of an invalid _guide_

Sometimes installers are annoying and require additional native libraries just to open sigh…

**Comment by mitsukiyouko555** [comment]
> You’d also need to have removed any files that the incorrect installed “Wineskin Winery” downloaded as those all would also have the quarantine flag added to them.

I Just dragged wine and moved it to trash, is that good enough or is there some terminal command i need to run to clear it fully? i checked the Read Me but i didnt see mentions about that.

Thanks for the help! :)

**Comment by Gcenx** [comment]
~/Library/Application Support/Wineskin/

**Comment by mitsukiyouko555** [comment]
OMG i uninstalled and reinstalled an it is working!!! thank you so much!!

**Comment by mitsukiyouko555** [comment]
ok it finished installing and the mouse works but the keyboard doesnt XDD i'll probs try this again some other day

**Comment by Gcenx** [comment]
If the game runs fullscreen it lightly tried to prompt for accessibility permissions, I mostly play games in a Windows mode where possible for this reason.

**Comment by mitsukiyouko555** [comment]
I see Thanks!

Though pausing from this for a while due to the few issues i ran into:

- gotta get avast antivirus to mark win32 stuff as false positive (too lazy to deal with that rn XD)
- after installing there is a starconflict.ink file on my desktop i moved it to the drice.c folder but couldnt open star conflict back up again (potentially cuz by that time i'd turned my antivirus back on.. i turned it off when installing)
- i'll try out that windows mode thing next time :D

Bookmarking this thread for when i want to try this again! appreciate all your help!
