### ISSUE TITLE
Mortal Kombat XL: Vertex shader function could not be compiled into pipeline

### ISSUE THREAD

**Issue by palmerj** [Gcenx/WineskinServer#184]
**Environment (please complete the following information):**
 - OS: 11.6.1 (20G224)
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.0.9-3
 - Engine version: WS11WineCX64bit20.0.4
 - Hardware: MacBook Pro (15-inch, 2019), 2.6 GHz 6-Core Intel Core i7, Radeon Pro 555X 4 GB
 - Application/Game Name Mortal Kombat XL (64bit) - directx 11 game.

**Describe the bug**

**To Reproduce**
Run the game and then perform any fatality. The two player character texture models disappear and only the body internals are left.  

**Expected behavior**
Player character texture models are drawn to the screen.

Seems the issue is shaders are not being compiled. See error snippet:

```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:473:9: error: no member named 'gl_CullDistance' in 'main0_out'
    out.gl_CullDistance[0] = out.o5;
    ~~~ ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Vertex shader function could not be compiled into pipeline. See previous logged error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_48c64a754f51018d85d9719a2c5751764481a5d6
err:     fs  : FS_bae6d9d5b407ddd219b7dcaeb457942a161fc78e
[mvk-info] Converting SPIR-V:
```

**LastRunWine.log**
I've set MVK_CONFIG_LOG_LEVEL=2 and MVK_DEBUG=1 to dump the SPIR-V/MSL/GLSL shader conversions.

Attached: [LastRunWine.log.zip](https://github.com/Gcenx/WineskinServer/files/7607981/LastRunWine.log.zip)

**Additional context**

The rest of the game seems to run well.

**Comment by Gcenx** [comment]
I doubt that title is really 32Bit considering wine(32on64) doesn’t have any Vulkan support due to the current lack of Vulkan trunking code.

Try replacing the copy of libMoltenVK from within the wrapper /Frameworks directory with one of the newer patches copies from here https://github.com/Gcenx/MoltenVK/releases/tag/v1.1.6

_1 copy contains a patch for M1 GPUs so maybe try the other patched copy first.

**Comment by palmerj** [comment]
Hi @Gcenx thanks for the response. Much appreciated. 

> I doubt that title is really 32Bit considering wine(32on64) doesn’t have any Vulkan support due to the current lack of Vulkan trunking code.

You are correct it is 64bit.

```
❯ file MK10.exe
MK10.exe: PE32+ executable (GUI) x86-64, for MS Windows
```

I just assumed it was 32bit as it was installed into the Program Files (x86) folder. 

> Try replacing the copy of libMoltenVK from within the wrapper /Frameworks directory with one of the newer patches copies from here https://github.com/Gcenx/MoltenVK/releases/tag/v1.1.6

Thanks. I already tried https://github.com/Gcenx/MoltenVK/releases/download/v1.1.6/macos_dxvk_patched-1.1.6.tar.xz and also crossover-21.0.0 yesterday but still the same error. Sorry I should have mentioned that. I will give https://github.com/Gcenx/MoltenVK/releases/download/v1.1.6/macos_dxvk_patched-1.1.6_1.tar.xz a try and see if that makes a difference.

**Comment by palmerj** [comment]
Still getting the same issues and error with macos_dxvk_patched-1.1.6_1.tar.xz

```
void main()
{
    vec4 _1229 = shader_in[0];
    _1229.x = uintBitsToFloat(uint(gl_VertexIndex) - uint(gl_BaseVertexARB));
    shader_in[0] = _1229;
    vs_main();
    gl_Position = o2;
    gl_CullDistance[0] = o5;
}


End GLSL


[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:473:9: error: no member named 'gl_CullDistance' in 'main0_out'
    out.gl_CullDistance[0] = out.o5;
    ~~~ ^
```

Log here (but without verbose MVK logging on https://gist.github.com/palmerj/42e08dea4a09a4ce80a748ccd2b84f73

**Comment by palmerj** [comment]
Any hints? Should I raise this issue with the MoltenVK project?

**Comment by Gcenx** [comment]
> Any hints? Should I raise this issue with the MoltenVK project?

I’m honestly not too sure what the issue could be with this, it might be a good idea to open an issue with upstream where they can figure out that component is causing the problem.

I’m still waiting on an official fix to resolve the M1 GPU lockup’s and working on modified gstreamer package to use with wine. And some other currently private endeavors.

**Comment by palmerj** [comment]
Ok, many thanks.
