### ISSUE TITLE
portingteam.com这个论坛完蛋了吗？

### ISSUE THREAD

**Issue by vskllee** [Gcenx/WineskinServer#19]
portingteam.com这个论坛完蛋了吗？

**Comment by Gcenx** [comment]
我不知道什么时候，我无法控制你应该在Discord上询问的网站。
I don’t know when, I have no control over the site you should ask on Discord.

另外请不要在其他问题上发帖再次提出这个问题，我会在我能够回答的时候回答。
Also please don’t post within other issues asking this question again, I will answer when I’m able to.

这一切都是通过谷歌翻译完成的，我只读写英文
This was all done via google translate, I only Read & Write English

**Comment by vskllee** [comment]
Thx
