### ISSUE TITLE
Feature Request: Instructions for engine assembly

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [Gcenx/WineskinServer#190]
A wiki page or similar with instructions to turn custom (locally built) wine builds (e.g. output from [here](https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/) into useable engine files for Winery

**Comment by Gcenx** [comment]
There’s currently no point packing third-party wine builds into Engines when they won’t function correctly within Wineskin.

Create a directory named `wswine.bundle` make a file called `version` Inside add the Engines name, copy in the wine packages directory’s so the contents will look something like this;

- wswine.bundle
- version
- bin
- lib
- lib64
- lib32on64 (if this exists)
- share

Now compress the `wswine.bundle` to tar.7z with the same name as within `version`

### Please note;
Use at your own risk as I won’t help get a third-party Engine up and running correctly within Wineskin.

I’ve helped a user do this and for months kept being told _I’m wrong_, yet when I compiled/packaged there sources the resulting Engine worked without issue yet there own never did.

**Comment by The-Minecraft-Scientist** [comment]
Thanks for the quick response! It sounds like I’m running into the same issue the user you helped was. I’ll experiment with it a bit more. Anyhow, I’ll close this issue.
