### ISSUE TITLE
How do I download older master wrappers?

### ISSUE THREAD

**Issue by stereokai** [Gcenx/WineskinServer#192]
First thing, this project is amazing, and big respect to you for keeping on pushing it to modern systems.

I had success with 2.9.0.9-3, and for some reason, I'm running into an issue with 2.9.0.9-4. I would like to compare the two versions.

Is there another way to get 2.9.0.9-3 again? The "download packages manually" option opens a dead mega.co.nz link.

Thanks a lot!

**Comment by Gcenx** [comment]
As you’ve not filled out the issue template nor provided any useful information not sure how I could possible resolve a possible issue with the latest master wrapper.

**Comment by Gcenx** [comment]
Closing in favor of the more valid https://github.com/Gcenx/WineskinServer/issues/193
