### ISSUE TITLE
How to get older master wrapper? (2.9.0.9-3)

### ISSUE THREAD

**Issue by stereokai** [Gcenx/WineskinServer#193]
**Environment (please complete the following information):**
 - OS: macOS 11.6.2 
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.0.9-4
 - Engine version: WS11WineCX21.2.0
 - Hardware: MacBook Pro 15 2013, A1398 
 - Application/Game Name NetVSTHost

**Describe the bug**
The program used to work fine with 2.9.0.9-3. 
After update to 2.9.0.9-4, I replaced (completely deleted) the old wrapper and re-created it with the new 2.9.0.9-4.
With 2.9.0.9-4, the program loads but freezes. After a consultation with the original developer of the program, he said the reason will be a kind of graphics library missing or graphics configuration.
Either way, I want to re-download 2.9.0.9-3 to try and recreate the wrapper I deleted.
If I won't be able to get the program to run again with 2.9.0.9-3, it means I'm including the wrong libraries.

**To Reproduce**
1. Open Wineskin Winery
2. Wrapper version shows latest (2.9.0.9-4)
3. Click "download packages manually"
4. A dead link on mega.co.nz opens

**Expected behavior**
Some way to get 2.9.0.9-3

**Comment by Gcenx** [comment]
> Engine version: Don't know what this is

As I’m at work this image will have to do
![05F423D8-26C5-4F8A-AF4A-843F7AB95D4F](https://user-images.githubusercontent.com/38226388/146251877-bd4fd3f2-f019-4569-9361-f8251c1a61ce.png)
See the “installed Engines” heading?\
When creating a wrapper you’ll have selected an “Engine” that will be what’s used within the wrapper.

**Comment by stereokai** [comment]
Thanks, I updated the correct information :)

I just want to be able to recreate the 2.9.0.9-3 version wrapper, before I dive deeper into this issue and have to bother you with even weirder things ;)

**Comment by Gcenx** [comment]
As I only just uploaded wrapper 2.9.0.9-4 and WS11WineCX21.1.0 it would make more sense to create another wrapper but this time use WS11WineCX20.0.4

Using an older wrapper with a newer engine is not recommended.

**Comment by stereokai** [comment]
Thanks, but please, how can I get 2.9.0.9-3 again?

**Comment by Gcenx** [comment]
> Thanks, but please, how can I get 2.9.0.9-3 again?

Get the older wrapper from here https://github.com/Gcenx/WineskinServer/blob/f4e90a4a68edaa5d94b1d9abea203c6cc781bf18/Wrapper/Wineskin-2.9.0.9-3.app.tar.7z

The obligatory I don’t recommend doing this.

**Comment by stereokai** [comment]
Thanks, but I already tried that, but unfortunately the wrappers created by manually extracting this archive in the directory `Wineskin/Wrapper` all have an issue with their link to `drive_c`

**Comment by stereokai** [comment]
And I get this error when trying to create a new wrapper with the 2.9.0.9-3 from your link:

<img width="243" alt="Screen Shot 2021-12-15 at 21 18 10" src="https://user-images.githubusercontent.com/2685357/146259038-31c2f6e4-4bdd-4778-9f52-33042de2143b.png">

**Comment by Gcenx** [comment]
Wineskin isn’t code-signed so you need to manually remove the quarantine flag from the downloaded archive before attempting to use it. This is explained in the readme and via the wiki.

The reason I don’t recommend manually downloading anything is due to the above.

**Comment by stereokai** [comment]
I see. I read that part, but wasn't aware that was the cause, because I was expecting a more explicit error. Thanks! I'll give it a try :)

**Comment by stereokai** [comment]
I'm reporting back - I successfully recreated the previous setup with 2.9.0.9-3 and WS11WineCX20.0.4 – and got NetVSTHost to work properly again.

That means NetVSTHost is incompatible with 2.9.0.9-4 and WS11WineCX21.1.0

**Comment by Gcenx** [comment]
> I'm reporting back - I successfully recreated the previous setup with 2.9.0.9-3 and WS11WineCX20.0.4 – and got NetVSTHost to work properly again.
> 
> That means NetVSTHost is incompatible with 2.9.0.9-4 and WS11WineCX21.1.0

Not necessarily, it may simply have issues with WS11WineCX21.1.0 and have nothing to do with the latest wrapper.

**Comment by stereokai** [comment]
I see. Are you interested in further information, like logs, traces etc.?

**Comment by Gcenx** [comment]
Those are always useful, however sometimes applications/games get broken by newer wine versions.

Some applications/games work with CX19.0.2 but might not work with CX20.0.4 for example. Or it could be a runtime related issue.

I’ve not received any reports of issues (yet) from PaulTheTall(PortingKit) who’s testing the latest wrapper/engine combinations currently.

**Comment by stereokai** [comment]
That's reasonable. Would you like anything other than the regular post-run log?

**Comment by Gcenx** [comment]
First move the working app somewhere else so it’s not an issue.

Next update the wrapper and use the same engine (CX20.0.4), if this still works move onto using CX21.1.0 it should fail when using “Test Run” then attach the log.

**Comment by stereokai** [comment]
> First move the working app somewhere else so it’s not an issue.

You mean clone it (copy paste)?

**Comment by Gcenx** [comment]
> > First move the working app somewhere else so it’s not an issue.
> 
> You mean clone it (copy paste)?

Copy/paste or simply more it to another directory.

**Comment by stereokai** [comment]
Got that. I'll do it now. Meanwhile, what is that correct way to configure the wrapper to include the 32bit Visual C++ 2010 SP1 Redistributable Package? Is that through here?
![image](https://user-images.githubusercontent.com/2685357/146268017-9265824c-ca46-4fc9-b5db-f5bd1da6bffa.png)

Or should I manually download the installer from Microsoft and install it myself? (That's what I have been doing)

**Comment by Gcenx** [comment]
If an application/game fails to run using Wineskin included version of a library you’d want to install the native one using winetricks so any needed workarounds/configuration setting and done correctly to function.

**Comment by stereokai** [comment]
Allow me to explain – The application I'm working with is standalone, and doesn't install the required libraries, even in a native Windows environment. Which way is therefore preferred? Manually installing it from the Microsoft installer, or through the option I marked using winetricks?

**Comment by Gcenx** [comment]
The preferred way is always winetricks

**Comment by stereokai** [comment]
I see. Do you have any idea if the I marked covers everything in the MSVCR 2010 SP1 package? I couldn't find a detailed content list anywhere :(

**Comment by Gcenx** [comment]
I’m not entirely sure since Microsoft don’t give details for vcrun2010 anymore but it’s checksum easy last updated august his year in winetricks so it’s possible it just contains everything now.

**Comment by stereokai** [comment]
Thanks, I'll give it a try too

**Comment by stereokai** [comment]
After multiple attempts, I can confidently say that NetVSTHost only works with the 2.9.0.9-3 and WS11WineCX20.0.4 combination.
In addition, using the Winetricks vcrun2010 package did not suffice – it was necessary to install the original VC++ 2010 Redis package from Microsoft.
