### ISSUE TITLE
The new created Wrapper App icon is crossed out and can't be used in my iOS environment.

### ISSUE THREAD

**Issue by jesusboyfriend** [Gcenx/WineskinServer#194]
**Environment (please complete the following information):**
 - OS: 10.12.6
 - Winery version: 1.8.4
 - Master Wrapper version: Wineskin-2.9.0.9-4 - Engine version: WS11WineCX64Bit21.1.0
 - Hardware: iMac (21.5-inch, Mid 2011) - Application/Game Name: Any App/Game

**Describe the bug**
Hi there,
didn't use Wineskin since Wrapper "Wineskin-2.9.0.7-rc2" and seen there was an update I updated as I usually do.
Went as normal to Create a New Blank Wrapper but once created I found the new blank "crossed out" and opening it I get the message "You can’t use this version of the application “MyCoolWrapper” with this version of macOS." "You have macOS 10.12.6. The application requires macOS 10.13 or later." 
I tried to reverse to the old Wrapper but I don't seem to find a way to do that and if I download Winery again the newest Wrapper is the only one available.
Hoping to don't waste your time on something maybe very simple to fix and wishing you a happy Christmas.

Regards

Zoo 

PS Thanks for the excellent work through the years!

**Comment by Gcenx** [comment]
This project now requires macOS High Sierra and later.

Here’s a direct url to the old wrapper you used prior https://github.com/Gcenx/WineskinServer/blob/958fcf8856d1a4d93cfd6695be3784acf9921db2/Wrapper/Wineskin-2.9.0.7-rc2.app.tar.7z

### Please note
As your running a now unsupported version of macOS I’ll provide little to no support, so if you attempt to use a newer Engine and it doesn’t work I won’t provide assistance.

**Comment by jesusboyfriend** [comment]
Thanks so much for the quick reply.
Unfortunately I don't really know how to put the old wrapper in the
Wineskin itself. I can use terminal if that helps but that's about it.
I don't want to take anymore of your time but again thanks!
Much appreciated.

Regards
Zoo
