### ISSUE TITLE
isolate_home winetricks

### ISSUE THREAD

**Issue by publicarray** [Gcenx/WineskinServer#2]
I used the `isolate_home` winetricks script but now winery is complaining:

```
Error while creating folder: The file “My Documents” couldn’t be saved in the folder “Wineskin” because a file with the same name already exists.
```

Same with these folders

* Desktop
* Downloads
* My Videos
* My Music
* My Pictures

**Comment by Gcenx** [comment]
> I used the `isolate_home` winetricks script but now winery is complaining:
> 
> ```
> Error while creating folder: The file “My Documents” couldn’t be saved in the folder “Wineskin” because a file with the same name already exists.
> ```
> Same with these folders
> 
> * Desktop
> * Downloads
> * My Videos
> * My Music
> * My Pictures

You don't need to use winetricks for that option its built into Wineskin.app under "Options"

Untick "Map User Mac OS X folders in wrapper"

**Comment by publicarray** [comment]
Right but It's still the same problem `The file “My Documents” couldn’t be saved in the folder “Wineskin” because a file with the same name already exists.`

**Comment by Gcenx** [comment]
> Right but It's still the same problem `The file “My Documents” couldn’t be saved in the folder “Wineskin” because a file with the same name already exists.`

Ah I see what your saying no, I disabled the option and my second launch now I get that same error gotta I will fix that and commit an update

**Comment by Gcenx** [comment]
@publicarray I added in additional checks now and I no longer get that error with that option disabled.

**Comment by publicarray** [comment]
Sweet thanks 👍

I have a question which repository contains the most uptodate source code? or where development is happening?

https://github.com/vitor251093/wineskin

https://github.com/WineskinCommunity/Wineskin

https://github.com/Gcenx/wineskin

**Comment by Gcenx** [comment]
> Sweet thanks 👍
> 
> I have a question which repository contains the most uptodate source code? or where development is happening?
> 
> https://github.com/vitor251093/wineskin
> 
> https://github.com/WineskinCommunity/Wineskin
> 
> https://github.com/Gcenx/wineskin

Well my source code for unoffical won’t direclty be uploaded I have my reasons.

But any changes & bug fixes do get merged back to;
https://github.com/vitor251093/wineskin

Currently unofficial is based off EngineRepacking2, that is an improved and expanded version of EngineRepacking branch that I created from code from unoffical and Vitor improves and expanded it so it was much more useful.


The current fixes will be added there when I get enough time to do them cleanly

**Comment by publicarray** [comment]
> Well my source code for unoffical won’t direclty be uploaded I have my reasons.

Interesting considering that the source GPL licenced. But I'm just happy that someone is willing to fix things 😄  Thanks!
