### ISSUE TITLE
Wineskin Startup Script - how to put path of dropped file into a variable?

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#200]
I probably should have figured this out for myself, but I can't, and haven't found any documentation.

Wineskin obviously knows the path of a file dropped on a Wineskin app, because it can open the file. Is there a way to use that path as a variable in the Wineskin Startup Script? I tried using $1 and "$1" but neither of those worked. Am I missing something obvious?

**Comment by Gcenx** [comment]
`$CONTENTSFOLD` gets you to the wrappers Contents directory.

The startup/shutdown scripts are not aware of anything else.

**Comment by emendelson** [comment]
OK - that matches what I found. Thank you.

Meanwhile, does the "custom commands" field have any way of getting the path of a dropped file? I see that the Windows command line can use "%1" but I couldn't make that do anything in the "custom commands" field. I also searched through doh123's old source code, but couldn't figure out how  the dropped file got the Windows command line. Someone who understood the code could figure it out in two minutes...

**Comment by Gcenx** [comment]
> I also searched through doh123's old source code, but couldn't figure out how the path of the dropped file got itself into the Windows command line

I don’t understand what your attempting to do here.

**Comment by emendelson** [comment]
What I'm trying to do is this:

If the user drops a file on my app, from a host folder that is NOT mapped to a drive letter in Wineskin, the result is a whole series of error messages. What I want to do is this; If the dropped file comes from any path other than the Desktop or Documents folders, I want to create an alias in the dosdevices folder which maps the host path to drive Y: in Wineskin. That way, WordPerfect for Windows can open the file from drive Y: and save it to drive Y:. 

This is what I already do with my AppleScript wrapper around the vDos DOS emulator. I'm hoping to find a way to do it entirely within Wineskin, without creating the wrapper. 

PS My shutdown script deletes any existing mapping of drive Y:, so it can be recreated the next time the user drops a file on the appl

**Comment by Gcenx** [comment]
It sounds like your Apple Script implements the removed “open with” function.

Bot sure why you’d bother to translate the PATH when you should be able to directly pass the file with its PATH directly to WineskinLauncher and it should run it. (I think it’s been a while since I’ve interested with it in this manner from terminal/scripting)

**Comment by emendelson** [comment]
I created an AppleScript that launches the Wineskin app with the POSIX path of the dropped file as a parameter. This works if the dropped file is in a folder that's mapped in the wrapper (Desktop, Documents, etc.). it doesn't work if the path is in a different folder. I get the error message that says there is no application specified for that type of file (sorry, I forgot the exact wording). The same thing happens if I drop the file on the Wineskin app.

**Comment by emendelson** [comment]
Well, I've been wasting your time (not for the first time). I was able to open files dropped from any folder on to my app that runs a DOS emulator (and I could open the file from inside the emulator), but I can't drop a file from any folder on to my WordPerfect for Windows app, even if the folder is mapped to a drive letter in Wineskin. I get the "There is no Windows program configured to open this type of file" error. 

You said that you removed an "Open with" function. If there's any way to make this work again, that might be helpful, but I understand that it may be a security risk. Closing this now.

**Comment by emendelson** [comment]
Just a follow-up. I solved this by writing an AppleScript wrapper that tests whether the dropped file is in one of the mapped folders (Desktop, Documents), and then runs the Wineskin app with the path as a parameter. If the path is not in the mapped folders, then the wrapper does two things:

1. It creates a shortcut to the parent folder in the dosdevices folder, mapping Y: to the parent folder
2. It modifies in info.plist to add the program parameter "y:\filename.ext"

This makes the dropped file open in the application. It would be good to be able to do this from the startup script or custom commands, but I know that's a lot to ask!
