### ISSUE TITLE
Windows app installer reports less than 32MB of RAM

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#202]
**Environment (please complete the following information):**
 - OS:  12.1
 - Winery version: 1.8.4.2
 - Master Wrapper version: Wineskin-2.9.0.9-4
 - Engine version: WS11WineCX64Bit21.1.0
 - Hardware:  MacBook Air 2017
 - Application/Game Name  WordPerfect Office x13

**Describe the bug**

When running the WordPerfect X3 installer, this error message appears:
`System Check`
`Your computer needs 32 MB or more RAM to run the WordPerfect OfficeReady. Setup has detected that your computer has less than 32 MB of RAM and will now exit.`

**To Reproduce**

Download WP Office X13 from archive.org; extract the files from the CD and copy them to drive C: in Wineskin; use the command prompt tool to run Setup.exe.

**Expected behavior**

This message should not appear.

**Screenshots**

![Screen Shot 2021-12-21 at 7 02 05 PM](https://user-images.githubusercontent.com/5208505/147023168-de420e7e-8a1c-44fe-a6fc-682b480b36d2.png)

**LastRunWine.log**
I'm sorry but I don't have a log for this.

**Additional context**

**Comment by Gcenx** [comment]
I’m going to guess this application was for Windows XP or older?

If that’s the case then in winecfg try setting to WinXP, as the application is lightly a 32Bit application use the none 64Bit CX21.1.0 Engine this will let you select below WinXP.

Usually older applications can’t read HDD/RAM/VRAM over a specific amount.

**Comment by emendelson** [comment]
It was WordPerfect Office X3, released 2006, so that sounds right. As it turns out, the part of the installation that failed was a part that I didn't want anyway; the rest of the suite installed perfectly. Will experiment with the XP setting. Thank you again!
