### ISSUE TITLE
San Andreas crashing on startup

### ISSUE THREAD

**Issue by adamfirst1986** [Gcenx/WineskinServer#211]
Hello, I have a problem with GTA San Andreas. For some reason, the game just crashes on startup. What can I do to fix it?
It works in Crossover and doh123 Wineskin

Mojave, iMac 2013
Here's the last wine log

[last-wine-log.txt](https://github.com/Gcenx/WineskinServer/files/7857465/last-wine-log.txt)

**Comment by Gcenx** [comment]
Please don’t skip the issue template that provides me needed information to help resolving issues.

**Comment by adamfirst1986** [comment]
Sorry! I thought maybe this was enough
Here's the full info

**Environment (please complete the following information):**
 - OS: Mojave
 - Winery version: Wineskin Winery v1.8.4.2
 - Master Wrapper version: Wineskin 2.9.0.9-4
 - Engine version: WS11WineCX21.1.0
 - Hardware: imac 2013
 - Application/Game Name: GTA San Andreas

**Describe the bug**
When I open the game, it crashes right away

**To Reproduce**
1. Make an app
2. Put the game folder in drive C
3. Start the game

**Expected behavior**
Game to start

**Screenshots**
Simply shows black

**LastRunWine.log**
``` 
002c:err:winediag:WS_getaddrinfo Failed to resolve your host name IP
0024:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 02D01123, 02D3C020, 02D3C038) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 02D39B68, 43) stub
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0024:fixme:dinput:IDirectInputDevice2WImpl_GetProperty DIPROP_VIDPID not implemented
00c0:fixme:imm:ImeSetActiveContext (0x161070, 0): stub
0024:fixme:imm:ImeSetActiveContext (0x184530, 1): stub
00c0:fixme:imm:ImmReleaseContext (00010022, 00161070): stub
0024:fixme:imm:ImmReleaseContext (00020050, 00184530): stub
0024:fixme:d3d:resource_check_usage Unhandled usage flags 0x20.
0024:fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
0024:err:gstreamer:gstdecoder_init_gst Failed to create decodebin; are 32-bit GStreamer "base" plugins installed?
wine: Unhandled page fault on read access to 0000000C at address 27628B2C (thread 0024), starting debugger...
0024:err:seh:start_debugger Couldn't start debugger L"false" (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger
0024:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0024:fixme:ntdll:EtwEventUnregister (0) stub.
0024:fixme:msvcrt:__clean_type_info_names_internal (02BE333C) stub
```

**Additional context**
I managed to start bigger games, but had not luck with this one

**Comment by Gcenx** [comment]
That makes a little more sense now, this seems more of a runtime issue sadly.

Launch winecfg and disable `gstreamer` I believe that _should_ get you into game.

**Comment by adamfirst1986** [comment]
I disabled winegstreamer and it worked! Thank you so much!!

But I also see a visual bug that slows down the performance
Is it okay to ask about it here or maybe I should create a separate issue thread?
Here's how it looks like: https://gfycat.com/elasticklutzyjunebug (car window flickering)

**Comment by Gcenx** [comment]
It might just be a wine regression or some additional native windows library is required check the log after running to see if it complains about something.

Other than that nothing much can be done other than try using a much more recent wine package.

I currently don’t provide any newer Winehq builds are the majority of users are using more recent macOS versions, but my Winehq packages are provided directly via brew, those however as those are upstream packages they don’t provide a GUI.

**Comment by adamfirst1986** [comment]
I understand. Still, it's great that it works! Thank you again! I just couldn't figure out
