### ISSUE TITLE
Unable to create blank wrapper, "Error while moving file..."

### ISSUE THREAD

**Issue by ThatOneBro** [Gcenx/WineskinServer#215]
**Environment (please complete the following information):**
 - OS:  macOS 10.14.6
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.0.9-4
 - Engine version: WS11WineCX64Bit21.1.0
 - Hardware:  MacBook Pro 15" 2017
 - Application/Game Name:  Not applicable

**Describe the bug**

When creating a new blank wrapper on a new installation of Winery, I keep getting an error message after Wine configures (which seems to happen twice, not sure if it's normal or not) which states: 
```Error while moving file: "derrick"(my local user) couldn't be moved to "users" because an item with the same name already exists.```

After this error, the app becomes unresponsive and must be force quit/killed.

**To Reproduce**

1. Installed Winery as per install instructions, both through homebrew and manually (removing quarantine, not using keka)
2. Installed WS11CX64Bit21.1.0 engine
3. Installed latest Master Wrapper with "Update" button
4. Clicked on "Create New Blank Wrapper"
5. Assigned name "Agos"(game I want to install on wrapper)
6. Pressed Enter

**Expected behavior**

From what I can tell, a blank wrapper should be able to be created.

**Screenshots**

<img width="429" alt="Screen Shot 2022-01-26 at 3 03 14 PM" src="https://user-images.githubusercontent.com/1592008/151254224-61e10837-0ed9-430f-9344-17b743eb1546.png">
Error message shown after Wine configures twice during wrapper creation. Winery then stops responding and must be killed/force quit.

**Additional context**

I don't know if it matters much, but I did have the official Wineskin installed briefly I believe. I'm not sure if there are some residual files somewhere that could be affecting the unofficial installation.

If you need anything else to work off of, please let me know! Thanks.

**Comment by Gcenx** [comment]
This usually happens when another wine process is still active/stuck ensure there’s no running wine processes or simply reboot and try again.

**Comment by ThatOneBro** [comment]
@Gcenx Ah yes, that worked quite nicely. I didn't even think other wine processes might be interfering... Thanks for the simple resolution. Appreciate all your work!
