### ISSUE TITLE
64bit engine Internet access fails

### ISSUE THREAD

**Issue by Alex1844** [Gcenx/WineskinServer#22]
I have just ported my 32 bit application to 64 bit and on Windows both versions work just fine.
32 bit also works fine in 32 bit Wineskin engines but in ALL 64 bit engines, the application works fine but it fails to connect to the Internet. It does not crash the application, nor does it freeze it, but the thread trying to connect to the Internet gets stuck at connecting to https web sites. The application is compiled with the latest OpenSSL

What could be a problem?

**Comment by Gcenx** [comment]
Did that also include trying WS10WineCX64Bit18.5.0? As that’s one I built personally all WS9 Engines are Winehq repacks.

Could you provide a log?

**Comment by Alex1844** [comment]
Sorry for not replying earlier, I was swamped with work.

The issue was caused by a call to AfxBeginThread in an old C++ application I maintain. It works fine on Windows 32/64 and Wineskin/WS10Wine18.5.0, but on WS10WineCX64Bit18.5.0 the call crashes the app.
I ended up replacing the AfxBeginThread call with a call to CreateThread wich works fine on all versions.

Thanks
