### ISSUE TITLE
Wineskin damaged

### ISSUE THREAD

**Issue by Stasioslaza** [Gcenx/WineskinServer#220]
Opened WineskinServer-master, checked Winery folder, nothing. Moved on to the Wrapper folder, found Wineskin-2.9.0.9-4.app.tar.7z, downloaded it, opened WineSkin-2.9.0.9-4, apparently, it is damaged and cannot be opened.

**Comment by Gcenx** [comment]
You’ve not read the projects readme and also skipped the issue template so closing.
