### ISSUE TITLE
Can't create Wrapper 

### ISSUE THREAD

**Issue by nevinhappy** [Gcenx/WineskinServer#229]
Env  Info : 
 - System : 11.5.1 
 - CPU : M1 
 - WineSkin : V1.8.4.2 
Issue Info : 
![图片](https://user-images.githubusercontent.com/1475079/154030739-111fec4a-4685-49b9-a34b-557575c9c396.png)
![图片](https://user-images.githubusercontent.com/1475079/154034219-21ec158d-869a-46ab-b8fd-eac688d19590.png)
I have installed WineSkin and I launched it, But I find I can't go next . 
- WS11WineCX65Bit21.1.0 is an offline file I downloaded from github and set to dir;
- Wrapper Version show "No Wrapper Installed".
- I still can't try "Update " and "Crete New Blank Wrapper"

**Comment by ChrisLensFlare** [comment]
Re-installing it worked for me.

**Comment by Gcenx** [comment]
Obligatory works for me

**Comment by nevinhappy** [comment]
> 

I think this issue is about accessing github.com.
