### ISSUE TITLE
My computer's available hard drive space starts dropping rapidly when using a wrapper with Steam

### ISSUE THREAD

**Issue by Hyperdimensionals** [Gcenx/WineskinServer#230]
- OS: 10.14.6
 - Winery version: 1.8.4.2
 - Master Wrapper version: Wineskin-2.9.0.9-4
 - Engine version: WS11WineCX64Bit21.1.0
 - Hardware: MacBook Pro (15-inch, 2019)
 - Application/Game Name: Steam

I seemed to have fixed this once I found your wiki on using Steam and added the launch commands `-udpforce -allosarches -cef-force-32bit`.  However, I'll still post this just in case it helps, and it'd be great if I could get some insight into why this happened. When I would start the wrapper with Steam, Steam would launch as expected, but I noticed my available hard drive space would start to drop rapidly. I tried launching it with about 50GB left on my hard drive, and then I cleared more space so I had 100+ GB left, and both times the available space would drop rapidly (as indicated when going to 'Get Info' on my hard drive) and eventually Mac OS warnings would pop up that my hard drive was almost full. Once I quit the wrapper, my hard drive space would rise back up again.

Also, I was trying to install Black Mesa and in Steam it would say I didn't have enough space, showing only about 10GB left.

But, I added those launch commands and both of these issues seemed to have resolved, and it is now letting me begin downloading Black Mesa.

**Comment by Gcenx** [comment]
Steam uses CEF for its browser but it’s bugged on macOS and needs those launch commands, those _should_ be injected automatically by the CX engines but half the time it fails (also happens with CrossOver)

The disk space one is annoying but I’ve found it being related to time machine local backs, after clearing those out the issue goes away. macOS itself ignores the space used by time machine local backups so it’s a little harder to figure it out.

Some older installers also have an interesting bug (even on windows) depending how large the drive is it can end up saying there’s not enough free space when there is plenty.

**Comment by Hyperdimensionals** [comment]
Thanks for the insight. Is the fact that I added the launch commands directly related to this bug resolving, or is there a chance it can happen regardless? If so, I guess I'll clear my local time machine backups.
