### ISSUE TITLE
Can not intstall visio

### ISSUE THREAD

**Issue by kingxiaofire** [Gcenx/WineskinServer#234]
Macbook Pro 13 2017 
MacOS 10.15.7
Wineskin-2.9.0.9-4
WS11WineCX64Bit21.1.0

First, I download the visio ISO file from https://msdn.itellyou.cn/.
Than , unzip the iso file with The Unarchiver.
Than , create new blank wrapper.
Than install the app by choosing the setup64.exe
But it was wrong, as follows, I don't know why, Can I have you suggests please?
Thank you.
![41CDBD58A01CF497D7106FC0A35405D3](https://user-images.githubusercontent.com/27213623/156870219-18ef9af4-b74b-4aa8-8fba-661f4befb4dd.jpg)

**Comment by emendelson** [comment]
Run Wineskin. Choose Advanced. In the "Windows EXE" field, browse to the Visio executable and choose it. (I don't know if this will work, but that is what you generally need to do in this situation.)

**Comment by kingxiaofire** [comment]
> This usually works when the downloaded file is a single ".exe"file, and I have successfully installed OriginLab, a drawing software on my mac. But it doesn't work for files that are "ISO" after download, although I unzipped the ISO and chose setup64.exe to install it. The steps are just like you said.
