### ISSUE TITLE
Disk access on Catalina

### ISSUE THREAD

**Issue by Alex1844** [Gcenx/WineskinServer#25]
I have weird issues running Wineskin wrapper on Catalina.

The Windows app works fine, but it cannot access Documents folder for example. OK, I figured I need to use System Preferences and Security permissions to add my app to Full Disk Access, and it starts working after that.

However, if I restart my Mac, it stops working. The app is still in the Full Disk Access, but has no access. If I rename the wrapper in /Applications folder, it starts working again, for a while, but then after a few days, or if I restart the machine, it stops again, and so on.

Any idea what may be going on?

**Comment by emendelson** [comment]
The problem seems to occur with apps that aren't notarized, and Wineskin apps seemingly can't be notarized. I've avoided it by NOT setting up the Documents folder as a Windows drive. Not convenient, but better than nothing.

**Comment by Gcenx** [comment]
Im not sure that wrapper can’t be notarized, the included symlinks could be causing an issue on blank wrappers.

Instead try to notarize WineskinLauncher as that’s the primary binary.


At the moment I’m busy testing CrossOver19 on Catalina, but I’d spoken Vitor and the plan is I’ll commit my cluster of a branch then when he gets time he will hopefully implement NSTask launching that should help resolve these macOS Catalina issues.

**Comment by emendelson** [comment]
I'm afraid I haven't figured out how to notarize a binary - I've only notarized apps, DMGs, and PKGs. If someone else can spell out the technique, I'll be glad to try it.

**Comment by Gcenx** [comment]
@emendelson I’ve not looked into it yet IRL is hectic at the moment.

It can be notarized while compiling so if none of us figure it out, it will be done in my next compile

**Comment by Alex1844** [comment]
I have just found out that if I launch WineskinLauncher by double clicking it in finder inside my .app/MacOS package, it launches my application with full disk access every time. 
If I launch my app in /Applications it does not have full disk access even though the app is given Full Disk Access in Security and Privacy.

Are you switching to NSTask in the next Wineskin release?

**Comment by Gcenx** [comment]
The next wrapper release won't be changed over it will just be a quick change to get wine32on64 functional. But the NSTask change might now the issue, it could be the lack of entitlements.

Once wine32on64 works I'll be pushing my current source back to https://github.com/vitor251093/wineskin under a new branch, then anyone who wants to help out can.

**Comment by Alex1844** [comment]
Does this give you any idea?

Whenever I launch my app, this is recorded in the console log with a different bundle identifier. Why is MacOS using a different bundle identifier from the one provided in info.plist?

TCCAccessCopyInformationInternal(): Failed to find application for bundle_id MyApp414617064.wineskin.prefs.
TCCAccessCopyInformationInternal(): Failed to find application for bundle_id MyApp105501160.wineskin.prefs.
TCCAccessCopyInformationInternal(): Failed to find application for bundle_id MyApp340212475.wineskin.prefs.

**Comment by Gcenx** [comment]
@Alex1844 I’ve scanned the codebase and .pref is now no more so that will be resolved in the next release I’ll be putting online shortly.

- Slight change to BundleID generation (.pref gone)
- Updated Runtime (December 24th 2019)
- Wine32on64 support (WineCX19.0.0)
- wstools.bundle removes 7z (fixes some issues with winetricks)
- wstools.bundle/lib is read first for older Engines
- /opt/local/lib is read before Frameworks on newer Engines

**Comment by Gcenx** [comment]
Closing in favor of #26 better to keep all Catalina within that issue since it not officially supporting it
