### ISSUE TITLE
Grey window when in "Open File" Windows Dialog

### ISSUE THREAD

**Issue by vicmarto** [Gcenx/WineskinServer#28]
When using a WS9Wine64Bit* engine from Winehq, the "Open File" Windows Dialog always appears grey, with no possibility to select any file.

Steps to reproduce it with Wineskin-Winery-1.8.4:

1. Create a blank wrapper (tested with WS9Wine64Bit5.1, WS9Wine64Bit5.0 and WS9Wine64Bit4.20)
2. Install a Windows 64 bits windows software, for example [KeePassXC (portable)](https://github.com/keepassxreboot/keepassxc/releases/download/2.5.3/KeePassXC-2.5.3-Win64-Portable.zip)
3. In KeePassXC make: Database > Open Database, and the following appears:

![Open File](https://user-images.githubusercontent.com/11044285/74035868-7adc4c00-49fe-11ea-8fce-d047948abd55.png)

WS11WineCX64Bit19.0.1 works as expected:

![Open File_CX](https://user-images.githubusercontent.com/11044285/74036285-4c12a580-49ff-11ea-93a6-f4852d1ce731.png)

**Comment by Gcenx** [comment]
I can confirm the issue, seems to be a winehq packing issue as my self compiled Wine-Staging-5.1 build doesn't have this issue.

I've uploaded WS10 compiles Wine-Staging-5.1 to my MEGA that's linked within Winery "Download Packages Manually" button that works correctly.

**Comment by vicmarto** [comment]
Sorry, there is nothing you can do? The problem is in the winehq side? Thanks.

**Comment by Gcenx** [comment]
@vicmarto yes unfortunately that’s a Winehq packing issue.

I did build WS10WineStaging5.1 & WS10WineStaging64Bit5.1 Engines and uploaded them to my MEGA folder, the linked is embedded into “Download Packages Manually” within Winery

Download the needed Engine and place into 
`~/Library/Application Support/Wineskin/Engines` now it will be available within Winery for new wrappers and Wineskin “change engine” menu.
