### ISSUE TITLE
Minifying the engine and wrapper for a specific Windows application

### ISSUE THREAD

**Issue by Alex1844** [Gcenx/WineskinServer#3]
Not really an issue, but a question that might be useful for others.

What is the best way to produce wrapper/engine with minimum size by eliminating the files that are not used by the Windows application you are running in Wineskin?

Lets say I just want to package a simple application like Notepad.exe. Having 400MB final package with the latest wrappers and engines is a huge overkill.

I have tried creating a wrapper, installing the application and then manually removing some files in the Wineskin wrapper and in Wine engine and then trying to run the application, but it is a tedious hit and miss experience because I basically need to test all the apps functionality every time.

Is there a way to use something like Dependency Walker (http://www.dependencywalker.com/) to identify the files actually needed and loaded while running the application in Wineskin?

Thanks for any suggestion.

**Comment by Gcenx** [comment]
If I figure something else out I will reopen this, or if you @Alex1844 finds something out please feel free to reopen and add the information.
