### ISSUE TITLE
Closing window oq Quit randomly don't work

### ISSUE THREAD

**Issue by PlanetIrata** [Gcenx/WineskinServer#30]
Hi, when I use Wineskin 2.9.0.6 and WS11WineCX19.0.1 engine, quitting my program with the menu or with the close button of the Window works randomly (one time on 10 maybe...). I've tried to check the option "Try to shutdown nicely so Windows program...", but it still is randomly exiting.

Any idea someone ?

Anyway, thanks for great work @Gcenx!

**Comment by Gcenx** [comment]
It sounds like something or some part of the application crashed and that’s causing the stray processes, WineskinLauncher won’t exit until wineserver exits

**Comment by PlanetIrata** [comment]
Fixed, it was related to the usage of Chromium Embedded Framework in my app in multithread mode. Setting CefSingleProcess to 1 solve the issue with Wineskin.

Thx for your work. Hope you'll release soon an engine for Catalina which not need to disable SIP 🤞
