### ISSUE TITLE
Wineskin Wrapper doesn't update

### ISSUE THREAD

**Issue by andynameistaken** [Gcenx/WineskinServer#307]
- When you choose "file to download and install" the progress bar just quickly goes to the end, but wrapper is not installed
- OS: macOS Monterey 12.6
- Wineskin: 1.8.4.2

**Comment by Gcenx** [comment]
This should now be resolved the archive had an extension that the current `wineskin winery` won't accept

**Comment by fixedprincess** [comment]
hello I need help:(((( I've been trying to install wineskin for so long and I can't, I have a MacBook with Monterey and every time I open the app it says "no wrapper installed" and Idk what to do to fix it, can somebody help me please?:(((
