### ISSUE TITLE
Wrappers can't be moved to an external drive

### ISSUE THREAD

**Issue by evelynparenteau** [Gcenx/WineskinServer#309]
If you try to move a wrapper (e.g. by dragging and dropping in Finder) to an external drive (mounted in `/Volumes` by the system), then trying to execute the moved wrapper results in a system dialog popping up that says "You can't open the application (wrapper name here) because it may be damaged or incomplete.". I tried working around this by making `~/Applications/Wineskin` a symlink to the external drive and then creating a new wrapper, but it actually fails in the same way.

**Comment by Gcenx** [comment]
Did you place those into a sub-directory after being placed onto the external drive?

I’ve moved a number of prebuilt wrappers onto my external drive all at the top and those function, so I’m assuming these were placed into a sub-directory?

**Comment by evelynparenteau** [comment]
Actually they are placed in the root directory, but on further investigation I think the problem is that this particular external drive has a case-sensitive filesystem. Reformatting as a normal APFS drive allows it to work normally.

**Comment by Gcenx** [comment]
Now that’s interesting, made the above new label for the situation as this will lightly come up again thanks for the feedback and resolution!
