### ISSUE TITLE
Game installer reports 40gb free in C:/, but my Mac has 85gb free, why is it only this much?

### ISSUE THREAD

**Issue by CharlieWhile13** [Gcenx/WineskinServer#31]
Games aren't letting me install them due to little space left, but my mac has double the space the installer's are claiming I have. Is there a file I need to change to re-size C:/

I'm on Catalina 10.15.4

**Comment by Gcenx** [comment]
I’ve had this free space issue and it was Time Machine causing these issues, I needed to disable it and force remove all Time Machine related data.

Somehow Time Machine leaves days behind that’s not been backed up when my backup was recent

**Comment by CharlieWhile13** [comment]
Can confirm deleting all the local snapshots worked, the inbuilt tool to check available space doesn't include these because normally they are purged automatically. 

The command for Terminal if anyone wants it is:
`for d in $(tmutil listlocalsnapshotdates | grep "-"); do sudo tmutil deletelocalsnapshots $d; done`
