### ISSUE TITLE
Black screen in game: Sea Dogs

### ISSUE THREAD

**Issue by nikitarkh** [Gcenx/WineskinServer#314]
**Environment (please complete the following information):**
 - OS: 13.0
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.1.5
 - Engine version: WS11WineCX64Bit22.0.1
 - Hardware: iMac 2021 M1
 - Application/Game Name: Sea Dogs Each His Own (Steam AppID 223330)

**Describe the bug**
Black screen when running game.

**Screenshots**
<img width="2032" alt="Снимок экрана 2022-10-31 в 15 43 43" src="https://user-images.githubusercontent.com/117089278/199014261-48f5f2c9-ae49-4d6d-8e51-8ba5a03aaf62.png">

**LastRunWine.log**
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/9901189/LastRunWine.log)

**Comment by Gcenx** [comment]
Doing a search it seems this game uses Unreal Engine 4, download https://github.com/The-Wineskin-Project/MoltenVK/releases/download/v1.2.0/macos-1.2.0-pr1678-UE4hack-Wideline-zeroinit.tar.xz extract and replace libmoltenvk.dylib from in `<wrapper name.app>/Contents/Frameworks/`

It seems you've not installed any version of DXVK you should also install `dxvk1103_macOS`

<br>

Might also want to install the following winetricks verb `d3dcompiler_47` 
```
04cc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\d3dcompiler_47.dll" at 00000001C8890000: builtin
```

**Comment by nikitarkh** [comment]
Thanks. I'm did it. But nothing changed.
[new LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/9901674/new.LastRunWine.log)

I'm tryed change enigine to ws11winecx64bit19.0.2. Rebuild wrapper. Then the game is run. But wine (4.12.1) ignored locale and i see bad cyrillic font.

**Comment by nikitarkh** [comment]
**Engine WS11WineCX19.0.2-2:**
Logs:
[CX64Bit19.0.2-2 LastRunWine.log.zip](https://github.com/Gcenx/WineskinServer/files/9902263/CX64Bit19.0.2-2.LastRunWine.log.zip)

Screen (with broken cyrillc font):
<img width="1988" alt="Снимок экрана 2022-10-31 в 17 43 23" src="https://user-images.githubusercontent.com/117089278/199038802-a9cb84b5-a150-42ee-9eb5-6a8f17997c16.png">

How i can fix locale permission in wine?

**Comment by Gcenx** [comment]
For the fonts you’ll need to find a native copy of that font.

Refer to this list https://www.codeweavers.com/support/wiki/mac/faq/cxoffice62_choosedifferentlanguage

Using there example that’s listed at the top, you put the following into the Custom CLI field.
```
export LC_ALL="ru_RU.UTF-8"
```
Just change `ru_RU.UTF-8` to what ever local you require.

**Comment by nikitarkh** [comment]
I did it. Nothing changed. I pasted this command into "Unix Commands" in Wrapper and into Steam game start parameters.

Maybe go back to the first option and run on ws11winecx64bt22 engine?

**Comment by Gcenx** [comment]
Might as well give it a try no promises it will work though.
