### ISSUE TITLE
Black window when opening Steam

### ISSUE THREAD

**Issue by stefo-beam2drive** [Gcenx/WineskinServer#315]
Environment:
 - OS: macOS 13 (=Ventura)
 - Winery version: 1.8.4.2
 - Master Wrapper version: Wineskin-2.9.1.5
 - Engine version: WS11WineCX64Bit22.0.1
 - Hardware: MacBook Pro 13" M1 2020, 256Gb, 8Gb Ram
 - Application/Game Name: Steam

Describe the bug:
Opening Steam shows a black window **with no UI at all**.

To Reproduce:
 - Create a Wrapper
 - Install DXVK (For BeamNG.drive)
 - Install Steam with Winetricks
 - Launch Steam 
 - black window with absolutely **no UI** pops up

Expected behavior:
Steam Login shows up and Steam can be **used**.
Like on a windows PC.

Screenshot:

![Bildschirm­foto 2022-10-31 um 22 17 24](https://user-images.githubusercontent.com/114953834/199113729-020cc9f4-dcab-46e0-a85d-3b380dbebd56.png)

Wine logs:
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/9905156/LastRunWine.log)
[LastRunX11.log](https://github.com/Gcenx/WineskinServer/files/9905157/LastRunX11.log)

Additional Information:
I already added the command to the unix command:
-noreactlogin -udpforce -allosarches -cef-force-32bit

I'm sorry if I didn't follow the writing guide that good.

**Comment by Gcenx** [comment]
The commands don’t go into the Unix field

Currently not near my Mac so borrowed a screenshot from PortingKit.
![A8DAFEDB-D168-4AF7-8DC3-671885C425AC](https://user-images.githubusercontent.com/38226388/199117186-bc858eac-9427-4d41-95b9-6ceac41c802b.jpeg)

**Comment by stefo-beam2drive** [comment]
Thank you so much!!
I'm sorry for being so stupid.
