### ISSUE TITLE
Wineskin-2.9.1.5 has no settings for windows or file formats

### ISSUE THREAD

**Issue by Q-mii** [Gcenx/WineskinServer#316]
I'm on MacOS 12.6.1, on the latest engine. I noticed that the latest wrapper has no settings for window setting and file extensions. How can this be fixed? Can I downgrade to a lower version of the wrapper?
<img width="260" alt="Screen Shot 2022-11-01 at 4 59 09 PM" src="https://user-images.githubusercontent.com/77647979/199363920-6b6dfcab-bb3c-461c-9c7b-f15999eebba0.png">
<img width="331" alt="Screen Shot 2022-11-01 at 4 59 20 PM" src="https://user-images.githubusercontent.com/77647979/199363935-dc10cb2e-3ccf-4dfe-ab73-703844d871cf.png">

**Comment by Gcenx** [comment]
I’ve removed screen setting.

Affording to other user reports the file extensions section didn’t function correctly, I’d partly disabled it in prior releases but then in asked for workaround. For now it’s simply hidden as it doesn’t work.

Not sure when/if I’ll get around to making that function work, you can still register file extensions to apps via regedit (see Winehq documentation for details)
