### ISSUE TITLE
Cannot edit or remove file formats

### ISSUE THREAD

**Issue by Q-mii** [Gcenx/WineskinServer#317]
In Wineskin 2.9.1.1, I can't remove file extensions or edit the ones I add.
<img width="164" alt="Screen Shot 2022-11-01 at 4 57 12 PM" src="https://user-images.githubusercontent.com/77647979/199363743-a152fb10-affe-4a01-ad43-a9f9a1ab9c48.png">

**Comment by Q-mii** [comment]
Why is this completed? The Wineskin that came with Clickteam allowed me to edit file extensions. Plus there are exe flags and a "use Start.exe" command. What happened?
<img width="674" alt="Screen Shot 2022-11-01 at 5 41 35 PM" src="https://user-images.githubusercontent.com/77647979/199369329-d9e994bb-1342-41f9-abfa-2cd799517bc0.png">

**Comment by Gcenx** [comment]
This was disabled as it no longer functions correctly, this was simply hidden in the latest version.

Use start is now automated, EXE Flags are added behind the Windows EXE in the same field.
