### ISSUE TITLE
Screen Options is missing from Main Menu as well as From Advanced Options Panel

### ISSUE THREAD

**Issue by cwelk** [Gcenx/WineskinServer#320]
- OS: macOS 13.0 Ventura
 - Winery version: 1.8.4.2
 - Master Wrapper version:  2.9.1.5
 - Engine version: CX 22.0.1
 - Hardware: MacBook Pro 2021

**Describe the bug**
Screen Options is missing from Main Menu as well as From Advanced Options Panel.
Now there is blank space where that button was.

**To Reproduce**
Hard because it was there initially. At one point it was gone, and even reinstalling wineskin and the wrapper did not help.

**Expected behavior**
Able to enter screen options page.

**Screenshots**
https://www.dropbox.com/s/qpgefume9klyuz6/issue_screenshot_a.png?dl=0
https://www.dropbox.com/s/p618fo1n1tb3dve/issue_screenshot_b.png?dl=0

**Comment by burhancabiroglu** [comment]
i had to

**Comment by Gcenx** [comment]
This isn’t a bug.

Screen options has simply been removed from Wineskin as outside of “Retina” everything else is useless.

Screen Options empty slot will be resolved with “winetricks” in a future wrapper bump, I may or may not restore “Retina” as this also caused sever performance loss. Retina mode can still be enabled manually via the winetricks menu and adjust text DPI via winecfg.

**Comment by cwelk** [comment]
Thank you for the fast reply.
If the image is non-fullscreen and additionally shrinked to half size (due to retina display I assume) is there a way to have it running fullscreen? **I did not find a "Retina" option when I searched wine tricks.**
See this screenshot of how it looks currently:
https://www.dropbox.com/s/dv0eimkm7kbi639/small.png?dl=0
**Sry asking noob questions, I really appreciate this project!**

**Comment by cwelk** [comment]
I created a fresh wrapper and only activated the dxvk verb now the 50% scaling is gone.
Thanks

**Comment by Gcenx** [comment]
> I created a fresh wrapper and only activated the dxvk verb now the 50% scaling is gone.

It’s the reverse, enabling _retina_ disables macOS native scaling.

Behind the scenes Wineskin would adjust wines font dpi to compensate but this could also cause problems for windows apps that were not high dpi aware.

**Comment by TrevorAlan11** [comment]
> Screen Options empty slot will be resolved with “winetricks” in a future wrapper bump, I may or may not restore “Retina” as this also caused sever performance loss. Retina mode can still be enabled manually via the winetricks menu and adjust text DPI via winecfg.

Which "wine trick"? There is no wine trick that is called Retina or HiDPI or anything of the sort? How does one enable it?

**Comment by Zetacat** [comment]
Hey guys! I found the solution that successfully enable RetinaMode. 

in regedit:
under `HKEY_CURRENT_USER\Software\Wine\Mac Driver\`
create a string named `RetinaMode` with value = `y`
(in my case the folder `Mac Driver` doesn't exists and I have to manually create it) 

<img width="742" alt="image" src="https://github.com/Gcenx/WineskinServer/assets/13826218/bd972e98-fee8-4296-b162-12f8cce0c7ca">
