### ISSUE TITLE
How to use Wrappers in Apps like Heroic Games Launcher?

### ISSUE THREAD

**Issue by flavioislima** [Gcenx/WineskinServer#329]
**Is your feature request related to a problem? Please describe.**
Hey guys, I am de the developer of [Heroic Games Launcher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher) and we support MacOS for a while now but Crossover only. 

So I just got a macOS to improve the development of Heroic on it and heard about your software, installed here and I am doing some tests. 
I found out how to use it and where the wine binaries are on the Wrapper package.

But I would like to know how can we call the wrapper from Heroic to launch the game.

This is how we call Crossover on a GOG game for instance:
`CX_BOTTLE=Heroic /Users/user/develop/HeroicGamesLauncher/public/bin/darwin/gogdl launch "/Users/user/Games/Heroic/Death's Door" 1948334236 --wine /Users/user/Downloads/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine --platform windows`

so probably we would just need to pass the WINEPREFIX with:
`/Users/user/Applications/Wineskin/HeroicWrapper.app/Contents/SharedSupport/prefix`

or we would use another ENV var?

For wine would be `/Users/user/Applications/Wineskin/HeroicWrapper.app/Contents/SharedSupport/wine/bin/wine`

I will test during the week if I find some time but I believe that would work :)

**Comment by Gcenx** [comment]
You'd want to use;
`/Users/user/Applications/Wineskin/HeroicWrapper.app/Wineskin.app/Contents/Resources/wine`

Also ensure to set;
`WINETRICKS_FALLBACK_LIBRARY_PATH=/Users/user/Applications/Wineskin/HeroicWrapper.app/Contents/Frameworks`

And yes the `WINEPREFIX` would be;
`/Users/user/Applications/Wineskin/HeroicWrapper.app/Contents/SharedSupport/prefix`

<br>

Though for usability it would be much nicer if the windows version of Heroic Games Launcher worked as then it could be more self contained.

<br>

<br>

<br>

<br>

For the macOS app you might actually find `wine-crossover` could be much more appealing.

```
brew install --cask --no-quarantine gcenx/wine/wine-crossover
```
See https://github.com/Gcenx/winecx/releases/download/crossover-wine-22.0.1/wine-crossover-22.0.1-osx64.tar.xz
If installed via brew it would give access to `wine` & `wine64`, if manually installed you could use `/Applications/Wine Crossover.app/Contents/Resources/wine/bin/wine64`

<br>

<br>

Winetricks fork aimed at macOS
```
brew install --formula gcenx/wine/winetricks
```
See https://github.com/The-Wineskin-Project/winetricks\
This provides custom dxvk verbs aka `dxvk1103_macOS`

**Comment by Gcenx** [comment]
I should note that `wine-crossover` is macOS Catalina and later only.

**Comment by flavioislima** [comment]
That's great, thanks for the clarification, I will add both Wineskin wrappers and Wine-crossover pretty soon.

**Comment by Gcenx** [comment]
If you require wine-crossover to be installed into the uses Applications directory you can force brew to do this at install time.
```
brew install --cask --appdir=$HOME/Applications --no-quarantine gcenx/wine/wine-crossover
```
_I could update the instructions in providing on my brew tap to reflect this._

<br>

<br>

I’m tweaking the next Wineskin wrapper update so the wrapper scripts automatically inject all the needed env.

So all you’d need to set is 
```
/Users/user/Applications/Wineskin/HeroicWrapper.app/Wineskin.app/Contents/Resources/wine
```

**Comment by flavioislima** [comment]
Ah good to know that it can be installed directly into the user's folder. I will add this info to our documentation as well.

And this change on wineskin would be pretty good because for now my idea was only to use the wine inside the wrapper. If you can bring the dependencies with that would be pretty cool.

I looked at you winetricks and I want to implement it in the future in heroic, since we have it on Linux, but we will need to render the options inside heroic since Mac does not come with zenity by default. 

Thanks for the help👍

**Comment by flavioislima** [comment]
hey @Gcenx we have just released a new version of Heroic with support for wine, dxvk and winetricks.
Although I have enabled dxvk and winetricks, it was basically for debugging process because I was not able to use them in my tests. Installing dxvk worked once but then didn't anymore.

For the dxvk, we make a backup of the DLLs on the prefix and register then as native using the wine reg command: you can see the logic here:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/tools.ts#L171

It works fine for linux this way but for mac doesn't, tried with both wine-crossver and wine from a wineskin bottle.

For winetricks, even having cabextract, zenity and p7zip installed, when trying to install dxvk for wine-crossver it fails because it says that the wine version is not supported, even if we pass the `--force` option.
I could not even install a DLL like d3dcompile_47 without it failing.

How exactly do you handle those on wineskin? 

thanks

**Comment by Gcenx** [comment]
> For the dxvk, we make a backup of the DLLs on the prefix 

That shouldn’t be required, remove the dlls along with the overrides and run `wine wineboot -u` would regenerate the missing dlls.

> and register then as native using the wine reg command: you can see the logic here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/tools.ts#L171

For DXVK-macOS it currently only provides 64Bit d3d10/11 related dlls, these must be set to native,builtin. Or the 32bit versions won’t function.

> It works fine for linux this way but for mac doesn't, tried with both wine-crossver and wine from a wineskin bottle.

Usually winetricks expects the following env to be set, WINE, WINE64 & WINESERVER. For wine-crossover set WINE & WINE64 to wine64 or I could do another bump to just include a duplicated copy. (wine-crossover-22.x+ uses upstreams WoW64 system)

> For winetricks, even having cabextract, zenity and p7zip installed, when trying to install dxvk for wine-crossver it fails because it says that the wine version is not supported, even if we pass the `--force` option. I could not even install a DLL like d3dcompile_47 without it failing.

That seems odd, are you attempting to use upstream winetricks and the Linux DXVK verbs?

winetricks-macOS has different versions requirements and are named differently to avoid confusion.

> How exactly do you handle those on wineskin?

Wineskin.app downloads my winetricks fork from head when first launched or the update button is used and placed into 

```
/Users/user/Applications/Wineskin/HeroicWrapper.app/Wineskin.app/Contents/Resources/
```

This same directory is prepended to PATH and WINETRICKS_FALLBACK_LIBRARY_PATH gets set and wineprefix also gets set to the one within the wrapper.

The selected verbs from the UI get passed to winetricks e.g. dotnet45 would become;

winetricks -q dotnet45

**Comment by flavioislima** [comment]
A-ha, interesting. Will do these improvements during the week.

I thought I had set winetricks URL to the one you have hosted here but looking at the code now I probably forgot to push this change. But locally I am using it since it shows DXVK_macOS.

Ok, thanks again for the clarification, will do these fixes and will include on the next release. Or maybe jus update the mac binary, will see. :)

**Comment by flavioislima** [comment]
Ok, did all these changes and now everything is working fine.
For winetricks to be able to see zeniry and the other dependencies

**Comment by Gcenx** [comment]
@flavioislima as of [Wineskin-2.9.1.6](https://github.com/Gcenx/WineskinServer/commit/d656d74a38e1d93c6d4e3cc0287ad7f18ca4f89b) any Wineskin wrapper built from using that wrapper version should set all its own ENV

I’d recently needed to tweak `wine-crossover` this restored the `wine` & `wine-preloader` binaries, a useful side effect for Heroic not needing to force `winetricks` to use `wine64` for everything. It’s still macOS Catalina only though.

On macOS Ventura you’d see some complaints from `preloader` see [bug 54420](https://bugs.winehq.org/show_bug.cgi?id=54420) 

Unfortunately it’s still not possible to run 32Bit windows binaries on a 64Bit only OS in using macOS even though the wine-8.0 released seemed to indicate it was working see [bug 54367](https://bugs.winehq.org/show_bug.cgi?id=54367)

**Comment by flavioislima** [comment]
Nice thanks for the update.
So for wineskin, it will work as a standard wine so it will respect the env variables and configs we setup in heroic?

Question does wine crossover comes with dxvk by default?
I was testing this week and if I disable dxvk on heroic, the dxvk hud would still show. So I was wondering. Or maybe my prefix was messed up, ahahaha

**Comment by Gcenx** [comment]
> Nice thanks for the update.

Well your trying to support my projects so it’s only fair.

<br>

> So for wineskin, it will work as a standard wine so it will respect the env variables and configs we setup in heroic?

Unless I’ve screwed up the wrapper scripts they should accept `WINEPREFIX` if that’s _not_ set it will default back to the wrappers prefix.

There’s should be no need to deal with setting `WINETRICKS_FALLBACK_LIBRARY_PATH` as the wine wrappers should handle finding compatible dylibs on there own now.

<br>

> Question does wine crossover comes with dxvk by default?

It doesn’t bundle the DXVK-macOS dlls nor can DXVK be installed by default in current versions of wine.

<br>

> I was testing this week and if I disable dxvk on heroic, the dxvk hud would still show. So I was wondering. Or maybe my prefix was messed up, ahahaha

It wasn’t uninstalled somehow, it’s possible you’d installed the DXVK-macOS dlls into the games directory and it simply used them.

**Comment by flavioislima** [comment]
Well, I think your project is great and we have the same goal of improving gaming, in this case, on macOS. That is definitely not easy so we should help each other :)

Ok, thanks for the answers. I think my prefix was screwed up, on a new prefix I can enable and disable DXVK just fine.

**Comment by Gcenx** [comment]
@flavioislima in preparation for the coming CX22.1.0 based packages I’ve pushed a newer DXVK-macOS release that provides 32Bit & 64Bit dlls.

I’ve tested this already with C&C: Remastered and S.T.A.L.K.E.R. Call of Pripyat [GOG] both 32Bit titles and both ran using DXVK.

While I’ve provided the dx9 dlls this time these haven’t tested, I’d probably skip these since CrossOver-22.1.0 still uses WineD3D OpenGL for DX9 and below.

**Comment by flavioislima** [comment]
> @flavioislima in preparation for the coming CX22.1.0 based packages I’ve pushed a newer DXVK-macOS release that provides 32Bit & 64Bit dlls.
> 
> I’ve tested this already with C&C: Remastered and S.T.A.L.K.E.R. Call of Pripyat [GOG] both 32Bit titles and both ran using DXVK.
> 
> While I’ve provided the dx9 dlls this time these haven’t tested, I’d probably skip these since CrossOver-22.1.0 still uses WineD3D OpenGL for DX9 and below.

That's great news. So this mean now on heroic we should register the 32bits dlls as well just like we do on Linux. I will update the install method this week.

Thanks for that 😁
