### ISSUE TITLE
Download Locations

### ISSUE THREAD

**Issue by cukabeka** [Gcenx/WineskinServer#342]
Hi, I tried the App and want to uninstall it. Where are the downloaded Wrappers and Winery Files stored? And how can I delete them?

**Comment by Gcenx** [comment]
Wineskin files are stored here
```
$HOME/Library/Application Support/Wineskin
```

Generated wrappers are by default placed into
```
$HOME/Applications/Wineskin
```

Lastly wine and winetricks specific files
```
$HOME/.cache/wine
$HOME/.cache/winetricks
```

**Comment by cukabeka** [comment]
Thanks for clarifying!
