### ISSUE TITLE
Trouble running Sid Meier's Alpha Centauri

### ISSUE THREAD

**Issue by gcohara** [Gcenx/WineskinServer#35]
Hi,

I'm having problems getting SMAC to work.
I created a wrapper using Unofficial Wineskin Winery (located in ~/Applications/), and using the engine WS11WineCX64Bit19.0.1 and wrapper Wineskin-2.9.0.6.
I placed this wrapper in ~/Applications/Wineskin/, and then using the installer I got from GOG.com, run the install within the wrapper, which seems to complete successfully.
I can then run the SMAC exe, and it launches, and shows the intro films. However, when I press a key/click to skip the intro films, or let them play fully, the window exits, flickers/resizes, and I am then taken to a screen where all I can see is the last frame of/frame where I skipped the intro film. 
I can hear the menu music, and sometimes keyboard shortcuts appear to work - e.g pressing q twices quits.

I am guessing this is something to do with video drivers.
I tried with different window systems and general fiddling around with the Screen Options but had no luck. 
Here is my log:
```
000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0xa003
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0xa007
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0xa00b
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x610f
0025:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:err:ole:CoGetClassObject class {d8f1eee0-f634-11cf-8700-00a0245d918b} not registered
0009:err:ole:CoGetClassObject no class object {d8f1eee0-f634-11cf-8700-00a0245d918b} could be created for context 0x1
0030:fixme:ddraw:ddraw_surface7_Flip Ignoring flags 0x1.
0009:err:ole:CoUninitialize Mismatched CoUninitialize
```

I did some research on the GOG forums, and it seems someone else has had luck getting it to run on Catalina (https://www.gog.com/forum/sid_meier_s_alpha_centauri_/anyone_able_to_play_the_game_after_upgrading_to_macos_catalina) , and someone else has had a similar issue but on Mojave (https://www.gog.com/forum/sid_meier_s_alpha_centauri_/macos_1014_mojave) which they managed to fix by forcing XQuartz - but I don't have an option to do that, and trying to run it with X11 didn't work.

I'd appreciate any help!

**Comment by Gcenx** [comment]
If the game is 32Bit you should be using WS11WineCX19.0.1 not WS11WineCX64Bit19.0.1.

The issue is lightly this one. 
```
0009:err:ole:CoGetClassObject class {d8f1eee0-f634-11cf-8700-00a0245d918b} not registered
```
The plugplay ones can be ignored.

Try using winetricks menu and install `ole32`

The XQuartz setting being referenced has no bearing on Unofficial Wineskin as I don’t ship a custom version of it and that, plus `wine32on64` current doesn’t support X11 (XQuartz)

Wineskin from doh123 bundled a custom patched version of XQuartz, this was 32Bit only and based on an ancient version of XQuartz making it a target for removal.\
Since Wine-1.5.28 the default display driver has been macDriver.\
The option of forcing the system version was to allow using the latest version of XQuartz over the bundled version.

**Comment by gcohara** [comment]
Thankyou for your reply.
I tried making a new wrapper with WS11WineCX19.0.1, and tried that. This gave the same problem. Then I went into the Winetricks menu, selected `ole32` and clicked Run, which gave this output:
```
warning: taskset/cpuset not available on your platform!
Executing mkdir -p /Users/georgeohara/Applications/Wineskin/SMAC.app/Contents
------------------------------------------------------
WINEPREFIX INFO:
Drive C: .
..
GOG Games
Program Files
ProgramData
users
windows

Registry info:
/Users/georgeohara/Applications/Wineskin/SMAC.app/Contents/Resources/system.reg:#arch=win32
/Users/georgeohara/Applications/Wineskin/SMAC.app/Contents/Resources/user.reg:#arch=win32
/Users/georgeohara/Applications/Wineskin/SMAC.app/Contents/Resources/userdef.reg:#arch=win32
------------------------------------------------------
------------------------------------------------------
wine cmd.exe /c echo '%AppData%' returned empty string, error message "/Users/georgeohara/Applications/Wineskin/SMAC.app/Contents/Resources/winetricks: line 3338: /Users/georgeohara/Applications/Wineskin/SMAC.app/Contents/Frameworks/wswine.bundle/bin/wine: Bad CPU type in executable" 
------------------------------------------------------



 Winetricks Commands Finished!!
```
Trying to run the game unfortunately still didn't work, with the same problem of only having sound on the main menu. This time the log says
```
001d:err:plugplay:process_IOService_Device object 0x6103
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x6107
001d:err:plugplay:process_IOService_Device object 0xa00b
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0xa00f
0025:fixme:reg:RegOpenUserClassesRoot (00000070, 0x0, 0x2000000, 0067F104) semi-stub
0025:fixme:ole:NdrCorrelationInitialize (0067E410, 0067DEFC, 1024, 0x0): semi-stub
0025:fixme:ole:NdrCorrelationFree (0067E410): stub
0009:fixme:reg:RegOpenUserClassesRoot (00000084, 0x0, 0x2000000, 0033F948) semi-stub
0009:fixme:reg:RegOpenUserClassesRoot (00000084, 0x0, 0x2000000, 0033F9B0) semi-stub
002e:fixme:ddraw:ddraw_surface7_Flip Ignoring flags 0x1.
```

**Comment by Gcenx** [comment]
Ok seems when I rebased winetricks again it caused that issue, use the winetricks menu and update winetricks again so it pulls in the newly patched version that should resolve `Bad CPU type in executable` 

Then try installing that specific trick again

**Comment by gcohara** [comment]
I did try that again, but didn't have any luck.
In the end I got it running on Linux Mint, so just played it on that - but if you want, I can keep investigating and posting logs.
Anyway, thanks for your help!
