### ISSUE TITLE
The new engine is not at the top of the engines list

### ISSUE THREAD

**Issue by Drovosek01** [Gcenx/WineskinServer#353]
I didn't immediately understand why my Wineskin Winery didn't display the new engine in the list until I started investigating where the list was loaded from. For some reason, the most recent engine is at the bottom of the list along with the old engines. It probably shouldn't be like this

![Снимок экрана 2023-02-19 в 01 37 45](https://user-images.githubusercontent.com/29478700/219902557-ccbf4391-ce45-4f98-a1f1-a67ac006e9f5.png)

![Снимок экрана 2023-02-19 в 01 38 07](https://user-images.githubusercontent.com/29478700/219902561-46fec49d-db42-4eea-8918-b881fc859b67.png)

**Comment by Gcenx** [comment]
The reason for this placement was explained in the commit see https://github.com/Gcenx/WineskinServer/commit/37dbc6784ec62b1aef4ba89106dfa22c7421190d

I don’t have the disposable income to simply replace/repair the basically dead Intel Mac see pinned issue https://github.com/Gcenx/WineskinServer/issues/306

**Comment by asmaloney** [comment]
Wouldn't just putting `WS11WineCX64Bit22.0.1-2` at the top of that file instead of the bottom fix this?

Not sure I understand how this relates to Intel Mac stuff?

**Comment by asmaloney** [comment]
I did read the commit message and it's not clear why it was added at the bottom.

> macOS Catalina and later only as this was rebuilt from the m1 mini not the mostly dead Intel macbook pro.

OK. How do I know that has anything to do with where you put it in this list?

**Comment by Gcenx** [comment]
> OK. How do I know that has anything to do with where you put it in this list?

Let’s say your running macOS High Sierra and this is your first time running Wineskin.

You see in the readme the project supports macOS High Sierra and thinking “great this will work for me”

Now you download the latest Engine and try to install Steam, it doesn’t work?, why doesn’t Steam work when the project claims to support my version of macOS?

<br>

So this macOS Catalina and later rebuild was move to the bottom of the list so it needs to be purposefully downloaded.

Once it’s on your system it will be near the top of your EngineList within Winery.

Can’t remember if the Engine ordering correctly handles the -* rebuilds but I usually remove them anyway.
