### ISSUE TITLE
Wineskin crashes on "Test Run"

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [Gcenx/WineskinServer#357]
- OS: Monterey 12.4
 - Winery version:
 - Master Wrapper version: latest as of 2/22/2023 (2.9.10 I think?)
 - Engine version: CXWine22.0.1
 - Hardware: 2010 Mac Pro
 - Application/Game Name Wineskin

**Describe the bug**
Clicking "Test Run" in wineskin sometimes causes the app to crash

**To Reproduce**
See above

**Expected behavior**
wineskin not to crash

**Crash Report**
<details>

------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Wineskin [5424]
Path:                  /Users/USER/*/SpaceEngineers.app/Wineskin.app/Contents/MacOS/Wineskin
Identifier:            com.unofficial.wineskin
Version:               2.9.1.6 (2.9.1.6)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-02-22 18:42:12.9781 -0800
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        83626718-9C6D-09B5-7960-F9863CCFEBE7

Sleep/Wake UUID:       CB54AF62-299A-462D-B4B5-06A197D16EF9

Time Awake Since Boot: 18000 seconds
Time Since Wake:       3667 seconds

System Integrity Protection: enabled

Crashed Thread:        4

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [5424]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff81bdac97a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff81bdacce8 mach_msg + 56
2   CoreFoundation                	    0x7ff81beaf540 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff81beadbd0 __CFRunLoopRun + 1276
4   CoreFoundation                	    0x7ff81bead014 CFRunLoopRunSpecific + 562
5   HIToolbox                     	    0x7ff824fca5e6 RunCurrentEventLoopInMode + 292
6   HIToolbox                     	    0x7ff824fca34a ReceiveNextEventCommon + 594
7   HIToolbox                     	    0x7ff824fca0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
8   AppKit                        	    0x7ff81e81dfad _DPSNextEvent + 927
9   AppKit                        	    0x7ff81e81c66a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
10  AppKit                        	    0x7ff81e80ed19 -[NSApplication run] + 586
11  AppKit                        	    0x7ff81e7e2c97 NSApplicationMain + 817
12  dyld                          	       0x103ed452e start + 462

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff81bdac97a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff81bdacce8 mach_msg + 56
2   CoreFoundation                	    0x7ff81beaf540 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff81beadbd0 __CFRunLoopRun + 1276
4   CoreFoundation                	    0x7ff81bead014 CFRunLoopRunSpecific + 562
5   AppKit                        	    0x7ff81e98b9ce _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff81bde94e1 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff81bde4f6b thread_start + 15

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff81bde4f48 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff81bde4f48 start_wqthread + 0

Thread 4 Crashed:
0   libdispatch.dylib             	    0x7ff81bc33dd7 _dispatch_assert_queue_fail + 99
1   libdispatch.dylib             	    0x7ff81bc33d74 dispatch_assert_queue + 144
2   HIToolbox                     	    0x7ff824fcc8d1 islGetInputSourceListWithAdditions + 119
3   HIToolbox                     	    0x7ff824fdfa9b _HaveOnlyOneKeyboardInputSource + 12
4   HIToolbox                     	    0x7ff824fdec5c MyActivateTSMDocument + 750
5   HIToolbox                     	    0x7ff824fe47e0 CallMyActivateTSMDocument + 82
6   CoreFoundation                	    0x7ff81bec8026 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
7   CoreFoundation                	    0x7ff81bec7b17 __CFRunLoopDoTimer + 923
8   CoreFoundation                	    0x7ff81bec767b __CFRunLoopDoTimers + 307
9   CoreFoundation                	    0x7ff81beadeb2 __CFRunLoopRun + 2014
10  CoreFoundation                	    0x7ff81bead014 CFRunLoopRunSpecific + 562
11  Foundation                    	    0x7ff81ccce50e -[NSConcreteTask waitUntilExit] + 332
12  Wineskin                      	       0x100b4bb1c -[WineskinAppDelegate systemCommand:withArgs:] + 55
13  Wineskin                      	       0x100b4f9eb -[WineskinAppDelegate runWineskinLauncherWithDisabledButtonsWithFlag:] + 199
14  Wineskin                      	       0x100b4d3cd -[WineskinAppDelegate runATestRun] + 58
15  Foundation                    	    0x7ff81cc3a994 __NSThread__start__ + 1009
16  libsystem_pthread.dylib       	    0x7ff81bde94e1 _pthread_start + 125
17  libsystem_pthread.dylib       	    0x7ff81bde4f6b thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff81bde4f48 start_wqthread + 0

Thread 4 crashed with X86 Thread State (64-bit):
  rax: 0xe408991c982200b3  rbx: 0x00006000028d0b00  rcx: 0x000000009961887f  rdx: 0x000000009981905b
  rdi: 0x000000000000007f  rsi: 0x00006000028d2d00  rbp: 0x00007000054e1b60  rsp: 0x00007000054e1b50
   r8: 0x0000000000002d00   r9: 0x0000000000000080  r10: 0x00000000000007fb  r11: 0x000000000000007f
  r12: 0x00007ff85dbe5e50  r13: 0x0000000000000000  r14: 0x00007fbf130d8ba0  r15: 0x0000000000000000
  rip: 0x00007ff81bc33dd7  rfl: 0x0000000000010206  cr2: 0x00007ff85d523528
  
Logical CPU:     2
Error Code:      0x00000000 
Trap Number:     6

Thread 4 instruction stream:
  e5 53 50 48 8d 5d f0 48-c7 03 00 00 00 00 48 8d  .SPH.].H......H.
  05 c2 85 03 00 48 8d 0d-1d 4b 03 00 85 f6 48 0f  .....H...K....H.
  45 c8 4c 8b 47 48 4d 85-c0 4c 0f 44 c0 48 8d 35  E.L.GHM..L.D.H.5
  a4 4a 03 00 48 8d 15 cd-4a 03 00 48 89 df 31 c0  .J..H...J..H..1.
  e8 26 1c 03 00 48 8b 1b-48 8d 3d ef 4a 03 00 48  .&...H..H.=.J..H
  89 de 31 c0 e8 ba ce 02-00 48 89 1d 51 f7 8e 41  ..1......H..Q..A
 [0f]0b 55 48 89 e5 48 8b-07 0f b6 40 28 48 8d 48  ..UH..H....@(H.H	<==
  ef 48 83 f9 02 73 70 48-8b 47 38 65 33 04 25 18  .H...spH.G8e3.%.
  00 00 00 83 f8 03 76 58-65 48 8b 0c 25 a0 00 00  ......vXeH..%...
  00 48 85 c9 0f 94 c2 74-41 48 39 f9 74 3c 65 48  .H.....tAH9.t<eH
  8b 04 25 a8 00 00 00 48-8b 51 18 48 85 c0 74 0f  ..%....H.Q.H..t.
  48 8b 30 48 85 d2 74 0b-48 39 f1 75 0d eb 07 31  H.0H..t.H9.u...1

Binary Images:
    0x7ff81bdab000 -     0x7ff81bde2fff libsystem_kernel.dylib (*) <8cc28466-fd2f-3c80-9834-9525b7beac19> /usr/lib/system/libsystem_kernel.dylib
    0x7ff81be30000 -     0x7ff81c330fff com.apple.CoreFoundation (6.9) <bddb824d-15df-3210-88e8-6aac5c154403> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff824f9c000 -     0x7ff82528ffff com.apple.HIToolbox (2.1.1) <06fdecd6-9f69-397b-b1e2-a8226c0ba7ed> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff81e7df000 -     0x7ff81f66efff com.apple.AppKit (6.9) <06015263-62ac-3b08-a298-dc835c18452a> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x103ecf000 -        0x103f3afff dyld (*) <71febccd-d9dc-3599-9971-2b3407c588a8> /usr/lib/dyld
    0x7ff81bde3000 -     0x7ff81bdeefff libsystem_pthread.dylib (*) <b5454e27-e8c7-3fdb-b77f-714f1e82e70b> /usr/lib/system/libsystem_pthread.dylib
    0x7ff81bc2f000 -     0x7ff81bc75fff libdispatch.dylib (*) <1a04b380-76e4-3e4b-b0fc-9837533d021d> /usr/lib/system/libdispatch.dylib
    0x7ff81cbe2000 -     0x7ff81cf9efff com.apple.Foundation (6.9) <e22e60bb-ab77-3120-862f-92fa74feffcf> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x100b48000 -        0x100b77fff com.unofficial.wineskin (2.9.1.6) <67e40bba-49fb-3282-9d7b-ec6ac5d69595> /Users/USER/*/SpaceEngineers.app/Wineskin.app/Contents/MacOS/Wineskin

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=683.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=683.8M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               768K        6 
Activity Tracing                   256K        1 
CG backing stores                 1680K        8 
CG image                           284K       40 
ColorSync                          220K       26 
CoreAnimation                     8060K      129 
CoreGraphics                        16K        3 
CoreImage                           44K        1 
CoreUI image data                 2488K       41 
Foundation                          52K        2 
Image IO                            12K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           276.9M       85 
MALLOC guard page                   48K       11 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                  192K        3 
STACK GUARD                       56.0M        6 
Stack                             10.5M        6 
VM_ALLOCATE                        132K       19 
__CTF                               756        1 
__DATA                            28.9M      499 
__DATA_CONST                      29.6M      323 
__DATA_DIRTY                      1587K      210 
__FONT_DATA                          4K        1 
__LINKEDIT                       645.6M        9 
__OBJC_RO                         82.8M        1 
__OBJC_RW                         3200K        2 
__TEXT                           496.2M      516 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
libnetwork                        1664K       24 
mapped file                      220.3M       46 
shared memory                      804K       22 
===========                     =======  ======= 
TOTAL                              2.2G     2046 
TOTAL, minus reserved VM space     1.8G     2046 

-----------
Full Report
-----------

{"app_name":"Wineskin","timestamp":"2023-02-22 18:42:24.00 -0800","app_version":"2.9.1.6","slice_uuid":"67e40bba-49fb-3282-9d7b-ec6ac5d69595","build_version":"2.9.1.6","platform":1,"bundleID":"com.unofficial.wineskin","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"C42A88D6-2FC5-46C0-A6F1-D310510B38D3","name":"Wineskin"}
{
  "uptime" : 18000,
  "procLaunch" : "2023-02-22 17:59:33.9284 -0800",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacPro5,1",
  "procStartAbsTime" : 15805155953448,
  "coalitionID" : 3821,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2023-02-22 18:42:12.9781 -0800",
  "incident" : "C42A88D6-2FC5-46C0-A6F1-D310510B38D3",
  "bug_type" : "309",
  "pid" : 5424,
  "procExitAbsTime" : 18364146580885,
  "cpuType" : "X86-64",
  "procName" : "Wineskin",
  "procPath" : "\/Users\/USER\/*\/SpaceEngineers.app\/Wineskin.app\/Contents\/MacOS\/Wineskin",
  "bundleInfo" : {"CFBundleShortVersionString":"2.9.1.6","CFBundleVersion":"2.9.1.6","CFBundleIdentifier":"com.unofficial.wineskin"},
  "storeInfo" : {"deviceIdentifierForVendor":"5DD97F3B-E1E0-5226-82E0-7820CDF3547F","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.unofficial.wineskin",
  "crashReporterKey" : "83626718-9C6D-09B5-7960-F9863CCFEBE7",
  "wakeTime" : 3667,
  "sleepWakeUUID" : "CB54AF62-299A-462D-B4B5-06A197D16EF9",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_INSTRUCTION","signal":"SIGILL"},
  "termination" : {"flags":0,"code":4,"namespace":"SIGNAL","indicator":"Illegal instruction: 4","byProc":"exc handler","byPid":5424},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 4,
  "threads" : [{"id":197055,"queue":"com.apple.main-thread","frames":[{"imageOffset":6522,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":7400,"symbol":"mach_msg","symbolLocation":56,"imageIndex":0},{"imageOffset":521536,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":515024,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":1},{"imageOffset":512020,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":1},{"imageOffset":189926,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":2},{"imageOffset":189258,"symbol":"ReceiveNextEventCommon","symbolLocation":594,"imageIndex":2},{"imageOffset":188645,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":70,"imageIndex":2},{"imageOffset":257965,"symbol":"_DPSNextEvent","symbolLocation":927,"imageIndex":3},{"imageOffset":251498,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1394,"imageIndex":3},{"imageOffset":195865,"symbol":"-[NSApplication run]","symbolLocation":586,"imageIndex":3},{"imageOffset":15511,"symbol":"NSApplicationMain","symbolLocation":817,"imageIndex":3},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":4}]},{"id":197109,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6522,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":7400,"symbol":"mach_msg","symbolLocation":56,"imageIndex":0},{"imageOffset":521536,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":515024,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":1},{"imageOffset":512020,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":1},{"imageOffset":1755598,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":3},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":280828,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":281109,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"triggered":true,"id":281378,"instructionState":{"instructionStream":{"bytes":[229,83,80,72,141,93,240,72,199,3,0,0,0,0,72,141,5,194,133,3,0,72,141,13,29,75,3,0,133,246,72,15,69,200,76,139,71,72,77,133,192,76,15,68,192,72,141,53,164,74,3,0,72,141,21,205,74,3,0,72,137,223,49,192,232,38,28,3,0,72,139,27,72,141,61,239,74,3,0,72,137,222,49,192,232,186,206,2,0,72,137,29,81,247,142,65,15,11,85,72,137,229,72,139,7,15,182,64,40,72,141,72,239,72,131,249,2,115,112,72,139,71,56,101,51,4,37,24,0,0,0,131,248,3,118,88,101,72,139,12,37,160,0,0,0,72,133,201,15,148,194,116,65,72,57,249,116,60,101,72,139,4,37,168,0,0,0,72,139,81,24,72,133,192,116,15,72,139,48,72,133,210,116,11,72,57,241,117,13,235,7,49],"offset":96}},"threadState":{"r13":{"value":0},"rax":{"value":16431551588551753907},"rflags":{"value":66054},"cpu":{"value":2},"r14":{"value":140458635135904},"rsi":{"value":105553159073024},"r8":{"value":11520},"cr2":{"value":140704694285608},"rdx":{"value":2575405147},"r10":{"value":2043},"r9":{"value":128},"r15":{"value":0},"rbx":{"value":105553159064320},"trap":{"value":6},"err":{"value":0},"r11":{"value":127},"rip":{"value":140703594397143,"matchesCrashFrame":1},"rbp":{"value":123145391315808},"rsp":{"value":123145391315792},"r12":{"value":140704701374032,"symbolLocation":0,"symbol":"gActiveDocID"},"rcx":{"value":2573305983},"flavor":"x86_THREAD_STATE","rdi":{"value":127}},"frames":[{"imageOffset":19927,"symbol":"_dispatch_assert_queue_fail","symbolLocation":99,"imageIndex":6},{"imageOffset":19828,"symbol":"dispatch_assert_queue","symbolLocation":144,"imageIndex":6},{"imageOffset":198865,"symbol":"islGetInputSourceListWithAdditions","symbolLocation":119,"imageIndex":2},{"imageOffset":277147,"symbol":"_HaveOnlyOneKeyboardInputSource","symbolLocation":12,"imageIndex":2},{"imageOffset":273500,"symbol":"MyActivateTSMDocument","symbolLocation":750,"imageIndex":2},{"imageOffset":296928,"symbol":"CallMyActivateTSMDocument","symbolLocation":82,"imageIndex":2},{"imageOffset":622630,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__","symbolLocation":20,"imageIndex":1},{"imageOffset":621335,"symbol":"__CFRunLoopDoTimer","symbolLocation":923,"imageIndex":1},{"imageOffset":620155,"symbol":"__CFRunLoopDoTimers","symbolLocation":307,"imageIndex":1},{"imageOffset":515762,"symbol":"__CFRunLoopRun","symbolLocation":2014,"imageIndex":1},{"imageOffset":512020,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":1},{"imageOffset":967950,"symbol":"-[NSConcreteTask waitUntilExit]","symbolLocation":332,"imageIndex":7},{"imageOffset":15132,"symbol":"-[WineskinAppDelegate systemCommand:withArgs:]","symbolLocation":55,"imageIndex":8},{"imageOffset":31211,"symbol":"-[WineskinAppDelegate runWineskinLauncherWithDisabledButtonsWithFlag:]","symbolLocation":199,"imageIndex":8},{"imageOffset":21453,"symbol":"-[WineskinAppDelegate runATestRun]","symbolLocation":58,"imageIndex":8},{"imageOffset":362900,"symbol":"__NSThread__start__","symbolLocation":1009,"imageIndex":7},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":281383,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703595933696,
    "size" : 229376,
    "uuid" : "8cc28466-fd2f-3c80-9834-9525b7beac19",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703596478464,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5246976,
    "uuid" : "bddb824d-15df-3210-88e8-6aac5c154403",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703748964352,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3096576,
    "uuid" : "06fdecd6-9f69-397b-b1e2-a8226c0ba7ed",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703640186880,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15269888,
    "uuid" : "06015263-62ac-3b08-a298-dc835c18452a",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4360826880,
    "size" : 442368,
    "uuid" : "71febccd-d9dc-3599-9971-2b3407c588a8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703596163072,
    "size" : 49152,
    "uuid" : "b5454e27-e8c7-3fdb-b77f-714f1e82e70b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703594377216,
    "size" : 290816,
    "uuid" : "1a04b380-76e4-3e4b-b0fc-9837533d021d",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703610839040,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 3919872,
    "uuid" : "e22e60bb-ab77-3120-862f-92fa74feffcf",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4306796544,
    "CFBundleShortVersionString" : "2.9.1.6",
    "CFBundleIdentifier" : "com.unofficial.wineskin",
    "size" : 196608,
    "uuid" : "67e40bba-49fb-3282-9d7b-ec6ac5d69595",
    "path" : "\/Users\/USER\/*\/SpaceEngineers.app\/Wineskin.app\/Contents\/MacOS\/Wineskin",
    "name" : "Wineskin",
    "CFBundleVersion" : "2.9.1.6"
  }
],
  "sharedCache" : {
  "base" : 140703592906752,
  "size" : 19331678208,
  "uuid" : "3765e290-e8ae-3af7-92bf-da62dfb8ac4f"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=683.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=683.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               768K        6 \nActivity Tracing                   256K        1 \nCG backing stores                 1680K        8 \nCG image                           284K       40 \nColorSync                          220K       26 \nCoreAnimation                     8060K      129 \nCoreGraphics                        16K        3 \nCoreImage                           44K        1 \nCoreUI image data                 2488K       41 \nFoundation                          52K        2 \nImage IO                            12K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           276.9M       85 \nMALLOC guard page                   48K       11 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  192K        3 \nSTACK GUARD                       56.0M        6 \nStack                             10.5M        6 \nVM_ALLOCATE                        132K       19 \n__CTF                               756        1 \n__DATA                            28.9M      499 \n__DATA_CONST                      29.6M      323 \n__DATA_DIRTY                      1587K      210 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       645.6M        9 \n__OBJC_RO                         82.8M        1 \n__OBJC_RW                         3200K        2 \n__TEXT                           496.2M      516 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                        1664K       24 \nmapped file                      220.3M       46 \nshared memory                      804K       22 \n===========                     =======  ======= \nTOTAL                              2.2G     2046 \nTOTAL, minus reserved VM space     1.8G     2046 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [

  ],
  "experiments" : [

  ]
}
}

Model: MacPro5,1, BootROM 9999.999.999.999.999, 6 processors, 6-Core Intel Xeon, 3.46 GHz, 24 GB, SMC 9.9999
Graphics: AMD Radeon RX 6800, AMD Radeon RX 6800, PCIe, 16 GB
Display: ASUS VG247Q1A, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Display: DELL3007WFPHC, 2560 x 1600, Main, MirrorOff, Online
Memory Module: DIMM 1, 8 GB, DDR3, 1333 MHz, 0x857F, 0x463732314752363546393333334700000000
Memory Module: DIMM 2, 8 GB, DDR3, 1333 MHz, 0x802C, 0x33364A535A4631473732505A2D3147344431
Memory Module: DIMM 3, 8 GB, DDR3, 1333 MHz, 0x802C, 0x33364A535A4631473732505A2D3147344431
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet 2, Ethernet, en1
Network Service: iPhone, Ethernet, en3
PCI Card: AMD Radeon RX 6800, gpu-controller, Slot-1@7,0,0
PCI Card: pci1002,ab28, Audio Device, Slot-1@7,0,1
PCI Card: pci1002,73a6, USB eXtensible Host Controller, Slot-1@7,0,2
PCI Card: pci1002,73a4, Unknown, Slot-1@7,0,3
Serial ATA Device: Samsung SSD 860 EVO 250GB, 250.06 GB
Serial ATA Device: WDC WD2002FAEX-007BA0, 2 TB
Serial ATA Device: WDC WD20EARS-00MVWB0, 2 TB
Serial ATA Device: WDC WD3200AAJS-41VWA0, 320.07 GB
USB Device: USB20Bus
USB Device: Ultra
USB Device: hub_device
USB Device: USB20Bus
USB Device: iPhone
USB Device: USBBus
USB Device: USBBus
USB Device: SteelSeries Sensei 310 eSports Mouse
USB Device: USBBus
USB Device: USBBus
USB Device: USBBus
USB Device: Bluetooth USB Host Controller
USB Device: USBBus
USB Device: SteelSeries Apex 7
FireWire Device: built-in_hub, 800mbit_speed
Thunderbolt Bus: 
</details>

**Comment by Gcenx** [comment]
Wineskin doesn’t always crash when using “Test Run”, this might be related to the spinner according to notes from Vitor, when Wineskin (the GUI) crashes this doesn’t affect WineskinLauncher.

I might simply disable the spinner and see if that really resolves the issue of the GUI crashing out.

**Comment by Gcenx** [comment]
The next wrapper update won't crash when using "Test Run" anymore, the downside is the buttons won't get locked but I believe that's a good enough compromise for the moment.

**Comment by The-Minecraft-Scientist** [comment]
Awesome! I’ll mark closed :)
