### ISSUE TITLE
"View Last Run Log File" in Wineskin should use Console instead of TextEdit

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [Gcenx/WineskinServer#358]
pretty self-explanatory. the Console app has a lot of nice tools that make working with log files a lot less painful than in textedit.

**Comment by Gcenx** [comment]
It's strange that `open` considers the default textedit

Current wrappers "View Last Run Logs" function
```
[self systemCommand:@"/usr/bin/open" withArgs:@[@"-e",[NSString stringWithFormat:@"%@/LastRunWine.log",logsFolder]]];
```

Next wrappers "View Last Run Logs" function
```
[self systemCommand:@"/usr/bin/open" withArgs:@[@"-a", @"Console",[NSString stringWithFormat:@"%@/LastRunWine.log",logsFolder]]];
```

**Comment by The-Minecraft-Scientist** [comment]
Awesome! not having to manually open Console every time I want to make sense of a crash will be really nice
