### ISSUE TITLE
Cannot launch EV Nova on macOS 13.3 (Beta).  Only error in LastRun log is that no driver could be loaded.

### ISSUE THREAD

**Issue by Geek671** [Gcenx/WineskinServer#359]
**Environment (please complete the following information):**
 - OS: macOS 13.3 Beta 2
 - Winery version: 1.8.4.2
 - Master Wrapper version: Wineskin 2.9.1.6
 - Engine version: WS11WineCX64Bit22.0.1-2
 - Hardware: MacBook Pro 16-inch, 2019 (Intel)
 - Application/Game Name: EV Nova 

**Describe the bug**

After installing macOS 13.3 Beta, I am unable to run EV Nova in WINE.  I get the following error at the end of the LastRun log, after all DLLs are successfully loaded:
`0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."`

I deleted all files associated with my wrapper from my system, and performed a clean install of the wrapper to check for Gatekeeper or sandboxing issues.  All of my launch scripts work, all of the files are placed where I want them, all of the symlinks are successfully initialized.  The only issue is that the driver can no longer be loaded.  I've refreshed wrappers and updated the engine as high as I can go.  It seems as though WINE isn't able to access needed system frameworks for the graphics/openGL driver.  I wonder if Apple locked something down, or if they changed the file structure of the frameworks themselves?  I noticed when peeking through the .so files in the 32-on64 Unix folder that the file paths to system frameworks follow the pattern:
`/System/Library/Frameworks/<name>.Framework/Versions/<A or C>/<name>/`
I looked at those locations, and for none of them is there a folder inside the A or C folder with the same name as the framework in macOS 13.3.  Could that be the cause?

**To Reproduce**

Attempt to launch a game that uses the Mac graphics driver and/or OpenGL while running any beta of macOS 13.3 (currently at 2).  Fails with error that no driver could be loaded when attempting to create a window.

**Expected behavior**

Game runs.  (worked fine up to macOS13.2.x)

**Screenshots**

N/A (no additional visual feedback occurs beyond errors in log)

**LastRunWine.log**

`002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\wineboot.exe" at 0000000140000000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00000001C8DB0000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 000000032A700000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\advapi32.dll" at 0000000330260000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ws2_32.dll" at 00000001EC2B0000: builtin
0034:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winemenubuilder.exe" at 0000000140000000: builtin
0034:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
0034:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
0034:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\services.exe" at 0000000140000000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00000001C8DB0000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 000000032A700000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\advapi32.dll" at 0000000330260000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0000000231AE0000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\version.dll" at 00000002F1FA0000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\setupapi.dll" at 000000021A7E0000: builtin
003c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\userenv.dll" at 0000000388E20000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winedevice.exe" at 0000000140000000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00000001C8DB0000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 000000032A700000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\advapi32.dll" at 0000000330260000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ntoskrnl.exe" at 00000002279A0000: builtin
0048:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0000000231AE0000: builtin
0054:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\drivers\\mountmgr.sys" at 00000001FBAC0000: builtin
0054:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\version.dll" at 00000002F1FA0000: builtin
0054:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\setupapi.dll" at 000000021A7E0000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winedevice.exe" at 0000000140000000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00000001C8DB0000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 000000032A700000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\advapi32.dll" at 0000000330260000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ntoskrnl.exe" at 00000002279A0000: builtin
0068:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0000000231AE0000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\drivers\\hidparse.sys" at 00000002ADF30000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\drivers\\winebus.sys" at 00000001C9230000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\version.dll" at 00000002F1FA0000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\setupapi.dll" at 000000021A7E0000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\win32u.dll" at 000000006AC60000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\drivers\\hidclass.sys" at 000000031DF10000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\drivers\\winehid.sys" at 00000003BA2A0000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\gdi32.dll" at 000000026B4C0000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\user32.dll" at 000000023D820000: builtin
0070:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\imm32.dll" at 00000003AFD00000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\plugplay.exe" at 0000000140000000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00000001C8DB0000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 000000032A700000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\advapi32.dll" at 0000000330260000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0000000231AE0000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\win32u.dll" at 000000006AB60000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\gdi32.dll" at 000000026B4C0000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\version.dll" at 00000002F1FA0000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\user32.dll" at 000000023D820000: builtin
008c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\imm32.dll" at 00000003AFD00000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\svchost.exe" at 0000000140000000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00000001C8DB0000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 000000032A700000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\advapi32.dll" at 0000000330260000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\wevtsvc.dll" at 00000002EBA70000: builtin
00a4:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0000000231AE0000: builtin
0054:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\drivers\\nsiproxy.sys" at 0000000229880000: builtin
0054:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\dnsapi.dll" at 000000029CFC0000: builtin
0054:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\nsi.dll" at 000000028DFA0000: builtin
0054:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\iphlpapi.dll" at 0000000240030000: builtin
0054:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\drivers\\ndis.sys" at 00000001DC4B0000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\version.dll" at 00000002F1FA0000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\win32u.dll" at 000000006BD60000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\user32.dll" at 000000023D820000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\gdi32.dll" at 000000026B4C0000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0000000231AE0000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\combase.dll" at 0000000327020000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ole32.dll" at 00000002E8F10000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\shcore.dll" at 00000003126F0000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\shlwapi.dll" at 00000002E3540000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\shell32.dll" at 00000001C69E0000: builtin
002c:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\imm32.dll" at 00000003AFD00000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\users\\Wineskin\\Documents\\Program Files\\EV Nova\\EV Nova.exe" at 0000000000400000: native
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\wow64.dll" at 000000006F000000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\wow64cpu.dll" at 000000006F100000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\users\\Wineskin\\Documents\\Program Files\\EV Nova\\EV Nova.exe" at 00400000: native
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 7B000000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 7B600000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00AF0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00B90000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 6BC00000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ADVAPI32.dll" at 61740000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\version.dll" at 63480000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\win32u.dll" at 6B670000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\user32.dll" at 6ED00000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\gdi32.dll" at 6C9C0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\imm32.dll" at 00C60000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\COMCTL32.dll" at 6CC40000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 62FC0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\combase.dll" at 016C0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ole32.dll" at 015A0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\shcore.dll" at 63BC0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\shlwapi.dll" at 64A40000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\SHELL32.dll" at 00C80000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msacm32.dll" at 017F0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\WINMM.dll" at 01720000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\dnsapi.dll" at 6E4C0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\nsi.dll" at 6F480000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\iphlpapi.dll" at 61500000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ws2_32.dll" at 6D780000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\WSOCK32.dll" at 00020000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winspool.drv" at 663C0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\comdlg32.dll" at 01810000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\users\\Wineskin\\Documents\\Program Files\\EV Nova\\iconv.dll" at 10000000: native
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\explorer.exe" at 0000000140000000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00000001C8DB0000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 000000032A700000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\advapi32.dll" at 0000000330260000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\version.dll" at 00000002F1FA0000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\win32u.dll" at 000000006B460000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\user32.dll" at 000000023D820000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\gdi32.dll" at 000000026B4C0000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0000000231AE0000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\imm32.dll" at 00000003AFD00000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winemac.drv" at 000000006B6A0000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\uxtheme.dll" at 00000002F7230000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\combase.dll" at 0000000327020000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ole32.dll" at 00000002E8F10000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\shcore.dll" at 00000003126F0000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\shlwapi.dll" at 00000002E3540000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\shell32.dll" at 00000001C69E0000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\oleaut32.dll" at 00000002739C0000: builtin
00bc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\actxprxy.dll" at 00000001D0830000: builtin
00d0:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcss.exe" at 0000000140000000: builtin
00d0:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernelbase.dll" at 000000007B000000: builtin
00d0:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\kernel32.dll" at 000000007B600000: builtin
00d0:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 00000001C8DB0000: builtin
00d0:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 00000003AF670000: builtin
00d0:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\sechost.dll" at 000000032A700000: builtin
00d0:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\advapi32.dll" at 0000000330260000: builtin
00d0:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0000000231AE0000: builtin
0024:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\uxtheme.dll" at 021C0000: builtin
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
`

**Additional context**

Incorrectly filled out issues will be close without notice!

**Comment by Gcenx** [comment]
That doesn’t sound too promising as `WS11WineCX64Bit22.0.1-2` was build with the latest version of Xcode so if Apple have changed the layout of there frameworks from macOS 13.3 that will affect any legacy applications/games that made use of these.

As I’m stuck using the m1 mini as my daily driver I can’t afford to upgrade to beta releases, let’s hope Apple provides fallbacks before the release.

**Comment by Geek671** [comment]
Thanks for responding.  Could it be possible to detect operating system version and use alternate paths?

**Comment by Gcenx** [comment]
I’ve checked with other devs and they’ve said there having no issues on the very latest end macOS beta on an Apple silicon system.

**Comment by Geek671** [comment]
How strange. Maybe it’s an Intel thing.

**Comment by Geek671** [comment]
Stranger yet...  I discovered an older version of my app does launch fine on 13.3.  So I tried to copy the wrapper into my new app and the copy always breaks.  I can't figure out what's different.

**Comment by Geek671** [comment]
Just installed the freshest beta...  No idea exactly what broke, but it seems Apple has fixed it.  Sorry to bother.

**Comment by Gcenx** [comment]
I guess whatever was broken on your end gotten resolved when the newer built was installed as I’d gotten multiple reports via discord of Wineskin working without issue on the each Beta build.
