### ISSUE TITLE
Catalina 10.15.4 - Installing Software Error- There is no windows program 

### ISSUE THREAD

**Issue by smaira** [Gcenx/WineskinServer#36]
OSX Catalina 10.15.4 

Can't install any software. Tried different installers for different softwares but all of them give the same error. 
![image](https://user-images.githubusercontent.com/1536558/82505955-85fa4a00-9acc-11ea-8755-0f5352ac8cfb.png)

I've set no32exec=0 to the boot arguments by booting into recovery mode and then using the command "nvram boot-args="no32exec=0" - following this article https://apple.stackexchange.com/questions/363574/how-much-of-32-bit-support-is-dropped-in-macos-catalina

I know that the current installer supports 64 bit but I also tried with different wrappers 32 bit and 64 bit. These are the engines I tried with.  

![image](https://user-images.githubusercontent.com/1536558/82506132-fd2fde00-9acc-11ea-97de-ce490c5d8c1a.png)

**Here is the output from ole 32**

```
warning: taskset/cpuset not available on your platform!
Executing mkdir -p /Users/sameermaira/Applications/Wineskin/Sh Jyoti Star.app/Contents
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 841d036144ecae5e0cbba3594fa19fad90cd1e8ecdb88b13370740cf149bad8d with wine-4.12.1 and WINEARCH=win64
Executing w_do_call ole32
Executing mkdir -p /Users/sameermaira/Applications/Wineskin/Sh Jyoti Star.app/Contents
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_ole32 
Executing cabextract -q -d /Users/sameermaira/Applications/Wineskin/Sh Jyoti Star.app/Contents/Resources/dosdevices/c:/windows/temp -L -F i386/ole32.dl_ /Users/sameermaira/.cache/winetricks/winxpsp3/WindowsXP-KB936929-SP3-x86-ENU.exe
Executing cabextract -q --directory=/Users/sameermaira/Applications/Wineskin/Sh Jyoti Star.app/Contents/Resources/dosdevices/c:/windows/syswow64 /Users/sameermaira/Applications/Wineskin/Sh Jyoti Star.app/Contents/Resources/dosdevices/c:/windows/temp/i386/ole32.dl_
Using native,builtin override for following DLLs: ole32
Executing wine32on64 regedit /S C:\windows\Temp\override-dll.reg
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg

 Winetricks Commands Finished!!
```

**Here is the log from inside the wrapper**
```
000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x8403
001d:err:plugplay:process_IOService_Device object 0x8307
001d:err:plugplay:process_IOService_Device object 0x8207
001d:err:plugplay:process_IOService_Device object 0x7f07
001d:err:plugplay:process_IOService_Device object 0xaa07
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0xaa0b
001d:err:plugplay:process_IOService_Device object 0xac0b
001d:err:plugplay:process_IOService_Device object 0xae07
001d:err:plugplay:process_IOService_Device object 0x15003
001d:err:plugplay:process_IOService_Device object 0xb003
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0025:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Success.

```

The one thing that I noticed was that if I goto Advanced and then select the Installer as the EXE file to run , then hit TEST RUN it brings up the installer. I actually installed something using this method but its not working on the other installer.

Any help will be appreciated.

Thanks
Sameer

**Comment by Gcenx** [comment]
You say at the start nothing installs but at the end you say you did manage to install something?

Some windows installs have additional requirements that wine doesn’t by default provide like jet/.Net or even some obscure dependencies.

As you haven’t provided the applications name nor provided a link for a trail there’s little myself or anyone else could attempt to assist with.

**Comment by smaira** [comment]
Sorry for the confusion. I'll try explaining again.

I am able to create the wrapper successfully. But when I double click the wrapper > Choose Install Software > Choose Setup Executable > it fails with the error shown above. 

So as a workaround I went into Advanced > Selected the Setup file in the Windows EXE field and then clicked "Test Run". This worked somehow and the software installed. Then I changed the EXE again to point to the exe under Program Files so that double clicking the wrapper launches the installed program. 

But this is not working for the other software I'm trying to install. I don't have the installer for the 2nd one but the first one can be downloaded here - https://www.vedicastrologer.org/jh/jh_full_install.zip - it's 32 bit. 

-Sameer

**Comment by mbunal** [comment]
i have this too. i just install your unofficial wineskin winery. i create empty wrapper named Eye4. after double clicking, click 'install software' -> 'choose setup executable'. i choose setup executable. and then that message: There is no windows program...

is there any solution?

**Comment by btocastillon** [comment]
I get the same error. There is not app in windows that will make this work. I am trying to install metatrader 5 or Steam, I get the same error for both

**Comment by Gcenx** [comment]
@smaira not had chance to reboot into Catalina to test this due to recent upstream wine bugs.
You might want to instead test using the pre-release wrapper/WineCX19.0.1-1 engines/Winery as those have been confirmed to be much more stable.

I don't use Virtualbox as I've always found it lacking especially on macOS, Parallels Desktop and VMWare Fusion work much better but or course are paid products.

@mbunal I searched and Eye4 shows as an Android and iOS application, there is a 64Bit version of BlueStacks for macOS so no clue where you're attempting to use Wine for this.

@btocastillon I don't know what your doing wrong as I run Steam on macOS Catalina using WineCX19.0.1 and PortingKit is using WineCX19.0.1 heavily for most Ports now.

**Comment by mbunal** [comment]
@Gcenx u are wrong. there is a windows application too:
[http://download2.eye4.cn/download2/application/app-Eye4-VStarcam.zip](http://download2.eye4.cn/download2/application/app-Eye4-VStarcam.zip)

**Comment by Gcenx** [comment]
@mbunal 
<img width="324" alt="Screen Shot 2020-05-24 at 10 30 57 PM" src="https://user-images.githubusercontent.com/38226388/82773178-6b4b0c80-9e0f-11ea-8530-aeda5e644e80.png">
<img width="781" alt="Screen Shot 2020-05-24 at 10 37 15 PM" src="https://user-images.githubusercontent.com/38226388/82773179-6be3a300-9e0f-11ea-8032-6c058c2e229a.png">

As I'd pointed out before use BlueStacks and the Android client

**Comment by mbunal** [comment]
@Gcenx i was able to run eye4 with official wineskin winery. anyway thanks for your replies.

**Comment by Gcenx** [comment]
@mbunal official Wineskin doesn’t have any engines for macOS Catalina

**Comment by smaira** [comment]
I rolled back to Mojave. Life is good again!

**Comment by mbunal** [comment]
@Gcenx i was able to run eye4 with official wineskin winery befora Catalina. anyway thanks for your replies.

**Comment by Jrogan23** [comment]
> Sorry for the confusion. I'll try explaining again.
> 
> I am able to create the wrapper successfully. But when I double click the wrapper > Choose Install Software > Choose Setup Executable > it fails with the error shown above.
> 
> So as a workaround I went into Advanced > Selected the Setup file in the Windows EXE field and then clicked "Test Run". This worked somehow and the software installed. Then I changed the EXE again to point to the exe under Program Files so that double clicking the wrapper launches the installed program.
> 
> But this is not working for the other software I'm trying to install. I don't have the installer for the 2nd one but the first one can be downloaded here - https://www.vedicastrologer.org/jh/jh_full_install.zip - it's 32 bit.
> 
> I can tell you for sure that both programs worked on Mojave via WineHQ, WineBottler & PlayOnMac. I didn't try WineSkinServer but I'm sure they would've worked with this too. There is something very frustrating about Catalina! I tried running them through VirtualBox but VB keeps crashing on Catalina too. Kernel fatigue or something. But I digress :)
> 
> I'm happy to share more logs but will need help finding them.
> 
> -Sameer

Hi Sameer,

Can you please clarify how you did the workaround--I think a similar process is described in the post by Jacob Korba here:
https://stackoverflow.com/questions/58891420/installing-wine-on-mac-os-catalina-error-no-available-formula-with-the-name-w

_**"Note: If you get the "No windows app to open the file"(Like I did) error, click advanced -> configuration and set the Windows EXE to the path to the installer. Then find the place that it has installed in and set that as Windows EXE. Then you can run by clicking Test Run."**_

But I do not quite understand how to do what you or the person above is describing. I am trying to create a wrapper for an OpenBUGS executable which is in my donwloads folders. Any clarification on this would be appreciated!

**Comment by Jrogan23** [comment]
Ok actually seemingly I figured this out, but then when I close the OpenBUGS program I get the message 

"No new executables found!

Maybe the installer failed...?

If you tried to install somewhere other than C: drive (drive_c in the wrapper) then you will get this message too.  All software must be installed in C: drive."
