### ISSUE TITLE
Support for WineCX 22.1?

### ISSUE THREAD

**Issue by sofakng** [Gcenx/WineskinServer#362]
Will you be adding support (ie. new engine) for WineCX 22.1?

Thanks!

**Comment by Gcenx** [comment]
It’s being worked on, thought the most imported improvement (Steam fix) was already back-ported into WS11WineCX64Bit22.0.1-2

I might provide a pre-release version soon as it includes a lot of interesting patchsets compared to CrossOver-22.1.0

**Comment by sofakng** [comment]
Sounds good.  I'll keep an eye out for it.  Thanks much!

**Comment by Gcenx** [comment]
@sofakng @Igor-Ruk @nevack check https://github.com/Gcenx/WineskinServer/issues/363
