### ISSUE TITLE
Added Engine - WS11WineCX64Bit22.1.0-rc2 (macOS Catalina and later only)

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#363]
This release candidate has a number of patchsets applied that are not a part of CrossOver-22.1.0;

<br>

### WS11WineCX64Bit22.1.0-rc1
- winecfg: Fix CurrentVersion registry string for Windows 10 and up. (upstream)
- ntdll: Default to Windows 10 (upstream)
- ntdll: Add Windows 11 version (upstream)
- mshtml: Wine Gecko 2.47.3 release (upstream)
- mscoree: Update Wine Mono to 7.4.0 (upstream)
- vkd3d: Import upstream release 1.5 (upstream)
- vkd3d: Import crossover-sources-22.1.0/vkd3d changes
-  loader: Fixes for preloader on macOS Ventura (upstream)
- openal32: Remove dll. (upstream)
- libs: Import code from upstream openldap 2.5.13. (upstream)
- ntdll: Don't use Wine frames during exception processing on x64 (staging)
- Disabled multiple unless warnings (HACK)
- additional fixes/hacks (e.g. Fallout4 dsound hack)
- Reverted _many_ unless CrossOver hacks

<br>

### WS11WineCX64Bit22.1.0-rc2
- Builtin steamwebhelper overrides
- Disabled additional stderr spam
- Reworked CrossOver kernelbase hacks

<br>

### winetricks changes (for WineCX22.1.0)
~~Currently in the process of rebuilding DXVK-macOS packages to take advantage of WineCX22.1.0 32Bit Vulkan support (macOS Catalina and later)~~

~~The winetricks changes will take sometime.~~

The DXVK verbs now install 32Bit dlls when using WineCX22.x and running macOS Catalina or later. This _might_ inadvertently break WineCX22.0.1-2 but that won’t be support once WineCX22.1.0 officially lands.

**Comment by nevack** [comment]
Created New Blank Wrapper.
Engine: WS11WineCX64Bit22.1.0-rc1
Wrapper version: 2.9.1.7
OS Version: 13.3 (b) Beta (22E7752300g)

Tried to install Steam via winetricks - install ok.
Steam bootstraps itself ok, show login screen.
After providing cred app steam crashes, consequent launches also fail after "retrieving account details ..." dialog.

Log 
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/10938121/LastRunWine.log)

**Comment by Gcenx** [comment]
Going off your log it's not finding installed files where as you can see with mine it finds them with no issue
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/10938165/LastRunWine.log)

I didn't even use the `steam` verb for but the actual installer.

Created New Blank Wrapper.
Engine: WS11WineCX64Bit22.1.0-rc1
Wrapper version: 2.9.1.7
OS Version: macOS 13.2 22D49 x86_64

**Comment by nevack** [comment]
> I didn't even use the `steam` verb for but the actual installer.

You are right, installing with official exe from store.steampowered.com fixed the issue.
I thought installing via winetricks verb is better as this method also installs some dependencies like fonts and other libs.

**Comment by Gcenx** [comment]
The verb also runs the official installer plus corefonts, it’s more lightly the issues where caused by some stuck wine processes.

**Comment by Gcenx** [comment]
I’m going to assume no feedback means that WineCX22.1.0-rc2 was good.

While I will provide an engine _named_ WineCX22.1.1 it’s internally WineCX22.1.0 with some additional patches since I’ve already back-ported the macOS Ventura 13.3 fix before CodeWeavers did.
