### ISSUE TITLE
wont let me install engines

### ISSUE THREAD

**Issue by poopdadoo** [Gcenx/WineskinServer#365]
im on a 2013 macbook pro and whenever i try to install an engine it gives me an error(that i cant seee because it goes away very fast)and goes back to the home page. i am on macos big sur.

**Comment by Gcenx** [comment]
You’ve skipped the issue template, knowing the Winery version you’ve installed would lightly help to explain _why_ you’re having issues downloading Engines.

I have a feeling you’ve completely ignored the readme and attempted to install manually.

**Comment by Gcenx** [comment]
If your sure that’s brew installed copy of Winery is the _only_ one then ether your system certs or outdated or something is blocking Winery from con texting to GitHub.

**Comment by Gcenx** [comment]
> Incorrectly filled out issues will be close without notice!
