### ISSUE TITLE
Steam won't work with DXVK (and MF) enabled

### ISSUE THREAD

**Issue by kubyon** [Gcenx/WineskinServer#366]
**Environment (please complete the following information):**
 - OS: Ventura 13.2
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.1.7
 - Engine version: WineCX 22.0.1-2
 - Hardware: Macbook Air 2020
 - Application/Game Name: Steam

**Describe the bug**
Upon installation of DXVK or MF (via winetricks) and activation (via winecfg), Steam displays a black screen (or the Wine Debugger window constantly flickers)

**To Reproduce**
Install latest DXVK verb (1103), MF, install and setup Steam (with -allosarches -cef-force-32bit as of writing). Enable DXVK by setting the dlls to native and launch Steam. 

**Expected behavior**
Steam won't display properly or stuck in a debug loop with MF, making the app unusable.

**Screenshots**

<img width="1012" alt="Untitled" src="https://user-images.githubusercontent.com/123789356/225166111-84f65516-1747-4444-bc23-136d67f8be7b.png">

**LastRunWine.log**
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/10974743/LastRunWine.log) (DXVK)

[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/10996483/LastRunWine.log) (MF)
**Additional context**

I was using Steam normally until the past few days, DXVK installed, launch args properly applied and all. However, since last night, Steam displays a black screen whenever I launch it, and only by deactivating DXVK can I hope to launch Steam normally (with 2 wine64-preloader) executables. I am not sure if this is a bug of not, as recent DXVK verbs seem to have the new inclusion of d3dcompiler, which may or may not be the cause.

**Comment by Gcenx** [comment]
As of Wineskin-2.9.1.7 there’s no need to add any launch arguments for Steam when using WineCX22.0.1-2 or WineCX22.1.0-rc1 as the way Steam gets launched was changed internally so the builtin hacks should automatically get applied.

I’d verified this with WineCX22.0.1-2 and WineCX22.1.0-rc2 and Steam worked without issue even when installed without using the Steam verb.

> I am not sure if this is a bug of not, as recent DXVK verbs seem to have the new inclusion of d3dcompiler, which may or may not be the cause.

This wouldn’t be related though I will be reverting the inclusion of d3dcompiler in a later winetricks rebase, currently working on rebuilding _all_ DXVK-macOS versions for WineCX22.1.0 since this introduces 32Bit DX10/11 support on macOS Catalina and later.

**Comment by Gcenx** [comment]
> Enable DXVK by setting the dlls to native and launch Steam.

The DXVK verbs already handle setting the correct overrides, forcing to “native” might actually cause issues.

**Comment by kubyon** [comment]
> The DXVK verbs already handle setting the correct overrides, forcing to “native” might actually cause issues.
I assume then native builtin would work the same way as native? Either way, Steam seems to be functioning normally now.
However, I have encountered another issue, with another winetricks verb. Would it be more convenient to post it here or in a separate new thread?

**Comment by Gcenx** [comment]
> I assume then native builtin would work the same way as native?

`native,builtin` means wine will use a native dll if found else fallback to a wine dll.

In the case of DXVK-macOS we’re _only_ installing 64Bit dlls and needing to fallback to the builtin wine dlls for 32Bit.

> However, I have encountered another issue, with another winetricks verb. Would it be more convenient to post it here or in a separate new thread?

Might as well post here as the copy of winetricks used in Wineskin has some custom verbs not found in upstream.

**Comment by kubyon** [comment]
That explains dll override preferences neatly enough, thanks. I'll leave the issue at that.

Regarding the peculiar winetricks verb, it's the mf (Windows Media Function) dll set, which I'm trying to install with Steam to experiment launching Resident Evil games. First few tests worked well, until yesterday when it broke alongside DXVK. Launching Steam with mf enabled (22.0.1-2 and 22.1.0-rc1) now leads wine to a debug loop, where the Wine Debugger window would constantly open and close, Steam would not load up at all  and  my other applications being screwed up hard (even getting to Mac's Force Quit menu was a challenge). I was wondering if this is due to a backend change of Wineskin or any chance. 
This issue is not really related to the one in OP, so if you feel it would be better to split, I'm glad to comply.

**Comment by Gcenx** [comment]
I’ve not really used `mf` before but was told it was working from the person who submitting it.

I’ll need to check if I own any game(s) that require this using this verb.

**Comment by kubyon** [comment]
This is an issue I have with Steam itself, as said - disabling mf-related dlls makes Steam work fine again. I don't know if there are any other games that require mf to run, but it would be good to know its general compatibility in other software.

**Comment by kubyon** [comment]
After further testing, it seems this is caused by mf not actually being implemented, causing wine to start a debug loop (which is somewhat confusing, given that the bug was fixed in upstream wine at some point)
Here is the log for reference (cmd+f -> mf)
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/10992343/LastRunWine.log)

**Comment by kubyon** [comment]
So essentially, this is a backend issue that could be unresolvable because of copyright and dependencies compilation problems? Those are fair points if the verb ended up being unsupported.
Also, since yesterday I have trouble understanding this quote:

>  Though once the mf verb gets installed it shouldn’t be touching the “wine” version but using the native copy.
Does this mean important mf dlls are already enable on a fresh wrapper?

**Comment by Gcenx** [comment]
Using Wineskin-2.9.1.8 with WineCX22.1.0-rc1, create a new blank wrapper and instal `dxvk_master` & `steam` verbs and manually select `steam.exe`

Now Steam should be working correctly, not tested with `mf` installed yet as I’m now away for until late Sunday.

**Comment by kubyon** [comment]
Got around to trying the newest DXVK verb with a fresh wrapper today. Steam now works great!
For some reason, mf (on that same new wrapper) now function normally as well (via RE7 demo) when all relevant dlls are forced native, which was not the case previously (though the log file still says mf dlls were not found). I suppose this mean the issue is resolved, so thanks for all the help! (It would be nice to know the cause of mf not working properly, however)
