### ISSUE TITLE
WineskinWinery app won't recognize any engine I instal

### ISSUE THREAD

**Issue by JeepCATgirl** [Gcenx/WineskinServer#382]
macOS version 13.2.1
 - Winery version: 1.8.4
 - Master Wrapper version: 2.9.0.5
 - Engine version: any
 - Hardware: MacBook Pro 15 2017
 - Application/Game Name: Spore

**Describe the bug**
The WineskinWinery app won't recognize any engine I instal

1. Open WineskinWinery app
2. Try to select an engine
3. See error

**Expected behavior**
Engine list to have something on it if I have the right engine installed

**Comment by Gcenx** [comment]
> Winery version: 1.8.4

That’s not the current version of “Wineskin Winery” _where_ did you even get that version as it’s archive was removed. This version also can’t obtain Engines directly.

> Master Wrapper version: 2.9.0.5

That wrapper is ancient.

> Engine version: any

This isn’t helpful.

<br>

As per the issue template

> Before posting your issue, please check the README.md & Wiki for informations:
    https://github.com/Gcenx/WineskinServer/blob/master/README.md
    https://github.com/Gcenx/WineskinServer/wiki
