### ISSUE TITLE
Request for Sierra 10.12.6 Support

### ISSUE THREAD

**Issue by MBP2011User** [Gcenx/WineskinServer#389]
Hi,

I can't use High Sierra on my computer, still using Sierra. 

I can't use the old wineskin because server doesn't exist.

This wineskin isn't compatible with Sierra.

Can you help?

Thanks

**Comment by Gcenx** [comment]
> I can't use High Sierra on my computer, still using Sierra.

https://dosdude1.com/highsierra/

> I can't use the old wineskin because server doesn't exist.

I’m sure there’s some users who have backups of the old project.

> This wineskin isn't compatible with Sierra.

This project has required macOS High Sierra or later for quite sometime now.

> Can you help?

Outside of someone donating hardware that’s capable of running OS X 10.8 and later no, it’s already a huge maintenance burden building for macOS High Sierra and later.

<br>

I know others have asked me about setting up GitHub sponsorship/patreon but doubt I’d even make enough to allow me cut back on my day job to work on “wine” related projects more.
