### ISSUE TITLE
No new executables found error message

### ISSUE THREAD

**Issue by Jrogan23** [Gcenx/WineskinServer#39]
Hi, I have followed instructions to install a windows program (in my case, OpenBUGS) using wineskin winery for Catalina 10.15.4. 

I first ran into the issue of "there is no windows program configured to open this type of file" but I managed to work around that by going to Advanced > then set the path to the OpenBUGS executable I had on my desktop in the Windows EXE field and then clicked "Test Run". This installed the software, but then I read in someone elses instructions that I needed to then change the EXE again to new location/path of the OpenBUGS executable that now shows up in the installed program files (x84) in the virtual c drive (right click your new wrapper > show package contents >drive_c>program files (x86) and find your program file and executable in there). After this, OpenBugs actually opened! However, when I closed it, I got this message:

"No new executables found!

Maybe the installer failed...?

If you tried to install somewhere other than C: drive (drive_c in the wrapper) then you will get this message too.  All software must be installed in C: drive."

I am wondering how I can fix this so that the program is actually registered as installed, and I can click on the OpenBUGS wrapper to launch it. Thank you!

**Comment by Gcenx** [comment]
- OpenBUGS323Setup.exe
- Wineskin-2.9.0.7 (current development build)
- WS11WineCX19.0.1-1
<img width="592" alt="Screen Shot 2020-05-31 at 12 25 24 PM" src="https://user-images.githubusercontent.com/38226388/83357353-d88ffd80-a339-11ea-8ec9-0d11111c8146.png">
I selected `OpenBUGS.exe` the resulting wrapper launched the executable correctly

**Comment by Jrogan23** [comment]
I'm not sure how you arrived there, as my error message did not look like that--but miraculously I just went to test the OpenBUGS wrapper again just to see test it again, and now it opens OpenBUGS when I double-click it! I really don't know what changed since the last time I tried and it didn't work--only  thing I can say is I think I restarted my computer once. Thanks for the help!
