### ISSUE TITLE
On osx 10.13.6 with multi monitor config open initial window at random position

### ISSUE THREAD

**Issue by nms42** [Gcenx/WineskinServer#40]
Well,
subject says all.

P.S. Opens at random position of the active monitor screen.

**Comment by Gcenx** [comment]
Subject doesn't say it all in this case, I can take a guess your saying `Wineskin` configuration application and `Wineskin Winery` open at a random location.

Is this assumption correct?

**Comment by nms42** [comment]
Ok, my report rather vague. (-;

(1) Wineskin application window always open in upper left corner of master monitor. Even when active/current monitor is not the master one.

(2) Wineskin Winery window opens at active monitor always. It opens in the middle of the screen or in the right edge at random. When in the middle, then secondary windows (add engine, ...) opens near the middle too. When in the right edge, then secondary windows goes to the screen of the monitor on the right.

**Comment by Gcenx** [comment]
I’ve made changes to Wineskin-2.9.0. that should cover this already for 10.11 and above systems.

The newer winery always seems to open in the center of my active monitor, I’m not sure what your explaining?

I’m using the XCode own centering setting for I believe all windows

**Comment by nms42** [comment]
Winery opens on the right edge of active monitor only sometimes. That is the very low priority annoyance. Can be ignored.
