### ISSUE TITLE
Steam login works, fails to load main interface

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [Gcenx/WineskinServer#406]
**Environment:**
 - OS: macOS 11.5.2
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.1.9
 - Engine version: WS11WineCX64Bit22.1.1-rc3
 - Hardware: MacBook Pro (13-inch, M1, 2020)
 - Steam

**Describe the bug**
The Steam login screen appears, I enter my user and pass, then the "Connecting Account USERNAME" loading window shows, as well as the "Updating User Configuration", then suddenly it just exits. No error messages, nothing. Doesnt get to the main interface at all.

**LastRunWine.log**
https://gist.github.com/matthewjumpsoffbuildings/1ce13cbd407bed076dafb60d53f48656

**Comment by Gcenx** [comment]
![Screenshot 2023-06-01 at 8 59 01 PM](https://github.com/Gcenx/WineskinServer/assets/38226388/6d1bdb17-f78e-4b96-93f7-a0ce294ad38b)

Steam is working for me on macOS Ventura 13.3.1(a), not updated to 13.4 yet same Engine

**Comment by matthewjumpsoffbuildings** [comment]
Do you think it's due to me being on an older macOS?

**Comment by matthewjumpsoffbuildings** [comment]
FWIW Steam launches fine using CrossOver trial

**Comment by Gcenx** [comment]
From what I’m seeing in the provided log it seems that it did login successfully and the main UI loaded as it’s complaining about not being able to play videos.

I don’t believe your macOS version matter heres are the deployment target is set at 10.13 as that’s the minimum I can set in Xcode14.x

So the remaining question would be _how_ did you install Steam?

**Comment by matthewjumpsoffbuildings** [comment]
I downloaded SteamSetup.exe from Steams website, and then used the 'Install Software' button on my new Blank Wrapper's Wineskin config dialogue

**Comment by Gcenx** [comment]
<img width="772" alt="Screen Shot 2023-06-03 at 4 15 48 PM" src="https://github.com/Gcenx/WineskinServer/assets/38226388/926da01b-8d2d-4405-bb8a-e9f8e7e13a64">

Also I have Steam working on macOS Mojave.

I did install using winetricks menu and then manually selected Steam.exe without any launch arguments and Steam worked just fine.

**Comment by matthewjumpsoffbuildings** [comment]
Yea I also manually selected steam.exe and dont have any launch arguments

**Comment by matthewjumpsoffbuildings** [comment]
Well, I just noticed this commit https://github.com/Gcenx/WineskinServer/commit/5a8aca43058008b1eeefff896d8c3ab3a9510326 so I changed my Engine to the latest (WineCX22.1.1) and now it works!

**Comment by Gcenx** [comment]
@matthewjumpsoffbuildings there’s actually a regression in that you’ll want to instead use WineCX22.1.1-1

That fixes cross-process windowing issues in Steam & Rockstar Games Launcher due to importing an upstream fix that causes issues with the cross-process hack.
