### ISSUE TITLE
It works in Ventura but Sonoma

### ISSUE THREAD

**Issue by SergeySlice** [Gcenx/WineskinServer#408]
I just run the wineskin 2.9.1.8 with engine WS11WineCX64Bit22.1.0-rc1.
It works fine in latest Ventura.
But on Sonoma I got the log with one line.
**LastRunWine.log**

objc[2432]: -[NSObject methodSignatureForSelector:] not available without CoreFoundation

**Comment by Gcenx** [comment]
Use WineCX22.1.1-2

**Comment by lilianmoraru** [comment]
Thank you. I can confirm that it works with WineCX22.1.1-2
