### ISSUE TITLE
Applications not running on macOS 14 Sonoma Developer Beta 1

### ISSUE THREAD

**Issue by ebp012** [Gcenx/WineskinServer#415]
I tried to open some apps I have, and Wineskin is stuck in a spinning wheel.

**Environment (please complete the following information):**
 - OS: 
 - Winery version:
 - Master Wrapper version:
 - Engine version:
 - Hardware: 
 - Application/Game Name 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**LastRunWine.log**

**Additional context**

Incorrectly filled out issues will be close without notice!

**Comment by Gcenx** [comment]
https://github.com/Gcenx/WineskinServer/commit/94599029bcf570bfb0c6cbd66289c117235ab309
