### ISSUE TITLE
Wineskin-2.9.0.6-1 has the same bundle version as 2.9.0.6

### ISSUE THREAD

**Issue by clobber** [Gcenx/WineskinServer#42]
Wineskin-2.9.0.6-1 has the same bundle version as 2.9.0.6, so existing wrappers don't see 2.9.0.6-1 as a "new" wrapper and forcing a wrapper update keeps the same 2.9.0.6 version string...

**Comment by Gcenx** [comment]
Wineskin-2.9.0.6-1 was not a real update\
The focus was to replace the embedded Runtime with the more stable version from Wineskin-2.9.0.7.

Wineskin-2.9.0.7 when released will correctly reflect the wrapper version.
