### ISSUE TITLE
Issues with wrapper & Steam

### ISSUE THREAD

**Issue by Dnao0** [Gcenx/WineskinServer#422]
Firstly amazing stuff!

I was able to play steam games on Mac, no issues, until..

I was using the rc2 version, now it does not show anymore.

Issue started after a STEAM update, got some error with 'Steamwebhelper.exe' after that everything broke, tried to re-install wine, wrapper and all but now i can't find the rc2 engine and the latest (WS11WineCX64Bit22.1.1-5) does not seem to work properly, can't create new wrapper and if i go to the previous latest version (WS11WineCX64Bit21.2.0-1) I can install steam but does not really starts, after 'verifying install' message from steam nothing happens

**Comment by Gcenx** [comment]
As you’ve ignored the issue template there’s no useful information to go off.

**Comment by Gcenx** [comment]
<img width="1207" alt="Screen Shot 2023-06-21 at 8 42 13 AM" src="https://github.com/Gcenx/WineskinServer/assets/38226388/983c2a8d-101e-40a6-b293-fe3763ec42a1">

**Comment by Gcenx** [comment]
macOS Big Sur had fixes in later patches it’s lightly you were running an early macOS Big Sur patch that didn’t have the later fixes
