### ISSUE TITLE
The games that requires media foundation crashes when launching.

### ISSUE THREAD

**Issue by rlarhsid** [Gcenx/WineskinServer#427]
**Environment (please complete the following information):**

OS: macOS 14.0 Sonoma & 13.4 Ventura (Both tested)
Winery version: 1.8.4.2
Master Wrapper version: Wineskin-2.9.1.9
Engine version: WS11WineCX64Bit22.1.1-7
Hardware: MacBook Pro 2021, M1 Max + 64GB RAM
Application/Game Name: DJMAX RESPECT V, Sixtar Gate: Startrail

**Describe the bug**
When launching a game that requires media foundation, it crashes immediately without any errors. I installed the gstreamer file from here: https://github.com/Gcenx/WineskinServer/issues/426

**To Reproduce**
1. Install Steam using Wineskin, 22.1.1-7 Engine.
2. Install the gstreamer stable package from the link: https://github.com/Gcenx/WineskinServer/issues/426
2. Launch one of the games that crashes (DJMAX RESPECT V, Sixtar Gate: Startrail).

**Expected behavior**
I expect the game launching correctly, showing all the BGAs that didn't show before due to media foundation problems.

**Screenshots**
No screenshots, but recorded the game crash: https://youtu.be/63uS02O7iR8

**LastRunWine.log**
Log was too long to paste here, so I attached it as a file.

**Additional context**
I'm very new to this, so there might be some mistakes while writing this. If there is anything additional to attach, I'll post it as fast as I could.

Incorrectly filled out issues will be close without notice!

[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/11990720/LastRunWine.log)

**Comment by Gcenx** [comment]
The problem is you have a brew Intel gstreamer installation

```
(wine:68472): GStreamer-WARNING **: 21:53:55.448: Failed to load plugin '/usr/local/lib/gstreamer-1.0/libgstdebug.dylib': dlopen(/usr/local/lib/gstreamer-1.0/libgstdebug.dylib, 0x0002): Library not loaded: @@HOMEBREW_PREFIX@@/opt/glib/lib/libgobject-2.0.0.dylib
  Referenced from: <93978E12-A893-3552-A21C-8BB376C8AD6A> /usr/local/Cellar/gstreamer/1.22.4/lib/libgstreamer-1.0.0.dylib
  Reason: tried: '/Applications/Steam.app/Contents/SharedSupport/wine/lib/libgobject-2.0.0.dylib' (no such file), '/Applications/Steam.app/Contents/SharedSupport/wine/lib64/libgobject-2.0.0.dylib' (no such file), '/Users/rlarhsid/Library/Application Support/Wineskin/Runtime/libgobject-2.0.0.dylib' (no such file), '/opt/local/lib/libgobject-2.0.0.dylib' (no such file), '/Applications/Steam.app/Contents/Frameworks/libgobject-2.0.0.dylib' (no such file), '/usr/lib/libgobject-2.0.0.dylib' (no such file, not in dyld cache), '/usr/libexec/libgobject-2.0.0.dylib' (no such file), '/usr/lib/system/libgobject-2.0.0.dylib' (no such file, not in dyld cache), '/opt/X11/lib/libgobject-2.0.0.dylib' (no such file)Library not loaded: @@HOMEBREW_CELLAR@@/gstreamer/1.22.4/lib/libgstreamer-1.0.0.dylib
  Referenced from: <D95B4C58-3FAC-3A19-9883-52F3B71445EC> /usr/local/Cellar/gstreamer/1.22.4/lib/libgstbase-1.0.0.dylib
  Reason: tried: '/Applications/Steam.app/Contents/SharedSupport/wine/lib/libgstreamer-1.0.0.dylib' (no such file), '/Applications/Steam.app/Contents/SharedSupport/wine/lib64/libgstreamer-1.0.0.dylib' (no such file), '/Users/rlarhsid/Library/Application Support/Wineskin/Runtime/libgstreamer-1.0.0.dylib' (no such file), '/opt/local/lib/libgstreamer-1.0.0.dylib' (no such file), '/Applications/Steam.app/Contents/Frameworks/libgstreamer-1.0.0.dylib' (no such file), '/usr/lib/libgstreamer-1.0.0.dylib' (no such file, not in dyld cache), '/usr/libexec/libgstreamer-1.0.0.dylib' (no such file), '/usr/lib/system/libgstreamer-1.0.0.dylib' (no such file, not in dyld cache), '/opt/X11/lib/libgstreamer-1.0.0.dylib' (no such file)Library not loaded: @@HOMEBREW_CELLAR@@/gstreamer/1.22.4/lib/libgstbase-1.0.0.dylib
  Referenced from: <8C80F69C-7A0F-37BC-9B88-1A0394BB93A6> /usr/local/Cellar/gstreamer/1.22.4/lib/libgstvideo-1.0.0.dylib
  Reason: tried: '/Applications/Steam.app/Contents/SharedSupport/wine/lib/libgstbase-1.0.0.dylib' (no such file), '/Applications/Steam.app/Contents/SharedSupport/wine/lib64/libgstbase-1.0.0.dylib' (no such file), '/Users/rlarhsid/Library/Application Support/Wineskin/Runtime/libgstbase-1.0.0.dylib' (no such file), '/opt/local/lib/libgstbase-1.0.0.dylib' (no such file), '/Applications/Steam.app/Contents/Frameworks/libgstbase-1.0.0.dylib' (no such file), '/usr/lib/libgstbase-1.0.0.dylib' (no such file, not in dyld cache), '/usr/libexec/libgstbase-1.0.0.dylib' (no such file), '/usr/lib/system/libgstbase-1.0.0.dylib' (no such file, not in dyld cache), '/opt/X11/lib/libgstbase-1.0.0.dylib' (no such file)
```

<br>

> GStreamer is also available on [Homebrew](https://brew.sh/), and you should be able to use that. However, please note that some plugins are not shipped by Homebrew, and you should avoid mixing Homebrew and the official installers on the same system.

In your case brews _relocation_ system is making there the dylib embedded rpath invalid

**Comment by rlarhsid** [comment]
Should I reinstall the gstreamer plugin? If so, how could I do it? I'd appreciate if you tell how to.

**Comment by Gcenx** [comment]
> Should I reinstall the gstreamer plugin? If so, how could I do it? I'd appreciate if you tell how to.

Currently you’d need to uninstall gstreamer package installed with brew.

I’ll make WineskinLauncher even more heavy handed to ignore a brew installation of gstreamer for the next wrapper update.

**Comment by rlarhsid** [comment]
I'll wait for the next update (couldn't solve anything by my own). Thanks for replying!

**Comment by rlarhsid** [comment]
I didn't know how to uninstall gstreamer package, so I just reinstalled the macOS itself.
After doing it, I reinstalled the gstreamer and set everything.
Now, the video is being rendered like this (Sixtar Gate: Startrail), and DJMAX RESPECT V Still crashes on launch.
![image](https://github.com/Gcenx/WineskinServer/assets/131584438/1b02a6e1-c80c-4969-8205-49dd1080e48a)

https://drive.google.com/file/d/1W4SB1PgDjHp8aK5uIgzoZo-UAKqLbzgd/view?usp=sharing
As the log file is too big too upload directly to Github, I attached it with a Google Drive link.

**Comment by Gcenx** [comment]
I see no complains from GStreamer this time so it might be something not implemented correctly on wine side, if you have each game in there own wrappers simply set a library override for `winegstreamer` and set it to `disabled`

If all your games are within a single wrapper it's more complicated, you'd need to add the games main executable for each game into winecfg then highlight it then click Librays tab and add `winegstreamer` and set to `disabled` for each affected executable.

Games that were working prior to GStreamer integration will work again without videos, games that were crashing before GStreamer integration will still crash.

**Comment by rlarhsid** [comment]
Disabling `winegstreamer` didn't help anything, I'd just better wait for the 22.1.1-8 version. Thank you for helping me a lot.

**Comment by rlarhsid** [comment]
Currently I'm using macOS 14 Sonoma Public Beta, and today I updated my wineskin to 22.1.1-rc8.

It seems that now the crashing bug is completely solved, but the gstreamer video rendering bug is still happening. I installed the gstreamer stable package (only this, no homebrew or anything). Still, the videos are being rendered like this:
<img width="1800" alt="image" src="https://github.com/Gcenx/WineskinServer/assets/131584438/34de7a26-efbe-435f-bc9f-01145d3c91fc">

Also, using gstreamer triggers a serious input lag, terrible framerates, and stuttering. I hope this could be fixed somehow (playing a rhythm game without any background videos will be too annoying😢).

If there is anything that is needed to fix this problem, I'll add it to here as fast as I could. (I live in Korea, so I might response a bit late.)

**Comment by rlarhsid** [comment]
+ I don't know if this will help, but it seems that this similar to me: https://github.com/ValveSoftware/Proton/issues/5920

**Comment by Gcenx** [comment]
Try putting that command into the Unix field

> export WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1

**Comment by rlarhsid** [comment]
It works! I really appreciate your help!! 😄 
<img width="1800" alt="image" src="https://github.com/Gcenx/WineskinServer/assets/131584438/4952e9b2-904f-42a6-a679-91bbbf2a8b1a">
