### ISSUE TITLE
No Installation on Catalina 10.15.5

### ISSUE THREAD

**Issue by MacGTO** [Gcenx/WineskinServer#43]
Hi all,
i have a strange issue:

I have installed the version V1.8.4: Wineskin-Winery-1.8.4 with WS11WineCX19.0.1-1 and 64-bit version.
I have set no32exec=0 on boot argument.
but when i create a blank wrapper i can't install anything.
it's always in busy state, and if i show content of my wrapper, i view that it don't create drive_c folder.

where is the problem?

**Comment by Gcenx** [comment]
Let’s see you have;
- Winery 1.8.4
- WS11WineCX19.0.1-1 (did Winery download this?)
- Wineskin-2.9.0.6-1 (did you install this via Winery?)

You said you can create a wrapper did you decide a the gecko prompts?

You say the wrapper is always busy, when does that occur what exact steps can be taken to creates this.

Also I’d recently revised the README, SIP on macOS Catalina protects most user directories, having SIP disabled avoids this specific issue. Wineskin in a later version will directly request access to the SIP protected user locations.

**Comment by MacGTO** [comment]
> Let’s see you have;
> 
> * Winery 1.8.4 _Yes_
> * WS11WineCX19.0.1-1 (did Winery download this? _Yes_ )
> * Wineskin-2.9.0.6-1 (did you install this via Winery? _yes_ )
> 
> You said you can create a wrapper did you decide a the gecko prompts? _I don't arrive to select gecko...just after 2 second that i click on Create my wrapper, programs show me the wrapper... i don't know where si the problem _
> 
> You say the wrapper is always busy, when does that occur what exact steps can be taken to creates this.
> 
> Also I’d recently revised the README, SIP on macOS Catalina protects most user directories, having SIP disabled avoids this specific issue. Wineskin in a later version will directly request access to the SIP protected user locations. _ yes SIP is disabled_ 

In _corsive_. my answer

**Comment by Gcenx** [comment]
I’m really not sure what you’re doing differently then other people who have this working, considering the my master wrapper is used with PortingKit

**Comment by Gcenx** [comment]
Closing due to in activity
