### ISSUE TITLE
 WS11WineCX64Bit22.1.1.tar.7z provides bin/wine and bin/wine-preloader but not WS11WineCX64Bit22.1.1-8.tar.7z 

### ISSUE THREAD

**Issue by Kethen** [Gcenx/WineskinServer#433]
**Environment (please complete the following information):**
 - OS: 10.13.6
 - Winery version: /
 - Master Wrapper version: /
 - Engine version: WS11WineCX64Bit22.1.1-8
 - Hardware: /
 - Application/Game Name: /
 
**Describe the bug**

If I understand correctly 32bit wine is still needed for pre-catalina macos for 32bit windows applications, and it does work on WS11WineCX64Bit22.1.1. However on WS11WineCX64Bit22.1.1-8 bin/wine and bin/wine-preloader seem to be missing, are future builds of the engine dropping 32bit support for pre catalina macos? Thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

**LastRunWine.log**

**Additional context**

Incorrectly filled out issues will be close without notice!

**Comment by Gcenx** [comment]
macOS High Sierra support is restored in `WS11WineCX64Bit22.1.1-10`
