### ISSUE TITLE
Create New Blank Wrapper is greyed out

### ISSUE THREAD

**Issue by Teghjyot** [Gcenx/WineskinServer#44]

**Comment by Gcenx** [comment]
What version of macOS are you running?

<img width="284" alt="Screen Shot 2020-06-21 at 3 07 57 PM" src="https://user-images.githubusercontent.com/38226388/85232916-031d2580-b3d1-11ea-8000-315afe40534c.png">

Did you click the "Update" button to download the master wrapper?

**Comment by Teghjyot** [comment]
10.15.6 Beta (macOS Catalina)

**Comment by Teghjyot** [comment]
Oh something just happened and it worked
Sorry!!!
