### ISSUE TITLE
Wineskin stopped working correctly after the MacOS 13.5.2 update

### ISSUE THREAD

**Issue by RHimadiiev** [Gcenx/WineskinServer#455]
**Environment (please complete the following information):**
 - OS: MacOS 13.5.2
 - Winery version: 
 - Master Wrapper version: 2.9.8.1
 - Engine version: WS11WineCX64bit22.1.0-rc2

 - Hardware: MacBook Pro M1 Max 16
 - AATranslator 2 (beta)

**Describe the bug**

After the MacOS 13.5.2 update AATranslator 2 cannot convert project formats anymore, aborting the process and showing "Unhandled exception occured in your application". I can launch the app, set the options, checkmarks, but it cannot process the files. 

**To Reproduce**

1. Launch AATranslator 2 wrapper
2. Set the Source and Output formats.
3. Select the input file and set the output folder.
4. Press Generate
=> Unhandled exception occured in your application message appears. 

**Expected behavior**
1. Launch AATranslator 2 wrapper
2. Set the Source and Output formats.
3. Select the input file and set the output folder.
4. Press Generate
5. App should convert the one format to another with no errors, 

**Screenshots**

**LastRunWine.log**

**Additional context**

Incorrectly filled out issues will be close without notice!

**Comment by RHimadiiev** [comment]
**Environment (please complete the following information):**
 - OS: MacOS 13.5.2
 - Winery version: 
 - Master Wrapper version: 2.9.8.2
 - Engine version: WS11WineCX64bit22.1.1-13

 - Hardware: MacBook Pro M1 Max 16
 - AATranslator 2 (beta)

**Describe the bug**

Installer gets aborted with new wrapper and engine

**To Reproduce**

1. Create a wrapper
2. Go to Winetricks and install dotnet472
3. Try to install the ATranslator2 x64_Release-v0.1.9.0
4.I nstallation gets aborted

**Expected behavior**

1. Create a wrapper
2. Go to Winetricks and install dotnet472
3. Try to install the ATranslator2 x64_Release-v0.1.9.0
4. It should be installed


**Screenshots**


**LastRunWine.log**

**Comment by Rastafabisch** [comment]
I recommend Updating your existing wrapper (make a backup, first) to the latest engine. You can do so by right clicking the wrapper in the finder, show package contents and run the included wineskin app. There you'll find the option to update your (semi) working wrapper to check wether that fixes your issue.

**Comment by RHimadiiev** [comment]
> I recommend updating your existing wrapper (make a backup, first) to the latest engine. You can do so by right clicking the wrapper in the finder, show package contents and run the included wineskin app. There you'll find the option to update your (semi) working wrapper to check wether that fixes your issue.

I tried it too. It didn't help. The same symptoms as in the initial report. No logs though. But the installer issue is not OK too. It did work before.

**Comment by 3583Bytes** [comment]
I am also have issues with the new MacOS update

**Comment by RHimadiiev** [comment]
When I try to change engine, there is an error appears related to .NET Framework. AATranslator needs .NET Framework. 
Maybe that's the reason of this bug.

**Screenshots**

**Comment by RHimadiiev** [comment]
Tried MacOS Sonoma. Still doesn't work with 22.1.1-14_D3Metal-v1.0.4

**Comment by RHimadiiev** [comment]
I've tried it now with fresh Ventura: doesn't work and console shows wineserver crashes.

**Comment by RHimadiiev** [comment]
I've tried it with the fresh Ventura and it doesn't work. Console says the wineserver crashed.

**Comment by RHimadiiev** [comment]
> Assuming you’d made a typo with the wrapper version so I’ll assume you mean you were using Wineskin-2.9.1.8 [9312bfb](https://github.com/Gcenx/WineskinServer/commit/9312bfb55f7c20f761cb2a9116795693753cf3b3) that’s still older than the current version available at the time you’d opened this issue.
> 
> Update to the latest wrapper in Winery and create a new wrapper using WS11WineCX64Bit22.1.1-14_D3DMetal-v1.0.4. Also attach LastRunWine.log

Currently I used 2.9.2.0 and the WS11WineCX64Bit32.0.1-wip3 on Ventura. 

I'll try it with the WS11WineCX64Bit22.1.1-14_D3DMetal-v1.0.4 but I did it on Sonoma and it didn't help.

**Comment by RHimadiiev** [comment]
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/12807170/LastRunWine.log)

This way?

**Comment by RHimadiiev** [comment]
> Looks like wine itself is working, the problem is the application probably wants native .Net
> 
> ```
> 0024:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"AATranslator2.exe" cannot be loaded
> 0024:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\Suite Spot Studios\\AATranslator2\\AATranslator2.exe" failed, status c0000135
> ```
> 
> See `mscoree.dll` complaint that means the application requires some version of .Net

This wasn't an issue before the MacOS 13.5.2. 
On Windows AATranslator 2 automatically installs .NET Framework 4.7.2
On a MacOS before 13.5.2 I installed dotnet472 in winetricks and when I installed AAT2, it didn't try to automatically install .NET Framework 4.7.2. It just installed an app itself and worked correctly. 

Now:
1. Install dotnet472 in winetricks
2. When I try to install the program it tries to repair .NET Framework 4.7.2 installation
3. Install the app itself and it doesn't start

**Comment by RHimadiiev** [comment]
I've just tried to create a new wrapper with latest engine and wrapper versions just to re-test. Installed dotnet472 and tried to run the install. It aborts install.  
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/12814048/LastRunWine.log)
[Winetricks.log](https://github.com/Gcenx/WineskinServer/files/12814049/Winetricks.log)

**Comment by RHimadiiev** [comment]
Tried to do the same again: no luck. Installer got aborted.
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/12816723/LastRunWine.log)

**Comment by RHimadiiev** [comment]
Tried WS11WineCX64Bit23.5.0 (D#DMetal-v1.0 wip)
Installer got aborted
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/12840622/LastRunWine.log)

**Comment by RHimadiiev** [comment]
This is more interesting:

1. Create a wrapper with any engine. You can use WS11WineCX64Bit23.5.0 (D3DMetal-v1.0 wip)
2. Winetricks — install dotnet472
3. Try to change the wrapper's engine to another version. 
You'll get this while it tries to change it:
<img width="423" alt="Screenshot 2023-10-08 at 18 56 42" src="https://github.com/Gcenx/WineskinServer/assets/144618187/788186fc-a386-4335-87c2-68c241340b18">

I didn't install AATranslator this time. SO I assume something in MacOS 13.5.2 broke the dotnet 472 in Winetricks. Or Winetricks in general. No?

**Comment by RHimadiiev** [comment]
I was able to fix it setting the wrapper to Windows 7 mode before installing everything. I've used the latest engine version but I am not sure it's because of the engine version.
