### ISSUE TITLE
Kerberos SSP support will not be available.

### ISSUE THREAD

**Issue by mikeccuk2005** [Gcenx/WineskinServer#46]
Macos Catalina
Wrapper:
Wineskins 2.9.0.7-Beta3
Engine:
WS11WineCX64Bit19.0.1

One of my application has an error:
`err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.`

Do I need to enable  gssapi flag somewhere?

**Comment by Gcenx** [comment]
Don’t use WS11WineCX64Bit19.0.1 use the newer WS11WineCX64Bit19.0.01-1 or WS11WineCX19.0.1-1 Engines
