### ISSUE TITLE
Genshin Impact not launching

### ISSUE THREAD

**Issue by niclimcy** [Gcenx/WineskinServer#475]
**Environment (please complete the following information):**
 - OS: macOS 14.0
 - Winery version: 2.9.2.0
 - Master Wrapper version: WS11WineCX64Bit
 - Engine version: 23.5.0-wip2-D3DMetal
 - Hardware: Macbook Pro 14 2021
 - Game Name: Genshin Impact

**Describe the bug**
Game does not launch from launcher, launcher reopens after awhile

**To Reproduce**
1. Install Genshin Impact installer from mihoyo website
2. Set launcher.exe as Windows app
3. Download game files (73GB)
4. Press launch, nothing happens

**Expected behavior**
After pressing launch, separate window of game should launch

**Screenshots**
N.A.

**LastRunWine.log**
https://gist.github.com/niclimcy/997a0b7339de5d9e751dfbe990d61a5c

**Additional context**
On Crossover 23.5, there is an overlay of html content also missing on wineskinserver in the game launcher. Game launches fine there and there are no additional hacks installed as I can see.

**Comment by antoninmuller** [comment]
same engine with cyberpunk = crash too

**Comment by niclimcy** [comment]
> @niclimcy ![Screenshot 2023-10-15 at 4 52 34 PM](https://user-images.githubusercontent.com/38226388/275354080-0dec5f2a-f63c-4a5c-9515-2c99ef75ac65.png)
> 
> The provided log gave me a hint to the actual issue this was easy to resolve and will be included in the next wip bum.

Nice. Are there any instructions on how I can compile the fix for myself first?

Also are there plans on using GPTK 1.0 which was released recently, or do we follow Crossover for such version bumps?

**Comment by niclimcy** [comment]
> > Nice. Are there any instructions on how I can compile the fix for myself first?
> 
> No as I don’t provide WineskinCX sources but it still requires more work due to the layering issue, I see it appear and vanish.
> 
> > Also are there plans on using GPTK 1.0 which was released recently, or do we follow Crossover for such version bumps?
> 
> I’m already bundling D3DMetal-v1.0 (stable) What you call GPTK is actually D3DMetal.
> 
> > Crossover shows it more consistently for some reason
> 
> This might be due to there still using D3DMetal-v1.0.4 beta, where as I’m bundling D3DMetal-v1.0 (stable)

How can I debug the layering issue?

**Comment by niclimcy** [comment]
> @niclimcy while the launcher layering probably won’t have been affected wip3 probably gets the game to launch.
> 
> Though if that’s anything like Diablo4 it might require enabling esync/msync.

Game launches fine now with wip3, do I close this issue and make a new one for the layering issue?

**Comment by niclimcy** [comment]
Regression with non wip build:

https://gist.github.com/niclimcy/5076a970b709818ea1ff1d4879f5b8d6

**Comment by niclimcy** [comment]
23.6 fixed it
