### ISSUE TITLE
How to create descriptive app name (not appname123456789Wine64-preloader)?

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#49]
This project has done wonders and I've now got my 64-bit apps running perfectly under various versions of macOS. I can't thank you enough.

One question: one of my apps needs to have the F1-F12 function keys appear on the TouchBar, and, with the help of other AppleScript programmers, I've figured out how to make an AppleScript wrapper tell macOS to use function keys when an app is running. (I use an AppleScript wrapper to launch the Wineskin app that I'm writing about.)

It would be much easier and more portable if I could use a more specific name than "vDos91511959Wine64-preloader". I've been trying to figure out how to change this, but all I can find in the bundle are lines like these in the preloader and WineServer bash scripts:

`DYLD_FALLBACK_LIBRARY_PATH="${WINESKIN_LIB_PATH_FOR_FALLBACK}" "$(dirname $0")/vDos91511959Wine64-preloader" "$@"`

What I can't find is where the "vDos91511959" string is that governs all the others. Is there any way to fix an existing app so it does this? (One reason I want to fix an existing app rather than create a new one is that I've added custom menus, startup and shutdown scripts, etc., and it would be extremely difficult to reconstruct these.) 

Or does the wineskinserver executable simply look for a file in wswine.bundle/bin with a name that ends with "Wine64-preloader"?

If it's impossible to use a more descriptive name, I'll understand. But if there's a way to do this, I'll be grateful to know about it.

**Comment by Gcenx** [comment]
I’d those AppleScript could replace the currently used FNToggle I’d be interested.

The bash wrappers were being generated based of the wrappers name plus a random number generator to produce a unique binary name.

The next release won’t have the feature but you could manually do it then the name will be fixed at all times, currently I know the BundleID gets regenerated on each launch that was partly responsible for the permission issues on Mojave/Catalina

**Comment by emendelson** [comment]
Probably I should just experiment with this - but do you know if I can simply rename the bash wrappers and change the FALLBACK etc path? What I wonder about is how the program decides which launcher to run, and finds the name to use....

The AppleScript that I use turns on F-keys in the touchbar. I've never found an AppleScript method that  controls the "Use F1 etc as standard function keys" (without using GUI scripting, which doesn't work with scripts that get distributed to other users) but I'll ask again on the Script Debugger forum. Meanwhile, if you want to add the UseFkeys-in-touchbar, the method is to run these commands:

First, to see if the touchbar is present:

`ioreg | grep TouchBarServer`

Then:

`defaults write com.apple.touchbar.agent PresentationModePerApp -dict-add com.comany.AppName functionKeys`

`killall ControlStrip`

**Comment by Gcenx** [comment]
I haven’t used 2.9.0.6 wrapper in quite sometime but WineskinLauncher checks if ${custom}Wineserver is still running else it will terminate so at least leave that name alone.

Within the wrapper only alter the binary name so MyCoolWrapper37474748Wine-preloader to what ever you want it to be and rename the binary, the fallback doesn’t need to be altered unless your adding your own custom paths before/after the WineskinLauncher generated paths.

**Comment by emendelson** [comment]
I'm probably being dense, but this is the situation. I'm using 2.9.0.7 and I've renamed the binary "vDos", but this is what happens when I launch it. If I try renaming any thing in the bin folder, nothing launches. Will I need to start from scratch and create a new binary?

In the screen shot you can see the name with the arbitrary number over on the right where I've hovered over the icon on the taskbar.

![Screen Shot 2020-07-10 at 12 51 41 PM](https://user-images.githubusercontent.com/5208505/87179802-56d2ae80-c2ad-11ea-92d1-a3628c90eef1.png)

**Comment by Gcenx** [comment]
The wrapper for wine64-preloader should contain the following
```
#!/bin/bash
 DYLD_FALLBACK_LIBRARY_PATH="${WINESKIN_LIB_PATH_FOR_FALLBACK}" "$(dirname "$0")/vDosWine64-preloader" "$@"
```

As nothing really loaded for you I’d guess your missing the DYLD_FALLBACK_LIBRARY_PATH configuration.

Your also not using the latest 2.9.0.7 version it’s on Beta4 currently and ready for release just warning on PK making the needed changes

**Comment by emendelson** [comment]
That worked!!! Thank you!! And I'll look forward to the new 2.9.0.7 version.

**Comment by emendelson** [comment]
Well, it turns out that I put you to a lot of trouble for nothing. In order to set the touch bar to use the function keys when a specific app is running, the app needs to have an identifier, and the preloader doesn't have one, so it seems to be impossible to set the touch bar to use the F-keys when wine is running. The next best thing would be to turn on the F-keys when launching the app and turning them off when exiting, and that's what I'll work on next.

Apologies for bothering you over something that makes no practical difference!

**Comment by emendelson** [comment]
I've tried various methods of setting the Fn keys in the Touch Bar, etc., but the problem seems to be that there's no com.xyz.abc.def ID associated with the Wineskin app that's currently running, and therefore no prefs file for it. Is there any hope that this can be added in the future? It's not essential for most applications, but it would be useful for setting things like full disk access, F-keys, etc., etc. 

One thing I tried was launching the Wineskin app from AppleScript launcher that stayed open, with the setting to display F-keys in the Touch Bar when the launcher was open. The trouble was that the F-keys didn't appear when the Wineskin app had the focus, only when the launcher had the focus. I should have figured this out before I tried to make it happen.

**Comment by Gcenx** [comment]
Created wrappers do have a unique BundleID, I’m also getting permissions prompts on Catalina/Big using 2.9.0.7-Beta4

I’ve already ready tested environment inheritance, on Catalina I provided full disk access to PortingKit.

I’d ensured the tccd database was wiped so only PortingKit had permissions then launched a Port that requires additional permissions and it inherited PortingKits permissions, when launched directly the wrapper was forced to request these permissions.

**Comment by emendelson** [comment]
OK, I'll try this again by creating a new wrapper and see what happens. I've been working with older ones. I'm right in thinking that you haven't released 2.9.0.7-Beta4? I'll wait for that rather than banging my head against the wall.

If you have a touch-bar Mac, could you try these two commands to see if they work?

`defaults write com.apple.touchbar.agent PresentationModePerApp -dict-add com.comany.AppName functionKeys`
`killall ControlStrip`

If you don't want to go to the trouble, I'll certainly test it as soon as Beta4 is available.

**Comment by emendelson** [comment]
And I hope it's OK to link the pre-release page here, because I always have a hard time finding it again...

https://github.com/Gcenx/WineskinServer/releases/tag/V1.8.4.2

**Comment by Alex1844** [comment]
Can we get access to the Beta 4?

**Comment by emendelson** [comment]
Just a quick report: I wasn't able to get the F-keys working from the touch bar with beta 3. Hoping for better luck with beta 4.

**Comment by Gcenx** [comment]
@Alex1844 I'm waiting on the new MoltenVK release before repacking the master wrapper

@emendelson I can't say if it will function as it sounds like your wrapping the Port, going off the PK testing it should work via environment inheritance as technically your wrapper is calling the Port its not beng ran directly like it would normally.\
So you need to ensure your wrapper also has a valid BundleID or it won't function.

**Comment by emendelson** [comment]
I can make the F-keys appear on the touch bar when the wrapper has the focus, but not when the Port has the focus; both the wrapper and port have valid IDs, and I've registered both. I'll experiment again when beta 4 shows up...

**Comment by Gcenx** [comment]
Losing due to inactivity
