### ISSUE TITLE
Wineskin 2.8.8.5 with WS10WineCX18.1 does not launch application on Yosemite

### ISSUE THREAD

**Issue by Alex1844** [Gcenx/WineskinServer#5]
I have tried the wrapper that works just fine on Mojave, and on Yosemite does not even launch. When I try Test Run in Winery, it reports success because it launches another exe it found, not the one specified, which does not have GUI so it appears that it did not launch anything.
I think it does not believe on El Capitan either, from the feedback I git, but have not tested yet.

**Comment by Alex1844** [comment]
It also does not associate the file type.

**Comment by Alex1844** [comment]
Here is the log file from Test Run. It should start this app
C:\\Program Files\\MyProgram\\MyProgram.exe
but instead it starts this one, which it found by itself
C:\\Program Files\\MyProgram\\unins000.exe


002e:fixme:msg:ChangeWindowMessageFilter c046 00000001
002e:fixme:win:DisableProcessWindowsGhosting : stub
002e:fixme:graphics:ShutdownBlockReasonDestroy (0x1007a): stub
002e:fixme:graphics:ShutdownBlockReasonCreate (0x1007a, L"Installing"): stub
002e:fixme:graphics:ShutdownBlockReasonDestroy (0x1007a): stub
002e:fixme:graphics:ShutdownBlockReasonCreate (0x1007a, L"Please wait while Setup installs MyProgram on your computer."): stub
002e:fixme:explorerframe:taskbar_list_SetProgressValue iface 0x84dc28, hwnd 0x1007a, ullCompleted 0, ullTotal 18ce48e stub!
002e:fixme:sfc:SfcIsFileProtected (0x0, L"C:\\Program Files\\MyProgram\\unins000.exe") stub
0030:err:menubuilder:cx_wineshelllink wineshelllink returned 1
0032:err:menubuilder:cx_wineshelllink wineshelllink returned 1
002e:fixme:explorerframe:taskbar_list_SetProgressState iface 0x84dc28, hwnd 0x1007a, flags 0 stub!
0034:err:menubuilder:cx_wineshelllink wineshelllink returned 1
0038:err:menubuilder:cx_wineshelllink wineshelllink returned 1
003a:err:menubuilder:cx_wineshelllink wineshelllink returned 1
003c:err:menubuilder:cx_wineshelllink wineshelllink returned 1
002e:fixme:graphics:ShutdownBlockReasonDestroy (0x1007a): stub
0036:err:menubuilder:InvokeShellLinker failed to extract icon from L"C:\\Program Files\\MyProgram\\MyProgram.url"
0036:err:menubuilder:cx_wineshelllink wineshelllink returned 1
0036:err:menubuilder:InvokeShellLinker failed to build the menu
003a:err:menubuilder:cx_wineshelllink wineshelllink returned 1
003a:err:menubuilder:InvokeShellLinker failed to build the menu
0032:err:menubuilder:cx_wineshelllink wineshelllink returned 1
0032:err:menubuilder:InvokeShellLinker failed to build the menu
003c:err:menubuilder:cx_wineshelllink wineshelllink returned 1
003c:err:menubuilder:InvokeShellLinker failed to build the menu
0038:err:menubuilder:cx_wineshelllink wineshelllink returned 1
0038:err:menubuilder:InvokeShellLinker failed to build the menu
0030:err:menubuilder:cx_wineshelllink wineshelllink returned 1
0030:err:menubuilder:InvokeShellLinker failed to build the menu
0034:err:menubuilder:cx_wineshelllink wineshelllink returned 1
0034:err:menubuilder:InvokeShellLinker failed to build the menu

**Comment by Alex1844** [comment]
And here is the log file from Mojave where it launches just fine

0009:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x33f450, 0x33f460 0x33f454
0009:fixme:nls:get_dummy_preferred_ui_language (0x38 0x33f450 0x33f460 0x33f454) returning a dummy value (current locale)
002c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x33fe5c
0009:fixme:shell:IPersistFile_fnSaveCompleted (0x1596a78)->(L"C:\\users\\crossover\\Recent\\MyProgram.dat.lnk"): stub
0009:fixme:shell:SHAddToRecentDocs Unsupported flags: 4
0009:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x33fe5c

**Comment by Gcenx** [comment]
WineCX18.1.0 I can rebuild I believe when my system was upgraded to Mojave 10.14.**1** release it also “upgraded” my XCode Command Line Tools from 9.4.1 to 10.

Do any wrapper built using this Wineskin fork even work on Yosemite?

**Comment by Alex1844** [comment]
I have just tried packaging an application in Yosemite and it fails. It keeps spinning and a message saying "Wineskin is currently busy" message

**Comment by Alex1844** [comment]
Exactly the same problem on Mountain Lion

**Comment by Gcenx** [comment]
> I have just tried packaging an application in Yosemite and it fails. It keeps spinning and a message saying "Wineskin is currently busy" message

I was afraid would be the case, last night I decided to test this on a Mac OS X 10.8 VM and I was unable to build anything.
I already spoke to VitorMM about this as it now also affect PortingKit.
I will also look into that after I rebuild rebuild the WineCX compiles just to be safe.

I have an idea to keep the new functions and also work on versions below El Capitan, but I won’t be posting an update until I verify it myself.

**Comment by Alex1844** [comment]
It works fine in Sierra.

Thanks for your hard work. You are very responsive

**Comment by Alex1844** [comment]
El Capitan no bueno.

So, everything from El Capitan (10.11) down to Mountain Lion (10.8) fails with exactly the same log files.

Sierra (10.12) and up, all work

**Comment by Gcenx** [comment]
> It works fine in Sierra.
> 
> Thanks for your hard work. You are very responsive

I try to respond if possible.
And thanks you for testing and letting me know the results.

> El Capitan no bueno.
> 
> So, everything from El Capitan (10.11) down to Mountain Lion (10.8) fails with exactly the same log files.
> 
> Sierra (10.12) and up, all work

Ah ok that’s not what I though would be the case, I thought it would be El Capitan (Metal) or High Sierra (Metal 2) would have been the lightly versions it would work with.

So if I can get it working in the OS X 10.8 VM it should function in anything above also, I believe the wrapper issue is due to the GPU detection but I could be wrong (not the first or last time)

**Comment by Gcenx** [comment]
@Alex1844 Well good news, I managed to get Wineskin-2.8.8Beta5 working by recompiling and disabling the gpu detection function as disabling the checkbox alone was not enough during my quick testing last night.

So as long as I don't use the new GPU detection function on anything below Sierra that's good, now I need to see about adding in the old gpu detection function for older system as a fallback.

Next I need to see about getting Winery repacking working on OSX 10.8 and possibly to Sierra?
Manual downloaded versions do work but repacking is a large component of this Wineskin version.

**Comment by Gcenx** [comment]
Currently rebuilding WineCX compiles to function on 10.8 correctly.
However if the version of OSX/macOS does not support the needed SSL version then no Steam Store... and no Downloading without the Steam work-around.

But on OSX/macOS versions that does support the needed SSL version then the Steam Store/Downloading _should function_
