### ISSUE TITLE
Steam Overlay not working when using D3DMetal Engines.

### ISSUE THREAD

**Issue by rlarhsid** [Gcenx/WineskinServer#503]
**Environment (please complete the following information):**
 - OS: Sonoma 14.1.2
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.2.0
 - Engine version: WineskinCX 23.6.0 (D3DMetal 1.1)
 - Hardware: 2021 MacBook Pro 14'
 - Application/Game Name: Any Games in Steam (Tested with DJMAX RESPECT V, vivid/stasis, EZ2ON REBOOT: R)

**Describe the bug**
Even if the option "Use Steam Overlay in Game" is turned on, the overlay doesn't appear when using D3DMetal Engines. Changing the application's engines to a Non-D3DMetal Engine and adding DXVK via Winetricks fixes this problem.

**To Reproduce**

Describe the steps to reproduce the behavior:
1. Build a Steam app, Using any type of D3DMetal Engines. In my case, I used WineskinCX 23.6.0 (D3DMetal 1.1).
2. Add the Winetricks (fakekorean, fakejapanese, steam).
3. Launch any game from Steam.
4. The Steam Overlay feature won't work.

**Expected behavior**
The Steam Overlay feature would work without any problems.

**Screenshots**
No Screenshots

**LastRunWine.log**
[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/13622990/LastRunWine.log)

**Additional context**
Nothing

Incorrectly filled out issues will be close without notice!

**Comment by Strangerxxx** [comment]
> Only Apple can resolve this as D3DMetal is there DirectX 11/12 > Metal API.

How did you get this knowledge?

I mean, I know it is a known bug, but I cant really get an idea why it happens.

My hope is that if more people will know the origin of the bug (exact lack of supporting something) the more probability it could be ever fixed.

@Gcenx could you please explain it a bit more?

Thx
