### ISSUE TITLE
Software Update

### ISSUE THREAD

**Issue by ledillow** [Gcenx/WineskinServer#53]
Upon trying to run the app, my computer tells me that a software update is necessary and that it cannot open because it can't check for malicious software.

**Comment by emendelson** [comment]
If System Preferences is telling you need a software update, that has nothing to do with Wineskin. It's probably just a coincidence that you saw both at the same time.

As for the app (it's not clear which app you're referring to), right-click and choose Open. You may need to do this twice.

**Comment by Gcenx** [comment]
As @emendelson says this has nothing todo with Wineskin
