### ISSUE TITLE
Apple Silicon ARM support ?

### ISSUE THREAD

**Issue by goodhyun** [Gcenx/WineskinServer#54]
This is not an issue but what lots of users will be curious about.

There are two dissenting opinions on this:
https://www.codeweavers.com/support/forums/general/?t=27;msg=228668 
https://www.codeweavers.com/support/forums/general/?t=27;msg=228011

Anybody tried anything on the development transition kit?

**Comment by abpostelnicu** [comment]
I think for this will be [Project Rosetta](https://en.m.wikipedia.org/wiki/Rosetta_(software)).

**Comment by Gcenx** [comment]
https://www.winehq.org/pipermail/wine-devel/2020-August/171857.html

Apple silicon uses 16KB page size, where wine uses 4KB this will cause major issues for wine.

> I think for this will be [Project Rosetta](https://en.m.wikipedia.org/wiki/Rosetta_(software)).

Rosetta2 isn’t a viable option for wine, quickly reading over the documentation for it explains why.

**Comment by d235j** [comment]
It seems that Codeweavers somehow has Crossover 20.0.1 and later working on Apple Silicon via Rosetta 2:
https://www.codeweavers.com/blog/jwhite/2020/11/10/its-great-to-live-in-interesting-times

**Comment by Gcenx** [comment]
> It seems that CodeWeavers somehow has Crossover 20.0.1 and later working on Apple Silicon via Rosetta 2:
> https://www.codeweavers.com/blog/jwhite/2020/11/10/its-great-to-live-in-interesting-times

Jeremy White has been working on support but at precent it doesn’t function on an actual Apple DTK at least so ignore this, it was more he’d hoped by the time M1 systems were launched the current version would ether be good to go or need some final tweaks.

He’d clarified this via the [BetterTesters forums](https://www.codeweavers.com/support/forums/bettertester/?t=1;msg=231127#c2)

But Crossover-wine-20.0.1 sources did include additional groundwork for Apple Silicon see [preloader_mac.c](https://github.com/Gcenx/winecx/blob/d9f33884e6a4634ffd8789c2b2a15770f568aa1b/loader/preloader_mac.c#L57-L66)

**Comment by d235j** [comment]
@Gcenx Indeed, the DTK lacks hardware support for 4K pages, which the M1 silicon uses for Rosetta 2. M1 also may have other hardware optimizations. I guess we'll see.

**Comment by d235j** [comment]
> https://www.winehq.org/pipermail/wine-devel/2020-August/171857.html
> 
> Apple silicon uses 16KB page size, where wine uses 4KB this will cause major issues for wine.

I believe this is pertaining to use of wine to run Windows-arm64 programs.
Without Apple providing an API to switch the M1 CPU into 4KB page mode outside Rosetta 2, this will be a problem.

> Rosetta2 isn’t a viable option for wine, quickly reading over the documentation for it explains why.

I'm unsure why this would be the case on computers that support 4KB pages in hardware (e.g. M1).

**Comment by Gcenx** [comment]
There has been multiple modifications to upstream wine for arm64 target since this, I’m ignoring this until people have access to actual M1 based systems.

**Comment by d235j** [comment]
@Gcenx 

It appears that the approach Crossover is taking is to make the code workable on Rosetta 2, in which case compiling wine for arm64 target would not be useful — instead, it would be compiled for x86_64 target.

My fear is that the i386_set_ldt / i386_get_ldt calls don't work in Rosetta 2, in which case Crossover won't work and wine would have to do its own translation. I think this is likely.
We'll see when people have M1 Macs to play with.

**Comment by Gcenx** [comment]
For the short term CodeWeavers plan to make use of Rosetta2, but long term a modification of Hangover will be required with a native arm64 version of wine.

We won’t know fully until we have access to an M1 based system, not sure I’ll be getting one but I can lightly get remote access to one.

**Comment by d235j** [comment]
Makes sense.

> [...] but long term a modification of Hangover will be required with a native arm64 version of wine.

For high performance, it will probably also be necessary to enable the CPU optimizations that Apple is using, which at least at the moment might require a kext.

**Comment by Gcenx** [comment]
> Makes sense.
> 
> > [...] but long term a modification of Hangover will be required with a native arm64 version of wine.
> 
> For high performance, it will probably also be necessary to enable the CPU optimizations that Apple is using to accelerate Rosetta 2, which at least at the moment might require a kext.

Well it seems I’ll need to obtain an Apple Silicon based system as CrossOver-20.0.2 has been shown running on macOS Big Sur 11.1 beta

**Comment by goodhyun** [comment]
better close this one, as @Gcenx is now working on the solution at #65  !
