### ISSUE TITLE
WinSCP crash on 23.7.1

### ISSUE THREAD

**Issue by niphor** [Gcenx/WineskinServer#540]
**Environment (please complete the following information):**
 - OS: Sonoma 14.3.1
 - Winery version: 1.8.4.2
 - Master Wrapper version: 2.9.2.0
 - Engine version: WS11WineCX64Bit23.7.1
 - Hardware: MacBook Pro 16 2019
 - Application/Game Name: [WinSCP Portable](https://winscp.net/download/WinSCP-6.3-Portable.zip)

**Describe the bug**
This application runs normally on Wine7.x with the OS version set to Win7, but it crashes on Wine8.x.

| Wrapper | Engine | OS | Result|
| -- | -- | -- | -- |
| 2.9.2.0 | WS11WineCX64Bit23.7.1 | Win10 | crash in most cases |
| 2.9.2.0 | WS11WineCX64Bit23.7.1 | Win7 | crash |
| 2.9.2.0 | WS11WineCX64Bit22.1.1-16 | Win10 | ListItem not render Properly |
| 2.9.2.0 | WS11WineCX64Bit22.1.1-16 | Win7 | work |

I would like to ask how to run it with `WS11WineCX64Bit23.7.1` or how to properly run with `WS11WineCX64Bit22.1.1-16(Win10)`.

**To Reproduce**
1. Download [WinSCP Portable](https://winscp.net/download/WinSCP-6.3-Portable.zip) and extract it.
2. Set the WineCfg system version to Windows7.
3. Run the program.

**Expected behavior**
![WinSCP_working](https://github.com/Gcenx/WineskinServer/assets/927255/deb9b17a-2889-494a-bece-5b73b4dc2250)

**Screenshots**
| Engine | OS | Result|
| -- | -- | -- |
| WS11WineCX64Bit23.7.1 | Win10 | ![WinSCP_StackTrace_Error](https://github.com/Gcenx/WineskinServer/assets/927255/8c0d8ecf-b7ad-4fff-b2ae-e3a8b05d2a42) |
| WS11WineCX64Bit23.7.1 | Win7 | ![WinSCP_StackTrace_Error](https://github.com/Gcenx/WineskinServer/assets/927255/8c0d8ecf-b7ad-4fff-b2ae-e3a8b05d2a42) |
| WS11WineCX64Bit22.1.1-16 | Win10 | ![WinSCP_Listview_not_visiable](https://github.com/Gcenx/WineskinServer/assets/927255/358ebafd-b05f-4bdb-bf7d-086b89534035)  ![WinSCP_Listview_not_visiable2](https://github.com/Gcenx/WineskinServer/assets/927255/66241bd3-cb0a-40ba-aaf1-b82f9282a9aa) |
| WS11WineCX64Bit22.1.1-16 | Win7 | work |

**LastRunWine.log**
`WS11WineCX64Bit23.7.1`
``` 
❯ cd /Users/xxx/Applications/Wineskin/MyCoolWrapper.app/drive_c
❯ wine  ./Program\ Files/WinSCP-6.3-Portable/WinSCP.exe
wineserver: using server-side synchronization.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00cc:err:environ:init_peb starting L"C:\\Program Files\\WinSCP-6.3-Portable\\WinSCP.exe" in experimental wow64 mode
00cc:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
00cc:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
00cc:fixme:thread:GetThreadUILanguage : stub, returning default language.
00cc:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0012D9C0, 00000000 0012D9E8
00cc:fixme:nls:get_dummy_preferred_ui_language (0x38 0x804 0012D9C0 00000000 0012D9E8) returning a dummy value (current locale)
00cc:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0012D9C0, 03883480 0012D9E8
00cc:fixme:nls:get_dummy_preferred_ui_language (0x38 0x804 0012D9C0 03883480 0012D9E8) returning a dummy value (current locale)
00cc:fixme:wtsapi:WTSRegisterSessionNotification Stub 0001007E 0x00000000
00cc:fixme:uxtheme:BufferedPaintInit Stub ()
00cc:fixme:ver:GetCurrentPackageFamilyName (0012FB40 00000000): stub
0118:fixme:shell:CustomDestinationList_BeginList 02097010 (0449FFF4 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 044A0008): stub
00cc:fixme:thread:get_thread_times not implemented on this platform
00cc:fixme:msg:ChangeWindowMessageFilterEx 0001007E c04c 1 00000000
00cc:fixme:dwmapi:DwmSetWindowAttribute (000100B6, 14, 0012F264, 4) stub
00cc:fixme:win:NtUserFlashWindowEx 0x1b8f320 - semi-stub
00d4:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
00d4:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
00cc:fixme:imm:ImeSetActiveContext (00010076, 1): stub
00cc:fixme:imm:ImmReleaseContext (000500CA, 00010076): stub
00cc:fixme:win:WINNLSEnableIME hwnd 000500CA enable -1: stub!
00cc:fixme:win:WINNLSEnableIME hwnd 000500CA enable -1: stub!
00cc:fixme:win:WINNLSEnableIME hwnd 000500CA enable -1: stub!
00cc:fixme:win:WINNLSEnableIME hwnd 000500CA enable -1: stub!
00cc:fixme:win:WINNLSEnableIME hwnd 000500CA enable -1: stub!
00cc:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 0001007E
00cc:fixme:uxtheme:BufferedPaintUnInit Stub ()
```

`WS11WineCX64Bit22.1.1-16`
```
❯ cd /Users/xxx/Applications/Wineskin/MyCoolWrapper.app/drive_c
❯ wine  ./Program\ Files/WinSCP-6.3-Portable/WinSCP.exe
wineserver: using server-side synchronization.
0024:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0024:fixme:thread:GetThreadUILanguage : stub, returning default language.
0024:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0012D9C0, 00000000 0012D9E8
0024:fixme:nls:get_dummy_preferred_ui_language (0x38 0012D9C0 00000000 0012D9E8) returning a dummy value (current locale)
0024:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0012D9C0, 03A23680 0012D9E8
0024:fixme:nls:get_dummy_preferred_ui_language (0x38 0012D9C0 03A23680 0012D9E8) returning a dummy value (current locale)
0024:fixme:wtsapi:WTSRegisterSessionNotification Stub 00010078 0x00000000
0024:fixme:uxtheme:BufferedPaintInit Stub ()
0024:fixme:ver:GetCurrentPackageFamilyName (0012FB40 00000000): stub
0108:fixme:shell:CustomDestinationList_BeginList 01C8F040 (046B81C4 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 046B81D8): stub
0024:fixme:thread:get_thread_times not implemented on this platform
0024:fixme:msg:ChangeWindowMessageFilterEx 00010078 c04c 1 00000000
0024:fixme:dwmapi:DwmSetWindowAttribute (000100B0, 14, 0012F264, 4) stub
0024:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 0, lp 0
0024:err:listview:LISTVIEW_WindowProc unknown msg 10bd, wp 1280e3c, lp 12f7a0
0024:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 0, lp 0
0024:err:listview:LISTVIEW_WindowProc unknown msg 10bd, wp 1280e3c, lp 12f7a0
0024:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 0, lp 0
0024:err:listview:LISTVIEW_WindowProc unknown msg 10bd, wp 1280e3c, lp 12f7c0
0024:fixme:win:RegisterDeviceNotificationW DBT_DEVTYP_HANDLE filter type not implemented
0024:fixme:imm:ImeSetActiveContext (0x4f4e928, 1): stub
0024:fixme:imm:ImmReleaseContext (00010192, 04F4E928): stub
0024:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 0, lp 0
0024:fixme:win:RegisterDeviceNotificationW DBT_DEVTYP_HANDLE filter type not implemented
00c4:fixme:imm:ImeSetActiveContext (0x37f590, 0): stub
00c4:fixme:imm:ImmReleaseContext (0000000000010020, 000000000037F590): stub
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (04F5E660 0012ED0C 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (0566D2E8 0012EB50 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (04F5E660 0012ED0C 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (05670B00 0012EB5C 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (0566D2E8 0012EB50 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (0566D2E8 0012ED0C 255)
0024:fixme:treeview:TREEVIEW_PrintClient Partial Stub: (hdc=074102A0 options=0)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (0569A290 0012EAE0 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (0574D188 0012E940 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (0574D188 0012EAFC 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (0574D188 0012EAFC 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (0574D188 0012EAFC 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (04F54710 0012F27C 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (04F5FEA0 0012F0C0 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (04F5FEA0 0012F27C 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (04F5FEA0 0012F27C 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (056AFDE0 0012F0CC 255)
0024:fixme:uxtheme:BufferedPaintSetAlpha Stub (056AFDE0 0012F0CC 255)
0024:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 00010078
0024:fixme:uxtheme:BufferedPaintUnInit Stub ()
```

**Comment by emendelson** [comment]
For what it's worth, WinSCP (non-portable) runs perfectly on a wrapper made with Wineskin 2.9.1.1 and WS11WineCX64bit21.2.0. I put this together a few years ago. I made a copy and updated to 22.x and 23.x engines, and the Windows app didn't start at all.

**Comment by niphor** [comment]
@Gcenx   I tried it with wineskin-devel  and indeed it works. 
thank you.


Additionally, I would like to inquire about the latest version of Chrome that can run on WineSkin. 

I'm currently able to run Chrome 90(OS:Win7 with ` --disable-gpu --no-sandbox --disable-software-rasterizer` parameters), but it's too old, and some extensions can't be used properly (such as Bitwarden). 

I've tried some newer chrome versions, but none of them work(GUI not render).

**Comment by niphor** [comment]
ok. thank you

**Comment by niphor** [comment]
test on WS11Wine64Bit9.2 in wineskin-devel.
WinSCP work with `OS:Win10` 

i tested chrome 109 with  `WS11Wine64Bit9.2`  still can't render
![image](https://github.com/Gcenx/WineskinServer/assets/927255/bbc2bdde-feb1-4880-aab4-4b361799241b)

but i got lucky with `--in-process-gpu` parameter, although it still displayed an ugly titlebar and became unresponsive after a while
![image](https://github.com/Gcenx/WineskinServer/assets/927255/b0c717c1-f033-4ea5-8127-112e265bc63e)

I also have another software [notepad2_mod](https://github.com/zufuliu/notepad2), which cannot display any content properly using Direct2D render.
test on WS11WineCX64Bit23.7.1、WS11WineCX64Bit23.7.1、WS11Wine64Bit9.x
on WS11WineCX64Bit22.1.1-16 and lower，it can render sometimes，most time unresponsive and freeze with No main window but a titlebar.

![image](https://github.com/Gcenx/WineskinServer/assets/927255/3c6b2c32-aa53-4049-9213-3ceadf5de852)

**Comment by niphor** [comment]
Yes, GDI works fine. 
Overall,I wish there were fewer bugs in DirectX within Wine.

I have no choice to use Windows Chrome (to login jumpserver) to perform VPS maintenance.
