### ISSUE TITLE
Issues on OS X 10.9

### ISSUE THREAD

**Issue by Wowfunhappy** [Gcenx/WineskinServer#55]
Hello! I'm running OS X 10.9, because it's my favorite OS, and I'm encountering some weirdness with this project.

When I use Wrapper 2.9.0.6, no recent 32bit engine is able to work in Mavericks, but 64bit versions do. Engines confirmed not working include WS11WineCX19.0.1-1, WS9Wine4.20, and WS9Wine5.0, and WS9Wine5.7. Interestingly however, WS9Wine4.0 works fine. Perhaps more notably, WS11WineCX64Bit19.0.1-1, WS9Wine64Bit5.0, and WS9Wine64Bit5.7 also work fine.

This appears to be the problem with the wrapper. If I use Wrapper 2.6.2 from the original/official Wineskin, all of the above 32bit engines work correctly!

I also tried using the prerelease Wineskin Winery with wrapper 2.9.0.7-Beta3. This appears to break _all_ engines, regardless of age or architecture. I tested WS9Wine64Bit4.0, WS9Wine4.0, and WS11WineCX64Bit19.0.1-1.

I know I'm on an old OS, but I would be super grateful if you'd be willing to look into this. Wine is actually a great way to run e.g. Electron apps which do have native Mac versions, but don't themselves support 10.9. Thank you so much!

**Comment by Gcenx** [comment]
Technically the project should function on 10.9.

Only 64Bit Engines working for you seems very strange when using the current release.

Beta3 only functions if you also unpack the provided Runtime, Beta3 doesn’t include an embedded runtime as I wanted help testing a new feature of loading the runtime from another location.

I would advise against using Wineskin-2.6.2 with later Engines especially when attempting to use with WS10 and later engines.

For the time being install XQuartz_2.7.7 or later into your system and use the current wrapper release should get you at least up and running until I’m able to replicate your results and look into a potential fix.

**Comment by Wowfunhappy** [comment]
> For the time being install XQuartz_2.7.7 or later into your system and use the current wrapper release should get you at least up and running

Oh, holy crap, that totally fixed it! I installed XQuartz, then used WS11WineCX19.0.1-1 and everything just worked without a hitch. Thank you!

**Comment by Gcenx** [comment]
Until [Bugzilla 49774](https://bugs.winehq.org/show_bug.cgi?id=49774) is resolved I won’t easily be able to verify if the runtime works correctly for system below macOS 10.13

**Comment by Gcenx** [comment]
I’ve tested running WineCX19.0.1-1 within a clean OSX10.9 VM, the engine ran without issue then tested running Wine5.17 this also ran without issue
