### ISSUE TITLE
"error while listing folder contents: dosdevices doesn't exist"

### ISSUE THREAD

**Issue by SnailPerson** [Gcenx/WineskinServer#558]
**Environment (please complete the following information):**
 - OS: 12.2.1
 - Winery version: Wineskin Winery 2.0
 - Master Wrapper version: 3.0
 - Engine version:WS12WineCX64Bit23.7.1-1
 - Hardware:  iMac (Retina 5K, 27-inch, 2017)
 - Application/Game Name  Wineskin Winery, wrapper creation bug

**Describe the bug**
 After installing wineskin winery via homebrew, i download the latest engine version and updated/installed wineskin 3.0 wrapper. When creating a new blank wrapper, an error pops up (twice) that says: "error while listing folder contents: dosdevices doesn't exist". Pressing OK finishes the wrapper creation. Setting up winetricks is pretty smooth until i try to run my selected winetricks (steam, dxvk, d3dcompiler_47). After hitting "run", the log returns:
`warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "" `
and another "error while listing folder contents: dosdevices doesn't exist" pops up. Nothing is downloaded.

**To Reproduce**
1. Install Wineskin Winery
2. Select and install WS12WineCX64Bit23.7.1-1 engine
3. Update Wrapper to Wineskin 3.0
4. Create a new blank wrapper
5. get error, press OK, let wrapper creation finish
6. open wrapper
7. go to advanced>winetricks
8. select "steam", "dxvk", "d3dcompiler_47" in winetricks
9. hit run
10. get second error

**Expected behavior**
 error-free wrapper and winetricks creation. And some not-missing "dosdevices"...

**Screenshots**

**LastRunWine.log**
 There is no log because nothing can be run because nothing can be installed properly because "dosdevices" doesn't exist.
Pressing "Test Run" after the failed Winetricks-installation attempts returns no log.

**Additional context**

Incorrectly filled out issues will be close without notice!

**Comment by SnailPerson** [comment]
Well that build is gone anyways, so my current issue is the missing dosdevices thing...

**Comment by SnailPerson** [comment]
im going to do a fresh install again, here's how it went.
1. running command `brew uninstall --force --zap wineskin`
2. checking ~/Library/Application Support/Wineskin and dragging the folder into trash
3. checking applications for wineskin winery and trashing it
4. selecting all related files and perma-deleting them within trash

5. running `brew install --cask --no-quarantine gcenx/wine/wineskin`
6. opening wineskin winery
7. install/update wrapper 3.0
8. install WS12WineCX64Bit23.7.1-1 engine
9. Creating a new blank wrapper
10. waited 10 minutes, winery does not respond

**Comment by SnailPerson** [comment]
should i input that command after or before installing wineskin

**Comment by SnailPerson** [comment]
okay
1. reinstalled wineskin
2. reinstalled / ran `brew install gcenx/wine/libinotify-kqueue`
3. opened wineskin winery
4. installed wrapper 3.0 
5. intalled 23.7.1.1-1
6. started creating a new blank wrapper
7. nope 
<img width="259" alt="Bildschirmfoto 2024-03-25 um 22 20 02" src="https://github.com/Gcenx/WineskinServer/assets/97041048/e38519ce-6b05-4c32-953c-60345769d655">

**Comment by SnailPerson** [comment]
programs during wrapper creation
<img width="259" alt="Bildschirmfoto 2024-03-25 um 22 28 21" src="https://github.com/Gcenx/WineskinServer/assets/97041048/ccf971d8-8e58-4165-87b1-c5d6294de65e">

**Comment by SnailPerson** [comment]
when configuring winetricks, it still screams dosdevices at me.
Ive already restarted the device before so that's a dead end also...

**Comment by SnailPerson** [comment]
> Works perfectly here - M2 Mac, Sonoma 14.4.1.

2017 intel mac, Monterey 12.2.1

**Comment by SnailPerson** [comment]
oh hey when building winetricks i get a different error this time.
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message ```
"/Users/USERNAME/Applications/Wineskin/BootlegSteam.app/Contents/Wineskin.app/Contents/Resources/wine: line 45: /Users/USERNAME/Applications/Wineskin/BootlegSteam.app/Contents/Wineskin.app/Contents/Resources/../../../SharedSupport/wine/bin/wine64: cannot execute binary file
/Users/USERNAME/Applications/Wineskin/BootlegSteam.app/Contents/Wineskin.app/Contents/Resources/wine: line 45: /Users/USERNAME/Applications/Wineskin/BootlegSteam.app/Contents/Wineskin.app/Contents/Resources/../../../SharedSupport/wine/bin/wine64: Undefined error: 0" 
```

**Comment by emendelson** [comment]
Tested on a 2015 Intel MacBook Pro running Monterey 12.7.2; worked perfectly. Performed exactly the same steps you performed, created a new wrapper, ran Winetricks to add some apps and fonts. All worked perfectly.

Maybe you should update Monterey from 12.2.1 to 12.7.2??

**Comment by SnailPerson** [comment]
So i updated my software to MacOS Ventura 13.6.6 and now stuff seems to be working again.
Just took two days of it pain and one corrupted harddrive later, but now i can enjoy bootleg steam again.
Thanks for the support!
