### ISSUE TITLE
Engines not working properly

### ISSUE THREAD

**Issue by Good-times-with-Eno** [Gcenx/WineskinServer#565]
When I click more engines, the dropdown becomes more like a code instead of proper dropdown. What is going on?!
![Screenshot 2024-04-03 at 1 43 05 PM](https://github.com/Gcenx/WineskinServer/assets/118423252/ef0b3d3e-40d8-4101-bee8-8e2c5c4fb88d)

**Comment by Good-times-with-Eno** [comment]
I did. Just didn't work...

**Comment by soffchen** [comment]
brew update
brew upgrade

that's all.

**Comment by Good-times-with-Eno** [comment]
Thanks guys, I tried all of the said suggestions and now it works! Yay

**Comment by Good-times-with-Eno** [comment]
Thanks guys, I tried all of the said suggestions and now it works! Yay :D
