### ISSUE TITLE
WineskinLauncher process crashing: Illegal Instruction

### ISSUE THREAD

**Issue by i0ntempest** [Gcenx/WineskinServer#57]
This only occurs on one of my 3 systems, a 9900K hackintosh. Another 2 are a 2018 Mac mini and a ThinkCentre Tiny hackintosh. Seems to be related to libsystem_pthread.dylib. Also, if I delete ~/Library/Caches/com.apple.nsservicescache.plist, the problem temporarily goes away (wineskin apps already created can be run), but if I try creating a wrapper then this file gets created again, the process crashes and the wrapper created is incomplete. Crash log attached.
Help please?

[Archive.zip](https://github.com/Gcenx/WineskinServer/files/5191498/Archive.zip)

**Comment by Gcenx** [comment]
What aversion of macOS is installed on said hackintosh?

What engine were you using exactly?, I’m assuming WineCX19.0.1-1 or some other WS10 engine as you mention libsystem_pthread.dylib

**Comment by i0ntempest** [comment]
OS version is 10.15.6 and I've tried WS11WineCX64Bit19.0.1-1, WS11WineCX6419.0.1-1, WS9Wine64Bit5.7 and WS9Wine5.7. Problem occurred after I moved my system from an iMac. Also I see this in the crash log:
```
Application Specific Information:
BUG IN CLIENT OF LIBDISPATCH: trying to lock recursively
```

**Comment by Gcenx** [comment]
So macOS Catalina, ok if you have homebrew installed could to test my wine-crossover package?

```
brew tap gcenx/wine
brew cask install --no-quarantine wine-crossover
```

It would be handy to see if wine(64/32on64) functions or not as it “should”

**Comment by i0ntempest** [comment]
Sure. Give me a min

**Comment by i0ntempest** [comment]
Tried running a 32bit game I have working in Wineskin, it crashes:
```
wine: Unhandled exception 0xc0000417 in thread 9 at address 0x1007:0x7bc72002 (thread 0009), starting debugger...
```
Also calling wine32on64 on any setup program gives an empty window.

**Comment by Gcenx** [comment]
If your using the `wine-crossover` package call `wine` it’s a wrapper script that handles dylib fallback

**Comment by i0ntempest** [comment]
Then this happens:
```
0009:err:msvcrt:MSVCRT__invalid_parameter (null):0 (null): (null) 6e2f7eff00000000
wine: Unhandled exception 0xc0000417 in thread 9 at address 0x1007:0x7bc72002 (thread 0009), starting debugger...
/Users/Admin/.wine/dosdevices/z:/Applications/Wine Crossover.app/Contents/Resources/wine/bin/winedbg: line 46: /Users/Admin/.wine/dosdevices/z:/Applications/Wine Crossover.app/Contents/Resources/wine/bin/wine: Bad CPU type in executable
/Users/Admin/.wine/dosdevices/z:/Applications/Wine Crossover.app/Contents/Resources/wine/bin/winedbg: line 46: /Users/Admin/.wine/dosdevices/z:/Applications/Wine Crossover.app/Contents/Resources/wine/bin/wine: Undefined error: 0
```

**Comment by Gcenx** [comment]
If you installed via brew just use a stock terminal session as it will install the symlinks I’d configured, using the “Wine Crossover” bundle terminal session will be configured differently

**Comment by i0ntempest** [comment]
I got it to work, it seems this game needs to be run from where it is installed. Also tried:
- installing 64bit WinRAR but the setup exe crashes with "serious error" window
- 32bit WinRAR seems to work fine
- foobar2000 seems to work fine

So what about the WineskinLauncher crash I'm having?

**Comment by Gcenx** [comment]
I’m unable to look at the log until I’m informs of my system, but are you sure it’s WineskinLauncher that’s crashing?, I know Wineskin.app has some issue with the busy spinner.

That plist links back to CoreServices, but it’s strange as I’d tested this version of OSX10.9 > macOS 11 with the occasional Wineskin.app crash on newer versions

**Comment by i0ntempest** [comment]
I think so, or at least the log says so. I have experienced Wineskin.app crash, it's different from this.

**Comment by i0ntempest** [comment]
Any news on this?

**Comment by Gcenx** [comment]
I’m not really sure what’s happening here and why it’s affecting on hackintosh  but not the other, I don’t have access to a hackintosh able system.

**Comment by i0ntempest** [comment]
The weird thing is it only happens on one of my hacks. I'll try again on a fresh OS install soon.
Nevertheless, I'm available to test new builds if there's any.
