### ISSUE TITLE
Winetricks commands seem to be broken

### ISSUE THREAD

**Issue by michael-ziedalski** [Gcenx/WineskinServer#58]
Hello, all. I have been glad to find this unofficial update of Winery, since it allows me to run decently updated Wine Engines while being on my old 10.11.6 rMBP.

At any rate, after installing some programs into a Wineskin 2.9.0.6, Eng. WS11WineCX64Bit19.0.1-1 wrapper, to fix some sound issues I attempted setting `sound=coreaudio` in winetricks. Running that, or in fact any other winetricks, gets me one of two errors (they do seem to alternate randomly)

1 -`wine: cannot find L"C:...` (wine cannot find some critical file within the wrapper)
2 - `wine: Access denied.`

The funny thing is, the official latest Winery ver. (Wineskin 2.6.2, Eng. WS9Win2.22) installs any chosen winetricks correctly.

What could be the reason for this discrepancy?

**Comment by Gcenx** [comment]
If you swap to the version of Winery from pre-release you’ll also get current wine Engines I build source bi weekly, as Winehqs macOS winebuild system was decommissioned from Wine-5.8.

Firstly get the latest master wrapper version from Winery (standard or pre-release) being Wineskin-2.9.0.7-rc1, make a new wrapper and test again.

Updating an older wrapper isn’t recommended, however if your insistent on updating a currently created wrapper you’ll need to do a couple of things;
- Update wrapper to latest version
- Change the engine (selecting the same engine is fine)
- Open the wrappers info.plist and modify the BundleID so it doesn’t contain invalid characters (Winery lists these when selecting an Wrappers name)

**Comment by michael-ziedalski** [comment]
Huh, so this seems like a simple fix. In that case, apologies for asking for this hand-holding, but how would I swap to the version of Winery from pre-release? I downloaded the latest file from this project's link, [here](https://github.com/Gcenx/WineskinServer/blob/master/Winery/WineskinWinery.app.tar.7z), and the latest available Winery ver. and Engine ver. I could see are what I posted.

Also, wouldn't the master wrapper version be what I downloaded above?

**Comment by Gcenx** [comment]
@michael-ziedalski [Wineskin.Winery.tzx](https://github.com/Gcenx/WineskinServer/releases/download/V1.8.4.2/Wineskin.Winery.txz)

Always get the downloads from [releases](https://github.com/Gcenx/WineskinServer/releases) section, the 7z packages are for Winery to download.

If you use homebrew the alternative is;
```
brew tap gcenx/wine
brew cask install --no-quarantine unofficial-wineskin
```

The other advantage of being on the pre-release version of Winery is having WS10 Engines for direct download.

**Comment by michael-ziedalski** [comment]
Homebrew I do know how to use, thank you - I went and reinstalled it like that, and made a new wrapper with WS11WineCX64Bit19.0.1-1 - but at the latest wrapper ver. Wineskin-2.9.0.7-rc1 now - and it seems like I get the same error:

```
...
Executing wine regedit /S C:\windows\Temp\set-sound.reg
wine: Access denied.
------------------------------------------------------
warning: Note: command wine regedit /S C:\windows\Temp\set-sound.reg returned status 5. Aborting
```

The WS9Win2.22 Eng., but with the current wrapper, is still able to run winetricks.

**Comment by Gcenx** [comment]
Strange as its working for me within a 10.9VM

to install into it I got a little lazy

```
curl -OL https://github.com/Gcenx/WineskinServer/releases/download/V1.8.4.2/Wineskin.Winery.txz
```

Then used Keka to unpackaged it and moved the app into my users applications folder, downloaded the wrapper & WS11WineCX19.0.1-1

```
warning: taskset/cpuset not available on your platform!
Executing mkdir -p /Users/gcenx-vm/Applications/Wineskin/WineCX19.0.1-1.app/Contents
Using winetricks 20200412-next - sha256sum: fad7d983b413389590c39d8de38040c2d36a3e374a7c842c4051e11afc8fe44b with wine-4.12.1 and WINEARCH=win32
Executing w_do_call steam
Executing mkdir -p /Users/gcenx-vm/Applications/Wineskin/WineCX19.0.1-1.app/Contents
Executing load_steam 
Executing mkdir -p /Users/gcenx-vm/.cache/winetricks/steam
Executing cd /Users/gcenx-vm/.cache/winetricks/steam
Downloading http://media.steampowered.com/client/installer/SteamSetup.exe to /Users/gcenx-vm/.cache/winetricks/steam
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  7 1536k    7  117k    0     0   207k      0  0:00:07 --:--:--  0:00:07  207k
100 1536k  100 1536k    0     0  2062k      0 --:--:-- --:--:-- --:--:-- 2062k
Executing cd /Users/gcenx-vm/Applications/Wineskin/WineCX19.0.1-1.app/Wineskin.app/Contents/Resources
Executing cd /Users/gcenx-vm/.cache/winetricks/steam
Executing mkdir -p /Users/gcenx-vm/.cache/winetricks/ahk
Executing cd /Users/gcenx-vm/.cache/winetricks/ahk
Downloading https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.0.48.05/AutoHotkey104805_Install.exe to /Users/gcenx-vm/.cache/winetricks/ahk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   650  100   650    0     0   1790      0 --:--:-- --:--:-- --:--:--  1795

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1999k  100 1999k    0     0  1348k      0  0:00:01  0:00:01 --:--:-- 2383k
Executing cd /Users/gcenx-vm/.cache/winetricks/steam
------------------------------------------------------
warning: Cannot find 7z. Using Windows 7-Zip instead. (You can avoid this by installing 7z, e.g. 'sudo apt-get install p7zip-full' or 'sudo yum install p7zip-plugins').
------------------------------------------------------
Executing w_do_call 7zip
Executing mkdir -p /Users/gcenx-vm/Applications/Wineskin/WineCX19.0.1-1.app/Contents
Executing load_7zip 
Executing mkdir -p /Users/gcenx-vm/.cache/winetricks/7zip
Executing cd /Users/gcenx-vm/.cache/winetricks/7zip
Downloading https://www.7-zip.org/a/7z1900.exe to /Users/gcenx-vm/.cache/winetricks/7zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 44 1158k   44  511k    0     0   364k      0  0:00:03  0:00:01  0:00:02  364k
100 1158k  100 1158k    0     0   641k      0  0:00:01  0:00:01 --:--:--  641k
Executing cd /Users/gcenx-vm/.cache/winetricks/steam
Executing cd /Users/gcenx-vm/.cache/winetricks/7zip
Executing wine 7z1900.exe /S
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
Executing cd /Users/gcenx-vm/.cache/winetricks/steam
Executing wine C:\Program Files\7-Zip\7z.exe x Y:\ahk\AutoHotkey104805_Install.exe -oY:\ahk AutoHotkey.exe AU3_Spy.exe

7-Zip 19.00 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 2047357 bytes (2000 KiB)

Extracting archive: Y:\ahk\AutoHotkey104805_Install.exe
--
Path = Y:\ahk\AutoHotkey104805_Install.exe
Type = Nsis
Physical Size = 2047357
Method = LZMA:23
Solid = +
Headers Size = 42403
Embedded Stub Size = 49152
SubType = NSIS-2

Everything is Ok

Files: 2
Size:       259616
Compressed: 2047357
Executing wine y:\ahk\AutoHotkey.exe C:\windows\Temp\steam.ahk
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
------------------------------------------------------
warning: Working around wine bug 22053 -- Disabling gameoverlayrenderer to prevent game crashes on some machines.
------------------------------------------------------
Using  override for following DLLs: gameoverlayrenderer
Executing wine regedit /S C:\windows\Temp\override-dll.reg
```

I'd be interested to know what's the permissions on wine/wine64/wine32on64 within `Wineskin.app/Contents/Resources/`

**Comment by michael-ziedalski** [comment]
So I checked those 3 files just now, and for them Finder reports `Read & Write` privileges for my user account, wheel, and everyone.

I tried installing steam like you did just now with winetricks, and it opens up the Steam install menu and allows all the steps to complete, but on the bottom of the logs there was this,

```
Using  override for following DLLs: gameoverlayrenderer
Executing wine regedit C:\windows\Temp\override-dll.reg
wine: cannot find L"C:\\windows\\system32\\regedit.exe"
------------------------------------------------------
warning: Note: command wine regedit C:\windows\Temp\override-dll.reg returned status 2. Aborting.

```

This does look like some sort of permissions error. Is there any more detailed logs I can find within the wrapper?

**Comment by Gcenx** [comment]
I’m assuming that’s also the case for the real wine binaries within /Frameworks/wswine.bundle/bin?

If those permissions are correct then all I can think is the wrappers wineprefix wasn’t generated correctly.

This can happen with some security software

**Comment by michael-ziedalski** [comment]
The permissions were the same in /Frameworks/wswine.bundle/bin . The only security software on my computer is Endpoint Security, and it is not running aggressively.

While still looking into this, if it is possible, would you be able to upload the winery wrapper that you were testing out? Maybe it could work for me, and I could look for any differences between them?

**Comment by Gcenx** [comment]
Endpoint Security regardless of vender is rather aggressive, it also doesn’t always prompt when quarantining/removing files it finds offensive.

I won’t have chance to bundle up any wrappers anytime soon, I’m hoping to backup/wipe/reinstall my main Mojave install then get macports done.

For the moment you should be able to use Wine versions up-to 4.6? As I believe that’s when mingw was introduced for building PE binaries.

**Comment by michael-ziedalski** [comment]
Will try to compile as late an engine as I can using Wine <4.6, and hope for the best.

Meanwhile, since wrappers can be shared across macs, if you would be inclined to upload the test wrapper you were using, it would not be greatly unappreciated.

**Comment by Gcenx** [comment]
Theres no need to compile Engines from source Winery will handle the repacking of Winehq packages.

Here is a correctly generated wrapper [WineCX19.0.1-1](https://mega.nz/file/mE40hSjA#nfphjAov4mhcuz4VTxFHEv9sWzMB-zJys_rj56UZch8) remove the quarantine flag before unpacking will save some headaches, but I suspect your security software will remove most of the PE binaries without warning causing it to break.
