### ISSUE TITLE
Need to add a wiki section

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#59]
As it seems the same questions/issues keep being opened seem a wiki would be useful

**Comment by Gcenx** [comment]
Added a basic wiki page, so if anyone want to help work on documentation they can do so in a fork and open a pull-request.

**Comment by thmrtnz** [comment]
Hi. I tried my hand at it, but I cannot find a way to open a pull-request which includes wiki modifications.
https://github.com/thmrtnz/WineskinServer/wiki

**Comment by Gcenx** [comment]
@thmrtnz yes it seems GitHub still never added the feature.

This can be done on my end ether via pushing your wiki fork to here or extracting any commits you made as patches then applying using git-am.

**Comment by Gcenx** [comment]
@thmrtnz instead of dealing with the wiki with patches I just replaced the current wiki with the one you written. And merged your pull-request for the issue template thank you for that one also.

**Comment by Gcenx** [comment]
If your interested in doing additional documentation/wiki I could add you to collaborators. If that's something your interested in let me know.

**Comment by thmrtnz** [comment]
Why not, I could tell more in the wiki.

**Comment by thmrtnz** [comment]
@Gcenx I would recommend adding this summary to the About section of the repository.

_Wineskin is a tool used to make ports of Windows softwares to macOS_
