### ISSUE TITLE
Disable Window Chroming Without X11

### ISSUE THREAD

**Issue by SheinH** [Gcenx/WineskinServer#6]
The official wineskin winery had support for disabling mac window chroming. Could this feature be ported into your wineskin version?

**Comment by Gcenx** [comment]
I believe your talking about this
>in winecfg, you turn off the two options for letting the window manager decorate and control windows... its the same option that can be toggled in Wineskin, although older versions of Wineskin had it off by default.

Although I believe that only worked with X11 not macDriver.

I’m not near my system at the moment to verify, but if it functions with macDriver I can add the option to the macDriver screen options menu tab.
