### ISSUE TITLE
TCCD hogs CPU (macOS 10.14.6, Winery 1.8.4.2, WS 2.9.0.7-rc1, WS11WineCX64Bit19.0.1-1)

### ISSUE THREAD

**Issue by ApexMods** [Gcenx/WineskinServer#61]
Hi Gcenx,

First of all a huge thanks for your work on Wineskin. You're a lifesaver! :)

Ran into a nasty issue, though. Testing a Dx9 game under macOS 10.14.6 (Winery 1.8.4.2 September 6th 2020, Wrapper 2.9.0.7-rc1, Engine WS11WineCX64Bit19.0.1-1), exiting the game / wrapper will cause the TCCD authentication daemon to spike to max CPU use forever (until machine shutdown / restart). Resetting TCC.db has no effect. My guess is that the new code-signed (but not notarized?) wrapper is causing the issue. In my case the wrapper is over 100 GB large, and Gatekeeper seems to try (and fail) "verifying" the whole thing again (and again).

I should mention that I only got the wrapper working by recursively stripping it of quarantine attributes ("xattr -rsd com.apple.quarantine "), which seemed odd with the code signature in place. It also looks like rsync (v3.2.3) fails to copy the wrapper's Frameworks folder, possibly also related to code-signing (your ObjectiveC_Extension).

An older 2.9.0.6-1 wrapper created with Winery 1.8.4 does not cause these issues, but I cannot rebuild that one, as now it seems 2.9.0.7-rc1 is the only one available.

As I need the wrapper for distribution, turning off SIP isn't an option. (Although that whole code-signing and notarizing thing is utter micro$oftian bull$hit from Apple - Steve is turning in his grave. /rant)

**Comment by Gcenx** [comment]
This indeed sounds strange.

How did you get the game files onto the Mac?, as all browsers add a quarantine flag causing anything installed to also receive the quarantine flag.

The current master wrapper shouldn’t be code-signed, the reason it’s not shipped code-signed/notarized currently is the moment the info.plist is altered in anyway this become invalid. That also caused the wrapper to be unable to request permissions.

The contents of Frameworks should also all be unsigned bar libMoltenVK.dylib as that’s from the VulkanSDK that’s already code-signed/notarized.

If you really want to use an older wrapper version (I really advice against this it will corrupted the users tccd and its BundleID might change on each launch) you can crag it via `curl -LO https://github.com/Gcenx/WineskinServer/blob/29a1803563a5a8ed2854f67e7fe553a1ede5b688/Wrapper/Wineskin-2.9.0.6-1.app.tar.7z` unpack using 7z in terminal.

Wineskin.app and Winery.app both contain the binary if your intending to avoid brew/port

At the moment I’ve been dealing with some other things, but the intention is to get this working by possibly embedding an info.plist directly into WineskinLauncher along with a static build of ObjectiveC_extensions that can then be code-signed/notarized thus leaving the wrapper modifiable (I hope)

**Comment by Gcenx** [comment]
Here is a possible workaround to this issue.

After you’ve gotten the wrapper setup as needed without quarantine flags, 

- launch Wineskin.app and use “winecfg”
- Remove “Z” from drive mounting
- Exit winecfg/Wineskin
- Create a pkg installer
- have pkg installer launched using “open” menu option

You might possibly need to add a script after the install phase to remove the quarantine flag (unsure if required)

**Comment by ApexMods** [comment]
Thanks for the quick response. The game files are local, but I test with archive downloads on remote machines (macOS 10.14. and 10.15). Everything gets even more complicated when 7z-compressing with Keka (there's a whole other quarantine issue involved there), but I digress. Anyhow, stripping quarantine has become the norm for distribution already, as users are fed up with that Gatekeeper nuisance (heck, on 10.15 it even tells users to trash the "broken" file, if it can't find a code signature).

Yeah, I had already tried removing the Z: link, but to no effect. If there are no code signatures in the 2.9.0.7-rc1 wrapper, I'll try rebuilding the whole thing again. The constant change in BundleID annoys to no end, so it's worth another shot. BTW, additional testing showed TCCD running wild as soon the wrapper is launched, not only after it exits. This also drags performance down to unacceptable levels.

**Comment by ApexMods** [comment]
Tried again with a fresh clean 2.9.0.7rc1 wrapper built. Same issue on 10.14 and 10.15: tccd runs at 100 percent CPU whenever the wrapper is launched, and it won’t stop until the machine is rebooted. I refreshed the wrapper, recursively cleared quarantine on it, gave it full disk access, reset tcc.db - all to no avail.

**Comment by ApexMods** [comment]
Well, I've tried everything, and finally gave up on wrapper version 2.9.0.7rc1. Although I somehow got the tccd issue to go away on 10.15.7 Catalina, nothing I tried on 10.14.6 Mojave works. Whenever the 2.9.0.7rc1 wrapper is launched, tccd ramps up to max CPU use and starts reading disk data at max speed. I stopped it just shy of a terabyte by rebooting the machine, as nothing else will get tccd to quit. All this time, it was vomiting errors e.g. about WineskinLauncher into the system log.

Found a working download for wrapper 2.9.0.6-1 on GitHub (sorry Gcenx, your curl address links to a non-working 75kb file), planted that into Winery's application support and rebuilt the game wrapper from scratch with 2.9.0.6-1 following the exact same procedure and settings as the 2.9.0.7rc1 one, and the tccd issue went away immediately.

**Comment by rfperuch** [comment]
Hi @ApexMods I had the tccd issue before but for now using the latest release it's not a problem anymore, at least on High Sierra and Catalina (I din't test it on Mojave, yet). The only additional step that I do (and I tell all those download my wrapper to do the same) is setting `xattr -crs MyCoolWrapper.app` right after download and install it at Applications folder. I'll test on Mojave to see if it bother me.
If you upload your wrapper (empty, without the 100GB game :D) I can test it on my machine if the tccd is invoked.

**Comment by ApexMods** [comment]
Thanks, @rfperuch, but I already strip the wrapper of all Apple junk like extended attributes, ACLs, DS_Store, etc. before packing it, and I include a tool to strip com.apple.quarantine after download and unpacking. On Mojave (tested on various machines), the tccd issue remains for the 2.9.0.7rc1 wrapper, no matter what I do, so I reverted back to 2.9.0.6-1. I don't know which change in the latest release candidate triggers tccd to freak out on 10.14, but it does, and there seems no way to fix it on the end user side.

**Comment by Gcenx** [comment]
What’s strange is I’m running Mojave with sip enabled and don’t have tccd cpu spiking even on this fresh install.

Also PaulTheTall said the current wrapper resolved tccd cpu spiking for them with PortingKit, but couldn’t update to the current wrapper due to some Ports still not been upgraded to newer Engines.

**Comment by ApexMods** [comment]
The **tccd spike on Mojave** was **solved in 2.9.0.6-1**, but it **returned with 2.9.0.7rc1**.

I've tested 2.9.0.7rc1 on several Macs, did a clean install of Mojave on one of them. Still, tccd went nuts.

Built yet another new wrapper based on 2.9.0.6-1, exact same setup, no issues with tccd.

**Comment by Gcenx** [comment]
I’ve dug into this more and managed to recreate this on macOS Mojave (but I needed to disabled SIP to get the issue)

I’ve found a possible workaround for the issue but I’ll need to also test this doesn’t cause issues on macOS Catalina permission prompts.

If your interested I can prove a link for the modified wrapper later so you can confirm if that resolved the issue on your end, but this current workaround will cause the min macOS version to become 10.11.

**Comment by Gcenx** [comment]
@ApexMods here's the modified wrapper [Wineskin-2.9.0.7-rc2](https://mega.nz/folder/3VoCDZRB#_Oq5HepcMpAQgTjG-wNfNA) this uses a workaround for WineskinLauncher that should help avoid the constant tccd hogging

**Comment by Gcenx** [comment]
@ApexMods this should be resolved in Wineskin-2.9.0.7-rc2, this newer wrapper requires replacing Winery with the newer version under the pre-releases section I uploaded earlier
