### ISSUE TITLE
Certain Files Show Up As Trojans

### ISSUE THREAD

**Issue by alexis-evelyn** [Gcenx/WineskinServer#62]
https://www.virustotal.com/gui/file/0041f16c85ee30dbd1272ca676c24cb5b7eb44c6fc171341a2dea80703d3b57f/detection

**Comment by emendelson** [comment]
There's no way to do anything about this. Wine goes very deeply into the OS, and will always trigger false positives.

**Comment by alexis-evelyn** [comment]
That sucks. I thought to let you know anyway. Thanks!
