### ISSUE TITLE
help me on this problem thanks

### ISSUE THREAD

**Issue by miistesure** [Gcenx/WineskinServer#63]
im trying to download among us and this happened 
https://gyazo.com/3216fcba5a2531d76d10b1581426ed11
the create blank wallpaper doesn't allow me to access it nor click on it
is this a bug or did I do something wrong?
thanks

**Comment by Gcenx** [comment]
You need to click “Update” button to download the master wrapper

**Comment by miistesure** [comment]
thanks dude ill let you know if I need help again 👍
