### ISSUE TITLE
No new executables found!

### ISSUE THREAD

**Issue by NxthanWasTaken** [Gcenx/WineskinServer#66]
Hey! I tried every other app, from Roblox's Executable, Notepad++, Steam, Minecraft Executables, to Finobe. Because Winenobe (Windows command line to Mac command line converter for Finobe) wasn't able to open since it's 32bit. I tried dragging executables in to drive_c, nothing happens but this nightmare warning sign.

_No new executables found! Maybe the installer failed...? If you tried to install somewhere other than C: drive (drive_c in the wrapper) then you will get this message too.  All software must be installed in C: drive._

And Roblox+Finobe's installer are special cause I can't just force them where to install. What's the deal about this? I'm on MacOS Catalina with WS11WineCX**64Bit**19.0.1-1.

**Comment by Gcenx** [comment]
You need to provide additional information as 32Bit applications and games are known to run using WineCX19.0.x engines on macOS Catalina 10.15.4 and greater patches, lower versions require SIP to be disabled this is explain in the README.md.

Here’s one of my own comments with a screenshot showing me installing Diablo 2 using wine32on64 before I’d even updated Wineskin to make use of it https://github.com/Gcenx/WineskinServer/issues/23#issuecomment-568775519
