### ISSUE TITLE
sh: winetricks: command not found

### ISSUE THREAD

**Issue by mePy2** [Gcenx/WineskinServer#67]
```
sh: winetricks: command not found



 Winetricks Commands Finished!!
```

**Comment by Gcenx** [comment]
You need to be connected to the internet for Wineskin.app to download winetricks from github the first time the Winetricks menu is launched

**Comment by mePy2** [comment]
> You need to be connected to the internet for Wineskin.app to download winetricks from github the first time the Winetricks menu is launched

I am connected to the internet to be honest.
Anyway, I am going to create a new wrapper just now. I will let you know. Thank you

**Comment by mePy2** [comment]
It worked thank you.

I tried to install `directplay`. It does something but still the check in the "Installed" column does not appear. Can you help me?
Closing this anyway.

**Comment by Gcenx** [comment]
Installed hasn't worked for a while now but not something I've really looked into fixing

**Comment by mePy2** [comment]
Oh, understood.

Well, so an issue about installed should be made eventually.
