### ISSUE TITLE
DXVK support?

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#68]
I’d like to gage the level of interest in DXVK for macOS.

I’ve had the DXVK dlls built for a while now and recently forked [MoltenVK](https://github.com/Gcenx/MoltenVK) & added the DXVK related patches on top of the current release then built the package using GitHub CL producing MoltenVK v1.1.1 with the patches needed to use the custom DXVK on macOS.

My concerns are as this version of MoltenVK is required to fake unsupported extensions (to keep DXVK happy) this could cause other Vulkan application/games to launch and crash instead of just failing to start, as this isn’t ideal I’m concerned providing this by default is a good idea or not.

**Comment by nsklaus** [comment]
make it available as an option / experimental builds. people will test if it provide any improvements then the results will speak for themselves after a while.

**Comment by Rastafabisch** [comment]
@Gcenx I think somewhere I read you yourself mentioning, that rather than stubbing in those features within MoltenVK, it might be possible avoiding declaring them altogether in the already modified DXVK source. Have you looked into this some more?

**Comment by Gcenx** [comment]
@Rastafabisch I haven’t really looked into that, since I have the M1 Mac mini on hand my focuses of getting Wineskin working within Rosetta2 first.

Once that’s working ok I’ll take a look if that’s possible, but I’m not sure if it’s possible as Chip Davis didn’t do this.

**Comment by Gcenx** [comment]
I’ve included DXVK support in the new pre-release master wrapper m, this requires an updated version of Winery due to internal changes. See #65 or read the pre-release sections notes.
