### ISSUE TITLE
issue using the program 

### ISSUE THREAD

**Issue by mosterlonnne** [Gcenx/WineskinServer#69]
im am a dummy in all of this but it seems to me when i download these files they are all just documents with different text on them. can anybody help me out i just need the program for a game.

**Comment by Gcenx** [comment]
You need to first download [Wineskin Winery](https://github.com/Gcenx/WineskinServer/releases/download/V1.8.4.2/Wineskin.Winery.txz) extract it and launch using secondary click and selecting “Open” and allowing or have Gatekeeper disabled.

From there you will need to update the master wrapper and download an Engine that will be used to create your blank wrapper.

Once a blank wrapper is created your able to install an application or game into it, while you could install multiple it’s usually not recommended as some workarounds that make game1 work might break game2 etc

**Comment by mosterlonnne** [comment]
Hi man i just wanted to say thank you, i think i got it all figured out now, atleast on the winery part. crazy quick response time!!.
now im just hoping this setup thing is gonna work :))

**Comment by mosterlonnne** [comment]
hi so im pretty sure this is in no way related to your work but i was wondering if you have any idea how to go forward. im getting stuck on installing net framework 4.5.2 and 4.6.2.  
again this isnt really your area so no worries, but hey might aswell try, you seem like you know more than me

**Comment by Gcenx** [comment]
.Net is annoying at best, it’s best to skip pint releases I’ve found so say you need 4.5.2 install 4.6 instead, if you need 4.6.2 get 4.7 or 4.8 etc. Just be aware that dotnet will take a long while to install.

To cover most cases check dotnet35 (needed for some older applications/games) and dotnet48 this will cover almost all use cases where dotnet requirements are concerned.

**Comment by Gcenx** [comment]
I should say you need to install these from the provided Winetricks menu

**Comment by mosterlonnne** [comment]
mybe i am still doing it wrong but i tried downloading this  https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer through the setup installer in wineskin winery and it still gets stuck, maybe i just gotta wait it out?

**Comment by Gcenx** [comment]
The actual steps are as follows;
- Second click the wrapper and select “view contents”
- Enter the Contents directly
- Launch “Wineskin”
- Click Advanced (opens to a larger menu”
- Click the second tab (advanced?)
- Click the “Winetricks” button
- It will auto download the latest version of winetricks from GitHub
- Select what you want to install
- Click install
- Wait
- Done

**Comment by mosterlonnne** [comment]
okay it has been downloading for awhile now, should i just assume it to be a long wait or is there maybe some corrupted files stopping ? it has been about 40 30 mins now.

its stuck on: 
Using native override for following DLLs: mscoree
Executing wine regedit /S C:\windows\Temp\override-dll.reg
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg
Executing touch /Users/maxjensen/Desktop/WOWPR.app/Contents/Resources/dosdevices/c:/windows/dotnet48.installed.workaround

**Comment by Gcenx** [comment]
The downloading can take a while but next time you need to install the same version of dotnet this will be skipped.

It can take a long time to finish installing dotnet that’s why I says it’s a PITA, but since you see dotnet48.installed.workaround it’s properly just cleaning up temp files.

As long as there wasn’t a stray crash process from before you started winetricks installing dotnet you should be fine

**Comment by mosterlonnne** [comment]
okay thank you so much, very nice of you to be doing this ekstra work:)))

**Comment by mosterlonnne** [comment]
okay so it seems to have worked, i closed the dotnet 48 thing and when i try to run the setup.exe thingagain it has installed the 4.52 and 4.6.2. so thats great. now it is just stuck on ''wineskin is currently busy, please wait''. i think i got it all figured out, thanks again

**Comment by mosterlonnne** [comment]
okay so it seems to be stuck on the busy screen. do you have any clue if this message from the dotnet48 installler thing might be something to be looked into?

------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
if you dont know or dont care its all good you have been more than helpfull

**Comment by Gcenx** [comment]
Reboot then trash the wrapper you created before.

Make a new blank wrapper and only install dotnet48 (this contains dotnet40 to dotnet48) using the winetricks menu.

Some wine version (Engines) can have issues installing some versions of dotnet even when using winetricks.
