### ISSUE TITLE
Problem with an exe file on M1

### ISSUE THREAD

**Issue by Cryseisin** [Gcenx/WineskinServer#75]
Hello!

I used to run this game on my early 2015 Macbook Pro using Wineskin without many problems (configuring it was tricky but it always worked fine). Now I changed my Mac with a new M1 one, I updated Wineskin to the latest version, but when it runs, it basically crashes immediately.

![](https://i.imgur.com/SlGRzKA.png)

I both updated the wrapper and tried with different engines (namely 64bit 19 and 20).
This is what the run log shows, can someone help me?

Thank you!

**Comment by Gcenx** [comment]
What game are you attempting to run?

**Comment by Cryseisin** [comment]
It's a pokemon fangame, Pokemon Insurgence

Thank you!

**Comment by VittorioBase** [comment]
same thing

**Comment by Gcenx** [comment]
Closing in favor of #74 as this is a duplicate.
