### ISSUE TITLE
M1 MBA Wine issues

### ISSUE THREAD

**Issue by tomparonett** [Gcenx/WineskinServer#76]
Hi so I'm newer to all of this type of stuff. I've noticed from the Initial Apple Silicon support that the rc2 wrapper version of this seems to run CX19 on M1 machines with minimum issues aside from the ones mentioned. However where I'm having a problem is that in my wrapper version it's saying it's version is rc1 and not rc2, and does not allow me to update. I've even re-downloaded all of the files from here, deleted the ones I had and emptied my trash. Tried again, not working. I've also gone into the wrapper folder and deleted "Wineskin-2.9.07-rc1.app.tar.7z" re launched, still the same. Says Rc1 wrapper version, so I said ok, and used archive utility.app to unzip wineskin-2.9.0.7-rc2.app.tar.7z and it produces another wine.app file, which when launched my system says it's broken and to delete. I'm very sorry if this is a very stupid question, but I'm quite lost.

**Comment by tomparonett** [comment]
to be clear when I say "not working" I'm referring to creating a wrapper under Ws11WineCX19.0.1-1, and using it to attempt to install steam.exe which just says "wine skin is busy" endlessly I also went into the wrapper I created and went to - Advanced---tools--"Wrapper Tools"--- update wrapper. 
This prompts a message saying: "Your wrapper version matches the master wrapper version.. no update needed. Do you want to force an update? I selected yes.
Another pop up- "Are you sure you want to do this update? It will change out the wrappers main wineskin files with newer copies from whatever mast wrapper you have installed with wineskin winery. The following files/folders will be replaced in the wrapper..."
I selected Yes and noting really changed so Idk

**Comment by Gcenx** [comment]
For Rosetta2 comparability check [pre-release](https://github.com/Gcenx/WineskinServer/releases/tag/V1.8.4.2) I’ve explained the situation and requirements.

Never manually download the master wrapper nor run it directly it won’t work and will then break it completely.

Download the newer version of Winery and to ensure no issues run the following command via terminal before extracting the archive.

```
xattr -drs com.apple.quarantine ~/Downloads
```

The above command will remove the quarantine flag from anything within your users Downloads directory, then extract the archive and replace the current version of Winery with the newer one.

Don’t extract using keka or any other third-part extraction utility or that will again add the quarantine flag.

Update the master wrapper via Winery and use any WS11 Engine, when prompted grant Winery/Wineskin the requested permissions to avoid issues.

**Comment by tomparonett** [comment]
Thank you for responding, I knew there was probably a simple fix thank you.

**Comment by tomparonett** [comment]
I've reviewed the pre release information, and I did what you said however I am still running into the same problem winery doesn't give me the option to update, the update button is grayed out. I am not sure what I'm missing

**Comment by Gcenx** [comment]
Enter the follow directory `~/Library/Application Support/Wineskin/Wrapper`

And delete the contents, then open Winery again and let it download Wineskin-2.9.0.7-rc2 master wrapper.

**Comment by tomparonett** [comment]
Im sorry I am unable to locate this directory. Should I be going to this through finder, or through terminal? 
I attached a screen shot for reference I hope it is visible... 
<img width="864" alt="Screen Shot 2021-01-07 at 12 10 18 PM" src="https://user-images.githubusercontent.com/75903045/103922120-52af0e80-50e1-11eb-983c-c18a9335188e.png">

**Comment by Gcenx** [comment]
Use finders “go to” function and copy/paste the command it will open the directory for you.

Your screenshot seems to show the system level directory where your wanting your users version `~/` means your user

**Comment by tomparonett** [comment]
Thank you when I had gone into my user which is "tomparonett" and go to applications, there is nothing in that folder. But using the go to function worked. I deleted it and selected update now however it is only allowing me to download rc1 and not rc2 :(

**Comment by tomparonett** [comment]
For reference: 
https://user-images.githubusercontent.com/75903045/103923230-d9b0b680-50e2-11eb-8636-234084f1c3b9.mov

**Comment by Gcenx** [comment]
Your using the wrong copy of Wineskin Winery. You need to have downloaded this one https://github.com/Gcenx/WineskinServer/releases/download/V1.8.4.2/Wineskin.Winery.txz

**Comment by tomparonett** [comment]
Ugh Okay, I thought I had the v1.8.4.2 downloaded, I suppose it must have been a seperate file from the main one. Thank you.
A bit of a funny situation I was playing around in the wrappers in the previous version and went to the settings and what not and you now how it shows like: c:/nothing.exe I used the browse function to put internet explorer there, then clicked "test" it suceeded than launched internet explorer and I was able to page to the steam website, download the installer and run it, and install it. I was also able to log into it, however after that it would not load the steam program when logged into. Not sure if something like that is intended, but I did that. 

 Now I have been able to install steam. with the updated version after the install it populated a message saying wineskin is unable to something or other and made me select which .exe file to run I selected steam.exe and hit ok. Went into the settings saw the c:/...steam.exe  closed the wrapper. Reopened from my applications page, the wrapper however no longer opens or functions. :( I will try again perhaps selecting a different steam exe file

**Comment by tomparonett** [comment]
I tried the steamx86.exe install file, wineskin crashes. I'm not sure how to get the file to run... now after I close out of the wrapper and attempt to open it... it doesn't how do I get back into the wrapper to configure its settings?

**Comment by Gcenx** [comment]
Hold down Shift while launching or do “Show Contents” and navigate inside until you done “Wineskin” as that’s the configuration utility.

**Comment by tomparonett** [comment]
I've done everything I an within my knowledge to try to figure out how to get this to work. I even tried the cx20 wrapper, it does the same thing as the 19 wrapper. I'm able to install run, and log in and after logging in nothing launches. 
Is there a known solution to something like this? I appreciate all of your help

**Comment by Gcenx** [comment]
Try something other then Steam as that’s known to sometime have issues, but it usually logins in and only shows a task tray icon so check for that.

Im currently having someone confirm some of my Rosetta2 findings, they haven’t testing Steam again yet but I have seen a post on Reddit saying it wasn’t working within PortingKit so maybe Valve broke thing again.

**Comment by tomparonett** [comment]
Ahh Okay thank you, what Im specifically trying to download is only available through steam at the moment. Not really sure what else to try at the moment I'll stay updated on the status though.

**Comment by Gcenx** [comment]
The issue with Steam not opening was a problem with gmp, this was resolved with rc4.

I recommend trashing the current wrapper you created and make a new one using the latest master wrapper, once created install Steam using winetricks and you should be set for the basics.

**Comment by ickam** [comment]
Hi,
Sorry to come on someone else's issue, but I have a problem with the windows version of Sims 4 on M1 mba.
The errors that I get from the test run are as follow:
`000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0019:err:plugplay:load_function_driver AddDevice failed for driver L"winebus", status 0xc0000002.
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0025:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:ver:GetCurrentPackageId (0x23dd80 0x0): stub
0029:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv4 not supported in this platform
0009:fixme:thread:SetThreadIdealProcessor (0xb0): stub
0009:fixme:thread:SetThreadIdealProcessor (0xb8): stub
0029:fixme:ntdll:EtwRegisterTraceGuidsW (0x3b46b324, 0x0, {f7b697a3-4db5-4d3b-be71-c4d284e6592f}, 7, 0x3b49d9c0, (null), (null), 0x3b4a1300): stub
0029:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {72b14a7d-704c-423e-92f8-7e6d64bcb92a}
0029:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2091f8a-1e0a-4731-84a2-0dd57c8a5261}
0029:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e8a3bf1f-a86b-4390-9c60-5390b969d22c}
0029:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {5727a00f-50be-4519-8256-f7699871fecb}
0029:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {7e854ec7-cdc4-405a-b5b2-aaf7c9e7d40c}
0029:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {79a60dc6-5fc8-4952-a41c-1163aeec5eb8}
0029:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {2718d25b-5bf5-4479-8e88-babc64bdbfca}
0029:fixme:process:GetNumaHighestNodeNumber (0xaaeea0): semi-stub
0009:fixme:thread:SetThreadIdealProcessor (0xdc): stub
0009:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
0009:fixme:msvcrt:MSVCRT__set_abort_behavior _WRITE_CALL_REPORTFAULT unhandled
0009:fixme:thread:SetThreadIdealProcessor (0x18c): stub
0009:fixme:thread:SetThreadIdealProcessor (0x194): stub
0009:fixme:thread:SetThreadIdealProcessor (0x240): stub
0009:fixme:win:RegisterDeviceNotificationW (hwnd=0x1004c, filter=0x23f4b8,flags=0x00000000) returns a fake device notification handle!
0009:fixme:d3d:wined3d_guess_gl_vendor Received unrecognized GL_VENDOR "Apple". Returning GL_VENDOR_UNKNOWN.
0009:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Apple". Returning HW_VENDOR_NVIDIA.
0009:fixme:d3d:select_card_handler Couldn't find a suitable card selector for GL vendor 0000 (using GL_RENDERER "Apple M1")
0009:fixme:d3d:wined3d_guess_gl_vendor Received unrecognized GL_VENDOR "Apple". Returning GL_VENDOR_UNKNOWN.
0009:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Apple". Returning HW_VENDOR_NVIDIA.
0009:fixme:d3d:select_card_handler Couldn't find a suitable card selector for GL vendor 0000 (using GL_RENDERER "Apple M1")
0009:fixme:d3d:wined3d_guess_gl_vendor Received unrecognized GL_VENDOR "Apple". Returning GL_VENDOR_UNKNOWN.
0009:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Apple". Returning HW_VENDOR_NVIDIA.
0009:fixme:d3d:select_card_handler Couldn't find a suitable card selector for GL vendor 0000 (using GL_RENDERER "Apple M1")
0009:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0009:fixme:wbemprox:enum_class_object_Next timeout not supported
0009:fixme:d3d:wined3d_guess_gl_vendor Received unrecognized GL_VENDOR "Apple". Returning GL_VENDOR_UNKNOWN.
0009:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Apple". Returning HW_VENDOR_NVIDIA.
0009:fixme:d3d:select_card_handler Couldn't find a suitable card selector for GL vendor 0000 (using GL_RENDERER "Apple M1")
0009:fixme:d3d:wined3d_guess_gl_vendor Received unrecognized GL_VENDOR "Apple". Returning GL_VENDOR_UNKNOWN.
0009:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Apple". Returning HW_VENDOR_NVIDIA.
0009:fixme:d3d:select_card_handler Couldn't find a suitable card selector for GL vendor 0000 (using GL_RENDERER "Apple M1")
0009:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:err:avicap:query_video_device Video 4 Linux support not enabled
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:d3d:debug_d3dformat Unrecognized 0x5a574152 (as fourcc: RAWZ) WINED3DFORMAT!
0009:fixme:d3d:wined3d_get_format Can't find format unrecognized (0x5a574152) in the format lookup table.
0009:fixme:thread:SetThreadIdealProcessor (0x374): stub
003d:fixme:thread:SetThreadIdealProcessor (0x380): stub
003d:fixme:thread:SetThreadIdealProcessor (0x384): stub
0009:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv6 not supported in this platform
0009:fixme:thread:SetThreadIdealProcessor (0x428): stub
0045:fixme:thread:SetThreadIdealProcessor (0x4b0): stub
0045:fixme:thread:SetThreadIdealProcessor (0x4b8): stub
0009:fixme:thread:SetThreadIdealProcessor (0x4e4): stub
0048:fixme:thread:SetThreadIdealProcessor (0x4d8): stub
003c:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
003c:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #1:
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:6: extension 'GL_ARB_uniform_buffer_object' is not supported
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:8: extension 'GL_EXT_texture_array' is not supported
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:9: extension 'GL_ARB_draw_instanced' is not supported
003c:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #2:
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:6: extension 'GL_ARB_uniform_buffer_object' is not supported
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:8: extension 'GL_EXT_texture_array' is not supported
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:10: extension 'GL_ARB_fragment_coord_conventions' is not supported
003c:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #3:
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: Output of vertex shader 'ffp_varying_fogcoord' not read by fragment shader
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: Output of vertex shader 'ffp_varying_specular' not read by fragment shader
003c:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #5:
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:6: extension 'GL_ARB_uniform_buffer_object' is not supported
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:8: extension 'GL_EXT_texture_array' is not supported
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:9: extension 'GL_ARB_draw_instanced' is not supported
003c:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #6:
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:6: extension 'GL_ARB_uniform_buffer_object' is not supported
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:8: extension 'GL_EXT_texture_array' is not supported
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: 0:10: extension 'GL_ARB_fragment_coord_conventions' is not supported
003c:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #7:
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: Output of vertex shader 'ffp_varying_fogcoord' not read by fragment shader
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: Output of vertex shader 'ffp_varying_diffuse' not read by fragment shader
003c:fixme:d3d_shader:print_glsl_info_log     WARNING: Output of vertex shader 'ffp_varying_specular' not read by fragment shader
0045:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
0045:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
0045:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
0045:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
wine: Unhandled illegal instruction at address 0x1800871e8 (thread 0045), starting debugger...
0045:err:seh:start_debugger Couldn't start debugger ("false") (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger
`

**Comment by Gcenx** [comment]
@ickam your issue isn’t related to this one, according to the log it seems Sim4 isn’t happy with the version of OpenGL that’s being provided. As there’s a native macOS version of sims4 (I know it’s missing dlc) you’d be better using that one.

**Comment by podycust** [comment]
> @ickam your issue isn’t related to this one, according to the log it seems Sim4 isn’t happy with the version of OpenGL that’s being provided. As there’s a native macOS version of sims4 (I know it’s missing dlc) you’d be better using that one.

Both the windows and Mac versions have the same DLC its just the console version that lag behind

**Comment by ickam** [comment]
I didn't realise the dlcs purchased on Windows would still work on mac without repurchasing, so hence I tried to use wineskin instead.

**Comment by Gcenx** [comment]
> Both the windows and Mac versions have the same DLC its just the console version that lag behind

Really?, I don’t own the game but I’d been told before that wasn’t the case. If that’s the case then there’s really no point in playing Sim4 via Wineskin on the newer versions of macOS/M1
