### ISSUE TITLE
How to apply themes

### ISSUE THREAD

**Issue by Dopeboyy** [Gcenx/WineskinServer#78]
i know you can apply msstyle themes to wine. how can you apply themes to this.

**Comment by Gcenx** [comment]
You do it the same way as wine.

Launch Winecfg and use the "Install theme" button
![Screen Shot 2021-01-10 at 1 25 34 PM](https://user-images.githubusercontent.com/38226388/104131875-5f34a080-5347-11eb-94f7-d91d5dd4d839.png)

**Comment by Dopeboyy** [comment]
> You do it the same way as wine.
> 
> 
> 
> Launch Winecfg and use the "Install theme" button
> 
> ![Screen Shot 2021-01-10 at 1 25 34 PM](https://user-images.githubusercontent.com/38226388/104131875-5f34a080-5347-11eb-94f7-d91d5dd4d839.png)

Where is a good place to find good themes for this. And is there any compatibility issues for certain themes? I know i should be looking for msstyle files.

**Comment by Gcenx** [comment]
Not sure as I don't use themes on wine

**Comment by Dopeboyy** [comment]
> Not sure as I don't use themes on wine

Is it possible to install wine-staging? To get the staging gtk theme feature?

**Comment by Gcenx** [comment]
I don’t build wine-staging with gtk and the depreciated Winehq wine-staging also weren’t built with gtk

**Comment by Dopeboyy** [comment]
> I don’t build wine-staging with gtk and the depreciated Winehq wine-staging also weren’t built with gtk

Thats a bummer thanks for the help man.

**Comment by Gcenx** [comment]
If your interested in building wine you can make use of my Macports overlay [macports-wine](https://github.com/Gcenx/macports-wine)

**Comment by Dopeboyy** [comment]
> I don’t build wine-staging with gtk and the depreciated Winehq wine-staging also weren’t built with gtk

What should i tick in winetricks to make my UI/experience be the best. Just for it to look/behave good. 

I have fontsmooth rgb, all fonts, win10 turned on. Anything else that would make the program i am running behave good

**Comment by Dopeboyy** [comment]
> If your interested in building wine you can make use of my Macports overlay [macports-wine](https://github.com/Gcenx/macports-wine)

I have no idea what to do with that honestly bro lol. 
![Screen Shot 2021-01-10 at 1 34 19 PM](https://user-images.githubusercontent.com/28695977/104136069-cef75b00-5348-11eb-8c7d-857a588ca862.png) but here's a screenshot of my app. the text seems a little off. any ideas on how I could make it better?

**Comment by Dopeboyy** [comment]
> > If your interested in building wine you can make use of my Macports overlay [macports-wine](https://github.com/Gcenx/macports-wine)
> 
> I have no idea what to do with that honestly bro lol even though I would love to try out gtk
> ![Screen Shot 2021-01-10 at 1 34 19 PM](https://user-images.githubusercontent.com/28695977/104136069-cef75b00-5348-11eb-8c7d-857a588ca862.png) but here's a screenshot of my app. the text seems a little off. any ideas on how I could make it better?

**Comment by Gcenx** [comment]
Maybe install `corefonts` via winetricks, mostly fonts never seem to look to great within wine and the font smoothing settings are applied by default within Wineskin.

An alternative is enabling Retina Mode checkbox.

As this isn't an actual Wineskin issue I'll close it but won't lock it
