### ISSUE TITLE
Wine-6.1+ Engines delayed

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#80]
Newer Engines won’t be made available for download until the next wrapper update is pushed due to changes on macports-ports that have affected my environment.

The runtime is currently being revised with the aim to maintain the current compatibility.

A new dependency will also be added `VKD3D` (currently v1.2) this won’t be useful for running games but was added into my Wine packages at the request of @oscarbg, since Wineskin uses shares the same runtime as my Wine packages it only makes sense to also include it here.

This means Wineskin could become useful for testing DXVK & VKD3D via MoltenVK when using a stock version of MoltenVK I’ve ether currently shipped patches version, this would also mean if an issue is found the entire packages could could be compressed and then ran on another target system without needing to worry about missing dependencies.

**Comment by Gcenx** [comment]
A new requirement was also added into wine called jxrlib, luckily it wasn’t too difficult to get that building properly see macports-wine [jxrlib](https://github.com/Gcenx/macports-wine/blob/master/graphics/jxrlib/Portfile)

Just incase someone wants to build wine using homebrew, there provided formula isn’t viable as it doesn’t produce a dylib.

**Comment by emendelson** [comment]
Probably irrelevant to this thread, but I didn't want to waste bandwidth on another one. I haven't experimented with recent updates until today, but just created a new wrapper, and everything seems faster than before, but maybe that's an illusion. 

What I can't figure out are these two things:

1. if there is a hope of Wineskin running 16-bit Windows 3.x apps under Catalina/Big Sur, etc., in the relatively near future. If there's any hope of that, could you let us know?

2. Is there any prospect of notarizing Wineskin apps?
 
Thanks again for your terrific work on this project!

**Comment by Gcenx** [comment]
I really can’t say if the new master wrapper has become faster or not, avoiding `tccd` freaking out may have helped speed things up while also getting permissions working maybe that’s related?

> if there is a hope of Wineskin running 16-bit Windows 3.x apps under Catalina/Big Sur, etc., in the relatively near future. If there's any hope of that, could you let us know?

I don’t see this happening in the near future.

> Is there any prospect of notarizing Wineskin apps?

`Wineskin Winery.app` shouldn’t have any major blockers maybe some tweaks here or there.

`Wineskin.app` This might also be possible with some additional tweaks. But would become invalid once winetricks is downloaded unless the location is moved?

`WineskinLauncher` I’ll be unable have this code-signed & notarized as the moment a wrapper is created this would become invalid, this should be possible after generation.

**Comment by emendelson** [comment]
Thanks for this update. I was wondering whether I'll be able to notarize the wrappers that I've been creating, and it sounds as if that should be possible. This is very encouraging news.

**Comment by vesper8** [comment]
Apologies if this is a noob question but is it normal that when I go in winecfg -> about it says I'm on Wine 5.0 ? I would have expected it to be on 6.0 at least.. with 6.1+ being delayed as per this thread.

I'm using the latest tag release from this repo Wineskin 2.9.0.7-rc4 with engine WS11WineCX20.0.2

Is this the absolute latest version I could be using on Mac at the moment?

Many thanks!

**Comment by Gcenx** [comment]
@vesper8 WineCX isn’t upstream wine but crossover-wine that I patch and compile from source, WineCX19 and greater are the only current source of wine32on64 currently.

**Comment by vesper8** [comment]
Thanks for the clarification. I had not even realized that WineCX stood for 'CrossOver Wine'. I see you also support 'Vanilla Wine' but that the latest release is 6.0. I understand now that this is what this thread is about. And I look forward to trying out your release of Wineskin with Wine 6.1-6.4 after the next wrapper update.

Out of curiosity, this wrapper.. does it have its own repository where I might learn more about it and follow its releases? Or is *this* the repository for the wrapper?

**Comment by Gcenx** [comment]
> Thanks for the clarification. I had not even realized that WineCX stood for 'CrossOver Wine'. I see you also support 'Vanilla Wine' but that the latest release is 6.0. I understand now that this is what this thread is about. And I look forward to trying out your release of Wineskin with Wine 6.1-6.4 after the next wrapper update.

I could provide the Engines now but as Macports moved from jpeg9 to jpeg turbo this could cause major issues for these newer wine versions.

> Out of curiosity, this wrapper.. does it have its own repository where I might learn more about it and follow its releases? Or is _this_ the repository for the wrapper?

I don’t maintain a separate GitHub for the master wrapper, once the next wrapper version is done I’ll push it and Winery will then want you to download it.

**Comment by AraHaan** [comment]
Is it possible to update my wrappers to Wine6.1? I get issues currently with wine5.0 when I try running an .NET Framework 4.7 application inside it that is a simple Windows Forms application.

**Comment by Gcenx** [comment]
Im not providing 6.x engines until #109 becomes the master wrapper.
