### ISSUE TITLE
GOG installers not working from external drive

### ISSUE THREAD

**Issue by jeanravin** [Gcenx/WineskinServer#81]
Hello,

I can't make GOG installers work. Probably since Wineskin-2.9.0.7-rc4. No problems if I use CrossOver, though.

I got this error message several times : "**there is no windows program configured to open this type of file**"

![Capture d’écran 2021-02-04 à 17 39 30](https://user-images.githubusercontent.com/1174299/106925830-bd6b5e00-6710-11eb-9e65-1e9936c8b2c2.png) (this is a PortingKit capture but I've got the exact same message in wineskin)

If I make a test run with the installer I get this : **Error while writting file: The file “exec2744918513.bat” couldn’t be saved using text encoding Western (ASCII).** 

With this log :
**Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Internal error.**

I've used those engines : cx64bit 20.0.2, 20.0.0, & the official 6.0 64bit

I'm using the latest Catalina.

**Comment by Gcenx** [comment]
From the error you’ve provided this would indicate a lack of permissions as I’d assume your install files are stored within your user /Downloads directory?

**Comment by jeanravin** [comment]
The installer files are located in an external drive. Indeed, if I copy the installer in my wineskin wrapper c: folder and run it, it works.

How can I fix that ?

**Comment by Gcenx** [comment]
When you attempted this were you printed to give PK/Wrappers name permissions?

As by default from macOS Catalina multiple directories are blocked by SIP and if permissions are not granted access will be blocked.

The above error is when happens when access to these protected location is blocked.

**Comment by jeanravin** [comment]
> When you attempted this were you prompted to give PK/Wrappers name permissions?
I already had accessibilty permissions. If this is what you're asking.

Also tried to copy the installer to user/downloads and it works. So, yeah it's a problem with external drives.

I think the SIP is disabled, or only partially (I can open unsigned apps)

OK, I tried another external drive and it's working… Hmm… I wonder if the problem could be that the drive is a corestorage volume… ( something unwanted, caused by an older macos install… that I never bothered to change…)

**Comment by Gcenx** [comment]
Accessibility permissions is different from permissions to access ~/Downloads, ~/Desktop etc, macOS Catalina and later require permissions to access multiple locations when SIP is enabled. These are usually prompts that say something like this

“Steam would like permissions to access Downloads”, these won’t happen if SIP is disabled.

SIP = System Integrity Protection

Running unsigned apps it controlled by Gatekeeper.

If another external drive is working and your also able to install from ~/Downloads then I’m not entirely sure what’s happening.

**Comment by jeanravin** [comment]
I suppose there's something fishy on my side… I'll try to reformat the drive later.

Anyway thanks for your help!
