### ISSUE TITLE
Updated project minimum requirements.

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#82]
Going forward macOS High Sierra will be the minimum supported version due less complexity with runtime maintenance.

From Wine-5.8 the minimum supported version of OS X is Mountain Lion, but requires MacOSX10.10.SDK to build.

So is there any interest in support for versions of macOS below High Sierra?

Is anyone willing to keep maintaining a legacy focused Runtime?

For the time being the Engines themselves will still be built targeting OS X 10.9 until that’s no longer possible.

**Comment by Rastafabisch** [comment]
Obviously I can only speak for myself, but I think aiming for High Sierra is absolutely fine. To my knowledge any Mac which supported 10.9 Mavericks supported at least 10.11 El Capitan. And [any Mac supporting El Capitan, can be easily patched to fully support High Sierra](http://dosdude1.com/highsierra/) .

**Comment by Gcenx** [comment]
@Rastafabisch that’s the stance being taken for PortingKit already in preparation for the changes here.

I’d assume it’s mostly outliners that are on much older versions of OS X.

I have a feeling that I’ll only get feedback on this once the changes have gone live and at that point it’ll be too late.
