### ISSUE TITLE
dxvk_macos.verb: No such file or directory

### ISSUE THREAD

**Issue by lincerely** [Gcenx/WineskinServer#83]
Wrapper Version: `Wineskin 2.9.0.7-rc1`
Engine: `WS11WineCX64Bit19.0.1-1`

Run winetricks custom command `dxvk_macos.verb` gives error "no such file or directory".

[Winetricks.log](https://github.com/Gcenx/WineskinServer/files/5930163/Winetricks.log)

**Comment by Gcenx** [comment]
For DXVK you require rc4, download this copy of [Winery](https://github.com/Gcenx/WineskinServer/releases/download/V1.8.4.2/Wineskin.Winery.txz), it’s possible you’ll see graphical glitches or depending on your GPU crashes (upstream MoltenVK bugs)

Currently we have PortingKit setup to force downgrade the version of MoltenVK to v1.1.0 you can obtain that from [here](https://github.com/Gcenx/MoltenVK/releases/download/v1.1.0/macos_dxvk_patched.tar.xz) unpack and replace the wrappers copy of libMoltenVK.dylib with the one in that archive. That resolves crashes on Apple Silicon devices.

**Comment by lincerely** [comment]
It works perfectly fine. Thanks for your help.

**Comment by vesper8** [comment]
I just managed to get Age of Empires 2 Definitive Edition working.

I got the latest Wineskin Winery 2.9.0.7-rc4 and used engine WS11WineCX64Bit20.0.2

I then installed Steam and configured steam to run using `"C:\Program Files (x86)\Steam\steam.exe" -no-browser -appLaunch 813780`

This allowed me to install Age of Empires 2 Definitive Edition from Steam and get around the problem with the Library being blank.

I the installed dxvk_macos.verb using the custom winetricks. And I received this warning: 

```
warning: dxvk_macos install completed, but installed file /Users/vesperknight/Applications/Wineskin/Age of Empires II DE.app/Contents/Resources/dosdevices/c:/windows/syswow64/dxgi.dll not found
```

Should I be worried about this warning? Above you mention having to install a special version of MoltenVK through PortingKit (maybe I'm saying this wrong) but I didn't have to do that?

And then using winetricks I installed DXD9, DXD10 and DXD11_43. Not sure if I needed all 3 but I installed them in order 9 -> 10 -> 11

And it just works beautifully!!

Anyway thought I would paste these instructions in case it helps anyone else. Thanks so much @Gcenx for all your hard work and making it possible to play DX11 games on Wineskin!! By the way I'm on a Macbook Pro 2013 with an Nvidia 750m

**Comment by Gcenx** [comment]
@vesper8 I haven’t looked at the DXVK verb for a while but I think that check was incorrect so you can ignore it.

PortingKit was replacing the version of MoltenVK but that’s really only been confirmed as required for Witcher3 with some video cards.

The Wineskin master wrapper currently contains MoltenVK v1.1.1 with some required modifications to run the custom DXVK on macOS.

At first I was rather reluctant to provide DXVK support but after a lot of testing it seemed to work decently enough, that was later also confirmed when PaulTheTall managed to run multiple games at decent levels.

The real hard work was done by CodeWeavers and there Mac developers, what I’ve done in comparison is making a shell script.

**Comment by vesper8** [comment]
Yes credit to the CodeWeavers dev for sure.. but don't be too modest either! You're making it possible for many to game on their Mac without having to purchase CrossOver and that's a big accomplishment : ) I for one appreciate your work a whole lot and certainly look forward to future improvements! Cyberpunk 2077 on the M1X/M2 later this year! =D
