### ISSUE TITLE
Internet Connection Issue

### ISSUE THREAD

**Issue by Crazzak** [Gcenx/WineskinServer#84]
Hey Wineskin Team,
first at all big thanks for making it possible that we can use our Project for Free on our Mac´s.

Yesterday I tried some Games like AmongUS which runs pretty great when your use DXVK, but I got a strange issue.
When I want to Host a Lobby on a Europa Server im getting an disconnect Error (screen attached) if I select the North America Servers I can host them, when a friend or I want to play on a Public Match in the Europa Server it's working too.

On different Games I have this same issue too like MTA for GTA:SA I can´t connect to any Server.
Do I need to install anything from winetrick? On a different PC whit Linux these Games are working, i already tried to disable the Firewall but there was no change.
PS: The Performance of GTA SA is pretty bad, do I have something to install though Winetricks or wait for the next Releases?.

Greetings
Andy
![Bildschirmfoto 2021-02-14 um 11 07 43](https://user-images.githubusercontent.com/74865067/107874312-f944b700-6eb8-11eb-85e9-bb1f16da67ae.png)

**Comment by podycust** [comment]
Those connection errors in among us isn't anything todo with wine its just too many people are trying to play it have the error message appear when I play it on Nintendo Switch

**Comment by Crazzak** [comment]
Thanks for your answer.
I know sometimes the Servers in AmongUs are busy but in my case on the IOS App its working and in Parallels it´s working too, even in Games like MTA or CoD4 which I installed in the Wrapper I can´t connect to any Server, the Servers are loading in the Server Browser but if I try to connect it fails.

**Comment by Gcenx** [comment]
Please provide more information as I'm able to connect to and host public servers that others can join without issue.

<img width="800" alt="Screen Shot 2021-02-14 at 7 49 50 PM" src="https://user-images.githubusercontent.com/38226388/107894509-db4d7580-6efd-11eb-851d-b20d03977665.png">

With the following configuration;
- macOS Mojave 10.14.6
- WineCX64Bit20.0.2
- Wineskin-2.9.0.7-rc4

**Comment by Crazzak** [comment]
Oh.. I forgot about the most important Information.
I´m using a Mac mini M1 8GB whit Big Sur 11.2.1, WineCX64bit20.0.2 and the Wineskin Version like you.

I was trying to use Wineskin on a old Hackintosh-Build whit High Sierra for test and there it´s working, I read that you own a M1 Mac too, can you try it on the M1 Mac maybe again?

**Comment by Gcenx** [comment]
![Screen Shot 2021-02-15 at 8 56 12 AM](https://user-images.githubusercontent.com/38226388/107955436-cad3e400-6f6b-11eb-91dc-3dd9cd5d9dd8.png)
I temp moved my Macports-wine install so it wouldn't interfere with testing, yes I'm also able to join public games on the M1 Mac Mini running macOS Big Sur 11.2.1

**Comment by Crazzak** [comment]
And Hosting is working too? 
I really don´t know, I have on other Games the same Issue like in Multi Theft Auto or Call of Duty. 
Do you have maybe any Solution for me what I could try?

**Comment by Gcenx** [comment]
Yes hosting a game worked for me without issue as randoms joined.

I really don’t have any clue what’s happening so unfortunately there no advice I can give you.
