### ISSUE TITLE
[BUG] wineskin's wine fails to start, but normal wine succeed.

### ISSUE THREAD

**Issue by nsklaus** [Gcenx/WineskinServer#86]
**Environment (please complete the following information):**
 - OS: 11.3 beta2
 - Winery version:
 - Master Wrapper version: 2.9.0.7-rc4
 - Engine version: WS11WineCX64bit20.0.2
 - Hardware: macbookpro m1

**Describe the bug**
wine refuse to start and log reports: 
`err:environ:run_wineboot failed to start wineboot c00000e5`
when that happens, if i try my own compiled wine, it starts fine.
something seems to be weird about the way wineskin starts its process. 

**To Reproduce**
Describe the steps to reproduce the behavior:
open wineskin ui>advanced>configuration, click test run and i often get log output
`err:environ:run_wineboot failed to start wineboot c00000e5`

for example, trying to run manually a game fails:
```
-> MoltenVK-1.1.2 $ ~/Applications/The\ Surge.app/Contents/SharedSupport/wine/bin/wine64 ~/Applications/The\ Surge.app/Contents/Resources/drive_c/Games/Fallout\ 4/Fallout4.exe 
0009:err:environ:run_wineboot failed to start wineboot c00000e5
zsh: segmentation fault  ~/Applications/The\ Surge.app/Contents/SharedSupport/wine/bin/wine64 
?139 MoltenVK-1.1.2 $ 
```

trying to run manually winecfg fails:
```
-> MoltenVK-1.1.2 $ ~/Applications/The\ Surge.app/Contents/SharedSupport/wine/bin/wine64 winecfg             
0009:err:environ:run_wineboot failed to start wineboot c00000e5
zsh: segmentation fault  ~/Applications/The\ Surge.app/Contents/SharedSupport/wine/bin/wine64 winecfg
?139 MoltenVK-1.1.2 $ 
```
but, trying to run manually winecfg using my own compiled wine succeed:
```
-> MoltenVK-1.1.2 $ wine64 winecfg
-> MoltenVK-1.1.2 $
```

**Expected behavior**
if there was a problem with macos 11.3 beta 2 it would have expected both wineskin and my own compiled wine to fail.
but only wineskin fails. 
to note: upon reboot, wineskin usualy starts just fine. but at some point later on (after computer went to sleep, or after a few times starting / stopping the game), suddenly wineskin will refuse to start. only solution is to reboot.
i expected wineskin to consistently succeeding at starting/stopping. but something is getting trashed, somewhere after a few runs. and when that happen only a reboot seems to solve it. and in the same time, custom build of wine i'm working on, seems to always starts/stop fine, even when wineskin is trashed and won't run anymore.

**Comment by nsklaus** [comment]
update: 
running a different engine (cx19 instead of cx20) and with packaged moltenvk (instead of a more recent own build) solves the problem of wineskin refusing to run until next reboot. at the price of a few fps apparently.

**Comment by Gcenx** [comment]
As was discussed via Discord, comparing CX20.0.2 to Wine-6.2 yields inaccurate results.

CX19.0.2-2 was compiled using the same compiler optimizations as CX20 but it’s not unusual for there to be a different in FPS between wine versions. CX19 (wine-4.12.1) vs CX20 (wine-5.0)

**Comment by Gcenx** [comment]
But as mentioned CX20 seems to be rather unstable, not sure if that improved or not with the unreleased CX20.0.4 (needs a newer runtime)

**Comment by Gcenx** [comment]
Apple already resolved this issue in a newer beta update.
