### ISSUE TITLE
Include otvdm for running 16-bit apps?

### ISSUE THREAD

**Issue by emendelson** [Gcenx/WineskinServer#87]
Probably this is impossible, but I thought it was at least worth asking:

Is there any chance that the code in this project could be included in Wineskin:

https://github.com/otya128/winevdm

I use it under 64-bit Windows to run Windows 3.x apps, and it works perfectly there. I tried installing it in a Wineskin wrapper and using it to run 16-bit software, and of course it didn't work. The otvdm.exe executable reported its version number but couldn't do anything else.

Again, probably this is simply impossible, but I'm asking in the hope that it might be easier than I thought.

Incidentally, I used my own installer for otvdm when testing with Wineskin; it makes installation easy:

http://www.columbia.edu/~em36/otvdm.html

**Comment by emendelson** [comment]
Sorry - this is NOT a bug. But I can't figure out how to remove that "bug" label!

**Comment by Gcenx** [comment]
I believe the “bug” tag is now added automatically from the issue template.

As this is based on wine 16>32Bit trunking code that night be why it’s not working but unsure without trying it myself.

**Comment by emendelson** [comment]
OK - I don't pretend to understand this, but I hope it might be worth looking into. There seems to be no practical method of running 16-bit Windows games and applications for Catalina or Big Sur without setting up a full Windows 3.1x system under DOSBox or DOSBox-X, which of course is always possible.

**Comment by spiffyguy** [comment]
Hi there, I wanted to add that I also would love to have 16-bit support working on the "wine32on64" version.

I was trying to play CivNet (that is a windows 16-bit version of Civilization 1 with networking support) with my kids but it wouldn't run using the WS11WineCX20.0.2 engine.

On Windows 10, this game works just fine after installing the mentioned "otvdm" @emendelson linked to above.

On the Mac side, I needed to settle with a VMWare VM of Windows 98 with TCP/IP networking so I could play multiplayer.

I did get the game installed on Windows 3.1 inside of DosBox but the DosBox version of IPX networking over TCP/IP is not "plug and play" for sending it to my cousins.  Easier to use TCP/IP directly in the VMWare VM instead.

The game is now "abandonware" and free to download if you want to use it for testing/seeing why 16-bit code doesn't work with the crossover/codeweavers solution for 32-bit apps/games.

Link to CivNet:

https://www.myabandonware.com/game/sid-meier-s-civnet-dvq

**Comment by Gcenx** [comment]
The linked project uses wines 16>32 trunking code and that’s marked as not supported within wine64 and by extension wine32on64.

Unless there were just some missing dependencies when @emendelson tried to use it (I doubt that would be the case) I don’t see anyway to get this functional, best case would be some larger companies require 16Bit support on macOS and pay CodeWeavers to recreate there trunking code so it’s functional in wine32on64.

**Comment by spiffyguy** [comment]
That makes sense and I agree that the "request" should be done probably with CodeWeavers. Thanks for replying!

**Comment by emendelson** [comment]
There's a year-old post at Codeweavers saying this is theoretically possible, but clearly not anything we can hope for soon:

https://www.codeweavers.com/support/forums/general/?t=27;mhl=226379;msg=222890#c3
