### ISSUE TITLE
KB2468871 needed to install program

### ISSUE THREAD

**Issue by tomparonett** [Gcenx/WineskinServer#89]
**Environment (please complete the following information):**
 - OS: [e.g. macOS version (10.13, 10.14, 10.15.4, 11...)] Mac OS Big Sur 11.2.1 M1 MBA 8GB memory
 - Winery version:Wineskin-2.9.0.7-rc4
 - Master Wrapper version: Wineskin-2.9.0.7-rc4
 - Engine version: WS11winecx64bit20.0.2
 - Hardware: [e.g. MacBook Pro 13 2016, Mac mini 2020...] M1 MacBook Air 

**Describe the bug**

I am running a program which requires the item in the description. I use wine tricks to attempt to install it with the following: dotnet40_KB2468871- MS .net 4.0 KB2468871. 
I get the following in the command line for wine tricks:
warning: taskset/cpuset not available on your platform!
Executing mkdir -p /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206-next - sha256sum: 872a62040e7518ab9d577dc78d3a13a55341e310e3926e6ce9d5a77e3ef6fcc9 with wine-5.0 and WINEARCH=win64
Executing w_do_call dotnet40_kb2468871
Executing mkdir -p /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet40_kb2468871 
Executing w_do_call dotnet40
Executing mkdir -p /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet40 
------------------------------------------------------
warning: This package (dotnet40) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
------------------------------------------------------
warning: dotnet40 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
Executing w_do_call remove_mono
Executing mkdir -p /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call winxp
Executing mkdir -p /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_winxp 
The operation completed successfully
Setting Windows version to winxp
Executing wine regedit /S C:\windows\Temp\set-winver.reg
Executing wine64 regedit /S C:\windows\Temp\set-winver.reg
------------------------------------------------------
warning: Running /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents/SharedSupport/wine/bin/wineserver -w. This will hang until all wine processes in prefix=/Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents/Resources terminate
------------------------------------------------------
Executing cd /Users/tomparonett/.cache/winetricks/dotnet40
Executing wine dotNetFx40_Full_x86_x64.exe /q /c:install.exe /q
Preparing: C:\12a3315c0cd3cc0d652b1d\netfx_Core_x64.msi...

Preparing: C:\12a3315c0cd3cc0d652b1d\netfx_Core_x86.msi...

Preparing: C:\12a3315c0cd3cc0d652b1d\netfx_Extended_x64.msi...

Preparing: C:\12a3315c0cd3cc0d652b1d\netfx_Extended_x86.msi...

Preparing: C:\12a3315c0cd3cc0d652b1d\RGB9RAST_x64.msi...

Preparing: C:\12a3315c0cd3cc0d652b1d\RGB9Rast_x86.msi...

Preparing: C:\12a3315c0cd3cc0d652b1d\header.bmp...

Preparing: C:\12a3315c0cd3cc0d652b1d\SplashScreen.bmp...

Preparing: C:\12a3315c0cd3cc0d652b1d\watermark.bmp...

Preparing: C:\12a3315c0cd3cc0d652b1d\DisplayIcon.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Print.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Rotate1.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Rotate2.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Rotate3.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Rotate4.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Rotate5.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Rotate6.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Rotate7.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Rotate8.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Save.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\Setup.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\stop.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\SysReqMet.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\SysReqNotMet.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\Graphics\warn.ico...

Preparing: C:\12a3315c0cd3cc0d652b1d\1033\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1042\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1041\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1037\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1025\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1035\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1030\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1044\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1043\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1040\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1029\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1031\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1036\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1032\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1038\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\2052\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1028\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\3076\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1055\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1053\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\3082\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\2070\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1046\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1049\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\1045\LocalizedData.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\Client\Parameterinfo.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\Extended\Parameterinfo.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\ParameterInfo.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\Strings.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\UiInfo.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\Client\UiInfo.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\Extended\UiInfo.xml...

Preparing: C:\12a3315c0cd3cc0d652b1d\SetupUi.xsd...

Preparing: C:\12a3315c0cd3cc0d652b1d\DHtmlHeader.html...

Preparing: C:\12a3315c0cd3cc0d652b1d\1033\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1025\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1028\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1030\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1031\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1029\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1036\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1035\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1032\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1038\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1037\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1040\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1041\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1042\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1044\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1043\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1046\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1045\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1055\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1053\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\2052\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\1049\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\3082\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\2070\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\3076\eula.rtf...

Preparing: C:\12a3315c0cd3cc0d652b1d\Setup.exe...

Preparing: C:\12a3315c0cd3cc0d652b1d\SetupUtility.exe...

Preparing: C:\12a3315c0cd3cc0d652b1d\SetupEngine.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1025\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1033\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1029\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1030\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1035\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1031\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1036\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1032\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1028\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\2052\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\3076\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1042\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1041\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1037\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1044\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1053\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1055\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1040\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1045\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1046\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1049\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1038\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\2070\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\3082\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\1043\SetupResources.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\SetupUi.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\sqmapi.dll...

Preparing: C:\12a3315c0cd3cc0d652b1d\Windows6.0-KB956250-v6001-x64.msu...

Preparing: C:\12a3315c0cd3cc0d652b1d\Windows6.0-KB956250-v6001-x86.msu...

Preparing: C:\12a3315c0cd3cc0d652b1d\Windows6.1-KB958488-v6001-x64.msu...

Preparing: C:\12a3315c0cd3cc0d652b1d\Windows6.1-KB958488-v6001-x86.msu...

Preparing: C:\12a3315c0cd3cc0d652b1d\netfx_Core.mzz...

Preparing: C:\12a3315c0cd3cc0d652b1d\netfx_Extended.mzz...

Using native override for following DLLs: mscoree
Executing wine regedit /S C:\windows\Temp\override-dll.reg
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
Setting Windows version to default
Executing wine regedit /S C:\windows\Temp\set-winver.reg
Executing wine64 regedit /S C:\windows\Temp\set-winver.reg
------------------------------------------------------
warning: Running /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents/SharedSupport/wine/bin/wineserver -w. This will hang until all wine processes in prefix=/Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents/Resources terminate
------------------------------------------------------
------------------------------------------------------
warning: Cannot find 7z. Using Windows 7-Zip instead. (You can avoid this by installing 7z, e.g. 'sudo apt-get install p7zip-full' or 'sudo yum install p7zip-plugins').
------------------------------------------------------
Executing w_do_call 7zip
Executing mkdir -p /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_7zip 
Executing cd /Users/tomparonett/.cache/winetricks/7zip
Executing wine 7z1900.exe /S
Executing cd /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Wineskin.app/Contents/Resources
Executing wine C:\Program Files (x86)\7-Zip\7z.exe x Y:\dotnet40_kb2468871\NDP40-KB2468871-v2-x64.exe -oC:\windows\temp NDP40-KB2468871.msp

7-Zip 19.00 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 28640160 bytes (28 MiB)

Extracting archive: Y:\dotnet40_kb2468871\NDP40-KB2468871-v2-x64.exe
--
Path = Y:\dotnet40_kb2468871\NDP40-KB2468871-v2-x64.exe
Type = PE
Physical Size = 28640160
CPU = x86
Characteristics = Executable 32-bit LargeAddress
Created = 2009-10-09 14:27:34
Headers Size = 1024
Checksum = 28648023
Name = NDP40-KB2468871-v2-x64.exe
Image Size = 212992
Section Alignment = 4096
File Alignment = 512
Code Size = 165376
Initialized Data Size = 24064
Uninitialized Data Size = 0
Linker Version = 10.0
OS Version = 5.1
Image Version = 10.0
Subsystem Version = 5.1
Subsystem = Windows GUI
DLL Characteristics = Relocated NX-Compatible TerminalServerAware
Stack Reserve = 1048576
Stack Commit = 8192
Heap Reserve = 1048576
Heap Commit = 4096
Image Base = 4194304
Comment = 
{
FileVersion: 10.0.30319.233
FileVersion: 10.0.21009.0
FileVersion: 10.0.21009.0 built by: DTG(RAVIR01-ravir)
ProductVersion: 10.0.30319.233
ProductVersion: 10.0.21009.0
CompanyName: Microsoft Corporation
FileDescription: Microsoft .NET Framework 4.0 Setup
FileDescription: Box Stub
InternalName: NDP40-KB2468871-v2-x64.exe
InternalName: BoxStub.exe
LegalCopyright: c Microsoft Corporation. All rights reserved.
OriginalFilename: NDP40-KB2468871-v2-x64.exe
OriginalFilename: BoxStub.exe
ProductName: Microsoft .NET Framework 4.0
ProductName: Microsoftr .NET Framework
}
----
Path = [0]
Size = 28443704
Packed Size = 28443704
Virtual Size = 28443704
Offset = 190464
--
Path = [0]
Type = 7z
Offset = 256
Physical Size = 28443441
Tail Size = 7
Headers Size = 1581
Method = LZMA:27 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Files: 103
Size:       200071029
Compressed: 28640160
Executing cd /Users/tomparonett/Applications/Wineskin/Oculus rift.app/Contents/Resources/dosdevices/c:/windows/temp
Executing wine msiexec /p NDP40-KB2468871.msp
------------------------------------------------------
warning: Note: command wine msiexec /p NDP40-KB2468871.msp returned status 69. Aborting.
------------------------------------------------------

 Winetricks Commands Finished!!

I read somewhere to attempt to get Samba.. Im a bit uneducated in computer programing but from my understanding it's easiest to obtain it through Mac ports so I downloaded that, and then got the files for Samba, I then moved the files into the wineskin directory so it could find whatever path was necessary for it to find (fyi I used: https://forum.winehq.org/viewtopic.php?t=16162) for this.  
I was hoping there is some information you can give me to get this installed because that's the hang up. I've been working to get the Oculus rift software running through wineskin.

Also not a big issue but when I do run the installer with the "test run" feature it runs.. and the screen flickers a bit is there a setting im missing that prevents that? 
Thank you!

**Comment by Gcenx** [comment]
If a winetricks verb fails to install that lightly a winetrikcs issue as the fail didn’t complain about a memory mapping issue so not a 32on64 issue.

As for Oculus rift software I’m sure that just won’t function within wine, maybe try installing DXVK also but I still don’t see that working.
