### ISSUE TITLE
WineCX no longer for direct download.

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/WineskinServer#9]
Currently these have been disabled for direct download, the reason is dotnet/vcrun or anything that needs to unpack and then run stalls out.

Until that problem is resolved upstream in the winebuilder I’m using, these won’t be avalaibe for download directly from Winery.

**Comment by ovvldc** [comment]
To what versions of CX does this apply? Also the earlier 17.5.1?

**Comment by Gcenx** [comment]
This definitely applied to 18.1.0 & 17.5.1.
Below that I’m not too sure, I removed access to them to be safe.
I don’t have too much free time in front of my system at the moment.

I would guess the 32bit versions below 17.5.1 may be working correctly, also the older git commit version of 17.5.1 may also work but not the 64Bit versions those had other bugs.

They are all still  available by downloading from GitHub, I just won’t risk Winery downloads unless I can be sure they won’t have the above problem.

**Comment by ovvldc** [comment]
Thanks! No rush :)

**Comment by Gcenx** [comment]
An update for those who only read GitHub for updates.

I traced the issue back to what seems a broken port from packages.macports.
The broken prebuilt package is Gnutls (or one of its dependancies)

Having Gnutls installed to my cross-compile setup breaks vcrun/dotnet, so I could provide compile without Gnutls the workaround would be installing ie7 with winetricks.

**Comment by Gcenx** [comment]
The reason the compiles were faults was thanks to packages.macports providing a broken prebuilt version of Gnutls, compiling with Gnutls and the issue went away but Gnutls is a big requirement.

At the moment I plan to compile Gnutls along with its dependancies from source to workaround this issue.

**Comment by Gcenx** [comment]
This will be resolved once the next wrapper update is releases, then I will restore access to WineCX builds via Winery and also add WineCX18.5.0 versions

**Comment by Gcenx** [comment]
Resolved
