### ISSUE TITLE
[Bug]: WS12WineCX23.7.1 not working with Path of Exile

### ISSUE THREAD

**Issue by marvinTD** [Gcenx/WineskinServer#9]
### Description

Winery version: v2.0.3
Master Wrapper version: 3.0.7
Engine version: WS12WineCX23.7.1
Hardware: MacBook Pro 14" 2021 M1 Pro 16GB RAM
Application/Game Name: Path of Exile
Render used: D3DMetal enabled. DirectX12 configured in production_Config.ini file in Path of Exile

Potentially related to #2 and/or #5 ?

I went ahead and added `export DYLD_PRINT_LIBRARIES=YES` to the Unix command field in case that's useful since I saw you request that in the other issue.

You can see the path of exile launcher flash open, then the game opens, black screen, you see a POE cursor, and it just closes itself

[LastRunWine.log](https://github.com/user-attachments/files/17358924/LastRunWine.log)

### macOS Version

Sequoia (macOS 15)

### Wrapper Version

Wineskin-3.0.7

### Engine

WS12WineCX23.7.1

### LastRunWineLog

```shell
Uploaded
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GrimDawn-max** [comment]
Can confirm POE works again after removing the 2.0 directory and using WS12WineCX23.7.1

**Comment by marvinTD** [comment]
Confirmed, thank you!
