### ISSUE TITLE
Can't seem to change menubar name or icon anymore

### ISSUE THREAD

**Issue by vesper8** [Gcenx/WineskinServer#90]
This was working previously but now it seems no matter what I do, anytime I open Wineskin.app inside one of my wrappers and go into Advanced, and then in the Configuration if I change the Menubar Name and/or the Icon (browsing to a download png icon). After I close (by clicking the X), the icon is not updated, even after I move the file to bust the cache. And when I return to the Advanced, I can see the changes I made were not saved and they've reverted to their previous values.

I tried running 'update wrapper' but it doesn't make the changes stick either. Any idea what could be causing this?

I'm using the very latest 1.8.4.2

**Comment by Gcenx** [comment]
The icon will change but you might need to use the `touch` Command on the wrapper or move it’s location, the menu bar lightly won’t ever be fixed due to the removed of WineskinX11 the macdriver has taken over.

Maybe it could be patched to get the same results eventually but that means more custom patches ontop of wine.

**Comment by vesper8** [comment]
Ok thanks.. I didn't know there was a known limitation that prevents you from changing the Menubar Name

As for the icon.. it looks like there was a problem with the icon I was trying to use.. it just wouldn't stick no matter what. I resized it to a perfect square 512x512 and reduced the file size a bit and afterwards it was able to save right away.. so there was a problem with the icon file itself.. not sure what it was.. too big.. too large.. or a corrupt format possibly
