### ISSUE TITLE
Cant enter config mode of a wrapper by hold down option key

### ISSUE THREAD

**Issue by beterhans** [Gcenx/WineskinServer#91]
**Environment (please complete the following information):**
 - OS: 11.2.3
 - Winery version: 1.8.4.1
 - Master Wrapper version: Wineskin-2.9.0.7-rc1
 - Engine version:WS11WineCX64bit19.0.1-1
 - Hardware: mac mini 2018

**Describe the bug**
in old version I can hold option key to enter a wrapper's setup or advanced menu.
but this version can't

Is there a command line way to enter the setup menu for a wraaper?
like ./WineskinLauncher --option?

**Comment by Gcenx** [comment]
I had disabled that option, but I do have it enabled in my local copy maybe also in the pre-release version, you really should be using the following version of [Winery](https://github.com/Gcenx/WineskinServer/releases/download/V1.8.4.2/Wineskin.Winery.txz)

I think that option is again enabled in that version however launching Wineskin.app in this manner can cause crashes. Also the newer master wrapper isn’t compatible with the older version so you’ll be unable to upgrade an older wrapper to the newer wrapper version without manual intervention. (I don’t recommend not support this)

Using “Show Contents” enter the .app until you find Wineskin.app and directly launch it, this method is less prone to crashing.

I don’t recommend launching a Wineskin wrapper via terminal as that will have issues with obtaining permissions, causing Wineskin to then have the same permissions you’ve granted to Terminal.

**Comment by beterhans** [comment]
Thanks

I never know the wineskin.app inside is the config app.
