### ISSUE TITLE
Is there any way to get running logs or output for troubleshooting?

### ISSUE THREAD

**Issue by beterhans** [Gcenx/WineskinServer#92]
I know when you under linux
you can wine path_to_exe.

and there is a lot of output for troubleshooting

but the wrapper won't allow you see it.

is there a way to see those output?
or is there a file log the output?

I also tried
/Applications/Wine/WinApp.app/Wineskin.app/Contents/Resources/wine64 path_to_exe
but it don't have the permission to access any files.

**Comment by Gcenx** [comment]
When using the option “Test Run” or enable the checkbox to save logs you will get that output it’s saves inside the wrapper under Resources/logs

However next time please fill out the issue template, that is a mandatory step.
