### ISSUE TITLE
step by step documentation needed

### ISSUE THREAD

**Issue by gileneusz** [Gcenx/WineskinServer#93]
please provide any step by step documentation for newbies about installation and running basic setup

or just paste this tutorial https://www.youtube.com/watch?v=2f9vROQJ-9c

**Comment by Gcenx** [comment]
Only a very basic guide will ever be provided, I won’t link to any YouTube video guides are they’re always outdated include the one you linked.

Basic steps are;
- Download “Wineskin Winery”
- Remove quarantine flag
- Unpackaged (don’t use keka)
- Launch “Wineskin Winery”
- Click the “Update” button
- Download an Engine
- Make a wrapper

After this it’s mostly on the user to figure out dependencies that are required to run the desired application/game.

Maybe I could add some basic explanation for what each button does, but mostly after the wrapper is created its up-to the person creating the wrapper on what they want to do/install. There’s no one set of instructions of everything it can get complicated sometimes.

**Comment by aidswidjaja** [comment]
Would you be open to receiving PRs for documentation, or does this have the potential to get outdated quickly as well?

**Comment by Gcenx** [comment]
@aidswidjaja I’m open for generic documentation.

**Comment by eduardonwa** [comment]
Yes. I have to say im a little lost here since I don't know if this wine-install does have the support to run 32bit apps on my Catalina. Thanks.

**Comment by Gcenx** [comment]
@eduardonwa [macOS Catalina](https://github.com/Gcenx/WineskinServer#macos-catalina-support)

> All future WS11 Engines automatically mean Catalina is supported.

As explained in that section `wine32on64` mean the engine functions on macOS Catalina.   
For reference see #26 

As I’ve said prior I’m open to improvements to documentation as that’s something I excel at. I am against YouTube guides as those always end up causing me headaches.  
I’ve seen guides directly linking to older releases (so I removed them) and then asking for funding that as you can guess never makes it’s way here.

If anyone wants to help improve the README or wiki I’m open to reviewing any Pull-requests.

**Comment by gustavopi** [comment]
I have tried to install this awesome with no success. Without some documentation, this project will remain some hacker thing - is it desired?
In the releases section there is four files and the source. I tried the 'WS10WineCX64Bit18.5.0.tar.7z' and the result was wswine.bundle. Don't know what is it, neither my macOS. Don't know what is the quarantine flag and how to remove it... :(
I am now using BigSur in an unsupported mac and have some experience with emulators and compatibility layers, so my feedback here is this project is inaccessible for most of enthusiasts like me that could join the community (if you wanna).

**Comment by Gcenx** [comment]
@gustavopi you went directly to the release section and didn’t check the README.md

https://github.com/Gcenx/WineskinServer/blob/356b45646bc0fa06428535f2e8798f09c5c46da4/README.md#L7-L15

The only thing you need to download yourself is Wineskin Winery, that’s is then used to download the current master wrapper and any Engine that’s listed.

As for improving documentation only one single user has offered to do this and you can see that contribution in the wiki pages. Yes I hate writing documentation as it’s a lot of offers and almost nobody reads it anyway.

**Comment by gustavopi** [comment]
Thank you! It's now installed.

I develop in PHP, JavaScript and C#, and I don't like writing documentation
myself either. But since I don't have a good memory, I have to take notes
in the code. What I did is to make a php script that separates my notes
(that have a specific sintaxe) from the code and... voilá, I have
documentation! Maybe you should consider something like this, just a
suggestion for you.

Thanks again for answering so quickly!
Gustavo.

Em qua., 11 de ago. de 2021 às 18:41, Dean M Greer ***@***.***>
escreveu:
