### ISSUE TITLE
No new executable found!

### ISSUE THREAD

**Issue by talhazahid** [Gcenx/WineskinServer#94]
**Environment (please complete the following information):**
 - OS: 10.15.5
 - Winery version:  Wineskin Winery v1.8.4.2
 - Master Wrapper version: WINESKIN 2.9.0.7-RC1
 - Engine version: WS11WineCX64Bit19.0.1-2 
 - Hardware: [ imac PRO 2017 Ryzentosh Ryzen 5 MSI Motherboard b450 MAX ]

**Describe the bug**

Hi Guys,

Great app.. but I am still unable to run this on my MacOS (AMD Hackintosh Ryzen 5), I had big Sur also and then I installed Catalina I know both don't support 32 bit anymore but I have seen on youtube that people are running on Catalina.. I am banging my head against the wall since 4 days and still unable to run steam..

as you can see from my screenshot I do have steam.exe in drive_C yet I am unable to run it, I have tried several methods but to no avail.. 

**To Reproduce**
Describe the steps to reproduce the behavior:
[e.g.
1. Go to 'just copy the steam.exe to drive c '
2. Click on 'wineskin.app outside of the folder'
3. Select steam.exe to execute
4. See error no new executable found if you tried to install other than c drive you will get this error

**Expected behavior**
I want to run steam.

**Screenshots**
![Screenshot 2021-03-21 at 9 35 42 PM](https://user-images.githubusercontent.com/8392047/111941042-6c7bb300-8a8d-11eb-97e3-5a09f135740f.png)

**Additional context**
please help me solve this issue

Thanks,
Talha

**Comment by Gcenx** [comment]
You’ve neglected to fill out the provided issue template, please edit your comment and fill out the provided issue template or this issue will be closed as invalid.

**Comment by talhazahid** [comment]
> You’ve neglected to fill out the provided issue template, please edit your comment and fill out the provided issue template or this issue will be closed as invalid.

please check now

**Comment by talhazahid** [comment]
> You’ve neglected to fill out the provided issue template, please edit your comment and fill out the provided issue template or this issue will be closed as invalid.

please check now

**Comment by Gcenx** [comment]
Please see the README where this issue was already explained; https://github.com/Gcenx/WineskinServer#hackintosh-support

**AMD** based systems are not supported due to being unable to run 32Bit code on macOS.
