### ISSUE TITLE
COM PORT (COM1/via USB)

### ISSUE THREAD

**Issue by caf5011** [Gcenx/WineskinServer#97]
- OS: MAC OS 11.2.3
 - Winery version: 1.8.4.2
 - Master Wrapper version: Wineskin-2.9.0.7-rc4
 - Engine version: WS11WineCX64Bit19.0.1-1
 - Hardware: MacBook Pro 13' Beginning 2015

**Describe the bug**
Not really a bug but I need to have access to my COM1 via an USB device, and it's impossible for me to find it or even activate a symlink to this device.
Could anyone could give me some advices

Thanks

**Comment by Gcenx** [comment]
This one is something I'm really not familiar with unfortunately, all the instructions I've found focus on Linux not macOS.
