### ISSUE TITLE
Installing Microsoft .NET Framework 4.5 (x86 and x64)

### ISSUE THREAD

**Issue by Section25** [Gcenx/WineskinServer#98]
I am trying to install an an old and rare game I haven't been able to play for decades which keeps trying to install Microsoft .NET Framework 4.5 (x86 and x64).

The game was downloaded from here:

https://download.cnet.com/Noms-or-Nomination-Whist/3000-2647_4-75976492.html

The download progress bar seems to zip along and then the installing progress bar drags on and when it reaches the end, it starts again.

It doesn't seem to matter which engine I try and I can't really find much information about Microsoft .NET Framework 4.5 (x86 and x64) which makes any sense to me. Should I give up? Or is there something I can do to sort this out?

Thanks.

![screenshot_13](https://user-images.githubusercontent.com/25088566/113230366-c6038f00-9290-11eb-844e-b23dcb62c59d.png)

**Environment (please complete the following information):**
 - OS: [e.g. macOS version (10.13, 10.14, 10.15.4, 11...)]
 - Winery version:
 - Master Wrapper version:
 - Engine version:
 - Hardware: [e.g. MacBook Pro 13 2016, Mac mini 2020...]

**Describe the bug**

**To Reproduce**
Describe the steps to reproduce the behavior:
[e.g.
4. See error]

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Gcenx** [comment]
Please reformat this issue using the provided issue template.
