### ISSUE TITLE
Running Skyrim

### ISSUE THREAD

**Issue by torquan** [Gcenx/WineskinServer#99]
**Environment (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - Winery version:  1.8.4.2
 - Master Wrapper version: Wineskin-2.9.0.7-rc4
 - Engine version: WS11WineCX64Bit20.0.2
 - Hardware: MacbookPro 2020, M1, 16GB RAM

**Describe the bug**
When launching the wrapper, nothing happens.

**To Reproduce**
Describe the steps to reproduce the behavior:
1. Install as described in WineskinServer Readme & Create Wrapper
2. Download skyrim (via steam)
3. copy files into the wrapper
4. Launch the wrapper

**Expected behavior**
Skyrim starting

**Screenshots**
the logs are the only visible output

**Additional context**
Currently when I launch the Wrapper, nothing visibly happens. I get the following log during test runs:

**With "SkyrimLauncher.exe selected:**
`000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0xac03
001d:err:plugplay:process_IOService_Device object 0xad03
001d:err:plugplay:process_IOService_Device object 0x15103
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0027:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
`

**With "TESV.exe selected:**
`000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x15203
001d:err:plugplay:process_IOService_Device object 0x15003
001d:err:plugplay:process_IOService_Device object 0x14f03
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0027:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.`

I've downloaded Skyrim via Steam. Before, I tried the same process with a simple game "Loading Screen Simulator" which I was able to run successfully.

This might be a dependancy issue. If somebody could point me in the direction how I can find out what's missing, that would be great. Did anyone else try running Skyrim already?

**Comment by Gcenx** [comment]
@torquan modify the issue and complete fill out the provided template

**Comment by torquan** [comment]
> @torquan modify the issue and complete fill out the provided template

Sorry, I went on blank issue as I wasn't sure this is a bug or a mistake on my end, so I didn't see the template.
I updated it.

**Comment by torquan** [comment]
I downloaded Skyrim Special Edition. There, I can open the Launcher, but clicking on "Play" closes the wrapper windor.
Should I open a new issue for SSE and close this one? Perhaps SSE is easier to get running, as the Launcher is working?

**Comment by Gcenx** [comment]
The issue template provides me with useful information, some issues have been resolved my simply using the latest version of Winery and master wrapper.

Sounds like your missing dependencies as Skyrim (LE) is known to work, Skyrim SE can also work but will have more graphical issues on the M1 systems.

Also for Skyrim don’t resolutions below 800 x 600 due to an unresolved Apple Silicon specific bug.

Skyrim SE requires DirectX10/11 so the custom DXVK verb also needs to be installed or the game won’t launch.

**Comment by torquan** [comment]
> The issue template provides me with useful information, some issues have been resolved my simply using the latest version of Winery and master wrapper.
> 
> Sounds like your missing dependencies as Skyrim (LE) is known to work, Skyrim SE can also work but will have more graphical issues on the M1 systems.
> 
> Also for Skyrim don’t resolutions below 800 x 600 due to an unresolved Apple Silicon specific bug.
> 
> Skyrim SE requires DirectX10/11 so the custom DXVK verb also needs to be installed or the game won’t launch.

Thanks for the reply.
Skyrim LE: How can I find out, which dependencies are missing?
Skyrim SE: I did run "dxvk_macos.verb" in Winetricks.

I read in another issue that BigSur 11.2.3 makes problems - Could this be the issue?

These are the logs when trying to run SkyrimSE:

`000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x15403
001d:err:plugplay:process_IOService_Device object 0x15303
001d:err:plugplay:process_IOService_Device object 0x15203
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0025:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:vcruntime:__telemetry_main_invoke_trigger (0000000000000000)
0009:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Apple". Returning HW_VENDOR_NVIDIA.
0009:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0009:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0009:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0009:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0009:fixme:vcruntime:__telemetry_main_return_trigger (0000000000000000)
002c:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
002c:fixme:heap:RtlSetHeapInformation 0x8e0000 0 0x21e690 4 stub
`

**Comment by Gcenx** [comment]
I don’t really see anything of note in that output honesty.

Currently at work so not sure on the exact requirements for Skyrim/SE however you could use PortingKit instead it will handle all of this for you.

PortingKit is a GUI frontend that uses my master wrapper and engines.

**Comment by torquan** [comment]
I found the problem and it's a pretty stupid one 😅

I installed Steam on macOS, as it didn't work via wineskin (store and library tab are empty). I then copied the skyrim files into the wrapper, as described. The reason why Skyrim didn't launch is because the steam version requires steam.. Should have thought of that earlier.

After installing Steam in my wrapper, moving skyrim in the correct folder and adjusting the manifest files, it worked.
Thanks for your time.

**Comment by torquan** [comment]
I found the problem and it's a pretty stupid one 😅

I installed Steam on macOS, as it didn't work via wineskin (store and library tab are empty). I then copied the skyrim files into the wrapper, as described. The reason why Skyrim didn't launch is because the steam version requires steam.. Should have thought of that earlier.

After installing Steam in my wrapper, moving skyrim in the correct folder and adjusting the manifest files, it worked.
Thanks for your time.

**Comment by Gcenx** [comment]
I did say graphical glitches will be common, Skyrim LE should be working last I checked it was working on macOS Big Sur.

I’m hoping the GPU differences are taken into account in CX21.

**Comment by torquan** [comment]
I don't hear any voice audio in Skyrim SE. Other sound effects work. Do you have an idea how I can fix that?

Skyrim LE throws now this error in the log:
`0025:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.`
[This post](https://forum.winehq.org/viewtopic.php?t=33023) suggests I need to install the "winbind" package, but is related to a linux device. I found other sources saying I need to install samba (to which I find mostly very old stuff, it was removed from brew too.)

**Comment by Gcenx** [comment]
To kinda fix the audio issues use xact verb.

Ignore the ntlm_auth messages, yes it’s related to samba I might eventually get around to bundling a clean version of ntlm_auth but it’s really worth the effort as almost nothing really requires it.

**Comment by torquan** [comment]
Thanks, sound is working now in SE.

I thought ntlm_auh is perhaps the reason why Skyrim LE doesn't start, thus the question. However, it's starting now (and I didn't change anything..) I'll probably stay with LE, as the graphic glitches are more annoying than I though when I saw that video.

Again, thank you very much!
